--KEY TECHs
angelsmods.functions.add_exception("tech-red-packs")
angelsmods.functions.add_exception("tech-red-labs")
angelsmods.functions.add_exception("tech-green-packs")
angelsmods.functions.add_exception("tech-green-labs")
angelsmods.functions.add_exception("tech-orange-packs")
angelsmods.functions.add_exception("tech-orange-labs")
angelsmods.functions.add_exception("tech-blue-packs")
angelsmods.functions.add_exception("tech-blue-labs")
angelsmods.functions.add_exception("tech-yellow-packs")
angelsmods.functions.add_exception("tech-yellow-labs")

angelsmods.functions.add_exception("tech-specialised-labs-basic-exploration-1")
angelsmods.functions.add_exception("tech-specialised-labs-basic-exploration-2")
angelsmods.functions.add_exception("tech-specialised-labs-basic-exploration-3")
angelsmods.functions.add_exception("tech-specialised-labs-basic-energy-1")
angelsmods.functions.add_exception("tech-specialised-labs-basic-energy-2")
angelsmods.functions.add_exception("tech-specialised-labs-basic-energy-3")
angelsmods.functions.add_exception("tech-specialised-labs-basic-logistic-1")
angelsmods.functions.add_exception("tech-specialised-labs-basic-logistic-2")
angelsmods.functions.add_exception("tech-specialised-labs-basic-logistic-3")
angelsmods.functions.add_exception("tech-specialised-labs-basic-enhancement-1")
angelsmods.functions.add_exception("tech-specialised-labs-basic-enhancement-2")
angelsmods.functions.add_exception("tech-specialised-labs-basic-enhancement-3")
angelsmods.functions.add_exception("tech-specialised-labs-basic-processing-1")
angelsmods.functions.add_exception("tech-specialised-labs-basic-processing-2")
angelsmods.functions.add_exception("tech-specialised-labs-basic-processing-3")
angelsmods.functions.add_exception("tech-specialised-labs-basic-warfare-1")
angelsmods.functions.add_exception("tech-specialised-labs-basic-warfare-2")
angelsmods.functions.add_exception("tech-specialised-labs-basic-warfare-3")
angelsmods.functions.add_exception("tech-specialised-labs-basic-basic-1")
angelsmods.functions.add_exception("tech-specialised-labs-basic-basic-2")
angelsmods.functions.add_exception("tech-specialised-labs-basic-basic-3")

--BASE
angelsmods.functions.add_exception("automation")

--BIO PROCESSING (not sure these are activated... i may have overridden these anyway)
angelsmods.functions.add_exception("bio-temperate-farming")
angelsmods.functions.add_exception("bio-temperate-farm")
angelsmods.functions.add_exception("bio-desert-farming")
angelsmods.functions.add_exception("bio-desert-farm")
angelsmods.functions.add_exception("bio-swamp-farming")
angelsmods.functions.add_exception("bio-swamp-farm")
