local OV = angelsmods.functions.OV
require("prototypes.overrides.industries-override-functions")

if mods['bobplates'] then
	--Adds bobplates cores
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("grinding", "datacore-processing-1", 2)
	OV.set_science_pack("polishing", "datacore-processing-1", 2)
	OV.set_science_pack("mixing-steel-furnace", "datacore-processing-1", 2)
	OV.set_science_pack("gas-canisters", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-2", "datacore-processing-1", 2)
	OV.set_science_pack("ceramics", "datacore-processing-2", 2)
end
if mods['bobassembly'] then
	--adds bobassembly stuffs
	OV.set_science_pack("oil-steel-furnace", "datacore-processing-1", 2)
	OV.set_science_pack("oil-mixing-steel-furnace", "datacore-processing-1", 2)
	OV.set_science_pack("oil-chemical-steel-furnace", "datacore-processing-1", 2)
	OV.set_science_pack("electrolyser-2", "datacore-processing-1", 2)
	OV.set_science_pack("bob-distillery-2", "datacore-processing-1", 2)
	OV.set_science_pack("multi-purpose-furnace-1", "datacore-processing-2", 2)
	OV.set_science_pack("chemical-plant-2", "datacore-processing-2", 2)
	OV.set_science_pack("chemical-plant-3", "datacore-processing-2", 2)
	OV.set_science_pack("electrolyser-3", "datacore-processing-2", 2)
	pack_replace("bob-distillery-3","blue","orange")
	OV.set_science_pack("bob-distillery-3", "datacore-processing-1", 2)
	core_tier_up("bob-distillery-5","processing")
end
if mods['bobgreenhouse'] then
	--adds bob greenhouse stuffs
	OV.set_science_pack("bob-greenhouse", "datacore-processing-1", 2)
	OV.set_science_pack("bob-fertiliser", "datacore-processing-1", 2)
end
--bob adjustable inserters automatically gets grabbed :D
if mods['bobclasses'] then
	--adds bob classes stuffs
	OV.set_science_pack("bodies", "datacore-enhance-2", 2)
end
if mods['bobmining'] then
	--adds bob classes stuffs
	OV.set_science_pack("bob-drills-1", "datacore-processing-1", 2)
	OV.set_science_pack("bob-area-drills-1", "datacore-processing-1", 2)
	OV.set_science_pack("bob-pumpjacks-1", "datacore-processing-1", 2)
	OV.set_science_pack("bob-drills-2", "datacore-processing-1", 2)
	OV.set_science_pack("bob-area-drills-2", "datacore-processing-1", 2)
	OV.set_science_pack("bob-pumpjacks-2", "datacore-processing-1", 2)
	OV.set_science_pack("bob-drills-3", "datacore-processing-2", 2)
	OV.set_science_pack("bob-area-drills-3", "datacore-processing-2", 2)
	OV.set_science_pack("bob-pumpjacks-3", "datacore-processing-2", 2)
	OV.remove_science_pack("steel-axe-5", "datacore-processing-1")
	core_tier_up("steel-axe-5","enhance")
	OV.remove_science_pack("steel-axe-6", "datacore-processing-1")
	core_tier_up("steel-axe-6","enhance")
end
if mods['bobmodules'] then
	--removes enhancement core from module techs (not modules)
	for rec_4tech in pairs(data.raw.technology) do
	  --fix modules to still work in bobs module lab
	  if string.find(rec_4tech,"-module-")~=nil  then
	    OV.remove_science_pack(rec_4tech, "datacore-enhance-1")
		end
	end
	OV.remove_science_pack("speed-module", "angels-science-pack-orange")
	OV.remove_science_pack("productivity-module", "angels-science-pack-orange")
	OV.remove_science_pack("effectivity-module", "angels-science-pack-orange")
	OV.remove_science_pack("effect-transmission-2", "datacore-processing-2")
	OV.set_science_pack("effect-transmission-2", "datacore-enhance-2", 2)
	core_replace("effect-transmission-3","processing","enhance")
	core_tier_up("effect-transmission-3","enhance")
	OV.remove_science_pack("module-merging", "datacore-enhance-1")
end
if mods['boblogistics'] then
	--adds bob classes stuffs
	OV.remove_science_pack("logistics-4", "datacore-processing-1")
	core_tier_up("logistics-4","logistic")
	OV.remove_science_pack("logistics-5", "datacore-processing-1")
	core_tier_up("logistics-5","logistic")
	OV.remove_science_pack("bob-armoured-railway-2", "datacore-processing-1")
	core_tier_up("bob-armoured-railway-2","logistic")
	OV.remove_science_pack("bob-armoured-fluid-wagon-2", "datacore-processing-1")
	core_tier_up("bob-armoured-fluid-wagon-2","logistic")
	OV.remove_science_pack("bob-robotics-3", "datacore-processing-1")
	core_tier_up("bob-robotics-3","logistic")
	OV.remove_science_pack("bob-robotics-4", "datacore-processing-1")
	core_tier_up("bob-robotics-4","logistic")
	OV.remove_science_pack("bob-robots-2", "datacore-processing-1")
	core_tier_up("bob-robots-2","logistic")
	OV.remove_science_pack("bob-robots-3", "datacore-processing-1")
	core_tier_up("bob-robots-3","logistic")
	OV.remove_science_pack("bob-robots-4", "datacore-processing-1")
	core_tier_up("bob-robots-4","logistic")
	OV.set_science_pack("bob-repair-pack-2", "datacore-enhance-1", 2)
	OV.set_science_pack("bob-repair-pack-3", "datacore-enhance-1", 2)
	OV.set_science_pack("bob-repair-pack-4", "datacore-enhance-1", 2)
	OV.set_science_pack("bob-repair-pack-5", "datacore-enhance-1", 2)
	OV.set_science_pack("bob-repair-pack-6", "datacore-enhance-1", 2)
	pack_replace("toolbelt-2","blue","green")
	OV.set_science_pack("toolbelt-2", "datacore-enhance-1", 2)
	OV.remove_science_pack("toolbelt-3", "datacore-processing-2")
	OV.set_science_pack("toolbelt-3", "datacore-enhance-2", 2)
	OV.remove_science_pack("toolbelt-4", "datacore-processing-1")
	OV.set_science_pack("toolbelt-4", "datacore-enhance-2", 2)
	OV.remove_science_pack("toolbelt-5", "datacore-processing-1")
	OV.set_science_pack("toolbelt-5", "datacore-enhance-2", 2)
	pack_replace("express-inserters","blue","orange")
	OV.remove_science_pack("express-inserters", "datacore-logistic-2")
	OV.set_science_pack("express-inserters", "datacore-logistic-1", 2)
	pack_replace("stack-inserter-2","blue","orange")
	OV.remove_science_pack("stack-inserter-2", "datacore-logistic-2")
	OV.set_science_pack("stack-inserter-2", "datacore-logistic-1", 2)
	OV.remove_science_pack("turbo-inserter", "datacore-processing-1")
	core_tier_up("turbo-inserter","logistic")
	OV.remove_science_pack("ultimate-inserter", "datacore-processing-1")
	core_tier_up("ultimate-inserter","logistic")
	OV.remove_science_pack("stack-inserter-3", "datacore-processing-1")
	core_tier_up("stack-inserter-3","logistic")
	OV.remove_science_pack("stack-inserter-4", "datacore-processing-1")
	core_tier_up("stack-inserter-4","logistic")
	OV.remove_science_pack("logistic-system-2", "datacore-processing-1")
	core_tier_up("logistic-system-2","logistic")
	OV.remove_science_pack("logistic-system-3", "datacore-processing-1")
	core_tier_up("logistic-system-3","logistic")
	OV.remove_science_pack("character-logistic-slots-7", "datacore-processing-1")
	core_tier_up("character-logistic-slots-7","logistic")
	OV.remove_science_pack("character-logistic-slots-8", "datacore-processing-1")
	core_tier_up("character-logistic-slots-8","logistic")
	OV.remove_science_pack("character-logistic-slots-9", "datacore-processing-1")
	core_tier_up("character-logistic-slots-9","logistic")
	OV.remove_science_pack("character-logistic-slots-10", "datacore-processing-1")
	core_tier_up("character-logistic-slots-10","logistic")
	OV.remove_science_pack("inserter-stack-size-bonus-3", "datacore-processing-1")
	core_tier_up("inserter-stack-size-bonus-3","logistic")
	OV.remove_science_pack("inserter-stack-size-bonus-4", "datacore-processing-1")
	core_tier_up("inserter-stack-size-bonus-4","logistic")
	OV.remove_science_pack("inserter-capacity-bonus-8", "datacore-processing-1")
	core_tier_up("inserter-capacity-bonus-8","logistic")
	OV.remove_science_pack("bob-fluid-handling-4", "datacore-processing-1")
	core_tier_up("bob-fluid-handling-4","logistic")
	OV.remove_science_pack("bob-infinite-worker-robots-storage-1", "datacore-processing-1")
	core_tier_up("bob-infinite-worker-robots-storage-1","logistic")
	OV.remove_science_pack("bob-infinite-character-logistic-trash-slots-1", "datacore-processing-1")
	core_tier_up("bob-infinite-character-logistic-trash-slots-1","logistic")
	pack_replace("bob-robo-modular-2","blue","orange")
	OV.set_science_pack("bob-robo-modular-1", "datacore-enhance-1", 2)
	OV.set_science_pack("bob-robo-modular-2", "datacore-enhance-1", 2)
	OV.remove_science_pack("bob-robo-modular-3", "datacore-processing-2")
	OV.set_science_pack("bob-robo-modular-3", "datacore-logistic-2", 2)
	OV.remove_science_pack("bob-robo-modular-4", "datacore-processing-1")
	OV.set_science_pack("bob-robo-modular-4", "datacore-logistic-2", 2)
end
--bob ores stuffs automatically gets grabbed :D (may want to swap the nuclear stuff to power?)
--bob enemies recipes automatically gets grabbed :D
--bob electronics recipes automatically gets grabbed :D
if mods['bobwarfare'] then
	--adds bob warfare stuffs
	OV.remove_science_pack("bob-power-armor-3", "datacore-war-1")
	core_tier_up("bob-power-armor-3","enhance")
	OV.remove_science_pack("bob-power-armor-4", "datacore-war-1")
	core_tier_up("bob-power-armor-4","enhance")
	OV.remove_science_pack("bob-power-armor-5", "datacore-war-1")
	core_tier_up("bob-power-armor-5","enhance")
	OV.remove_science_pack("bob-robot-attack-drones", "datacore-logistic-1")
	OV.remove_science_pack("bob-robot-plasma-drones", "datacore-logistic-1")
	OV.remove_science_pack("bob-robot-gun-drones", "datacore-logistic-1")
	core_tier_up("bob-laser-turrets-5","war")
	core_tier_up("bob-plasma-rocket","war")
	core_tier_up("bob-sniper-turrets-3","war")
	core_tier_up("bob-tanks-3","war")
	core_tier_up("bob-artillery-turret-2","war")
	core_tier_up("bob-artillery-turret-3","war")
	core_tier_up("bob-artillery-wagon-2","war")
	core_tier_up("bob-artillery-wagon-3","war")
	core_tier_up("bob-plasma-turrets-5","war")
	core_tier_up("combat-robotics-4","war")
	OV.remove_science_pack("nitroglycerin-processing", "datacore-war-1")
	OV.remove_science_pack("cordite-processing", "datacore-war-1")
	OV.set_science_pack("radars", "datacore-exploration-1", 2)
	OV.set_science_pack("radars-2", "datacore-exploration-1", 2)
	pack_replace("radars-3","blue","orange")
	OV.set_science_pack("radars-3", "datacore-exploration-1", 2)
	OV.set_science_pack("radars-4", "datacore-exploration-2", 2)
	OV.remove_science_pack("radars-4", "datacore-war-2")
	OV.set_science_pack("poison-mine", "datacore-war-2", 2)
	OV.set_science_pack("slowdown-mine", "datacore-war-2", 2)
	OV.set_science_pack("distractor-mine", "datacore-war-2", 2)
	core_tier_up("bob-plasma-bullets","war")
	core_tier_up("bob-shotgun-plasma-shells","war")
end
if mods['bobvehicleequipment'] then
	--adds bob vehicle equipment stuffs
	OV.remove_science_pack("vehicle-engine-equipment", "datacore-processing-1")
	core_tier_up("vehicle-engine-equipment","enhance")
	OV.remove_science_pack("vehicle-battery-equipment-4", "datacore-processing-1")
	core_tier_up("vehicle-battery-equipment-4","enhance")
	OV.remove_science_pack("vehicle-battery-equipment-5", "datacore-processing-1")
	core_tier_up("vehicle-battery-equipment-5","enhance")
	OV.remove_science_pack("vehicle-battery-equipment-6", "datacore-processing-1")
	core_tier_up("vehicle-battery-equipment-6","enhance")
	OV.remove_science_pack("vehicle-solar-panel-equipment-4", "datacore-processing-1")
	core_tier_up("vehicle-solar-panel-equipment-4","enhance")
	OV.remove_science_pack("vehicle-solar-panel-equipment-5", "datacore-processing-1")
	core_tier_up("vehicle-solar-panel-equipment-5","enhance")
	OV.remove_science_pack("vehicle-solar-panel-equipment-6", "datacore-processing-1")
	core_tier_up("vehicle-solar-panel-equipment-6","enhance")
	OV.remove_science_pack("vehicle-fusion-cell-equipment-2", "datacore-processing-1")
	core_tier_up("vehicle-fusion-cell-equipment-2","enhance")
	OV.remove_science_pack("vehicle-fusion-cell-equipment-3", "datacore-processing-1")
	core_tier_up("vehicle-fusion-cell-equipment-3","enhance")
	OV.remove_science_pack("vehicle-fusion-cell-equipment-4", "datacore-processing-1")
	core_tier_up("vehicle-fusion-cell-equipment-4","enhance")
	OV.remove_science_pack("vehicle-fusion-cell-equipment-5", "datacore-processing-1")
	core_tier_up("vehicle-fusion-cell-equipment-5","enhance")
	OV.remove_science_pack("vehicle-fusion-cell-equipment-6", "datacore-processing-1")
	core_tier_up("vehicle-fusion-cell-equipment-6","enhance")
	OV.remove_science_pack("vehicle-fusion-reactor-equipment-2", "datacore-processing-1")
	core_tier_up("vehicle-fusion-reactor-equipment-2","enhance")
	OV.remove_science_pack("vehicle-fusion-reactor-equipment-3", "datacore-processing-1")
	core_tier_up("vehicle-fusion-reactor-equipment-3","enhance")
	OV.remove_science_pack("vehicle-fusion-reactor-equipment-4", "datacore-processing-1")
	core_tier_up("vehicle-fusion-reactor-equipment-4","enhance")
	OV.remove_science_pack("vehicle-fusion-reactor-equipment-5", "datacore-processing-1")
	core_tier_up("vehicle-fusion-reactor-equipment-5","enhance")
	OV.remove_science_pack("vehicle-fusion-reactor-equipment-6", "datacore-processing-1")
	core_tier_up("vehicle-fusion-reactor-equipment-6","enhance")
	OV.remove_science_pack("vehicle-roboport-equipment-4", "datacore-processing-1")
	core_tier_up("vehicle-roboport-equipment-4","enhance")
	core_replace("vehicle-roboport-modular-equipment-4","processing","enhance")
	core_tier_up("vehicle-roboport-modular-equipment-4","enhance")
	pack_replace("vehicle-roboport-modular-equipment-1","green","orange")
	OV.set_science_pack("vehicle-roboport-modular-equipment-1", "datacore-enhance-1", 2)
end
if mods['bobequipment'] then
	--adds bob personal equipment stuffs
	OV.remove_science_pack("night-vision-equipment-3", "datacore-processing-1")
	core_tier_up("night-vision-equipment-3","enhance")
	OV.remove_science_pack("exoskeleton-equipment-3", "datacore-processing-1")
	core_tier_up("exoskeleton-equipment-3","enhance")
	OV.remove_science_pack("bob-battery-equipment-4", "datacore-processing-1")
	core_tier_up("bob-battery-equipment-4","enhance")
	OV.remove_science_pack("bob-battery-equipment-5", "datacore-processing-1")
	core_tier_up("bob-battery-equipment-5","enhance")
	OV.remove_science_pack("bob-battery-equipment-6", "datacore-processing-1")
	core_tier_up("bob-battery-equipment-6","enhance")
	OV.remove_science_pack("solar-panel-equipment-4", "datacore-processing-1")
	core_tier_up("solar-panel-equipment-4","enhance")
	OV.remove_science_pack("fusion-reactor-equipment-2", "datacore-processing-1")
	core_tier_up("fusion-reactor-equipment-2","enhance")
	OV.remove_science_pack("fusion-reactor-equipment-3", "datacore-processing-1")
	core_tier_up("fusion-reactor-equipment-3","enhance")
	OV.remove_science_pack("fusion-reactor-equipment-4", "datacore-processing-1")
	core_tier_up("fusion-reactor-equipment-4","enhance")
	OV.remove_science_pack("personal-roboport-mk4-equipment", "datacore-processing-1")
	core_tier_up("personal-roboport-mk4-equipment","enhance")
	pack_replace("personal-roboport-modular-equipment-1","green","orange")
	OV.set_science_pack("personal-roboport-modular-equipment-1", "datacore-enhance-1", 2)
	core_replace("personal-roboport-modular-equipment-4","processing","enhance")
	core_tier_up("personal-roboport-modular-equipment-4","enhance")
end
if mods['bobpower'] then
	--adds bob power stuffs
	core_replace("fluid-generator-1","logistic","energy")
	pack_replace("fluid-generator-2","blue","orange")
	OV.remove_science_pack("fluid-generator-2", "datacore-logistic-2")
	OV.set_science_pack("fluid-generator-2", "datacore-energy-1", 2)
	OV.remove_science_pack("fluid-generator-3", "datacore-logistic-1")
	core_replace("fluid-generator-3","processing","energy")
	core_tier_up("fluid-generator-3","energy")
	OV.remove_science_pack("bob-electric-energy-accumulators-4", "datacore-processing-1")
	core_tier_up("bob-electric-energy-accumulators-4","energy")
	OV.set_science_pack("bob-oil-generator-1", "datacore-energy-1", 2)
	OV.set_science_pack("bob-oil-generator-2", "datacore-energy-1", 2)
	pack_replace("bob-oil-generator-3","blue","orange")
	OV.set_science_pack("bob-oil-generator-3", "datacore-energy-1", 2)
	OV.remove_science_pack("bob-oil-generator-4", "datacore-processing-2")
	OV.set_science_pack("bob-oil-generator-4", "datacore-energy-2", 2)
	OV.set_science_pack("bob-steam-engine-2", "datacore-energy-1", 2)
	OV.set_science_pack("bob-steam-engine-3", "datacore-energy-1", 2)
	pack_replace("bob-steam-engine-4","blue","orange")
	OV.set_science_pack("bob-steam-engine-4", "datacore-energy-1", 2)
	OV.remove_science_pack("bob-steam-engine-5", "datacore-processing-2")
	OV.set_science_pack("bob-steam-engine-5", "datacore-energy-2", 2)
	OV.set_science_pack("bob-steam-turbine-1", "datacore-energy-1", 2)
	pack_replace("bob-steam-turbine-2","blue","orange")
	OV.set_science_pack("bob-steam-turbine-2", "datacore-energy-1", 2)
	OV.remove_science_pack("bob-steam-turbine-3", "datacore-processing-2")
	OV.set_science_pack("bob-steam-turbine-3", "datacore-energy-2", 2)
	OV.set_science_pack("bob-boiler-2", "datacore-energy-1", 2)
	OV.set_science_pack("bob-boiler-3", "datacore-energy-1", 2)
	pack_replace("bob-boiler-4","blue","orange")
	OV.set_science_pack("bob-boiler-4", "datacore-energy-1", 2)
	OV.remove_science_pack("bob-boiler-5", "datacore-processing-2")
	OV.set_science_pack("bob-boiler-5", "datacore-energy-2", 2)
	OV.set_science_pack("bob-oil-boiler-1", "datacore-energy-1", 2)
	OV.set_science_pack("bob-oil-boiler-2", "datacore-energy-1", 2)
	pack_replace("bob-oil-boiler-3","blue","orange")
	OV.set_science_pack("bob-oil-boiler-3", "datacore-energy-1", 2)
	OV.remove_science_pack("bob-oil-boiler-4", "datacore-processing-2")
	OV.set_science_pack("bob-oil-boiler-4", "datacore-energy-2", 2)
	OV.set_science_pack("bob-heat-exchanger-1", "datacore-energy-1", 2)
	pack_replace("bob-heat-exchanger-2","blue","orange")
	OV.set_science_pack("bob-heat-exchanger-2", "datacore-energy-1", 2)
	OV.remove_science_pack("bob-heat-exchanger-3", "datacore-processing-2")
	OV.set_science_pack("bob-heat-exchanger-3", "datacore-energy-2", 2)
	OV.set_science_pack("bob-heat-pipe-1", "datacore-energy-1", 2)
	pack_replace("bob-heat-pipe-2","blue","orange")
	OV.set_science_pack("bob-heat-pipe-2", "datacore-energy-1", 2)
	OV.remove_science_pack("bob-heat-pipe-3", "datacore-processing-2")
	OV.set_science_pack("bob-heat-pipe-3", "datacore-energy-2", 2)
	OV.remove_science_pack("bob-nuclear-power-2", "datacore-processing-1")
	core_tier_up("bob-nuclear-power-2","energy")
	OV.remove_science_pack("bob-nuclear-power-3", "datacore-processing-1")
	core_tier_up("bob-nuclear-power-3","energy")
	OV.set_science_pack("electric-pole-2", "datacore-energy-1", 2)
	pack_replace("electric-pole-3","blue","orange")
	OV.set_science_pack("electric-pole-3", "datacore-energy-1", 2)
	OV.remove_science_pack("electric-pole-4", "datacore-processing-2")
	OV.set_science_pack("electric-pole-4", "datacore-energy-2", 2)
	OV.set_science_pack("electric-substation-2", "datacore-energy-1", 2)
	pack_replace("electric-substation-3","blue","orange")
	OV.set_science_pack("electric-substation-3", "datacore-energy-1", 2)
	OV.remove_science_pack("electric-substation-4", "datacore-processing-2")
	OV.set_science_pack("electric-substation-4", "datacore-energy-2", 2)
	OV.set_science_pack("burner-reactor-1", "datacore-energy-1", 2)
	pack_replace("burner-reactor-2","blue","orange")
	OV.set_science_pack("burner-reactor-2", "datacore-energy-1", 2)
	OV.remove_science_pack("burner-reactor-3", "datacore-processing-2")
	OV.set_science_pack("burner-reactor-3", "datacore-energy-2", 2)
	OV.set_science_pack("fluid-reactor-1", "datacore-energy-1", 2)
	OV.remove_science_pack("fluid-reactor-1", "datacore-logistic-1")
	pack_replace("fluid-reactor-2","blue","orange")
	OV.set_science_pack("fluid-reactor-2", "datacore-energy-1", 2)
	OV.remove_science_pack("fluid-reactor-2", "datacore-logistic-2")
	OV.remove_science_pack("fluid-reactor-3", "datacore-processing-1")
	core_replace("fluid-reactor-3","logistic","energy")
	core_tier_up("fluid-reactor-3","energy")
end
--[[OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	OV.set_science_pack("electrolysis-1", "datacore-processing-1", 2)
	core_replace("bodies","basic","enhance")]]
