data:extend({
  --TIER 3
  {
    type = "recipe",
    name = "angels-ore1-crystal-processing",
    category = "angels-ore-sorting-3",
    subgroup = "angels-ore-sorting-t3",
    energy_required = 2,
    enabled = false,
    allow_decomposition = false,
    auto_recycle = false,
    hide_from_signal_gui = false,
    ingredients = { { type = "item", name = "angels-ore1-crystal", amount = 8 } },
    results = {
      { type = "item", name = "angels-slag", amount = 1 },
    },
    icons = {
      { icon = "__angelsrefininggraphics__/graphics/icons/sort-icon.png", icon_size = 32 },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/angels-ore1/angels-ore1-crystal.png",
        icon_size = 32,
        scale = 0.5,
        shift = { -10, 10 },
      },
    },
    order = "a[angels-ore1-crystal-processing]",
  },
  {
    type = "recipe",
    name = "angels-ore2-crystal-processing",
    category = "angels-ore-sorting-3",
    subgroup = "angels-ore-sorting-t3",
    energy_required = 2,
    enabled = false,
    allow_decomposition = false,
    auto_recycle = false,
    hide_from_signal_gui = false,
    ingredients = { { type = "item", name = "angels-ore2-crystal", amount = 8 } },
    results = {
      { type = "item", name = "angels-slag", amount = 1 },
    },
    icons = {
      { icon = "__angelsrefininggraphics__/graphics/icons/sort-icon.png", icon_size = 32 },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/angels-ore2/angels-ore2-crystal.png",
        icon_size = 32,
        scale = 0.5,
        shift = { -10, 10 },
      },
    },
    icon_size = 32,
    order = "b[angels-ore2-crystal-processing]",
  },
  {
    type = "recipe",
    name = "angels-ore3-crystal-processing",
    category = "angels-ore-sorting-3",
    subgroup = "angels-ore-sorting-t3",
    energy_required = 2,
    enabled = false,
    allow_decomposition = false,
    auto_recycle = false,
    hide_from_signal_gui = false,
    ingredients = { { type = "item", name = "angels-ore3-crystal", amount = 8 } },
    results = {
      { type = "item", name = "angels-slag", amount = 1 },
    },
    icons = {
      { icon = "__angelsrefininggraphics__/graphics/icons/sort-icon.png", icon_size = 32 },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/angels-ore3/angels-ore3-crystal.png",
        icon_size = 32,
        scale = 0.5,
        shift = { -10, 10 },
      },
    },
    icon_size = 32,
    order = "c[angels-ore3-crystal-processing]",
  },
  {
    type = "recipe",
    name = "angels-ore4-crystal-processing",
    category = "angels-ore-sorting-3",
    subgroup = "angels-ore-sorting-t3",
    energy_required = 2,
    enabled = false,
    allow_decomposition = false,
    auto_recycle = false,
    hide_from_signal_gui = false,
    ingredients = { { type = "item", name = "angels-ore4-crystal", amount = 8 } },
    results = {
      { type = "item", name = "angels-slag", amount = 1 },
    },
    icons = {
      { icon = "__angelsrefininggraphics__/graphics/icons/sort-icon.png", icon_size = 32 },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/angels-ore4/angels-ore4-crystal.png",
        icon_size = 32,
        scale = 0.5,
        shift = { -10, 10 },
      },
    },
    order = "d[angels-ore4-crystal-processing]",
  },
  {
    type = "recipe",
    name = "angels-ore5-crystal-processing",
    category = "angels-ore-sorting-3",
    subgroup = "angels-ore-sorting-t3",
    energy_required = 2,
    enabled = false,
    allow_decomposition = false,
    auto_recycle = false,
    hide_from_signal_gui = false,
    ingredients = { { type = "item", name = "angels-ore5-crystal", amount = 8 } },
    results = {
      { type = "item", name = "angels-slag", amount = 1 },
    },
    icons = {
      { icon = "__angelsrefininggraphics__/graphics/icons/sort-icon.png", icon_size = 32 },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/angels-ore5/angels-ore5-crystal.png",
        icon_size = 32,
        scale = 0.5,
        shift = { -10, 10 },
      },
    },
    icon_size = 32,
    order = "e[angels-ore5-crystal-processing]",
  },
  {
    type = "recipe",
    name = "angels-ore6-crystal-processing",
    category = "angels-ore-sorting-3",
    subgroup = "angels-ore-sorting-t3",
    energy_required = 2,
    enabled = false,
    allow_decomposition = false,
    auto_recycle = false,
    hide_from_signal_gui = false,
    ingredients = { { type = "item", name = "angels-ore6-crystal", amount = 8 } },
    results = {
      { type = "item", name = "angels-slag", amount = 1 },
    },
    icons = {
      { icon = "__angelsrefininggraphics__/graphics/icons/sort-icon.png", icon_size = 32 },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/angels-ore6/angels-ore6-crystal.png",
        icon_size = 32,
        scale = 0.5,
        shift = { -10, 10 },
      },
    },
    icon_size = 32,
    order = "f[angels-ore6-crystal-processing]",
  },
})
