data:extend({
  --GEODES
  {
    type = "recipe",
    name = "angels-geode-blue-processing",
    category = "angels-ore-refining-t1",
    subgroup = "angels-geode-processing-1",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-geode-blue", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-dust", amount = 1 },
      { type = "item", name = "angels-stone-crushed", amount = 2 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/geode-blue.png",
    icon_size = 32,
    order = "a[geode-blue-processing]",
  },
  {
    type = "recipe",
    name = "angels-geode-red-processing",
    category = "angels-ore-refining-t1",
    subgroup = "angels-geode-processing-1",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-geode-red", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-dust", amount = 1 },
      { type = "item", name = "angels-stone-crushed", amount = 2 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/geode-red.png",
    icon_size = 32,
    order = "f[geode-red-processing]",
  },
  {
    type = "recipe",
    name = "angels-geode-yellow-processing",
    category = "angels-ore-refining-t1",
    subgroup = "angels-geode-processing-1",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-geode-yellow", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-dust", amount = 2 },
      { type = "item", name = "angels-stone-crushed", amount = 1 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/geode-yellow.png",
    icon_size = 32,
    order = "c[geode-yellow-processing]",
  },
  {
    type = "recipe",
    name = "angels-geode-purple-processing",
    category = "angels-ore-refining-t1",
    subgroup = "angels-geode-processing-1",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-geode-purple", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-dust", amount = 2 },
      { type = "item", name = "angels-stone-crushed", amount = 3 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/geode-purple.png",
    icon_size = 32,
    order = "b[geode-purple-processing]",
  },
  {
    type = "recipe",
    name = "angels-geode-cyan-processing",
    category = "angels-ore-refining-t1",
    subgroup = "angels-geode-processing-1",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-geode-cyan", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-dust", amount = 3 },
      { type = "item", name = "angels-stone-crushed", amount = 2 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/geode-cyan.png",
    icon_size = 32,
    order = "e[geode-cyan-processing]",
  },
  {
    type = "recipe",
    name = "angels-geode-lightgreen-processing",
    category = "angels-ore-refining-t1",
    subgroup = "angels-geode-processing-1",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-geode-lightgreen", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-dust", amount = 3 },
      { type = "item", name = "angels-stone-crushed", amount = 2 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/geode-lightgreen.png",
    icon_size = 32,
    order = "d[geode-lightgreen-processing]",
  },
})
