data:extend({
  --STONE & SLAG
  {
    type = "recipe",
    name = "slag-processing-1",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "a",
  },
  {
    type = "recipe",
    name = "slag-processing-2",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "b",
  },
  {
    type = "recipe",
    name = "slag-processing-3",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "c",
  },
  {
    type = "recipe",
    name = "slag-processing-4",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing-2",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "d",
  },
  {
    type = "recipe",
    name = "slag-processing-5",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing-2",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "e",
  },
  {
    type = "recipe",
    name = "slag-processing-6",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing-2",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "f",
  },
  {
    type = "recipe",
    name = "slag-processing-7",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing-2",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "g",
  },
  {
    type = "recipe",
    name = "slag-processing-8",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing-3",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "h",
  },
  {
    type = "recipe",
    name = "slag-processing-9",
    localised_name = { "item-name.angels-void" },
    category = "crystallizing-3",
    subgroup = "slag-processing-1",
    energy_required = 8,
    enabled = false,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("mineral-sludge"),
    order = "i",
  },
  {
    type = "recipe",
    name = "slag-processing-stone",
    category = "ore-refining-t1",
    subgroup = "processing-crafting",
    energy_required = 1,
    enabled = false,
    allow_decomposition = false,
    ingredients = { { type = "item", name = "slag", amount = 1 } },
    results = {
      { type = "item", name = "stone-crushed", amount = 2 },
    },
    order = "c[slag-processing-stone]",
  },
  {
    type = "recipe",
    name = "stone-crushed",
    localised_name = { "item-name.stone" },
    category = "crafting",
    subgroup = "processing-crafting",
    ingredients = {
      { type = "item", name = "stone-crushed", amount = 2 },
    },
    results = {
      { type = "item", name = "stone", amount = 1 },
    },
    energy_required = 0.5,
    enabled = true,
    order = "d[stone-crushed]",
  },
})
