data:extend({
  --STONE & SLAG
  {
    type = "recipe",
    name = "angels-slag-processing-1",
    localised_name = { "item-name.angels-void" },
    category = "angels-crystallizing",
    subgroup = "angels-slag-processing-1",
    energy_required = 8,
    enabled = false,
    hidden = true,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "angels-mineral-sludge", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-mineral-sludge"),
    order = "a",
  },
  {
    type = "recipe",
    name = "angels-slag-processing-2",
    localised_name = { "item-name.angels-void" },
    category = "angels-crystallizing",
    subgroup = "angels-slag-processing-1",
    energy_required = 8,
    enabled = false,
    hidden = true,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "angels-mineral-sludge", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-mineral-sludge"),
    order = "b",
  },
  {
    type = "recipe",
    name = "angels-slag-processing-3",
    localised_name = { "item-name.angels-void" },
    category = "angels-crystallizing",
    subgroup = "angels-slag-processing-1",
    energy_required = 8,
    enabled = false,
    hidden = true,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "angels-mineral-sludge", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-mineral-sludge"),
    order = "c",
  },
  {
    type = "recipe",
    name = "angels-slag-processing-4",
    localised_name = { "item-name.angels-void" },
    category = "angels-crystallizing",
    subgroup = "angels-slag-processing-1",
    energy_required = 8,
    enabled = false,
    hidden = true,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "angels-mineral-sludge", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-mineral-sludge"),
    order = "d",
  },
  {
    type = "recipe",
    name = "angels-slag-processing-5",
    localised_name = { "item-name.angels-void" },
    category = "angels-crystallizing",
    subgroup = "angels-slag-processing-1",
    energy_required = 8,
    enabled = false,
    hidden = true,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "angels-mineral-sludge", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-mineral-sludge"),
    order = "e",
  },
  {
    type = "recipe",
    name = "angels-slag-processing-6",
    localised_name = { "item-name.angels-void" },
    category = "angels-crystallizing",
    subgroup = "angels-slag-processing-1",
    energy_required = 8,
    enabled = false,
    hidden = true,
    allow_decomposition = false,
    show_amount_in_title = false,
    always_show_products = true,
    ingredients = {
      { type = "fluid", name = "angels-mineral-sludge", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-void", amount = 1 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-mineral-sludge"),
    order = "f",
  },
  {
    type = "recipe",
    name = "angels-stone-crushed",
    category = "angels-ore-refining-t1",
    subgroup = "angels-processing-crafting",
    energy_required = 1,
    enabled = false,
    allow_decomposition = false,
    ingredients = { { type = "item", name = "angels-slag", amount = 1 } },
    results = {
      { type = "item", name = "angels-stone-crushed", amount = 2 },
    },
    icons = angelsmods.functions.add_icon_layer(
      {
        {
          icon = "__angelsrefininggraphics__/graphics/icons/ore-crusher.png",
          icon_size = 64,
          scale = 0.5
        }
      },
      angelsmods.functions.get_object_icons("angels-stone-crushed"),
      { 10, 10 },
      0.5
    ),
    order = "c[slag-processing-stone]",
  },
  {
    type = "recipe",
    name = "angels-stone-from-crushed-stone",
    localised_name = { "item-name.stone" },
    category = "crafting",
    subgroup = "angels-processing-crafting",
    ingredients = {
      { type = "item", name = "angels-stone-crushed", amount = 2 },
    },
    results = {
      { type = "item", name = "stone", amount = 1 },
    },
    energy_required = 0.5,
    enabled = true,
    order = "d[stone-crushed]",
  },
})
