local function angels_air_filter_fluid_boxes()
  return {
    {
      production_type = "input",
      pipe_picture = angelsmods.petrochem.electrolyserpictures(),
      pipe_covers = pipecoverspictures(),
      volume = 1000,
      pipe_connections = { { flow_direction = "input", direction = defines.direction.north, position = { 0, -2 }, } },
    },
    {
      production_type = "output",
      pipe_picture = angelsmods.petrochem.electrolyserpictures(),
      pipe_covers = pipecoverspictures(),
      volume = 100,
      pipe_connections = { { flow_direction = "output", position = { 0, 2 }, direction = defines.direction.south } },
    },
  }
end

circuit_connector_definitions["angels-air-filter"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  4, main_offset = util.by_pixel(-4.375,  62.625), shadow_offset = util.by_pixel(-4.375,  62.625), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel(-4.375,  62.625), shadow_offset = util.by_pixel(-4.375,  62.625), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel(-4.375,  62.625), shadow_offset = util.by_pixel(-4.375,  62.625), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel(-4.375,  62.625), shadow_offset = util.by_pixel(-4.375,  62.625), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-air-filter",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelspetrochemgraphics__/graphics/icons/air-filter.png",
        icon_size = 32,
      },
    }, 1, angelsmods.petrochem.number_tint),
    subgroup = "angels-petrochem-buildings-electrolyser",
    order = "b[angels-air-filter]-a",
    place_result = "angels-air-filter",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-air-filter",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelspetrochemgraphics__/graphics/icons/air-filter.png",
        icon_size = 32,
      },
    }, 1, angelsmods.petrochem.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-air-filter" },
    fast_replaceable_group = "angels-air-filter",
    next_upgrade = "angels-air-filter-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 0.3,
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-petrochem-air-filtering" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -6 },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-air-filter"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        filename = "__angelspetrochemgraphics__/graphics/entity/air-filter/air-filter.png",
        width = 256,
        height = 256,
        frame_count = 36,
        line_length = 6,
        shift = { 0.5, -0.5 },
        animation_speed = 0.5,
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/idle1.ogg", volume = 1 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = angels_air_filter_fluid_boxes(),
  },
  {
    type = "item",
    name = "angels-air-filter-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelspetrochemgraphics__/graphics/icons/air-filter.png",
        icon_size = 32,
      },
    }, 2, angelsmods.petrochem.number_tint),
    subgroup = "angels-petrochem-buildings-electrolyser",
    order = "b[angels-air-filter]-b",
    place_result = "angels-air-filter-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-air-filter-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelspetrochemgraphics__/graphics/icons/air-filter.png",
        icon_size = 32,
      },
    }, 2, angelsmods.petrochem.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-air-filter-2" },
    fast_replaceable_group = "angels-air-filter",
    next_upgrade = "angels-air-filter-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 0.3,
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-petrochem-air-filtering" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -7.2 },
    },
    energy_usage = "175kW",
    circuit_connector = circuit_connector_definitions["angels-air-filter"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        filename = "__angelspetrochemgraphics__/graphics/entity/air-filter/air-filter.png",
        width = 256,
        height = 256,
        frame_count = 36,
        line_length = 6,
        shift = { 0.5, -0.5 },
        animation_speed = 0.5,
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/idle1.ogg", volume = 1 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = angels_air_filter_fluid_boxes(),
  },
  {
    type = "item",
    name = "angels-air-filter-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelspetrochemgraphics__/graphics/icons/air-filter.png",
        icon_size = 32,
      },
    }, 3, angelsmods.petrochem.number_tint),
    subgroup = "angels-petrochem-buildings-electrolyser",
    order = "b[angels-air-filter]-c",
    place_result = "angels-air-filter-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-air-filter-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelspetrochemgraphics__/graphics/icons/air-filter.png",
        icon_size = 32,
      },
    }, 3, angelsmods.petrochem.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-air-filter-3" },
    fast_replaceable_group = "angels-air-filter",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 0.3,
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-petrochem-air-filtering" },
    crafting_speed = 2.25,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -8.4 },
    },
    energy_usage = "225kW",
    circuit_connector = circuit_connector_definitions["angels-air-filter"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        filename = "__angelspetrochemgraphics__/graphics/entity/air-filter/air-filter.png",
        width = 256,
        height = 256,
        frame_count = 36,
        line_length = 6,
        shift = { 0.5, -0.5 },
        animation_speed = 0.5,
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/idle1.ogg", volume = 1 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = angels_air_filter_fluid_boxes(),
  },
})
