data:extend({
  --CONVERTER VALVE
  {
    type = "item",
    name = "valve-converter",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-converter.png",
    icon_size = 32,
    subgroup = "angels-fluid-control",
    order = "a[valve]-e[valve-converter]",
    place_result = "valve-converter",
    stack_size = 10,
  },
  {
    type = "furnace",
    name = "valve-converter",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-converter.png",
    icon_size = 32,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    minable = { mining_time = 1, result = "valve-converter" },
    max_health = 100,
    fast_replaceable_group = "pipe",
    corpse = "small-remnants",
    collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    crafting_categories = { "angels-converter" },
    result_inventory_size = 0,
    crafting_speed = 2,
    source_inventory_size = 0,
    resistances = {
      {
        type = "fire",
        percent = 80,
      },
      {
        type = "explosion",
        percent = 30,
      },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = {
          { flow_direction = "input", position = { 0, -0 }, direction = defines.direction.north },
        },
      },
      {
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { 0, 0 }, direction = defines.direction.south },
        },
      },
    },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 0.0025 * 60 },
    },
    energy_usage = "30kW",
    graphics_set = {
      animation = {
        north = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-converter.png",
          priority = "extra-high",
          frame_count = 1,
          width = 64,
          height = 64,
          shift = { 0, -0 },
        },
        east = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-converter.png",
          priority = "extra-high",
          x = 64,
          frame_count = 1,
          width = 64,
          height = 64,
          shift = { 0, 0 },
        },
        south = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-converter.png",
          priority = "extra-high",
          x = 128,
          frame_count = 1,
          width = 64,
          height = 64,
          shift = { 0, -0.05 },
        },
        west = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-converter.png",
          priority = "extra-high",
          x = 192,
          frame_count = 1,
          width = 64,
          height = 64,
          shift = { 0, 0 },
        },
      },
    },
    impact_category = "metal",
    repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
    open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
    close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  },
})
