data:extend({
  {
    type = "item",
    name = "angels-flare-stack",
    icon = "__angelspetrochemgraphics__/graphics/icons/flare-stack.png",
    icon_size = 64,
    subgroup = "angels-petrochem-buildings-steam",
    order = "b[angels-flare-stack]",
    place_result = "angels-flare-stack",
    stack_size = 10,
  },
  {
    type = "furnace",
    name = "angels-flare-stack",
    icon = "__angelspetrochemgraphics__/graphics/icons/flare-stack.png",
    icon_size = 64,
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("furnace", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-flare-stack" },
    max_health = 100,
    fast_replaceable_group = "angels-flare-stack",
    corpse = "small-remnants",
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -1, -1 }, { 1, 1 } },
    drawing_box_vertical_extension = 4,
    crafting_categories = { "angels-chemical-void" },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "pollution" },
    result_inventory_size = 0,
    source_inventory_size = 0,
    crafting_speed = 2,
    show_recipe_icon = false,
    resistances = {
      {
        type = "fire",
        percent = 80,
      },
      {
        type = "explosion",
        percent = 30,
      },
    },
    forced_symmetry = "horizontal",
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = {
          { flow_direction = "input", position = { 0.5, 0.5 }, direction = defines.direction.south },
        },
      },
    },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 15 },
    },
    energy_usage = "30kW",
    graphics_set = {
      animation = {
        north = {
          layers = {
            {
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack.png",
              priority = "extra-high",
              frame_count = 1,
              width = 142,
              height = 429,
              shift = util.by_pixel(0, -65),
              scale = 0.5,
            },
            {
              draw_as_shadow = true,
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-shadow.png",
              priority = "extra-high",
              width = 382,
              height = 135,
              frame_count = 1,
              shift = util.by_pixel(61, 10),
              scale = 0.5,
            },
          },
        },
        east = {
          layers = {
            {
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack.png",
              priority = "extra-high",
              width = 142,
              height = 429,
              x = 142,
              frame_count = 1,
              shift = util.by_pixel(0, -65),
              scale = 0.5,
            },
            {
              draw_as_shadow = true,
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-shadow.png",
              priority = "extra-high",
              width = 382,
              height = 135,
              x = 382,
              frame_count = 1,
              shift = util.by_pixel(61, 10),
              scale = 0.5,
            },
          },
        },
        south = {
          layers = {
            {
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack.png",
              priority = "extra-high",
              width = 142,
              height = 429,
              x = 284,
              frame_count = 1,
              shift = util.by_pixel(0, -65),
              scale = 0.5,
            },
            {
              draw_as_shadow = true,
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-shadow.png",
              priority = "extra-high",
              width = 382,
              height = 135,
              x = 764,
              frame_count = 1,
              shift = util.by_pixel(61, 10),
              scale = 0.5,
            },
          },
        },
        west = {
          layers = {
            {
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack.png",
              priority = "extra-high",
              width = 142,
              height = 429,
              x = 426,
              frame_count = 1,
              shift = util.by_pixel(0, -65),
              scale = 0.5,
            },
            {
              draw_as_shadow = true,
              filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-shadow.png",
              priority = "extra-high",
              width = 382,
              height = 135,
              x = 1146,
              frame_count = 1,
              shift = util.by_pixel(61, 10),
              scale = 0.5,
            },
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          constant_speed = true,
          north_position = util.by_pixel(-3, -166),
          east_position = util.by_pixel(-3, -170),
          south_position = util.by_pixel(3, -170),
          west_position = util.by_pixel(3, -166),
          animation = {
            filename = "__base__/graphics/entity/oil-refinery/oil-refinery-fire.png",
            line_length = 10,
            width = 40,
            height = 81,
            frame_count = 60,
            animation_speed = 0.75,
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          north_animation = {
            filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-light.png",
            priority = "extra-high",
            width = 142,
            height = 429,
            frame_count = 1,
            shift = util.by_pixel(0, -65),
            blend_mode = "additive-soft",
            draw_as_glow = true,
            scale = 0.5,
          },
          east_animation = {
            filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-light.png",
            priority = "extra-high",
            width = 142,
            height = 429,
            x = 142,
            frame_count = 1,
            shift = util.by_pixel(0, -65),
            blend_mode = "additive-soft",
            draw_as_glow = true,
            scale = 0.5,
          },
          south_animation = {
            filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-light.png",
            priority = "extra-high",
            width = 142,
            height = 429,
            x = 284,
            frame_count = 1,
            shift = util.by_pixel(0, -65),
            blend_mode = "additive-soft",
            draw_as_glow = true,
            scale = 0.5,
          },
          west_animation = {
            filename = "__angelspetrochemgraphics__/graphics/entity/flare-stack/flare-stack-light.png",
            priority = "extra-high",
            width = 142,
            height = 429,
            x = 426,
            frame_count = 1,
            shift = util.by_pixel(0, -65),
            blend_mode = "additive-soft",
            draw_as_glow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
    open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
    close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  },
})
