data:extend({
  --CHECK VALVE
  {
    type = "item",
    name = "angels-valve-inspector",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-inspector.png",
    icon_size = 32,
    subgroup = "angels-fluid-control",
    order = "a[valve]-a[valve-inspector]",
    place_result = "angels-valve-inspector",
    stack_size = 10,
  },
  {
    type = "storage-tank",
    name = "angels-valve-inspector",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-inspector.png",
    icon_size = 32,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-valve-inspector" },
    max_health = 100,
    corpse = "small-remnants",
    resistances = {
      {
        type = "fire",
        percent = 80,
      },
      {
        type = "explosion",
        percent = 30,
      },
    },
    fast_replaceable_group = "pipe",
    two_direction_only = false,
    collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    flow_length_in_ticks = 10,
    fluid_box = {
      volume = 1000,
      pipe_covers = pipecoverspictures(),
      pipe_connections = {
        { position = { 0, -0 }, direction = defines.direction.north },
        { position = { 0, 0 }, direction = defines.direction.south },
      },
    },
    window_bounding_box = { { -0.125, 0.6875 }, { 0.1875, 1.1875 } },
    pictures = {
      picture = {
        north = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-inspector.png",
          priority = "extra-high",
          width = 64,
          height = 64,
          shift = { 0, -0 },
        },
        east = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-inspector.png",
          priority = "extra-high",
          x = 64,
          width = 64,
          height = 64,
          shift = { 0, 0 },
        },
        south = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-inspector.png",
          priority = "extra-high",
          x = 128,
          width = 64,
          height = 64,
          shift = { 0, -0.05 },
        },
        west = {
          filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-inspector.png",
          priority = "extra-high",
          x = 192,
          width = 64,
          height = 64,
          shift = { 0, 0 },
        },
      },
    },
    impact_category = "metal",
    repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
    open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
    close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
    circuit_connector = circuit_connector_definitions["offshore-pump"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
  },
  --RETURN VALVE
  {
    type = "item",
    name = "angels-valve-one-way",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-return.png",
    icon_size = 32,
    subgroup = "angels-fluid-control",
    order = "a[valve]-b[valve-one-way]",
    place_result = "angels-valve-one-way",
    stack_size = 10,
  },
  {
    type = "valve",
    name = "angels-valve-one-way",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-return.png",
    icon_size = 32,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-valve-one-way" },
    max_health = 100,
    corpse = "small-remnants",
    resistances = {
      {
        type = "fire",
        percent = 80,
      },
      {
        type = "explosion",
        percent = 30,
      },
    },
    fast_replaceable_group = "pipe",
    collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    mode = "one-way",
    flow_rate = 20,
    fluid_box = {
      volume = 1000,
      pipe_covers = pipecoverspictures(),
      pipe_connections = {
        { flow_direction = "input-output", position = { 0, -0 }, direction = defines.direction.north },
        { flow_direction = "output", position = { 0, 0 }, direction = defines.direction.south },
      },
    },
    animations = {
      north = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-return.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        shift = { 0, -0 },
      },
      east = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-return.png",
        priority = "extra-high",
        x = 64,
        width = 64,
        height = 64,
        shift = { 0, 0 },
      },
      south = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-return.png",
        priority = "extra-high",
        x = 128,
        width = 64,
        height = 64,
        shift = { 0, -0.05 },
      },
      west = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-return.png",
        priority = "extra-high",
        x = 192,
        width = 64,
        height = 64,
        shift = { 0, 0 },
      },
    },
    impact_category = "metal",
    repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
    open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
    close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  },
  --OVERFLOW VALVE
  {
    type = "item",
    name = "angels-valve-overflow",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-overflow.png",
    icon_size = 32,
    subgroup = "angels-fluid-control",
    order = "a[valve]-c[valve-overflow]",
    place_result = "angels-valve-overflow",
    stack_size = 10,
  },
  {
    type = "valve",
    name = "angels-valve-overflow",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-overflow.png",
    icon_size = 32,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-valve-overflow" },
    max_health = 100,
    corpse = "small-remnants",
    resistances = {
      {
        type = "fire",
        percent = 80,
      },
      {
        type = "explosion",
        percent = 30,
      },
    },
    fast_replaceable_group = "pipe",
    collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    mode = "overflow",
    threshold = 0.8,
    flow_rate = 20,
    fluid_box = {
      volume = 1000,
      pipe_covers = pipecoverspictures(),
      pipe_connections = {
        { flow_direction = "input-output", position = { 0, -0 }, direction = defines.direction.north },
        { flow_direction = "output", position = { 0, 0 }, direction = defines.direction.south },
      },
    },
    animations = {
      north = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-overflow.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        shift = { 0, -0 },
      },
      east = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-overflow.png",
        priority = "extra-high",
        x = 64,
        width = 64,
        height = 64,
        shift = { 0, 0 },
      },
      south = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-overflow.png",
        priority = "extra-high",
        x = 128,
        width = 64,
        height = 64,
        shift = { 0, -0.05 },
      },
      west = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-overflow.png",
        priority = "extra-high",
        x = 192,
        width = 64,
        height = 64,
        shift = { 0, 0 },
      },
    },
    impact_category = "metal",
    repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
    open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
    close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  },
  --UNDERFLOW VALVE
  {
    type = "item",
    name = "angels-valve-top-up",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-underflow.png",
    icon_size = 32,
    subgroup = "angels-fluid-control",
    order = "a[valve]-d[valve-top-up]",
    place_result = "angels-valve-top-up",
    stack_size = 10,
  },
  {
    type = "valve",
    name = "angels-valve-top-up",
    icon = "__angelspetrochemgraphics__/graphics/icons/valve-underflow.png",
    icon_size = 32,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-valve-top-up" },
    max_health = 100,
    corpse = "small-remnants",
    resistances = {
      {
        type = "fire",
        percent = 80,
      },
      {
        type = "explosion",
        percent = 30,
      },
    },
    fast_replaceable_group = "pipe",
    collision_box = { { -0.29, -0.29 }, { 0.29, 0.29 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    mode = "top-up",
    threshold = 0.8,
    flow_rate = 20,
    fluid_box = {
      volume = 1000,
      pipe_covers = pipecoverspictures(),
      pipe_connections = {
        { flow_direction = "input-output", position = { 0, -0 }, direction = defines.direction.north },
        { flow_direction = "output", position = { 0, 0 }, direction = defines.direction.south },
      },
    },
    animations = {
      north = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-underflow.png",
        priority = "extra-high",
        width = 64,
        height = 64,
        shift = { 0, -0 },
      },
      east = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-underflow.png",
        priority = "extra-high",
        x = 64,
        width = 64,
        height = 64,
        shift = { 0, 0 },
      },
      south = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-underflow.png",
        priority = "extra-high",
        x = 128,
        width = 64,
        height = 64,
        shift = { 0, -0.05 },
      },
      west = {
        filename = "__angelspetrochemgraphics__/graphics/entity/valve/valve-underflow.png",
        priority = "extra-high",
        x = 192,
        width = 64,
        height = 64,
        shift = { 0, 0 },
      },
    },
    impact_category = "metal",
    repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
    open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
    close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  },
})