data:extend({
  {
    type = "item",
    name = "angels-inserter",
    icon = "__base__/graphics/icons/inserter.png",
    flags = { "goes-to-quickbar" },
    place_result = "angels-inserter",
    stack_size = 50,
  },
  {
    type = "inserter",
    name = "angels-inserter",
    icon = "__base__/graphics/icons/inserter.png",
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-inserter" },
    max_health = 40,
    corpse = "small-remnants",
    resistances = {
      {
        type = "fire",
        percent = 90,
      },
    },
    collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
    selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
    pickup_position = { 0, -1 },
    insert_position = { 0, 1.2 },
    energy_per_movement = 10000,
    energy_per_rotation = 10000,
    extension_speed = 0.03,
    rotation_speed = 0.014,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      drain = "0kW",
    },
    fast_replaceable_group = "inserter",
    vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
    working_sound = {
      match_progress_to_activity = true,
      sound = {
        {
          filename = "__base__/sound/inserter-basic-1.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-2.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-3.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-4.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-5.ogg",
          volume = 0.75,
        },
      },
    },
    hand_base_picture = {
      filename = "__base__/graphics/entity/inserter/inserter-hand-base.png",
      priority = "extra-high",
      width = 8,
      height = 33,
    },
    hand_closed_picture = {
      filename = "__base__/graphics/entity/inserter/inserter-hand-closed.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    hand_open_picture = {
      filename = "__base__/graphics/entity/inserter/inserter-hand-open.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    hand_base_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed-shadow.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    hand_open_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open-shadow.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    platform_picture = {
      sheet = {
        filename = "__base__/graphics/entity/inserter/inserter-platform.png",
        priority = "extra-high",
        width = 46,
        height = 46,
        shift = { 0.09375, 0 },
      },
    },
    circuit_wire_connection_point = inserter_circuit_wire_connection_point,
    circuit_connector_sprites = inserter_circuit_connector_sprites,
    circuit_wire_max_distance = inserter_circuit_wire_max_distance,
  },
  {
    type = "item",
    name = "angels-long-inserter",
    icon = "__base__/graphics/icons/inserter.png",
    flags = { "goes-to-quickbar" },
    place_result = "angels-long-inserter",
    stack_size = 10,
  },
  {
    type = "inserter",
    name = "angels-long-inserter",
    icon = "__base__/graphics/icons/inserter.png",
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-long-inserter" },
    max_health = 40,
    corpse = "small-remnants",
    resistances = {
      {
        type = "fire",
        percent = 90,
      },
    },
    collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
    selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
    pickup_position = { 0, -2 },
    insert_position = { 0, 2.2 },
    energy_per_movement = 10000,
    energy_per_rotation = 10000,
    rotation_speed = 0.02,
    extension_speed = 0.0457,
    hand_size = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      drain = "0kW",
    },
    extension_speed = 0.03,
    rotation_speed = 0.014,
    fast_replaceable_group = "inserter",
    vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
    working_sound = {
      match_progress_to_activity = true,
      sound = {
        {
          filename = "__base__/sound/inserter-basic-1.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-2.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-3.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-4.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-5.ogg",
          volume = 0.75,
        },
      },
    },
    hand_base_picture = {
      filename = "__base__/graphics/entity/long-handed-inserter/long-handed-inserter-hand-base.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_picture = {
      filename = "__base__/graphics/entity/long-handed-inserter/long-handed-inserter-hand-closed.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    hand_open_picture = {
      filename = "__base__/graphics/entity/long-handed-inserter/long-handed-inserter-hand-open.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    hand_base_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed-shadow.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    hand_open_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open-shadow.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    platform_picture = {
      sheet = {
        filename = "__base__/graphics/entity/inserter/inserter-platform.png",
        priority = "extra-high",
        width = 46,
        height = 46,
        shift = { 0.09375, 0 },
      },
    },
    circuit_wire_connection_point = inserter_circuit_wire_connection_point,
    circuit_connector_sprites = inserter_circuit_connector_sprites,
    circuit_wire_max_distance = inserter_circuit_wire_max_distance,
  },
  {
    type = "item",
    name = "angels-filter-inserter",
    icon = "__base__/graphics/icons/inserter.png",
    flags = { "goes-to-quickbar" },
    place_result = "angels-filter-inserter",
    stack_size = 10,
  },
  {
    type = "inserter",
    name = "angels-filter-inserter",
    icon = "__base__/graphics/icons/inserter.png",
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-filter-inserter" },
    max_health = 40,
    corpse = "small-remnants",
    resistances = {
      {
        type = "fire",
        percent = 90,
      },
    },
    collision_box = { { -0.15, -0.15 }, { 0.15, 0.15 } },
    selection_box = { { -0.4, -0.35 }, { 0.4, 0.45 } },
    pickup_position = { 0, -1 },
    insert_position = { 0, 1.2 },
    energy_per_movement = 10000,
    energy_per_rotation = 10000,
    extension_speed = 0.03,
    rotation_speed = 0.014,
    filter_count = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      drain = "10kW",
    },
    fast_replaceable_group = "inserter",
    vehicle_impact_sound = { filename = "__base__/sound/car-metal-impact.ogg", volume = 0.65 },
    working_sound = {
      match_progress_to_activity = true,
      sound = {
        {
          filename = "__base__/sound/inserter-basic-1.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-2.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-3.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-4.ogg",
          volume = 0.75,
        },
        {
          filename = "__base__/sound/inserter-basic-5.ogg",
          volume = 0.75,
        },
      },
    },
    hand_base_picture = {
      filename = "__base__/graphics/entity/stack-filter-inserter/stack-filter-inserter-hand-base.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_picture = {
      filename = "__base__/graphics/entity/stack-filter-inserter/stack-filter-inserter-hand-closed.png",
      priority = "extra-high",
      width = 24,
      height = 41,
    },
    hand_open_picture = {
      filename = "__base__/graphics/entity/stack-filter-inserter/stack-filter-inserter-hand-open.png",
      priority = "extra-high",
      width = 32,
      height = 41,
    },
    hand_base_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-base-shadow.png",
      priority = "extra-high",
      width = 8,
      height = 34,
    },
    hand_closed_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-closed-shadow.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    hand_open_shadow = {
      filename = "__base__/graphics/entity/burner-inserter/burner-inserter-hand-open-shadow.png",
      priority = "extra-high",
      width = 18,
      height = 41,
    },
    platform_picture = {
      sheet = {
        filename = "__base__/graphics/entity/inserter/inserter-platform.png",
        priority = "extra-high",
        width = 46,
        height = 46,
        shift = { 0.09375, 0 },
      },
    },
    circuit_wire_connection_point = inserter_circuit_wire_connection_point,
    circuit_connector_sprites = inserter_circuit_connector_sprites,
    circuit_wire_max_distance = inserter_circuit_wire_max_distance,
  },
})
