data:extend(
{
  --CASING
  {
    type = "item",
    name = "casing-1",
    icon = "__angelsindustries__/graphics/icons/motor-1.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-casing",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "casing-2",
    icon = "__angelsindustries__/graphics/icons/motor-2.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-casing",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "casing-3",
    icon = "__angelsindustries__/graphics/icons/motor-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-casing",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "casing-4",
    icon = "__angelsindustries__/graphics/icons/motor-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-casing",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "casing-5",
    icon = "__angelsindustries__/graphics/icons/motor-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-casing",
    order = "e",
    stack_size = 200,
  },
  --ELECTRIC MOTOR
  {
    type = "item",
    name = "motor-1",
    icon = "__angelsindustries__/graphics/icons/motor-1.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-motors",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "motor-2",
    icon = "__angelsindustries__/graphics/icons/motor-2.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-motors",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "motor-3",
    icon = "__angelsindustries__/graphics/icons/motor-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-motors",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "motor-4",
    icon = "__angelsindustries__/graphics/icons/motor-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-motors",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "motor-5",
    icon = "__angelsindustries__/graphics/icons/motor-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-motors",
    order = "e",
    stack_size = 200,
  },
  --SUBCOMPONENTS
  {
    type = "item",
    name = "angels-gear",
    icon = "__angelsindustries__/graphics/icons/gear.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-axle",
    icon = "__angelsindustries__/graphics/icons/axle.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-roller-chain",
    icon = "__angelsindustries__/graphics/icons/roller-chain.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-spring",
    icon = "__angelsindustries__/graphics/icons/spring.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-bearing",
    icon = "__angelsindustries__/graphics/icons/bearing.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "e",
    stack_size = 200,
  },
  --MECHANICAL PARTS
  {
    type = "item",
    name = "mechanical-parts",
    icon = "__angelsindustries__/graphics/icons/mechanical-parts.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "f",
    stack_size = 200,
  },
}
)
