data:extend(
{
  --COMPONENTS
  {
    type = "item",
    name = "grate-iron",
    icon = "__angelsindustries__/graphics/icons/grate-iron.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-grates",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "grate-steel",
    icon = "__angelsindustries__/graphics/icons/grate-steel.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-grates",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "grate-aluminium",
    icon = "__angelsindustries__/graphics/icons/grate-aluminium.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-grates",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "grate-titanium",
    icon = "__angelsindustries__/graphics/icons/grate-titanium.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-grates",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "grate-tungsten",
    icon = "__angelsindustries__/graphics/icons/grate-tungsten.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-grates",
    order = "e",
    stack_size = 200,
  },
  --CONSTRUCTION FRAMES
  {
    type = "item",
    name = "construction-frame-1",
    icon = "__angelsindustries__/graphics/icons/construction-frame-1.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-frames",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "construction-frame-2",
    icon = "__angelsindustries__/graphics/icons/construction-frame-2.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-frames",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "construction-frame-3",
    icon = "__angelsindustries__/graphics/icons/construction-frame-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-frames",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "construction-frame-4",
    icon = "__angelsindustries__/graphics/icons/construction-frame-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-frames",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "construction-frame-5",
    icon = "__angelsindustries__/graphics/icons/construction-frame-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-frames",
    order = "e",
    stack_size = 200,
  },
  --CONSTRUCTION PARTS
  {
    type = "item",
    name = "angels-girder",
    icon = "__angelsindustries__/graphics/icons/girder.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-components",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-rivet",
    icon = "__angelsindustries__/graphics/icons/rivet.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-components",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-plating",
    icon = "__angelsindustries__/graphics/icons/plating.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-components",
    order = "c",
    stack_size = 200,
  },
  --CONSTRUCTION COMPONENTS
  {
    type = "item",
    name = "construction-components",
    icon = "__angelsindustries__/graphics/icons/construction-components.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-construction-components",
    order = "f",
    stack_size = 200,
  },
}
)
