data:extend(
{
  {
    type = "item",
    name = "block-empty-1",
    icon = "__angelsindustries__/graphics/icons/block-empty-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "a",
    stack_size = 200,
  }, 
  {
    type = "item",
    name = "block-empty-2",
    icon = "__angelsindustries__/graphics/icons/block-empty-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-empty-3",
    icon = "__angelsindustries__/graphics/icons/block-empty-3.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "c",
    stack_size = 200,
  }, 
  {
    type = "item",
    name = "block-empty-4",
    icon = "__angelsindustries__/graphics/icons/block-empty-4.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "d",
    stack_size = 200,
  }, 
  {
    type = "item",
    name = "block-empty-5",
    icon = "__angelsindustries__/graphics/icons/block-empty-5.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "e",
    stack_size = 200,
  }, 
  {
    type = "item",
    name = "block-fluidbox-1",
    icon = "__angelsindustries__/graphics/icons/block-fluidbox.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "f",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-fluidbox-2",
    icon = "__angelsindustries__/graphics/icons/block-fluidbox.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "g",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-mechanical-1",
    icon = "__angelsindustries__/graphics/icons/block-mechanical.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "h",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-mechanical-2",
    icon = "__angelsindustries__/graphics/icons/block-mechanical.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "i",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-base-1",
    icon = "__angelsindustries__/graphics/icons/block-base-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "j",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-base-2",
    icon = "__angelsindustries__/graphics/icons/block-base-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "k",
    stack_size = 200,
  },
--REFINING
  {
    type = "item",
    name = "block-refining-1",
    icon = "__angelsindustries__/graphics/icons/block-refining-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-refining",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-refining-2",
    icon = "__angelsindustries__/graphics/icons/block-refining-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-refining",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-refining-3",
    icon = "__angelsindustries__/graphics/icons/block-refining-3.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-refining",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-refining-4",
    icon = "__angelsindustries__/graphics/icons/block-refining-4.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-refining",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-refining-5",
    icon = "__angelsindustries__/graphics/icons/block-refining-5.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-refining",
    order = "e",
    stack_size = 200,
  },
--PETROCHEM
  {
    type = "item",
    name = "block-petrochem-1",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-petrochem",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-petrochem-2",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-petrochem",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-petrochem-3",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-3.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-petrochem",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-petrochem-4",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-4.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-petrochem",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-petrochem-5",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-5.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-petrochem",
    order = "e",
    stack_size = 200,
  },
--SMELTING
  {
    type = "item",
    name = "block-smelting-1",
    icon = "__angelsindustries__/graphics/icons/block-smelting-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-smelting",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-smelting-2",
    icon = "__angelsindustries__/graphics/icons/block-smelting-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-smelting",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-smelting-3",
    icon = "__angelsindustries__/graphics/icons/block-smelting-3.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-smelting",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-smelting-4",
    icon = "__angelsindustries__/graphics/icons/block-smelting-4.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-smelting",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-smelting-5",
    icon = "__angelsindustries__/graphics/icons/block-smelting-5.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-smelting",
    order = "e",
    stack_size = 200,
  },
}
)
