data:extend(
{
  --CONSTRUCTIOn
  {
    type = "item",
    name = "block-construction-1",
    icon = "__angelsindustries__/graphics/icons/block-construction-1.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-construction-2",
    icon = "__angelsindustries__/graphics/icons/block-construction-2.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-construction-3",
    icon = "__angelsindustries__/graphics/icons/block-construction-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-construction-4",
    icon = "__angelsindustries__/graphics/icons/block-construction-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-construction-5",
    icon = "__angelsindustries__/graphics/icons/block-construction-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-frames",
    order = "e",
    stack_size = 200,
  },
  --CONSTRUCTIOn
  {
    type = "item",
    name = "block-electronics-1",
    icon = "__angelsindustries__/graphics/icons/block-construction-1.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-electronics",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-electronics-2",
    icon = "__angelsindustries__/graphics/icons/block-construction-2.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-electronics",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-electronics-3",
    icon = "__angelsindustries__/graphics/icons/block-construction-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-electronics",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-electronics-4",
    icon = "__angelsindustries__/graphics/icons/block-construction-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-electronics",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-electronics-5",
    icon = "__angelsindustries__/graphics/icons/block-construction-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-electronics",
    order = "e",
    stack_size = 200,
  },
  --FLUIDBOX
  {
    type = "item",
    name = "block-fluidbox-1",
    icon = "__angelsindustries__/graphics/icons/block-fluidbox.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "f",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-fluidbox-2",
    icon = "__angelsindustries__/graphics/icons/block-fluidbox.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "g",
    stack_size = 200,
  },
  --MECHANICAL
  {
    type = "item",
    name = "block-mechanical-1",
    icon = "__angelsindustries__/graphics/icons/block-mechanical.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "h",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-mechanical-2",
    icon = "__angelsindustries__/graphics/icons/block-mechanical.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-basic",
    order = "i",
    stack_size = 200,
  },
  --PRODUCTION, EXTRACTION, PROCESSING
  {
    type = "item",
    name = "block-production-1",
    icon = "__angelsindustries__/graphics/icons/block-refining-1.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-production-2",
    icon = "__angelsindustries__/graphics/icons/block-refining-2.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-extraction-3",
    icon = "__angelsindustries__/graphics/icons/block-smelting-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-extraction-4",
    icon = "__angelsindustries__/graphics/icons/block-smelting-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-extraction-5",
    icon = "__angelsindustries__/graphics/icons/block-smelting-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "e",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-mprocessing-3",
    icon = "__angelsindustries__/graphics/icons/block-refining-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "f",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-mprocessing-4",
    icon = "__angelsindustries__/graphics/icons/block-refining-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "g",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-mprocessing-5",
    icon = "__angelsindustries__/graphics/icons/block-refining-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "h",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-cprocessing-3",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "i",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-cprocessing-4",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "j",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-cprocessing-5",
    icon = "__angelsindustries__/graphics/icons/block-petrochem-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "k",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-bprocessing-3",
    icon = "__angelsindustries__/graphics/icons/block-smelting-3.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "l",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-bprocessing-4",
    icon = "__angelsindustries__/graphics/icons/block-smelting-4.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "m",
    stack_size = 200,
  },
  {
    type = "item",
    name = "block-bprocessing-5",
    icon = "__angelsindustries__/graphics/icons/block-smelting-5.png",
    icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "blocks-processing",
    order = "n",
    stack_size = 200,
  },
}
)
