data:extend(
{
--ELECTRIC MOTOR
  {
    type = "item",
    name = "electric-motor-1",
    icon = "__angelsindustries__/graphics/icons/electric-motor-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-cable-harness",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "electric-motor-2",
    icon = "__angelsindustries__/graphics/icons/electric-motor-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-cable-harness",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "electric-motor-3",
    icon = "__angelsindustries__/graphics/icons/electric-motor-3.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-cable-harness",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "electric-motor-4",
    icon = "__angelsindustries__/graphics/icons/electric-motor-4.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-cable-harness",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "electric-motor-5",
    icon = "__angelsindustries__/graphics/icons/electric-motor-5.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-cable-harness",
    order = "e",
    stack_size = 200,
  },
--MECHANICAL PARTS
  {
    type = "item",
    name = "mechanical-parts-1",
    icon = "__angelsindustries__/graphics/icons/mechanical-parts-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "mechanical-parts-2",
    icon = "__angelsindustries__/graphics/icons/mechanical-parts-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "mechanical-parts-3",
    icon = "__angelsindustries__/graphics/icons/mechanical-parts-3.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "mechanical-parts-4",
    icon = "__angelsindustries__/graphics/icons/mechanical-parts-4.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "mechanical-parts-5",
    icon = "__angelsindustries__/graphics/icons/mechanical-parts-5.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-parts",
    order = "e",
    stack_size = 200,
  },
  --SUBCOMPONENTS
  {
    type = "item",
    name = "angels-gear",
    icon = "__angelsindustries__/graphics/icons/gear.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-subcomponents",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-axle",
    icon = "__angelsindustries__/graphics/icons/axle.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-subcomponents",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-roller-chain",
    icon = "__angelsindustries__/graphics/icons/roller-chain.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-subcomponents",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-spring",
    icon = "__angelsindustries__/graphics/icons/spring.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-subcomponents",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-bearing",
    icon = "__angelsindustries__/graphics/icons/bearing.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-mechanical-subcomponents",
    order = "e",
    stack_size = 200,
  },
}
)
