data:extend(
{
--DATACORES
  {
    type = "tool",
    name = "datacore-exploration-1",
    icon = "__angelsindustries__/graphics/icons/datacore-exploration-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-1",
    order = "a[datacore-exploration-1]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-exploration-2",
    icon = "__angelsindustries__/graphics/icons/datacore-exploration-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-2",
    order = "a[datacore-exploration-2]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-basic",
    icon = "__angelsindustries__/graphics/icons/datacore-basic.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-1",
    order = "g[datacore-basic]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-enhance-1",
    icon = "__angelsindustries__/graphics/icons/datacore-enhance-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-1",
    order = "b[datacore-enhance-1]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-enhance-2",
    icon = "__angelsindustries__/graphics/icons/datacore-enhance-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-2",
    order = "b[datacore-enhance-2]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-energy-1",
    icon = "__angelsindustries__/graphics/icons/datacore-energy-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-1",
    order = "c[datacore-energy-1]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-energy-2",
    icon = "__angelsindustries__/graphics/icons/datacore-energy-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-2",
    order = "c[datacore-energy-2]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-logistic-1",
    icon = "__angelsindustries__/graphics/icons/datacore-logistic-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-1",
    order = "d[datacore-logistic-1]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-logistic-2",
    icon = "__angelsindustries__/graphics/icons/datacore-logistic-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-2",
    order = "d[datacore-logistic-2]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-processing-1",
    icon = "__angelsindustries__/graphics/icons/datacore-processing-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-1",
    order = "e[datacore-processing-1]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-processing-2",
    icon = "__angelsindustries__/graphics/icons/datacore-processing-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-2",
    order = "e[datacore-processing-2]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-war-1",
    icon = "__angelsindustries__/graphics/icons/datacore-war-1.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-1",
    order = "f[datacore-war-1]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "datacore-war-2",
    icon = "__angelsindustries__/graphics/icons/datacore-war-2.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-datacore-2",
    order = "f[datacore-war-2]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
--SCIENCE PACK
  {
    type = "tool",
    name = "angels-science-pack-grey",
    icon = "__angelsindustries__/graphics/icons/science-pack-grey.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-science-pack",
    order = "a[science-pack-grey]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "angels-science-pack-red",
    icon = "__angelsindustries__/graphics/icons/science-pack-red.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-science-pack",
    order = "b[science-pack-red]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "angels-science-pack-green",
    icon = "__angelsindustries__/graphics/icons/science-pack-green.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-science-pack",
    order = "c[science-pack-green]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "angels-science-pack-orange",
    icon = "__angelsindustries__/graphics/icons/science-pack-orange.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-science-pack",
    order = "d[science-pack-orange]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "angels-science-pack-blue",
    icon = "__angelsindustries__/graphics/icons/science-pack-blue.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-science-pack",
    order = "e[science-pack-blue]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
  {
    type = "tool",
    name = "angels-science-pack-yellow",
    icon = "__angelsindustries__/graphics/icons/science-pack-yellow.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
    subgroup = "angels-science-pack",
    order = "f[science-pack-yellow]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount"
  },
--COMPONENTS
  {
    type = "item",
    name = "science-data-analyzer",
    icon = "__angelsindustries__/graphics/icons/science-data-analyzer.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
	subgroup = "angels-pack-components",
    order = "a",
    stack_size = 200
  },
  {
    type = "item",
    name = "science-force-analyzer",
    icon = "__angelsindustries__/graphics/icons/science-force-analyzer.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
	subgroup = "angels-pack-components",
    order = "b",
    stack_size = 200
  },
  {
    type = "item",
    name = "science-harmonics-analyzer",
    icon = "__angelsindustries__/graphics/icons/science-harmonics-analyzer.png",
	icon_size = 32,
    flags = {"goes-to-main-inventory"},
	subgroup = "angels-pack-components",
    order = "c",
    stack_size = 200
  },
}
)
