data:extend({
  ---------------------------------------------------------------------------
  -- TIER 1 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-ore1-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore1/angels-ore1-crushed.png",
    icon_size = 32,
    pictures = {
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-1.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-2.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-3.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-4.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-5.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-6.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-7.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-8.png",
        scale = 0.5,
        tint = { r = 60 / 255, g = 84 / 255, b = 116 / 255 },
      },
    },
    subgroup = "angels-ore-processing-a",
    order = "a[angels-ore1-crushed]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore2-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore2/angels-ore2-crushed.png",
    icon_size = 32,
    pictures = {
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-1.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-2.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-3.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-4.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-5.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-6.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-7.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-8.png",
        scale = 0.5,
        tint = { r = 0.55, g = 0.51, b = 0.30 },
      },
    },
    subgroup = "angels-ore-processing-a",
    order = "b[angels-ore1-crushed]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore3-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore3/angels-ore3-crushed.png",
    icon_size = 32,
    pictures = {
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-1.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-2.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-3.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-4.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-5.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-6.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-7.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-8.png",
        scale = 0.5,
        tint = { r = 0.42, g = 0.71, b = 0.86 },
      },
    },
    subgroup = "angels-ore-processing-a",
    order = "c[angels-ore1-crushed]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore4-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore4/angels-ore4-crushed.png",
    icon_size = 32,
    pictures = {
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-1.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-2.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-3.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-4.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-5.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-6.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-7.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-8.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
    },
    subgroup = "angels-ore-processing-a",
    order = "d[angels-ore1-crushed]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore5-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore5/angels-ore5-crushed.png",
    icon_size = 32,
    pictures = {
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-1.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-2.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-3.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-4.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-5.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-6.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-7.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-8.png",
        scale = 0.5,
        tint = { r = 0.68, g = 0.18, b = 0.16 },
      },
    },
    subgroup = "angels-ore-processing-a",
    order = "e[angels-ore1-crushed]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore6-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore6/angels-ore6-crushed.png",
    icon_size = 32,
    pictures = {
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-1.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-2.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-3.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-4.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-5.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-6.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-7.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-8.png",
        scale = 0.5,
        tint = { r = 0.75, g = 0.5, b = 0.25 },
      },
    },
    subgroup = "angels-ore-processing-a",
    order = "f[angels-ore1-crushed]",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- TIER 1.5 ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-ore8-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore8-crushed.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-a",
    order = "g",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore8-powder",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore8-powder.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-a",
    order = "h",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore9-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore9-crushed.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-a",
    order = "i",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore9-powder",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore9-powder.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-a",
    order = "j",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- TIER 2 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-ore1-chunk",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore1/angels-ore1-chunk.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "a[angels-ore1-chunk]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore2-chunk",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore2/angels-ore2-chunk.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "b[angels-ore2-chunk]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore3-chunk",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore3/angels-ore3-chunk.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "c[angels-ore3-chunk]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore4-chunk",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore4/angels-ore4-chunk.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "d[angels-ore4-chunk]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore5-chunk",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore5/angels-ore5-chunk.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "e[angels-ore5-chunk]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore6-chunk",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore6/angels-ore6-chunk.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "f[angels-ore6-chunk]",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- TIER 2.5 ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "fluid",
    name = "angels-ore8-sludge",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 104, 112, 113 }, { 104, 112, 113 }, { 133, 196, 060 }, { 133, 196, 060 } }
    ),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 132 / 255, g = 176 / 255, b = 11 / 255 },
    flow_color = { r = 132 / 255, g = 176 / 255, b = 11 / 255 },
    max_temperature = 0,
  },
  {
    type = "item",
    name = "angels-ore8-dust",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore8-dust.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "g",
    stack_size = 200,
  },
  {
    type = "fluid",
    name = "angels-ore9-sludge",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 095, 106, 090 }, { 095, 106, 090 }, { 254, 110, 022, 0.8 }, { 254, 110, 022, 0.8 } }
    ),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    --base_color = {r = 255 / 255, g = 119 / 255, b = 0 / 255},
    base_color = { r = 254 / 255, g = 110 / 255, b = 22 / 255 },
    --flow_color = {r = 255 / 255, g = 119 / 255, b = 0 / 255},
    flow_color = { r = 254 / 255, g = 110 / 255, b = 22 / 255 },
    max_temperature = 0,
  },
  {
    type = "item",
    name = "angels-ore9-dust",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore9-dust.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-b",
    order = "h",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- TIER 3 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-ore1-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore1/angels-ore1-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "a[angels-ore1-crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore2-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore2/angels-ore2-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "b[angels-ore2-crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore3-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore3/angels-ore3-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "c[angels-ore3-crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore4-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore4/angels-ore4-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "d[angels-ore4-crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore5-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore5/angels-ore5-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "e[angels-ore5-crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore6-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore6/angels-ore6-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "f[angels-ore6-crystal]",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- TIER 3.5 ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "fluid",
    name = "angels-ore8-solution",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(nil, { { 104, 112, 113 }, nil, { 133, 196, 060 } }),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 132 / 255, g = 176 / 255, b = 11 / 255 },
    flow_color = { r = 132 / 255, g = 176 / 255, b = 11 / 255 },
    max_temperature = 0,
  },
  {
    type = "fluid",
    name = "angels-ore8-anode-sludge",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 104, 112, 113 }, { 104, 112, 113 }, { 133, 196, 060, 0.7 }, { 165, 093, 051 } }
    ),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 132 / 255, g = 116 / 255, b = 11 / 255 },
    flow_color = { r = 132 / 255, g = 116 / 255, b = 11 / 255 },
    max_temperature = 0,
  },
  {
    type = "fluid",
    name = "angels-ore8-slime",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 133, 196, 060 }, nil, { 113, 224, 028, 0.9 } }
    ),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    --base_color = {r = 133 / 255, g = 196 / 255, b = 60 / 255},
    base_color = { r = 133 / 255, g = 224 / 255, b = 28 / 255 },
    --flow_color = {r = 133 / 255, g = 196 / 255, b = 60 / 255},
    flow_color = { r = 133 / 255, g = 224 / 255, b = 28 / 255 },
    max_temperature = 0,
  },
  {
    type = "item",
    name = "angels-ore8-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore8-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "g",
    stack_size = 200,
  },
  {
    type = "fluid",
    name = "angels-ore9-solution",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 095, 106, 090 }, nil, { 254, 110, 022, 0.8 } }
    ),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 254 / 255, g = 110 / 255, b = 22 / 255 },
    flow_color = { r = 254 / 255, g = 110 / 255, b = 22 / 255 },
    max_temperature = 0,
  },
  {
    type = "fluid",
    name = "angels-ore9-anode-sludge",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 095, 106, 090 }, { 095, 106, 090 }, { 254, 110, 022, 0.7 }, { 165, 093, 051 } }
    ),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 186 / 255, g = 110 / 255, b = 22 / 255 },
    flow_color = { r = 186 / 255, g = 110 / 255, b = 22 / 255 },
    max_temperature = 0,
  },
  {
    type = "fluid",
    name = "angels-ore9-slime",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 254, 110, 022 }, nil, { 252, 103, 005, 0.9 } }
    ),
    subgroup = "angels-fluids-refining",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 252 / 255, g = 103 / 255, b = 5 / 255 },
    flow_color = { r = 252 / 255, g = 103 / 255, b = 5 / 255 },
    max_temperature = 0,
  },
  {
    type = "item",
    name = "angels-ore9-crystal",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore9-crystal.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-c",
    order = "g",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- TIER 4 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-ore1-pure",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore1/angels-ore1-pure.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-d",
    order = "a[angels-ore1-pure]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore2-pure",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore2/angels-ore2-pure.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-d",
    order = "b[angels-ore2-pure]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore3-pure",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore3/angels-ore3-pure.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-d",
    order = "c[angels-ore3-pure]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore4-pure",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore4/angels-ore4-pure.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-d",
    order = "d[angels-ore4-pure]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore5-pure",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore5/angels-ore5-pure.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-d",
    order = "e[angels-ore5-pure]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-ore6-pure",
    icon = "__angelsrefininggraphics__/graphics/icons/angels-ore6/angels-ore6-pure.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-d",
    order = "f[angels-ore6-pure]",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- GEODES -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-geode-blue",
    icon = "__angelsrefininggraphics__/graphics/icons/geode-blue.png",
    icon_size = 32,
    subgroup = "angels-geode-processing-1",
    order = "a",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-geode-purple",
    icon = "__angelsrefininggraphics__/graphics/icons/geode-purple.png",
    icon_size = 32,
    subgroup = "angels-geode-processing-1",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-geode-yellow",
    icon = "__angelsrefininggraphics__/graphics/icons/geode-yellow.png",
    icon_size = 32,
    subgroup = "angels-geode-processing-1",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-geode-lightgreen",
    icon = "__angelsrefininggraphics__/graphics/icons/geode-lightgreen.png",
    icon_size = 32,
    subgroup = "angels-geode-processing-1",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-geode-cyan",
    icon = "__angelsrefininggraphics__/graphics/icons/geode-cyan.png",
    icon_size = 32,
    subgroup = "angels-geode-processing-1",
    order = "e",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-geode-red",
    icon = "__angelsrefininggraphics__/graphics/icons/geode-red.png",
    icon_size = 32,
    subgroup = "angels-geode-processing-1",
    order = "f",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-dust",
    icon = "__angelsrefininggraphics__/graphics/icons/crystal-dust.png",
    icon_size = 32,
    subgroup = "angels-geode-processing-1",
    order = "g",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- EXTRAS -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-stone-crushed",
    icon = "__angelsrefininggraphics__/graphics/icons/stone-crushed.png",
    icon_size = 32,
    pictures = {
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-1.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-2.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-3.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-4.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-5.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-6.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-7.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
      {
        size = 64,
        filename = "__angelsrefininggraphics__/graphics/icons/crushed/crushed-8.png",
        scale = 0.5,
        tint = { r = 164 / 255, g = 164 / 255, b = 164 / 255 },
      },
    },
    subgroup = "angels-slag-processing-1",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-milling-drum",
    icon = "__angelsrefininggraphics__/graphics/icons/milling-drum.png",
    icon_size = 32,
    subgroup = "angels-ore-powderizer",
    order = "z[milling-drum]-a[new]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-milling-drum-lubricated",
    icon = "__angelsrefininggraphics__/graphics/icons/milling-drum-lubricated.png",
    icon_size = 32,
    subgroup = "angels-ore-powderizer",
    order = "z[milling-drum]-b[lubricated]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-slag",
    icon = "__angelsrefininggraphics__/graphics/icons/slag.png",
    icon_size = 32,
    subgroup = "angels-slag-processing-1",
    order = "a",
    stack_size = 200,
  },
  {
    type = "fluid",
    name = "angels-slag-slurry",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(nil, { { 140, 073, 029 } }),
    subgroup = "angels-ore-sorting-fluid",
    order = "a[slag]-b[stone]",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 140 / 255, g = 73 / 255, b = 29 / 255 },
    flow_color = { r = 140 / 255, g = 73 / 255, b = 29 / 255 },
    max_temperature = 0,
  },
  {
    type = "fluid",
    name = "angels-mineral-sludge",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(nil, { { 230, 116, 017 }, { 135, 071, 028 } }),
    subgroup = "angels-ore-sorting-fluid",
    order = "b[mineral]",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 135 / 255, g = 71 / 255, b = 28 / 255 },
    flow_color = { r = 135 / 255, g = 71 / 255, b = 28 / 255 },
    max_temperature = 0,
  },
  {
    type = "item",
    name = "angels-filter-frame",
    icon = "__angelsrefininggraphics__/graphics/icons/filter-frame.png",
    icon_size = 32,
    subgroup = "angels-processing-crafting",
    order = "b[filter]-a[frame]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-filter-coal",
    icon = "__angelsrefininggraphics__/graphics/icons/filter-coal.png",
    icon_size = 32,
    subgroup = "angels-processing-crafting",
    order = "b[filter]-b[coal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-filter-ceramic",
    icon = "__angelsrefininggraphics__/graphics/icons/filter-ceramic.png",
    icon_size = 32,
    subgroup = "angels-processing-crafting",
    order = "b[filter]-c[ceramic]-a[new]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-filter-ceramic-used",
    icon = "__angelsrefininggraphics__/graphics/icons/filter-ceramic-used.png",
    icon_size = 32,
    subgroup = "angels-processing-crafting",
    order = "b[filter]-c[ceramic]-b[used]",
    stack_size = 200,
  },
  {
    type = "fluid",
    name = "angels-crystal-slurry",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 105, 237, 038 }, { 211, 255, 052 }, { 100, 255, 000 }, { 147, 207, 47 } }
    ),
    subgroup = "angels-ore-sorting-fluid",
    order = "c[crystal]-a",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 147 / 255, g = 207 / 255, b = 47 / 255 },
    flow_color = { r = 100 / 255, g = 255 / 255, b = 0 / 255 },
    max_temperature = 0,
  },
  {
    type = "fluid",
    name = "angels-crystal-seedling",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(nil, { { 105, 237, 038 }, nil, { 100, 255, 000 } }),
    subgroup = "angels-ore-sorting-fluid",
    order = "c[crystal]-b",
    default_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 105 / 255, g = 237 / 255, b = 38 / 255 },
    flow_color = { r = 100 / 255, g = 255 / 255, b = 0 / 255 },
    max_temperature = 0,
  },
  ---------------------------------------------------------------------------
  -- CATALYSTS --------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-catalysator-brown",
    icon = "__angelsrefininggraphics__/graphics/icons/catalysator-brown.png",
    icon_size = 32,
    subgroup = "angels-processing-crafting",
    order = "a[catalysator]-a[brown]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-catalysator-green",
    icon = "__angelsrefininggraphics__/graphics/icons/catalysator-green.png",
    icon_size = 32,
    subgroup = "angels-processing-crafting",
    order = "a[catalysator]-b[green]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-catalysator-orange",
    icon = "__angelsrefininggraphics__/graphics/icons/catalysator-orange.png",
    icon_size = 32,
    subgroup = "angels-processing-crafting",
    order = "a[catalysator]-c[orange]",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- VOID -------------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-void",
    icon = "__angelsrefininggraphics__/graphics/icons/void.png",
    icon_size = 32,
    hidden = true,
    subgroup = "angels-processing-crafting",
    stack_size = 200,
  },
  ---------------------------------------------------------------------------
  -- VANILLA ----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-iron-nugget",
    icon = "__angelsrefininggraphics__/graphics/icons/iron-nugget.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-t0",
    order = "b[angels-iron-nugget]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-iron-pebbles",
    icon = "__angelsrefininggraphics__/graphics/icons/iron-pebbles.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-t0",
    order = "a[angels-iron-pebbles]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-iron-slag",
    icon = "__angelsrefininggraphics__/graphics/icons/iron-slag.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-t0",
    order = "c[angels-iron-slag]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-copper-nugget",
    icon = "__angelsrefininggraphics__/graphics/icons/copper-nugget.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-t0",
    order = "e[angels-copper-nugget]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-copper-pebbles",
    icon = "__angelsrefininggraphics__/graphics/icons/copper-pebbles.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-t0",
    order = "d[angels-copper-pebbles]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-copper-slag",
    icon = "__angelsrefininggraphics__/graphics/icons/copper-slag.png",
    icon_size = 32,
    subgroup = "angels-ore-processing-t0",
    order = "f[angels-copper-slag]",
    stack_size = 200,
  },
})
