data:extend(
{
  {
    type = "item-group",
    name = "angels-components",
    order = "pa",
    inventory_order = "pa",
	icon_size = 64,
    icon = "__angelscomponents__/graphics/technology/components-tech.png",
  },
  {
    type = "item-subgroup",
    name = "angels-board",
    group = "angels-components",
    order = "a",
  },
  {
    type = "item-subgroup",
    name = "angels-circuit-board",
    group = "angels-components",
    order = "b",
  },
  {
    type = "item-subgroup",
    name = "angels-loaded-circuit-board",
    group = "angels-components",
    order = "c",
  },
  {
    type = "item-subgroup",
    name = "angels-circuit-components",
    group = "angels-components",
    order = "d",
  },
  {
    type = "item-subgroup",
    name = "angels-circuit-intermediates",
    group = "angels-components",
    order = "e",
  },
  {
    type = "item-group",
    name = "angels-tech",
    order = "pb",
    inventory_order = "pb",
	icon_size = 64,
    icon = "__angelscomponents__/graphics/technology/tech-blue.png",
  },
  {
    type = "item-subgroup",
    name = "angels-science-pack",
    group = "angels-tech",
    order = "a",
  },
  {
    type = "item-subgroup",
    name = "angels-datacore-1",
    group = "angels-tech",
    order = "b",
  },
  {
    type = "item-subgroup",
    name = "angels-datacore-2",
    group = "angels-tech",
    order = "c",
  },
  {
    type = "item-subgroup",
    name = "angels-labs-1",
    group = "angels-tech",
    order = "y",
  },
  {
    type = "item-subgroup",
    name = "angels-labs-2",
    group = "angels-tech",
    order = "z",
  },
  {
    type = "item-group",
    name = "angels-enhancement",
    order = "pa",
    inventory_order = "pc",
	icon_size = 64,
    icon = "__angelscomponents__/graphics/technology/vequip.png",
  },
  {
    type = "item-subgroup",
    name = "angels-equipment-energy",
    group = "angels-enhancement",
    order = "a",
  },
  {
    type = "item-subgroup",
    name = "angels-equipment-movement",
    group = "angels-enhancement",
    order = "b",
  },
  {
    type = "item-subgroup",
    name = "angels-equipment-robo",
    group = "angels-enhancement",
    order = "c",
  },
  {
    type = "item-subgroup",
    name = "angels-equipment-ldef",
    group = "angels-enhancement",
    order = "d",
  },
  {
    type = "item-subgroup",
    name = "angels-equipment-hdef",
    group = "angels-enhancement",
    order = "e",
  },
  {
    type = "item-subgroup",
    name = "angels-equipment-lat",
    group = "angels-enhancement",
    order = "f",
  },
  {
    type = "item-subgroup",
    name = "angels-equipment-hat",
    group = "angels-enhancement",
    order = "g",
  },
  }
  )