data:extend(
{
  --TIER 1
  {
    type = "item",
    name = "angels-ore1-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore1-crushed.png",
    icon_size = 32,
    --icon_mipmaps = 8,
    icon_mipmaps = 2,
    pictures =
    {
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-1.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-2.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-3.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-4.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-5.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-6.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-7.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-8.png",   scale = 0.25, mipmap_count = 1, tint = {r=60/255, g=84/255, b=116/255} },
    },
    subgroup = "ore-processing-a",
    order = "a[angels-ore1-crushed]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore2-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore2-crushed.png",
    icon_size = 32,
    --icon_mipmaps = 8,
    icon_mipmaps = 2,
    pictures =
    {
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-1.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-2.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-3.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-4.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-5.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-6.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-7.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-8.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.55, g=0.51, b=0.30} },
    },
    subgroup = "ore-processing-a",
    order = "b[angels-ore1-crushed]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore3-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore3-crushed.png",
    icon_size = 32,
    --icon_mipmaps = 8,
    icon_mipmaps = 2,
    pictures =
    {
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-1.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-2.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-3.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-4.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-5.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-6.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-7.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-8.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.42, g=0.71, b=0.86} },
    },
    subgroup = "ore-processing-a",
    order = "c[angels-ore1-crushed]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore4-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore4-crushed.png",
    icon_size = 32,
    --icon_mipmaps = 8,
    icon_mipmaps = 2,
    pictures =
    {
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-1.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-2.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-3.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-4.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-5.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-6.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-7.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-8.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.75, b=0.75} },
    },
    subgroup = "ore-processing-a",
    order = "d[angels-ore1-crushed]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore5-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore5-crushed.png",
    icon_size = 32,
    --icon_mipmaps = 8,
    icon_mipmaps = 2,
    pictures =
    {
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-1.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-2.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-3.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-4.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-5.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-6.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-7.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-8.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.68, g=0.18, b=0.16} },
    },
    subgroup = "ore-processing-a",
    order = "e[angels-ore1-crushed]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore6-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore6-crushed.png",
    icon_size = 32,
    --icon_mipmaps = 8,
    icon_mipmaps = 2,
    pictures =
    {
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-1.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-2.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-3.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-4.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-5.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-6.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-7.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-8.png",   scale = 0.25, mipmap_count = 1, tint = {r=0.75, g=0.5, b=0.25} },
    },
    subgroup = "ore-processing-a",
    order = "f[angels-ore1-crushed]",
    stack_size = 200
  },
  --TIER 1.5
  {
    type = "item",
    name = "angels-ore8-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-crushed.png",
    icon_size = 32,
    subgroup = "ore-processing-a",
    order = "g",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore8-powder",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-powder.png",
    icon_size = 32,
    subgroup = "ore-processing-a",
    order = "h",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore9-crushed",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-crushed.png",
    icon_size = 32,
    subgroup = "ore-processing-a",
    order = "i",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore9-powder",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-powder.png",
    icon_size = 32,
    subgroup = "ore-processing-a",
    order = "j",
    stack_size = 200
  },
  --TIER 2
  {
    type = "item",
    name = "angels-ore1-chunk",
    icon = "__angelsrefining__/graphics/icons/angels-ore1-chunk.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "a[angels-ore1-chunk]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore2-chunk",
    icon = "__angelsrefining__/graphics/icons/angels-ore2-chunk.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "b[angels-ore2-chunk]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore3-chunk",
    icon = "__angelsrefining__/graphics/icons/angels-ore3-chunk.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "c[angels-ore3-chunk]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore4-chunk",
    icon = "__angelsrefining__/graphics/icons/angels-ore4-chunk.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "d[angels-ore4-chunk]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore5-chunk",
    icon = "__angelsrefining__/graphics/icons/angels-ore5-chunk.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "e[angels-ore5-chunk]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore6-chunk",
    icon = "__angelsrefining__/graphics/icons/angels-ore6-chunk.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "f[angels-ore6-chunk]",
    stack_size = 200
  },
  --TIER 2.5
  {
    type = "fluid",
    name = "angels-ore8-sludge",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-sludge.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=132/255, g=176/255, b=11/255},
    flow_color = {r=132/255, g=176/255, b=11/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "item",
    name = "angels-ore8-dust",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-dust.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "g",
    stack_size = 200
  },
  {
    type = "fluid",
    name = "angels-ore9-sludge",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-sludge.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=255/255, g=119/255, b=0/255},
    flow_color = {r=255/255, g=119/255, b=0/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "item",
    name = "angels-ore9-dust",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-dust.png",
    icon_size = 32,
    subgroup = "ore-processing-b",
    order = "h",
    stack_size = 200
  },
  --TIER 3
  {
    type = "item",
    name = "angels-ore1-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore1-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "a[angels-ore1-crystal]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore2-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore2-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "b[angels-ore2-crystal]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore3-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore3-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "c[angels-ore3-crystal]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore4-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore4-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "d[angels-ore4-crystal]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore5-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore5-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "e[angels-ore5-crystal]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore6-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore6-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "f[angels-ore6-crystal]",
    stack_size = 200
  },
  --TIER 3.5
  {
    type = "fluid",
    name = "angels-ore8-solution",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-solution.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=255/255, g=119/255, b=0/255},
    flow_color = {r=255/255, g=119/255, b=0/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "angels-ore8-anode-sludge",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-anode-sludge.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=255/255, g=119/255, b=0/255},
    flow_color = {r=255/255, g=119/255, b=0/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "angels-ore8-slime",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-slime.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=255/255, g=119/255, b=0/255},
    flow_color = {r=255/255, g=119/255, b=0/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "item",
    name = "angels-ore8-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore8-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "g",
    stack_size = 200
  },
  {
    type = "fluid",
    name = "angels-ore9-solution",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-solution.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=255/255, g=119/255, b=0/255},
    flow_color = {r=255/255, g=119/255, b=0/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "angels-ore9-anode-sludge",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-anode-sludge.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=255/255, g=119/255, b=0/255},
    flow_color = {r=255/255, g=119/255, b=0/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "angels-ore9-slime",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-slime.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=255/255, g=119/255, b=0/255},
    flow_color = {r=255/255, g=119/255, b=0/255},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "item",
    name = "angels-ore9-crystal",
    icon = "__angelsrefining__/graphics/icons/angels-ore9-crystal.png",
    icon_size = 32,
    subgroup = "ore-processing-c",
    order = "g",
    stack_size = 200
  },
  --TIER 4
  {
    type = "item",
    name = "angels-ore1-pure",
    icon = "__angelsrefining__/graphics/icons/angels-ore1-pure.png",
    icon_size = 32,
    subgroup = "ore-processing-d",
    order = "a[angels-ore1-pure]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore2-pure",
    icon = "__angelsrefining__/graphics/icons/angels-ore2-pure.png",
    icon_size = 32,
    subgroup = "ore-processing-d",
    order = "b[angels-ore2-pure]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore3-pure",
    icon = "__angelsrefining__/graphics/icons/angels-ore3-pure.png",
    icon_size = 32,
    subgroup = "ore-processing-d",
    order = "c[angels-ore3-pure]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore4-pure",
    icon = "__angelsrefining__/graphics/icons/angels-ore4-pure.png",
    icon_size = 32,
    subgroup = "ore-processing-d",
    order = "d[angels-ore4-pure]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore5-pure",
    icon = "__angelsrefining__/graphics/icons/angels-ore5-pure.png",
    icon_size = 32,
    subgroup = "ore-processing-d",
    order = "e[angels-ore5-pure]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-ore6-pure",
    icon = "__angelsrefining__/graphics/icons/angels-ore6-pure.png",
    icon_size = 32,
    subgroup = "ore-processing-d",
    order = "f[angels-ore6-pure]",
    stack_size = 200
  },
  --GEODES
  {
    type = "item",
    name = "geode-blue",
    icon = "__angelsrefining__/graphics/icons/geode-blue.png",
    icon_size = 32,
    subgroup = "geode-processing-1",
    order = "a",
    stack_size = 200
  },
  {
    type = "item",
    name = "geode-purple",
    icon = "__angelsrefining__/graphics/icons/geode-purple.png",
    icon_size = 32,
    subgroup = "geode-processing-1",
    order = "b",
    stack_size = 200
  },
  {
    type = "item",
    name = "geode-yellow",
    icon = "__angelsrefining__/graphics/icons/geode-yellow.png",
    icon_size = 32,
    subgroup = "geode-processing-1",
    order = "c",
    stack_size = 200
  },
  {
    type = "item",
    name = "geode-lightgreen",
    icon = "__angelsrefining__/graphics/icons/geode-lightgreen.png",
    icon_size = 32,
    subgroup = "geode-processing-1",
    order = "d",
    stack_size = 200
  },
  {
    type = "item",
    name = "geode-cyan",
    icon = "__angelsrefining__/graphics/icons/geode-cyan.png",
    icon_size = 32,
    subgroup = "geode-processing-1",
    order = "e",
    stack_size = 200
  },
  {
    type = "item",
    name = "geode-red",
    icon = "__angelsrefining__/graphics/icons/geode-red.png",
    icon_size = 32,
    subgroup = "geode-processing-1",
    order = "f",
    stack_size = 200
  },
  {
    type = "item",
    name = "crystal-dust",
    icon = "__angelsrefining__/graphics/icons/crystal-dust.png",
    icon_size = 32,
    subgroup = "geode-processing-1",
    order = "g",
    stack_size = 200
  },
  --EXTRAS
  {
    type = "item",
    name = "stone-crushed",
    icon = "__angelsrefining__/graphics/icons/stone-crushed.png",
    icon_size = 32,
    --icon_mipmaps = 8,
    icon_mipmaps = 2,
    pictures =
    {
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-1.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
      { size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-2.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-3.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-4.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-5.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-6.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-7.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
      --{ size = 64, filename = "__angelsrefining__/graphics/icons/crushed/crushed-8.png",   scale = 0.25, mipmap_count = 1, tint = {r=164/255, g=164/255, b=164/255} },
    },
    subgroup = "slag-processing-1",
    order = "a",
    stack_size = 200
  },
  {
    type = "item",
    name = "milling-drum",
    icon = "__angelsrefining__/graphics/icons/milling-drum.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    order = "j",
    stack_size = 200
  },
  {
    type = "item",
    name = "milling-drum-used",
    icon = "__angelsrefining__/graphics/icons/milling-drum-used.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    order = "k",
    stack_size = 200
  },
  {
    type = "item",
    name = "slag",
    icon = "__angelsrefining__/graphics/icons/slag.png",
    icon_size = 32,
    subgroup = "slag-processing-1",
    order = "b",
    stack_size = 200
  },
  {
    type = "fluid",
    name = "slag-slurry",
    icon = "__angelsrefining__/graphics/icons/slurry.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.7, g=0.6, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "mineral-sludge",
    icon = "__angelsrefining__/graphics/icons/mineral-sludge.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.7, g=0.6, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "item",
    name = "filter-frame",
    icon = "__angelsrefining__/graphics/icons/filter-frame.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    stack_size = 200
  },
  {
    type = "item",
    name = "filter-coal",
    icon = "__angelsrefining__/graphics/icons/filter-coal.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    stack_size = 200
  },
  {
    type = "item",
    name = "filter-ceramic",
    icon = "__angelsrefining__/graphics/icons/filter-ceramic.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    stack_size = 200
  },
  {
    type = "item",
    name = "filter-ceramic-used",
    icon = "__angelsrefining__/graphics/icons/filter-ceramic-used.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    stack_size = 200
  },
  {
    type = "fluid",
    name = "crystal-slurry",
    icon = "__angelsrefining__/graphics/icons/crystal-slurry.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.7, g=0.6, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "crystal-seedling",
    icon = "__angelsrefining__/graphics/icons/crystal-seedling.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.7, g=0.6, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  {
    type = "fluid",
    name = "crystal-matrix",
    icon = "__angelsrefining__/graphics/icons/crystal-matrix.png",
    icon_size = 32,
    subgroup = "fluids-refining",
    default_temperature = 25,
    heat_capacity = "1KJ",
    base_color = {r=0.7, g=0.6, b=0.2},
    flow_color = {r=0.5, g=0.5, b=0.5},
    max_temperature = 100,
    pressure_to_speed_ratio = 0.4,
    flow_to_energy_ratio = 0.59,
  },
  --CATALYSTS
  {
    type = "item",
    name = "catalysator-brown",
    icon = "__angelsrefining__/graphics/icons/catalysator-brown.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    stack_size = 200
  },
  {
    type = "item",
    name = "catalysator-green",
    icon = "__angelsrefining__/graphics/icons/catalysator-green.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    stack_size = 200
  },
  {
    type = "item",
    name = "catalysator-orange",
    icon = "__angelsrefining__/graphics/icons/catalysator-orange.png",
    icon_size = 32,
    subgroup = "processing-crafting",
    stack_size = 200
  },
  --VOID
  {
    type = "item",
    name = "angels-void",
    icon = "__angelsrefining__/graphics/icons/void.png",
    icon_size = 32,
    flags = {"hidden"},
    subgroup = "processing-crafting",
    stack_size = 200
  },
  --VANILLA
  {
    type = "item",
    name = "angels-iron-nugget",
    icon = "__angelsrefining__/graphics/icons/iron-nugget.png",
    icon_size = 32,
    subgroup = "ore-processing-t0",
    order = "b[angels-iron-nugget]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-iron-pebbles",
    icon = "__angelsrefining__/graphics/icons/iron-pebbles.png",
    icon_size = 32,
    subgroup = "ore-processing-t0",
    order = "a[angels-iron-pebbles]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-iron-slag",
    icon = "__angelsrefining__/graphics/icons/iron-slag.png",
    icon_size = 32,
    subgroup = "ore-processing-t0",
    order = "c[angels-iron-slag]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-copper-nugget",
    icon = "__angelsrefining__/graphics/icons/copper-nugget.png",
    icon_size = 32,
    subgroup = "ore-processing-t0",
    order = "e[angels-copper-nugget]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-copper-pebbles",
    icon = "__angelsrefining__/graphics/icons/copper-pebbles.png",
    icon_size = 32,
    subgroup = "ore-processing-t0",
    order = "d[angels-copper-pebbles]",
    stack_size = 200
  },
  {
    type = "item",
    name = "angels-copper-slag",
    icon = "__angelsrefining__/graphics/icons/copper-slag.png",
    icon_size = 32,
    subgroup = "ore-processing-t0",
    order = "f[angels-copper-slag]",
    stack_size = 200
  },
}
)