local function angels_blast_furnace_fluid_boxes()
  return {
    {
      production_type = "input",
      pipe_covers = pipecoverspictures(),
      volume = 1000,
      pipe_connections = { { flow_direction = "input", position = { 0, 2 }, direction = defines.direction.south } },
    },
    {
      production_type = "output",
      pipe_covers = pipecoverspictures(),
      volume = 1000,
      pipe_connections = {
        { flow_direction = "output", position = { 0, -2 }, direction = defines.direction.north },
      },
    },
  }
end

circuit_connector_definitions["angels-blast-furnace"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  4, main_offset = util.by_pixel( 8.875,  58.625), shadow_offset = util.by_pixel( 8.875,  58.625), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 8.875,  58.625), shadow_offset = util.by_pixel( 8.875,  58.625), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 8.875,  58.625), shadow_offset = util.by_pixel( 8.875,  58.625), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 8.875,  58.625), shadow_offset = util.by_pixel( 8.875,  58.625), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-blast-furnace",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    subgroup = "angels-blast-furnace",
    order = "a[blast-furnace]",
    place_result = "angels-blast-furnace",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-blast-furnace",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-blast-furnace" },
    fast_replaceable_group = "angels-blast-furnace",
    next_upgrade = "angels-blast-furnace-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-blast-smelting" },
    crafting_speed = 1,
    energy_source = {
      type = "burner",
      effectivity = 1,
      fuel_inventory_size = 1,
      emissions_per_minute = { pollution = 1.8 },
      smoke = {
        {
          name = "smoke",
          deviation = { 0.1, 0.1 },
          frequency = 10,
          north_position = { -2.0, -1.8 },
          south_position = { -2.0, -1.8 },
          east_position = { -2.0, -1.8 },
          west_position = { -2.0, -1.8 },
          starting_vertical_speed = 0.08,
          starting_frame_deviation = 60,
        },
      },
      light_flicker = {
        color = { 0, 0, 0 },
        minimum_light_size = 0,
        light_intensity_to_size_coefficient = 0,
      },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-blast-furnace"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-base.png",
            priority = "high",
            width = 328,
            height = 376,
            shift = util.by_pixel(0, -13.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-shadow.png",
            priority = "high",
            width = 445,
            height = 245,
            shift = util.by_pixel(29, 19.5),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-fire.png",
            priority = "high",
            width = 23,
            height = 50,
            line_length = 8,
            frame_count = 48,
            animation_speed = 0.5,
            shift = util.by_pixel(3, 29),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-glow.png",
            priority = "high",
            width = 60,
            height = 43,
            blend_mode = "additive",
            shift = util.by_pixel(5, 39),
            draw_as_glow = true,
            scale = 0.75,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-working-light.png",
            priority = "high",
            width = 328,
            height = 376,
            blend_mode = "additive",
            shift = util.by_pixel(0, -13.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/oil-refinery.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes_off_when_no_fluid_recipe = true,
    fluid_boxes = angels_blast_furnace_fluid_boxes(),
  },
  {
    type = "item",
    name = "angels-blast-furnace-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    subgroup = "angels-blast-furnace",
    order = "b[blast-furnace-2]",
    place_result = "angels-blast-furnace-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-blast-furnace-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-blast-furnace-2" },
    fast_replaceable_group = "angels-blast-furnace",
    next_upgrade = "angels-blast-furnace-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-blast-smelting", "angels-blast-smelting-2" },
    crafting_speed = 1.5,
    energy_source = {
      type = "burner",
      effectivity = 1,
      fuel_inventory_size = 1,
      emissions_per_minute = { pollution = 2.4 },
      smoke = {
        {
          name = "smoke",
          deviation = { 0.1, 0.1 },
          frequency = 10,
          north_position = { -2.0, -1.8 },
          south_position = { -2.0, -1.8 },
          east_position = { -2.0, -1.8 },
          west_position = { -2.0, -1.8 },
          starting_vertical_speed = 0.08,
          starting_frame_deviation = 60,
        },
      },
      light_flicker = {
        color = { 0, 0, 0 },
        minimum_light_size = 0,
        light_intensity_to_size_coefficient = 0,
      },
    },
    energy_usage = "200kW",
    circuit_connector = circuit_connector_definitions["angels-blast-furnace"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-base.png",
            priority = "high",
            width = 328,
            height = 376,
            shift = util.by_pixel(0, -13.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-shadow.png",
            priority = "high",
            width = 445,
            height = 245,
            shift = util.by_pixel(29, 19.5),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-fire.png",
            priority = "high",
            width = 23,
            height = 50,
            line_length = 8,
            frame_count = 48,
            animation_speed = 0.5,
            shift = util.by_pixel(3, 29),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-glow.png",
            priority = "high",
            width = 60,
            height = 43,
            blend_mode = "additive",
            shift = util.by_pixel(5, 39),
            draw_as_glow = true,
            scale = 0.75,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-working-light.png",
            priority = "high",
            width = 328,
            height = 376,
            blend_mode = "additive",
            shift = util.by_pixel(0, -13.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/oil-refinery.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes_off_when_no_fluid_recipe = true,
    fluid_boxes = angels_blast_furnace_fluid_boxes(),
  },
  {
    type = "item",
    name = "angels-blast-furnace-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    subgroup = "angels-blast-furnace",
    order = "c[blast-furnace-3]",
    place_result = "angels-blast-furnace-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-blast-furnace-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-blast-furnace-3" },
    fast_replaceable_group = "angels-blast-furnace",
    next_upgrade = "angels-blast-furnace-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-blast-smelting", "angels-blast-smelting-2", "angels-blast-smelting-3" },
    crafting_speed = 2,
    energy_source = {
      type = "burner",
      effectivity = 1,
      fuel_inventory_size = 1,
      emissions_per_minute = { pollution = 3 },
      smoke = {
        {
          name = "smoke",
          deviation = { 0.1, 0.1 },
          frequency = 10,
          north_position = { -2.0, -1.8 },
          south_position = { -2.0, -1.8 },
          east_position = { -2.0, -1.8 },
          west_position = { -2.0, -1.8 },
          starting_vertical_speed = 0.08,
          starting_frame_deviation = 60,
        },
      },
      light_flicker = {
        color = { 0, 0, 0 },
        minimum_light_size = 0,
        light_intensity_to_size_coefficient = 0,
      },
    },
    energy_usage = "250kW",
    circuit_connector = circuit_connector_definitions["angels-blast-furnace"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-base.png",
            priority = "high",
            width = 328,
            height = 376,
            shift = util.by_pixel(0, -13.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-shadow.png",
            priority = "high",
            width = 445,
            height = 245,
            shift = util.by_pixel(29, 19.5),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-fire.png",
            priority = "high",
            width = 23,
            height = 50,
            line_length = 8,
            frame_count = 48,
            animation_speed = 0.5,
            shift = util.by_pixel(3, 29),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-glow.png",
            priority = "high",
            width = 60,
            height = 43,
            blend_mode = "additive",
            shift = util.by_pixel(5, 39),
            draw_as_glow = true,
            scale = 0.75,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-working-light.png",
            priority = "high",
            width = 328,
            height = 376,
            blend_mode = "additive",
            shift = util.by_pixel(0, -13.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/oil-refinery.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes_off_when_no_fluid_recipe = true,
    fluid_boxes = angels_blast_furnace_fluid_boxes(),
  },
  {
    type = "item",
    name = "angels-blast-furnace-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    subgroup = "angels-blast-furnace",
    order = "d[blast-furnace-4]",
    place_result = "angels-blast-furnace-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-blast-furnace-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/blast-furnace.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-blast-furnace-4" },
    fast_replaceable_group = "angels-blast-furnace",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-blast-smelting", "angels-blast-smelting-2", "angels-blast-smelting-3", "angels-blast-smelting-4" },
    crafting_speed = 3,
    energy_source = {
      type = "burner",
      effectivity = 1,
      fuel_inventory_size = 1,
      emissions_per_minute = { pollution = 3.6 },
      smoke = {
        {
          name = "smoke",
          deviation = { 0.1, 0.1 },
          frequency = 10,
          north_position = { -2.0, -1.8 },
          south_position = { -2.0, -1.8 },
          east_position = { -2.0, -1.8 },
          west_position = { -2.0, -1.8 },
          starting_vertical_speed = 0.08,
          starting_frame_deviation = 60,
        },
      },
      light_flicker = {
        color = { 0, 0, 0 },
        minimum_light_size = 0,
        light_intensity_to_size_coefficient = 0,
      },
    },
    energy_usage = "300kW",
    circuit_connector = circuit_connector_definitions["angels-blast-furnace"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-base.png",
            priority = "high",
            width = 328,
            height = 376,
            shift = util.by_pixel(0, -13.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-shadow.png",
            priority = "high",
            width = 445,
            height = 245,
            shift = util.by_pixel(29, 19.5),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-fire.png",
            priority = "high",
            width = 23,
            height = 50,
            line_length = 8,
            frame_count = 48,
            animation_speed = 0.5,
            shift = util.by_pixel(3, 29),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-glow.png",
            priority = "high",
            width = 60,
            height = 43,
            blend_mode = "additive",
            shift = util.by_pixel(5, 39),
            draw_as_glow = true,
            scale = 0.75,
          },
        },
        {
          fadeout = true,
          north_position = { 0, 0 },
          east_position = { 0, 0 },
          south_position = { 0, 0 },
          west_position = { 0, 0 },
          effect = "flicker",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/blast-furnace/blast-furnace-working-light.png",
            priority = "high",
            width = 328,
            height = 376,
            blend_mode = "additive",
            shift = util.by_pixel(0, -13.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/oil-refinery.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes_off_when_no_fluid_recipe = true,
    fluid_boxes = angels_blast_furnace_fluid_boxes(),
  },
})
