data:extend({
  {
    type = "item",
    name = "casting-machine",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    subgroup = "angels-casting-machine",
    order = "a[casting-machine]",
    place_result = "casting-machine",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "casting-machine",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "casting-machine" },
    fast_replaceable_group = "casting-machine",
    next_upgrade = "casting-machine-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box = { { -1.5, -1.8 }, { 1.5, 1.5 } },
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "casting" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "150kW",
    --ingredient_count = 2,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-base.png",
            priority = "high",
            width = 205,
            height = 244,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-shadow.png",
            priority = "high",
            width = 248,
            height = 206,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(11.5, 8.5),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-light.png",
            priority = "high",
            width = 205,
            height = 244,
            shift = util.by_pixel(0, -2),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 1, 1.4 }, direction = defines.direction.south } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { -1.4, 1 }, direction = defines.direction.west } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = {
          { flow_direction = "input", position = { -1, -1.4 }, direction = defines.direction.north },
        },
      },
      {
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "output", position = { 1.4, -1 }, direction = defines.direction.east } },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "casting-machine-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    subgroup = "angels-casting-machine",
    order = "b[casting-machine-2]",
    place_result = "casting-machine-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "casting-machine-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "casting-machine-2" },
    fast_replaceable_group = "casting-machine",
    next_upgrade = "casting-machine-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box = { { -1.5, -1.8 }, { 1.5, 1.5 } },
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "casting", "casting-2" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "200kW",
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-base.png",
            priority = "high",
            width = 205,
            height = 244,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-shadow.png",
            priority = "high",
            width = 248,
            height = 206,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(11.5, 8.5),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-light.png",
            priority = "high",
            width = 205,
            height = 244,
            shift = util.by_pixel(0, -2),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 1, 1.4 }, direction = defines.direction.south } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { -1.4, 1 }, direction = defines.direction.west } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = {
          { flow_direction = "input", position = { -1, -1.4 }, direction = defines.direction.north },
        },
      },
      {
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "output", position = { 1.4, -1 }, direction = defines.direction.east } },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "casting-machine-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    subgroup = "angels-casting-machine",
    order = "c[casting-machine-3]",
    place_result = "casting-machine-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "casting-machine-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "casting-machine-3" },
    fast_replaceable_group = "casting-machine",
    next_upgrade = "casting-machine-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box = { { -1.5, -1.8 }, { 1.5, 1.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "casting", "casting-2", "casting-3" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3 },
    },
    energy_usage = "250kW",
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-base.png",
            priority = "high",
            width = 205,
            height = 244,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-shadow.png",
            priority = "high",
            width = 248,
            height = 206,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(11.5, 8.5),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-light.png",
            priority = "high",
            width = 205,
            height = 244,
            shift = util.by_pixel(0, -2),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 1, 1.4 }, direction = defines.direction.south } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { -1.4, 1 }, direction = defines.direction.west } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = {
          { flow_direction = "input", position = { -1, -1.4 }, direction = defines.direction.north },
        },
      },
      {
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "output", position = { 1.4, -1 }, direction = defines.direction.east } },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "casting-machine-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    subgroup = "angels-casting-machine",
    order = "d[casting-machine-4]",
    place_result = "casting-machine-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "casting-machine-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "casting-machine-4" },
    fast_replaceable_group = "casting-machine",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box = { { -1.5, -1.8 }, { 1.5, 1.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "casting", "casting-2", "casting-3", "casting-4" },
    crafting_speed = 3,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3.6 },
    },
    energy_usage = "250kW",
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-base.png",
            priority = "high",
            width = 205,
            height = 244,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-shadow.png",
            priority = "high",
            width = 248,
            height = 206,
            line_length = 7,
            frame_count = 49,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(11.5, 8.5),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/casting-machine/casting-machine-light.png",
            priority = "high",
            width = 205,
            height = 244,
            shift = util.by_pixel(0, -2),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 1, 1.4 }, direction = defines.direction.south } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { -1.4, 1 }, direction = defines.direction.west } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = {
          { flow_direction = "input", position = { -1, -1.4 }, direction = defines.direction.north },
        },
      },
      {
        production_type = "output",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "output", position = { 1.4, -1 }, direction = defines.direction.east } },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
