circuit_connector_definitions["angels-ore-processing-machine"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  4, main_offset = util.by_pixel(-5.125,  28.125), shadow_offset = util.by_pixel(-5.125,  28.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel(-5.125,  28.125), shadow_offset = util.by_pixel(-5.125,  28.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel(-5.125,  28.125), shadow_offset = util.by_pixel(-5.125,  28.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel(-5.125,  28.125), shadow_offset = util.by_pixel(-5.125,  28.125), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-ore-processing-machine",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    subgroup = "angels-processing-machine",
    order = "a[ore-processing-machine]",
    place_result = "angels-ore-processing-machine",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-processing-machine",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-processing-machine" },
    fast_replaceable_group = "angels-ore-processing-machine",
    next_upgrade = "angels-ore-processing-machine-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box_vertical_extension = 0.333,
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-ore-processing" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 2,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-base.png",
            priority = "high",
            width = 196,
            height = 206,
            line_length = 5,
            frame_count = 25,
            animation_speed = 0.5,
            shift = util.by_pixel(-0.5, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-shadow.png",
            priority = "high",
            width = 243,
            height = 137,
            repeat_count = 25,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12.5, 16),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          apply_recipe_tint = "primary",
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-top.png",
            priority = "high",
            width = 192,
            height = 139,
            shift = util.by_pixel(0, -22.5),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-processing-machine-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    subgroup = "angels-processing-machine",
    order = "b[ore-processing-machine-2]",
    place_result = "angels-ore-processing-machine-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-processing-machine-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-processing-machine-2" },
    fast_replaceable_group = "angels-ore-processing-machine",
    next_upgrade = "angels-ore-processing-machine-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box_vertical_extension = 0.333,
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-ore-processing", "angels-ore-processing-2" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "200kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-base.png",
            priority = "high",
            width = 196,
            height = 206,
            line_length = 5,
            frame_count = 25,
            animation_speed = 0.5,
            shift = util.by_pixel(-0.5, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-shadow.png",
            priority = "high",
            width = 243,
            height = 137,
            repeat_count = 25,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12.5, 16),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          apply_recipe_tint = "primary",
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-top.png",
            priority = "high",
            width = 192,
            height = 139,
            shift = util.by_pixel(0, -22.5),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-processing-machine-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    subgroup = "angels-processing-machine",
    order = "c[ore-processing-machine-3]",
    place_result = "angels-ore-processing-machine-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-processing-machine-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-processing-machine-3" },
    fast_replaceable_group = "angels-ore-processing-machine",
    next_upgrade = "angels-ore-processing-machine-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box_vertical_extension = 0.333,
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-ore-processing", "angels-ore-processing-2", "angels-ore-processing-3" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3 },
    },
    energy_usage = "250kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-base.png",
            priority = "high",
            width = 196,
            height = 206,
            line_length = 5,
            frame_count = 25,
            animation_speed = 0.5,
            shift = util.by_pixel(-0.5, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-shadow.png",
            priority = "high",
            width = 243,
            height = 137,
            repeat_count = 25,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12.5, 16),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          apply_recipe_tint = "primary",
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-top.png",
            priority = "high",
            width = 192,
            height = 139,
            shift = util.by_pixel(0, -22.5),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-processing-machine-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    subgroup = "angels-processing-machine",
    order = "d[ore-processing-machine-4]",
    place_result = "angels-ore-processing-machine-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-processing-machine-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/ore-processing-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-processing-machine-4" },
    fast_replaceable_group = "angels-ore-processing-machine",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    drawing_box_vertical_extension = 0.333,
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-ore-processing", "angels-ore-processing-2", "angels-ore-processing-3", "angels-ore-processing-4" },
    crafting_speed = 3,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3.6 },
    },
    energy_usage = "300kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-base.png",
            priority = "high",
            width = 196,
            height = 206,
            line_length = 5,
            frame_count = 25,
            animation_speed = 0.5,
            shift = util.by_pixel(-0.5, -2),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-shadow.png",
            priority = "high",
            width = 243,
            height = 137,
            repeat_count = 25,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12.5, 16),
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          apply_recipe_tint = "primary",
          fadeout = true,
          constant_speed = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-dust.png",
            priority = "high",
            width = 107,
            height = 170,
            line_length = 5,
            frame_count = 20,
            animation_speed = 0.40,
            shift = util.by_pixel(0, -21.5),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/ore-processing-machine/ore-processing-machine-top.png",
            priority = "high",
            width = 192,
            height = 139,
            shift = util.by_pixel(0, -22.5),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
