circuit_connector_definitions["angels-pellet-press"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  2, main_offset = util.by_pixel(-21.25, -16.375), shadow_offset = util.by_pixel(-21.25, -16.375), show_shadow = true },
  { variation =  2, main_offset = util.by_pixel(-21.25, -16.375), shadow_offset = util.by_pixel(-21.25, -16.375), show_shadow = true },
  { variation =  2, main_offset = util.by_pixel(-21.25, -16.375), shadow_offset = util.by_pixel(-21.25, -16.375), show_shadow = true },
  { variation =  2, main_offset = util.by_pixel(-21.25, -16.375), shadow_offset = util.by_pixel(-21.25, -16.375), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-pellet-press",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    subgroup = "angels-pellet-press",
    order = "a[pellet-press]",
    place_result = "angels-pellet-press",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-pellet-press",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-pellet-press" },
    fast_replaceable_group = "angels-pellet-press",
    next_upgrade = "angels-pellet-press-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-pellet-pressing" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "200kW",
    circuit_connector = circuit_connector_definitions["angels-pellet-press"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 2,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-base.png",
            priority = "high",
            width = 200,
            height = 199,
            line_length = 10,
            frame_count = 60,
            animation_speed = 0.5,
            shift = util.by_pixel(0, 0),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-shadow.png",
            priority = "high",
            width = 246,
            height = 132,
            line_length = 6,
            frame_count = 60,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12, 17),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/idle1.ogg", volume = 0.9 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-pellet-press-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    subgroup = "angels-pellet-press",
    order = "b[pellet-press-2]",
    place_result = "angels-pellet-press-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-pellet-press-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-pellet-press-2" },
    fast_replaceable_group = "angels-pellet-press",
    next_upgrade = "angels-pellet-press-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-pellet-pressing", "angels-pellet-pressing-2" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "250kW",
    circuit_connector = circuit_connector_definitions["angels-pellet-press"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-base.png",
            priority = "high",
            width = 200,
            height = 199,
            line_length = 10,
            frame_count = 60,
            animation_speed = 0.5,
            shift = util.by_pixel(0, 0),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-shadow.png",
            priority = "high",
            width = 246,
            height = 132,
            line_length = 6,
            frame_count = 60,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12, 17),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/idle1.ogg", volume = 0.9 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-pellet-press-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    subgroup = "angels-pellet-press",
    order = "c[pellet-press-3]",
    place_result = "angels-pellet-press-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-pellet-press-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-pellet-press-3" },
    fast_replaceable_group = "angels-pellet-press",
    next_upgrade = "angels-pellet-press-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-pellet-pressing", "angels-pellet-pressing-2", "angels-pellet-pressing-3" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3 },
    },
    energy_usage = "300kW",
    circuit_connector = circuit_connector_definitions["angels-pellet-press"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-base.png",
            priority = "high",
            width = 200,
            height = 199,
            line_length = 10,
            frame_count = 60,
            animation_speed = 0.5,
            shift = util.by_pixel(0, 0),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-shadow.png",
            priority = "high",
            width = 246,
            height = 132,
            line_length = 6,
            frame_count = 60,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12, 17),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/idle1.ogg", volume = 0.9 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-pellet-press-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    subgroup = "angels-pellet-press",
    order = "d[pellet-press-4]",
    place_result = "angels-pellet-press-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-pellet-press-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/pellet-press.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-pellet-press-4" },
    fast_replaceable_group = "angels-pellet-press",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -1.4, -1.4 }, { 1.4, 1.4 } },
    selection_box = { { -1.5, -1.5 }, { 1.5, 1.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-pellet-pressing", "angels-pellet-pressing-2", "angels-pellet-pressing-3", "angels-pellet-pressing-4" },
    crafting_speed = 3,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3.6 },
    },
    energy_usage = "350kW",
    circuit_connector = circuit_connector_definitions["angels-pellet-press"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-base.png",
            priority = "high",
            width = 200,
            height = 199,
            line_length = 10,
            frame_count = 60,
            animation_speed = 0.5,
            shift = util.by_pixel(0, 0),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/pellet-press/pellet-press-shadow.png",
            priority = "high",
            width = 246,
            height = 132,
            line_length = 6,
            frame_count = 60,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(12, 17),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/idle1.ogg", volume = 0.9 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
