circuit_connector_definitions["angels-ore-processing-machine"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation = 32, main_offset = util.by_pixel(-6.375, -39.5), shadow_offset = util.by_pixel(-6.375, -39.5), show_shadow = true },
  { variation = 32, main_offset = util.by_pixel(-6.375, -39.5), shadow_offset = util.by_pixel(-6.375, -39.5), show_shadow = true },
  { variation = 32, main_offset = util.by_pixel(-6.375, -39.5), shadow_offset = util.by_pixel(-6.375, -39.5), show_shadow = true },
  { variation = 32, main_offset = util.by_pixel(-6.375, -39.5), shadow_offset = util.by_pixel(-6.375, -39.5), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-powder-mixer",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    subgroup = "angels-powder-mixer",
    order = "a[powder-mixer]",
    place_result = "angels-powder-mixer",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-powder-mixer",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-powder-mixer" },
    fast_replaceable_group = "angels-powder-mixer",
    next_upgrade = "angels-powder-mixer-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -1, -1 }, { 1, 1 } },
    drawing_box_vertical_extension = 0.55,
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-powder-mixing" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "100kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-base.png",
            priority = "high",
            width = 138,
            height = 170,
            line_length = 4,
            frame_count = 4,
            animation_speed = 0.5,
            shift = util.by_pixel(0.5, -9.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-shadow.png",
            priority = "high",
            width = 183,
            height = 99,
            repeat_count = 4,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(13, 9),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-powder-mixer-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    subgroup = "angels-powder-mixer",
    order = "b[powder-mixer-2]",
    place_result = "angels-powder-mixer-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-powder-mixer-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-powder-mixer-2" },
    fast_replaceable_group = "angels-powder-mixer",
    next_upgrade = "angels-powder-mixer-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -1, -1 }, { 1, 1 } },
    drawing_box_vertical_extension = 0.55,
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-powder-mixing", "angels-powder-mixing-2" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "125kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-base.png",
            priority = "high",
            width = 138,
            height = 170,
            line_length = 4,
            frame_count = 4,
            animation_speed = 0.5,
            shift = util.by_pixel(0.5, -9.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-shadow.png",
            priority = "high",
            width = 183,
            height = 99,
            repeat_count = 4,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(13, 9),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-powder-mixer-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    subgroup = "angels-powder-mixer",
    order = "c[powder-mixer-3]",
    place_result = "angels-powder-mixer-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-powder-mixer-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-powder-mixer-3" },
    fast_replaceable_group = "angels-powder-mixer",
    next_upgrade = "angels-powder-mixer-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -1, -1 }, { 1, 1 } },
    drawing_box_vertical_extension = 0.55,
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-powder-mixing", "angels-powder-mixing-2", "angels-powder-mixing-3" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3 },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-base.png",
            priority = "high",
            width = 138,
            height = 170,
            line_length = 4,
            frame_count = 4,
            animation_speed = 0.5,
            shift = util.by_pixel(0.5, -9.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-shadow.png",
            priority = "high",
            width = 183,
            height = 99,
            repeat_count = 4,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(13, 9),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-powder-mixer-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    subgroup = "angels-powder-mixer",
    order = "d[powder-mixer-4]",
    place_result = "angels-powder-mixer-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-powder-mixer-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/powder-mixer-ico.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-powder-mixer-4" },
    fast_replaceable_group = "angels-powder-mixer",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -1, -1 }, { 1, 1 } },
    drawing_box_vertical_extension = 0.55,
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-powder-mixing", "angels-powder-mixing-2", "angels-powder-mixing-3", "angels-powder-mixing-4" },
    crafting_speed = 3,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3.6 },
    },
    energy_usage = "175kW",
    circuit_connector = circuit_connector_definitions["angels-ore-processing-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-base.png",
            priority = "high",
            width = 138,
            height = 170,
            line_length = 4,
            frame_count = 4,
            animation_speed = 0.5,
            shift = util.by_pixel(0.5, -9.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/powder-mixer/powder-mixer-shadow.png",
            priority = "high",
            width = 183,
            height = 99,
            repeat_count = 4,
            animation_speed = 0.5,
            draw_as_shadow = true,
            shift = util.by_pixel(13, 9),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/ore-processing-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
