data:extend({
  {
    type = "item",
    name = "angels-sintering-oven",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    subgroup = "angels-sintering-oven",
    order = "a[sintering-oven]",
    place_result = "angels-sintering-oven",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-sintering-oven",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-sintering-oven" },
    fast_replaceable_group = "angels-sintering-oven",
    next_upgrade = "angels-sintering-oven-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-sintering" },
    crafting_speed = 0.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.2 },
    },
    energy_usage = "100kW",
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-base.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-shadow.png",
            priority = "high",
            width = 424,
            height = 227,
            shift = util.by_pixel(23, 28),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-glow.png",
            priority = "high",
            width = 326,
            height = 350,
            blend_mode = "additive",
            shift = util.by_pixel(-1, -6.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-light.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/sintering-oven.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-sintering-oven-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    subgroup = "angels-sintering-oven",
    order = "b[sintering-oven-2]",
    place_result = "angels-sintering-oven-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-sintering-oven-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-sintering-oven-2" },
    fast_replaceable_group = "angels-sintering-oven",
    next_upgrade = "angels-sintering-oven-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-sintering", "angels-sintering-2" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "150kW",
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-base.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-shadow.png",
            priority = "high",
            width = 424,
            height = 227,
            shift = util.by_pixel(23, 28),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-glow.png",
            priority = "high",
            width = 326,
            height = 350,
            blend_mode = "additive",
            shift = util.by_pixel(-1, -6.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-light.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/sintering-oven.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-sintering-oven-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    subgroup = "angels-sintering-oven",
    order = "c[sintering-oven-3]",
    place_result = "angels-sintering-oven-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-sintering-oven-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-sintering-oven-3" },
    fast_replaceable_group = "angels-sintering-oven",
    next_upgrade = "angels-sintering-oven-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-sintering", "angels-sintering-2", "angels-sintering-3" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "200kW",
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-base.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-shadow.png",
            priority = "high",
            width = 424,
            height = 227,
            shift = util.by_pixel(23, 28),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-glow.png",
            priority = "high",
            width = 326,
            height = 350,
            blend_mode = "additive",
            shift = util.by_pixel(-1, -6.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-light.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/sintering-oven.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-sintering-oven-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    subgroup = "angels-sintering-oven",
    order = "d[sintering-oven-4]",
    place_result = "angels-sintering-oven-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-sintering-oven-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-sintering-oven-4" },
    fast_replaceable_group = "angels-sintering-oven",
    next_upgrade = "angels-sintering-oven-5",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-sintering", "angels-sintering-2", "angels-sintering-3", "angels-sintering-4" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3 },
    },
    energy_usage = "250kW",
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-base.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-shadow.png",
            priority = "high",
            width = 424,
            height = 227,
            shift = util.by_pixel(23, 28),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-glow.png",
            priority = "high",
            width = 326,
            height = 350,
            blend_mode = "additive",
            shift = util.by_pixel(-1, -6.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-light.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/sintering-oven.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-sintering-oven-5",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 5, angelsmods.smelting.number_tint),
    subgroup = "angels-sintering-oven",
    order = "d[sintering-oven-5]",
    place_result = "angels-sintering-oven-5",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-sintering-oven-5",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/sintering-oven.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 5, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-sintering-oven-5" },
    fast_replaceable_group = "angels-sintering-oven",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-sintering", "angels-sintering-2", "angels-sintering-3", "angels-sintering-4", "angels-sintering-5" },
    crafting_speed = 3,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3.6 },
    },
    energy_usage = "300kW",
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-base.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            scale = 0.5,
          },
          {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-shadow.png",
            priority = "high",
            width = 424,
            height = 227,
            shift = util.by_pixel(23, 28),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-glow.png",
            priority = "high",
            width = 326,
            height = 350,
            blend_mode = "additive",
            shift = util.by_pixel(-1, -6.5),
            draw_as_glow = true,
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/sintering-oven/sintering-oven-light.png",
            priority = "high",
            width = 326,
            height = 350,
            shift = util.by_pixel(-1, -6.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/sintering-oven.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
