local function angels_strand_casting_machine_fluid_boxes()
  return {
    {
      production_type = "input",
      pipe_covers = pipecoverspictures(),
      volume = 1000,
      pipe_connections = { { flow_direction = "input", position = { -1, 2 }, direction = defines.direction.south } },
    },
    {
      production_type = "input",
      pipe_covers = pipecoverspictures(),
      volume = 1000,
      pipe_connections = { { flow_direction = "input", position = { 1, 2 }, direction = defines.direction.south } },
    },
    {
      production_type = "input",
      pipe_covers = pipecoverspictures(),
      volume = 1000,
      pipe_connections = {
        { flow_direction = "input", position = { -1, -2 }, direction = defines.direction.north },
      },
    },
    {
      production_type = "output",
      pipe_covers = pipecoverspictures(),
      volume = 1000,
      pipe_connections = {
        { flow_direction = "output", position = { 1, -2 }, direction = defines.direction.north },
      },
    },
  }
end

circuit_connector_definitions["angels-strand-casting-machine"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  5, main_offset = util.by_pixel( 50,  11.625), shadow_offset = util.by_pixel( 50,  11.625), show_shadow = true },
  { variation =  5, main_offset = util.by_pixel( 50,  11.625), shadow_offset = util.by_pixel( 50,  11.625), show_shadow = true },
  { variation =  5, main_offset = util.by_pixel( 50,  11.625), shadow_offset = util.by_pixel( 50,  11.625), show_shadow = true },
  { variation =  5, main_offset = util.by_pixel( 50,  11.625), shadow_offset = util.by_pixel( 50,  11.625), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-strand-casting-machine",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    subgroup = "angels-strand-casting-machine",
    order = "a[strand-casting-machine]",
    place_result = "angels-strand-casting-machine",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-strand-casting-machine",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 1, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-strand-casting-machine" },
    fast_replaceable_group = "angels-strand-casting-machine",
    next_upgrade = "angels-strand-casting-machine-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 0,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-strand-casting" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-strand-casting-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    fluid_boxes = angels_strand_casting_machine_fluid_boxes(),
    impact_category = "metal",
    graphics_set = {
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            layers = {
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-idle-state.png",
                priority = "high",
                width = 329,
                height = 392,
                shift = util.by_pixel(0, -16.5),
                scale = 0.5,
              },
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-shadow.png",
                priority = "high",
                width = 444,
                height = 311,
                draw_as_shadow = true,
                shift = util.by_pixel(29.5, 3.5),
                scale = 0.5,
              },
            },
          },
        },
        {
          apply_recipe_tint = "primary",
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-recipe-mask.png",
            priority = "high",
            width = 329,
            height = 392,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-working-animation.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-light.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/strand-casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-strand-casting-machine-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    subgroup = "angels-strand-casting-machine",
    order = "b[strand-casting-machine-2]",
    place_result = "angels-strand-casting-machine-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-strand-casting-machine-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 2, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-strand-casting-machine-2" },
    fast_replaceable_group = "angels-strand-casting-machine",
    next_upgrade = "angels-strand-casting-machine-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-strand-casting", "angels-strand-casting-2" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "200kW",
    circuit_connector = circuit_connector_definitions["angels-strand-casting-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    fluid_boxes = angels_strand_casting_machine_fluid_boxes(),
    impact_category = "metal",
    graphics_set = {
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            layers = {
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-idle-state.png",
                priority = "high",
                width = 329,
                height = 392,
                shift = util.by_pixel(0, -16.5),
                scale = 0.5,
              },
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-shadow.png",
                priority = "high",
                width = 444,
                height = 311,
                draw_as_shadow = true,
                shift = util.by_pixel(29.5, 3.5),
                scale = 0.5,
              },
            },
          },
        },
        {
          apply_recipe_tint = "primary",
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-recipe-mask.png",
            priority = "high",
            width = 329,
            height = 392,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-working-animation.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-light.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/strand-casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-strand-casting-machine-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    subgroup = "angels-strand-casting-machine",
    order = "c[strand-casting-machine-3]",
    place_result = "angels-strand-casting-machine-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-strand-casting-machine-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 3, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-strand-casting-machine-3" },
    fast_replaceable_group = "angels-strand-casting-machine",
    next_upgrade = "angels-strand-casting-machine-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-strand-casting", "angels-strand-casting-2", "angels-strand-casting-3" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3 },
    },
    energy_usage = "250kW",
    circuit_connector = circuit_connector_definitions["angels-strand-casting-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    fluid_boxes = angels_strand_casting_machine_fluid_boxes(),
    impact_category = "metal",
    graphics_set = {
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            layers = {
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-idle-state.png",
                priority = "high",
                width = 329,
                height = 392,
                shift = util.by_pixel(0, -16.5),
                scale = 0.5,
              },
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-shadow.png",
                priority = "high",
                width = 444,
                height = 311,
                draw_as_shadow = true,
                shift = util.by_pixel(29.5, 3.5),
                scale = 0.5,
              },
            },
          },
        },
        {
          apply_recipe_tint = "primary",
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-recipe-mask.png",
            priority = "high",
            width = 329,
            height = 392,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-working-animation.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-light.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/strand-casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-strand-casting-machine-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    subgroup = "angels-strand-casting-machine",
    order = "d[strand-casting-machine-4]",
    place_result = "angels-strand-casting-machine-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-strand-casting-machine-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelssmeltinggraphics__/graphics/icons/strand-casting-machine.png",
        icon_size = 64,
        scale = 0.5,
      },
    }, 4, angelsmods.smelting.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-strand-casting-machine-4" },
    fast_replaceable_group = "angels-strand-casting-machine",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-strand-casting", "angels-strand-casting-2", "angels-strand-casting-3", "angels-strand-casting-4" },
    crafting_speed = 3,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3.6 },
    },
    energy_usage = "250kW",
    circuit_connector = circuit_connector_definitions["angels-strand-casting-machine"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    fluid_boxes = angels_strand_casting_machine_fluid_boxes(),
    impact_category = "metal",
    graphics_set = {
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            layers = {
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-idle-state.png",
                priority = "high",
                width = 329,
                height = 392,
                shift = util.by_pixel(0, -16.5),
                scale = 0.5,
              },
              {
                filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-shadow.png",
                priority = "high",
                width = 444,
                height = 311,
                draw_as_shadow = true,
                shift = util.by_pixel(29.5, 3.5),
                scale = 0.5,
              },
            },
          },
        },
        {
          apply_recipe_tint = "primary",
          always_draw = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-recipe-mask.png",
            priority = "high",
            width = 329,
            height = 392,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-working-animation.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelssmeltinggraphics__/graphics/entity/strand-casting-machine/strand-casting-machine-light.png",
            priority = "high",
            width = 329,
            height = 392,
            line_length = 6,
            frame_count = 24,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -16.5),
            draw_as_light = true,
            scale = 0.5,
          },
        },
      },
    },
    working_sound = {
      sound = { filename = "__angelssmeltinggraphics__/sound/strand-casting-machine.ogg", volume = 0.45 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
