	angelsmods.functions.make_void("raw-wood", "bio")

	angelsmods.functions.make_void("algae-green", "bio")
	angelsmods.functions.make_void("algae-brown", "bio")
	angelsmods.functions.make_void("algae-red", "bio")
	angelsmods.functions.make_void("algae-blue", "bio")
	
	angelsmods.functions.make_void("temperate-garden", "bio")
	angelsmods.functions.make_void("desert-garden", "bio")
	angelsmods.functions.make_void("water-garden", "bio")
	
	angelsmods.functions.make_void("temperate-1", "bio")
	angelsmods.functions.make_void("temperate-1-seed", "bio")
	angelsmods.functions.make_void("temperate-2", "bio")
	angelsmods.functions.make_void("temperate-2-seed", "bio")
	angelsmods.functions.make_void("temperate-3", "bio")
	angelsmods.functions.make_void("temperate-3-seed", "bio")
	angelsmods.functions.make_void("temperate-4", "bio")
	angelsmods.functions.make_void("temperate-4-seed", "bio")
	angelsmods.functions.make_void("temperate-5", "bio")
	angelsmods.functions.make_void("temperate-5-seed", "bio")
	
	angelsmods.functions.make_void("desert-1", "bio")
	angelsmods.functions.make_void("desert-1-seed", "bio")
	angelsmods.functions.make_void("desert-2", "bio")
	angelsmods.functions.make_void("desert-2-seed", "bio")
	angelsmods.functions.make_void("desert-3", "bio")
	angelsmods.functions.make_void("desert-3-seed", "bio")
	angelsmods.functions.make_void("desert-4", "bio")
	angelsmods.functions.make_void("desert-4-seed", "bio")
	angelsmods.functions.make_void("desert-5", "bio")
	angelsmods.functions.make_void("desert-5-seed", "bio")
	
	angelsmods.functions.make_void("water-1", "bio")
	angelsmods.functions.make_void("water-1-seed", "bio")
	angelsmods.functions.make_void("water-2", "bio")
	angelsmods.functions.make_void("water-2-seed", "bio")
	angelsmods.functions.make_void("water-3", "bio")
	angelsmods.functions.make_void("water-3-seed", "bio")
	angelsmods.functions.make_void("water-4", "bio")
	angelsmods.functions.make_void("water-4-seed", "bio")
	angelsmods.functions.make_void("water-5", "bio")
	angelsmods.functions.make_void("water-5-seed", "bio")
	
	angelsmods.functions.make_seed("temperate-1")
	angelsmods.functions.make_seed("temperate-2")
	angelsmods.functions.make_seed("temperate-3")
	angelsmods.functions.make_seed("temperate-4")
	angelsmods.functions.make_seed("temperate-5")
	
	angelsmods.functions.make_seed("desert-1")
	angelsmods.functions.make_seed("desert-2")
	angelsmods.functions.make_seed("desert-3")
	angelsmods.functions.make_seed("desert-4")
	angelsmods.functions.make_seed("desert-5")
	
	angelsmods.functions.make_seed("water-1")
	angelsmods.functions.make_seed("water-2")
	angelsmods.functions.make_seed("water-3")
	angelsmods.functions.make_seed("water-4")
	angelsmods.functions.make_seed("water-5")
