entities = {
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 96,
    minable = true,
    name = "hidden-electric-energy-interface",
    operable = false,
    position = {
      x = 37,
      y = 6,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 74,
    minable = true,
    name = "big-electric-pole",
    operable = true,
    position = {
      x = 37,
      y = 6,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 1,
    inventory = {
      {
        ["rocket-fuel"] = 1,
      },
      {},
      {},
      {},
    },
    minable = true,
    name = "steel-furnace",
    operable = true,
    position = {
      x = 2,
      y = -20,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 2,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -18.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 3,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -19.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 4,
    inventory = {
      {
        ["rocket-fuel"] = 1,
      },
      {},
      {},
      {},
    },
    minable = true,
    name = "steel-furnace",
    operable = true,
    position = {
      x = 2,
      y = -18,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 5,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 0.5,
      y = -19.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 6,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 0.5,
      y = -18.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 7,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 3.5,
      y = -18.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 8,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 3.5,
      y = -19.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 9,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -19.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 10,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -18.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 11,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -16.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 12,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -17.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 13,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = 2.5,
      y = -16.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 14,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -17.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 15,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -16.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 16,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -14.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 17,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -15.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 18,
    inventory = {
      {
        ["rocket-fuel"] = 1,
      },
      {},
      {},
      {},
    },
    minable = true,
    name = "steel-furnace",
    operable = true,
    position = {
      x = 2,
      y = -15,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 19,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 0.5,
      y = -14.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 20,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 3.5,
      y = -14.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 21,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -15.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 22,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -14.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 23,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -12.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 24,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -13.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 25,
    inventory = {
      {
        ["rocket-fuel"] = 1,
      },
      {},
      {},
      {},
    },
    minable = true,
    name = "steel-furnace",
    operable = true,
    position = {
      x = 2,
      y = -13,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 26,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 0.5,
      y = -13.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 27,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 3.5,
      y = -13.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 28,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -13.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 29,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -12.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 31,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = -11.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 32,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 5.5,
      y = -10.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 33,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -11.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 34,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 4.5,
      y = -10.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 35,
    inventory = {
      {},
    },
    minable = true,
    name = "iron-chest",
    operable = true,
    position = {
      x = 6.5,
      y = -10.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 46,
    minable = true,
    name = "big-electric-pole",
    operable = true,
    position = {
      x = 11,
      y = -8,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 47,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = -4.5,
      y = -9.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 56,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = 2.5,
      y = -7.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 57,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = -14,
      y = -4,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 58,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -9,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 59,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -7,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 60,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -5,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 61,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -3,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 62,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -1,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 63,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 1,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 64,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 3,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 65,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 5,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 66,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 7,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 67,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 9,
      y = -5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 3,
    force = "player",
    index = 68,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = 14,
      y = -4,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 7,
    force = "player",
    index = 69,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -17,
      y = -1,
    },
    rotatable = true,
  },
  {
    backer_name = "A",
    destructible = true,
    direction = 2,
    force = "player",
    index = 70,
    minable = true,
    name = "train-stop",
    operable = true,
    position = {
      x = 9,
      y = -3,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 1,
    force = "player",
    index = 71,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 17,
      y = -1,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 1,
    force = "player",
    index = 72,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = -20,
      y = 2,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 73,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = 20,
      y = 2,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 75,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -21,
      y = 7,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 76,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 21,
      y = 7,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 77,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -21,
      y = 9,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 78,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 21,
      y = 9,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 79,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = -20,
      y = 14,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 5,
    force = "player",
    index = 80,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = 20,
      y = 14,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 5,
    force = "player",
    index = 81,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -17,
      y = 17,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 7,
    force = "player",
    index = 82,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = -14,
      y = 20,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 83,
    minable = true,
    name = "curved-rail",
    operable = true,
    position = {
      x = 14,
      y = 20,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 3,
    force = "player",
    index = 84,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 17,
      y = 17,
    },
    rotatable = true,
  },
  {
    backer_name = "B",
    destructible = true,
    direction = 6,
    force = "player",
    index = 85,
    minable = true,
    name = "train-stop",
    operable = true,
    position = {
      x = -9,
      y = 19,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 86,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -9,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 87,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -7,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 88,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -5,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 89,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -3,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 90,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = -1,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 91,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 1,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 92,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 3,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 93,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 5,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 94,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 7,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 95,
    minable = true,
    name = "straight-rail",
    operable = true,
    position = {
      x = 9,
      y = 21,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 99,
    inventory = {
      {
        ["angels-ore1"] = 8,
      },
    },
    minable = true,
    name = "steel-chest",
    operable = true,
    position = {
      x = -1.5,
      y = 23.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 100,
    inventory = {
      {
        ["angels-ore1"] = 31,
      },
    },
    minable = true,
    name = "steel-chest",
    operable = true,
    position = {
      x = -0.5,
      y = 23.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 101,
    inventory = {
      {
        ["angels-ore1"] = 78,
      },
    },
    minable = true,
    name = "steel-chest",
    operable = true,
    position = {
      x = 1.5,
      y = 23.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 102,
    inventory = {
      {
        ["angels-ore1"] = 78,
      },
    },
    minable = true,
    name = "steel-chest",
    operable = true,
    position = {
      x = 0.5,
      y = 23.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 103,
    inventory = {
      {
        ["angels-ore1"] = 8,
      },
    },
    minable = true,
    name = "steel-chest",
    operable = true,
    position = {
      x = 3.5,
      y = 23.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 104,
    inventory = {
      {
        ["angels-ore1"] = 29,
      },
    },
    minable = true,
    name = "steel-chest",
    operable = true,
    position = {
      x = 2.5,
      y = 23.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 105,
    minable = true,
    name = "big-electric-pole",
    operable = true,
    position = {
      x = 13,
      y = 24,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 106,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = -2.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 107,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -1.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 108,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -0.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 109,
    line_contents = {
      {
        ["angels-ore1"] = 1,
      },
      {
        ["angels-ore1"] = 4,
      },
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -0.5,
      y = 25.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 110,
    line_contents = {
      {
        ["angels-ore1"] = 5,
      },
      {
        ["angels-ore1"] = 2,
      },
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -1.5,
      y = 25.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 111,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 1.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 112,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 0.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 113,
    line_contents = {
      {},
      {
        ["angels-ore1"] = 4,
      },
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 0.5,
      y = 25.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 114,
    line_contents = {
      {
        ["angels-ore1"] = 4,
      },
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 25.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 115,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 3.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 4,
    force = "player",
    index = 116,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = 2.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 117,
    line_contents = {
      {
        ["angels-ore1"] = 4,
      },
      {
        ["angels-ore1"] = 1,
      },
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 2.5,
      y = 25.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 118,
    line_contents = {
      {
        ["angels-ore1"] = 2,
      },
      {
        ["angels-ore1"] = 5,
      },
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 3.5,
      y = 25.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 119,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = 4.5,
      y = 24.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 120,
    line_contents = {
      {},
      {},
      {},
      {},
      {},
      {
        ["angels-ore1"] = 1,
      },
      {
        ["angels-ore1"] = 1,
      },
      {},
    },
    minable = true,
    name = "fast-splitter",
    operable = true,
    position = {
      x = 1,
      y = 26.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 121,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 27.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 122,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 29.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 123,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 28.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 124,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = -2.5,
      y = 30.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 125,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 31.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 126,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 30.5,
    },
    rotatable = true,
  },
  {
    amount = 384,
    destructible = true,
    force = "neutral",
    index = 127,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 291,
    destructible = true,
    force = "neutral",
    index = 128,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 432,
    destructible = true,
    force = "neutral",
    index = 129,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 203,
    destructible = true,
    force = "neutral",
    index = 130,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 408,
    destructible = true,
    force = "neutral",
    index = 131,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 132,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 133,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 32.5,
    },
    rotatable = true,
  },
  {
    amount = 367,
    destructible = true,
    force = "neutral",
    index = 134,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 340,
    destructible = true,
    force = "neutral",
    index = 135,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 272,
    destructible = true,
    force = "neutral",
    index = 136,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 236,
    destructible = true,
    force = "neutral",
    index = 137,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 33.5,
    },
    rotatable = true,
  },
  {
    amount = 276,
    destructible = true,
    force = "neutral",
    index = 138,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 321,
    destructible = true,
    force = "neutral",
    index = 139,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 225,
    destructible = true,
    force = "neutral",
    index = 140,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 398,
    destructible = true,
    force = "neutral",
    index = 141,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 437,
    destructible = true,
    force = "neutral",
    index = 142,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 415,
    destructible = true,
    force = "neutral",
    index = 143,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 144,
    inventory = {
      nil,
      {},
    },
    minable = true,
    name = "electric-mining-drill",
    operable = true,
    position = {
      x = -0.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 270,
    destructible = true,
    force = "neutral",
    index = 145,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 337,
    destructible = true,
    force = "neutral",
    index = 146,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 394,
    destructible = true,
    force = "neutral",
    index = 147,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 413,
    destructible = true,
    force = "neutral",
    index = 148,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 149,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 150,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 359,
    destructible = true,
    force = "neutral",
    index = 151,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 318,
    destructible = true,
    force = "neutral",
    index = 152,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 349,
    destructible = true,
    force = "neutral",
    index = 153,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 397,
    destructible = true,
    force = "neutral",
    index = 154,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 155,
    inventory = {
      nil,
      {},
    },
    minable = true,
    name = "electric-mining-drill",
    operable = true,
    position = {
      x = 3.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 214,
    destructible = true,
    force = "neutral",
    index = 156,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 398,
    destructible = true,
    force = "neutral",
    index = 157,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 309,
    destructible = true,
    force = "neutral",
    index = 158,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 34.5,
    },
    rotatable = true,
  },
  {
    amount = 218,
    destructible = true,
    force = "neutral",
    index = 159,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 35.5,
    },
    rotatable = true,
  },
  {
    amount = 405,
    destructible = true,
    force = "neutral",
    index = 160,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 402,
    destructible = true,
    force = "neutral",
    index = 161,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 162,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = -2.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 304,
    destructible = true,
    force = "neutral",
    index = 163,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 200,
    destructible = true,
    force = "neutral",
    index = 164,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 435,
    destructible = true,
    force = "neutral",
    index = 165,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 464,
    destructible = true,
    force = "neutral",
    index = 166,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 380,
    destructible = true,
    force = "neutral",
    index = 167,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 239,
    destructible = true,
    force = "neutral",
    index = 168,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 224,
    destructible = true,
    force = "neutral",
    index = 169,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 431,
    destructible = true,
    force = "neutral",
    index = 170,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 171,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 172,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 236,
    destructible = true,
    force = "neutral",
    index = 173,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 233,
    destructible = true,
    force = "neutral",
    index = 174,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 302,
    destructible = true,
    force = "neutral",
    index = 175,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 223,
    destructible = true,
    force = "neutral",
    index = 176,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 285,
    destructible = true,
    force = "neutral",
    index = 177,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 197,
    destructible = true,
    force = "neutral",
    index = 178,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 321,
    destructible = true,
    force = "neutral",
    index = 179,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 36.5,
    },
    rotatable = true,
  },
  {
    amount = 312,
    destructible = true,
    force = "neutral",
    index = 180,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 181,
    minable = true,
    name = "medium-electric-pole",
    operable = true,
    position = {
      x = 5.5,
      y = 37.5,
    },
    rotatable = true,
  },
  {
    amount = 291,
    destructible = true,
    force = "neutral",
    index = 182,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 415,
    destructible = true,
    force = "neutral",
    index = 183,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 257,
    destructible = true,
    force = "neutral",
    index = 184,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 384,
    destructible = true,
    force = "neutral",
    index = 185,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 293,
    destructible = true,
    force = "neutral",
    index = 186,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 347,
    destructible = true,
    force = "neutral",
    index = 187,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 2,
    force = "player",
    index = 188,
    inventory = {
      nil,
      {},
    },
    minable = true,
    name = "electric-mining-drill",
    operable = true,
    position = {
      x = -0.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 282,
    destructible = true,
    force = "neutral",
    index = 189,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 273,
    destructible = true,
    force = "neutral",
    index = 190,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 327,
    destructible = true,
    force = "neutral",
    index = 191,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 355,
    destructible = true,
    force = "neutral",
    index = 192,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 193,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 194,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = 1.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 249,
    destructible = true,
    force = "neutral",
    index = 195,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 411,
    destructible = true,
    force = "neutral",
    index = 196,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 308,
    destructible = true,
    force = "neutral",
    index = 197,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 491,
    destructible = true,
    force = "neutral",
    index = 198,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 199,
    inventory = {
      nil,
      {},
    },
    minable = true,
    name = "electric-mining-drill",
    operable = true,
    position = {
      x = 3.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 473,
    destructible = true,
    force = "neutral",
    index = 200,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 283,
    destructible = true,
    force = "neutral",
    index = 201,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 236,
    destructible = true,
    force = "neutral",
    index = 202,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 38.5,
    },
    rotatable = true,
  },
  {
    amount = 289,
    destructible = true,
    force = "neutral",
    index = 203,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 39.5,
    },
    rotatable = true,
  },
  {
    amount = 299,
    destructible = true,
    force = "neutral",
    index = 204,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 354,
    destructible = true,
    force = "neutral",
    index = 205,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -2.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 318,
    destructible = true,
    force = "neutral",
    index = 206,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 227,
    destructible = true,
    force = "neutral",
    index = 207,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -1.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 373,
    destructible = true,
    force = "neutral",
    index = 208,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 446,
    destructible = true,
    force = "neutral",
    index = 209,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = -0.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 409,
    destructible = true,
    force = "neutral",
    index = 210,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 238,
    destructible = true,
    force = "neutral",
    index = 211,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 0.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 454,
    destructible = true,
    force = "neutral",
    index = 212,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 466,
    destructible = true,
    force = "neutral",
    index = 213,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 1.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 472,
    destructible = true,
    force = "neutral",
    index = 214,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 413,
    destructible = true,
    force = "neutral",
    index = 215,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 2.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 411,
    destructible = true,
    force = "neutral",
    index = 216,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 440,
    destructible = true,
    force = "neutral",
    index = 217,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 3.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 272,
    destructible = true,
    force = "neutral",
    index = 218,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 440,
    destructible = true,
    force = "neutral",
    index = 219,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 4.5,
      y = 41.5,
    },
    rotatable = true,
  },
  {
    amount = 381,
    destructible = true,
    force = "neutral",
    index = 220,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 40.5,
    },
    rotatable = true,
  },
  {
    amount = 311,
    destructible = true,
    force = "neutral",
    index = 221,
    minable = true,
    name = "angels-ore1",
    operable = true,
    position = {
      x = 5.5,
      y = 41.5,
    },
    rotatable = true,
  },
  -- additions for angels compatibility
  {
    destructible = true,
    force = "player",
    index = 300,
    inventory = {
      {},
      {},
      {},
      {},
    },
    minable = true,
    name = "angels-ore-crusher",
    operable = true,
    position = {
      x = -3.5,
      y = -11.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 301,
    inventory = {
      {},
      {},
      {},
      {},
    },
    minable = true,
    name = "angels-ore-crusher",
    operable = true,
    position = {
      x = -3.5,
      y = -14.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 302,
    inventory = {
      {},
      {},
      {},
      {},
    },
    minable = true,
    name = "angels-ore-crusher",
    operable = true,
    position = {
      x = -3.5,
      y = -18.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 303,
    minable = true,
    name = "medium-electric-pole",
    position = {
      x = -4.5,
      y = -16.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 304,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -1.5,
      y = -17.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 305,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -1.5,
      y = -13.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 306,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -1.5,
      y = -12.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 307,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -5.5,
      y = -17.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 308,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -5.5,
      y = -13.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    direction = 6,
    force = "player",
    index = 309,
    minable = true,
    name = "fast-inserter",
    operable = true,
    position = {
      x = -5.5,
      y = -12.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 310,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -8.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 311,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -9.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 312,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -10.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 313,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -11.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 314,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -12.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 315,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -13.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 316,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -14.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 317,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -15.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 318,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -16.5,
    },
    rotatable = true,
  },
  {
    destructible = true,
    force = "player",
    index = 319,
    line_contents = {
      {},
      {},
    },
    minable = true,
    name = "fast-transport-belt",
    operable = true,
    position = {
      x = -6.5,
      y = -17.5,
    },
    rotatable = true,
  },
}
