require("prototypes.tips-and-tricks.1-exploration.1-exploration")
require("prototypes.tips-and-tricks.1-1-shoot-targeting.1-1-shoot-targeting")
require("prototypes.tips-and-tricks.1-2-native-inhabitants.1-2-native-inhabitants")
require("prototypes.tips-and-tricks.1-2-x-native-houses.1-2-x-native-houses")
require("prototypes.tips-and-tricks.1-2-x-x-native-aliens.1-2-x-x-native-aliens")
