if angelsmods.industries.components then
  data:extend({
    {
      type = "item",
      name = "angels-rocket-hull",
      icon = "__angelsindustries__/graphics/icons/rocket-hull.png",
      icon_size = 32,
      subgroup = "angels-rocket",
      order = "a[parts]-a",
      stack_size = 200,
    },
    {
      type = "item",
      name = "angels-rocket-ion-thruster",
      icon = "__angelsindustries__/graphics/icons/rocket-ion-thruster.png",
      icon_size = 32,
      subgroup = "angels-rocket",
      order = "a[parts]-b",
      stack_size = 200,
    },
    {
      type = "item",
      name = "angels-rocket-ion-booster",
      icon = "__angelsindustries__/graphics/icons/rocket-ion-booster.png",
      icon_size = 32,
      subgroup = "angels-rocket",
      order = "a[parts]-c",
      stack_size = 200,
    },
    {
      type = "item",
      name = "angels-rocket-fusion-reactor",
      icon = "__angelsindustries__/graphics/icons/rocket-fusion-reactor.png",
      icon_size = 32,
      subgroup = "angels-rocket",
      order = "a[parts]-d",
      stack_size = 200,
    },
    {
      type = "item",
      name = "angels-rocket-shield-array",
      icon = "__angelsindustries__/graphics/icons/rocket-shield-array.png",
      icon_size = 32,
      subgroup = "angels-rocket",
      order = "a[parts]-e",
      stack_size = 200,
    },
    {
      type = "item",
      name = "angels-rocket-laser-array",
      icon = "__angelsindustries__/graphics/icons/rocket-laser-array.png",
      icon_size = 32,
      subgroup = "angels-rocket",
      order = "a[parts]-f",
      stack_size = 200,
    },
  })
end
