data:extend(
{
--SEPARATOR
	{
    type = "recipe",
    name = "separator",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"pipe", 10},
	{"stone-brick", 10},
	{"electronic-circuit", 5},
	},
    result= "separator",
    --icon = "__angelspetrochem__/graphics/icons/separator.png",
    },
	{
    type = "recipe",
    name = "separator-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"separator", 1},
	{"pipe", 10},
	{"aluminium-plate", 10},
	{"stone-brick", 10},
	{"advanced-circuit", 5},
	},
    result= "separator-2",
    --icon = "__angelspetrochem__/graphics/icons/separator.png",
    },
	{
    type = "recipe",
    name = "separator-3",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"separator-2", 1},
	{"pipe", 10},
	{"titanium-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "separator-3",
    --icon = "__angelspetrochem__/graphics/icons/separator.png",
    },
	{
    type = "recipe",
    name = "separator-4",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"separator-3", 1},
	{"pipe", 10},
	{"tungsten-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "separator-4",
    --icon = "__angelspetrochem__/graphics/icons/separator.png",
    },
--GAS REFINERY
	{
    type = "recipe",
    name = "gas-refinery",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"pipe", 10},
	{"stone-brick", 10},
	{"electronic-circuit", 5},
	},
    result= "gas-refinery",
    --icon = "__angelspetrochem__/graphics/icons/gas-refinery.png",
    },
	{
    type = "recipe",
    name = "gas-refinery-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"gas-refinery", 1},
	{"pipe", 10},
	{"aluminium-plate", 10},
	{"stone-brick", 10},
	{"advanced-circuit", 5},
	},
    result= "gas-refinery-2",
    --icon = "__angelspetrochem__/graphics/icons/gas-refinery.png",
    },
	{
    type = "recipe",
    name = "gas-refinery-3",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"gas-refinery-2", 1},
	{"pipe", 10},
	{"titanium-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "gas-refinery-3",
    --icon = "__angelspetrochem__/graphics/icons/gas-refinery.png",
    },
	{
    type = "recipe",
    name = "gas-refinery-4",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"gas-refinery-3", 1},
	{"pipe", 10},
	{"tungsten-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "gas-refinery-4",
    --icon = "__angelspetrochem__/graphics/icons/gas-refinery.png",
    },
--STEAM CRACKER
	{
    type = "recipe",
    name = "steam-cracker",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"pipe", 10},
	{"stone-brick", 10},
	{"electronic-circuit", 5},
	},
    result= "steam-cracker",
    --icon = "__angelspetrochem__/graphics/icons/steam-cracker.png",
    },
	{
    type = "recipe",
    name = "steam-cracker-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steam-cracker", 1},
	{"pipe", 10},
	{"aluminium-plate", 10},
	{"stone-brick", 10},
	{"advanced-circuit", 5},
	},
    result= "steam-cracker-2",
    --icon = "__angelspetrochem__/graphics/icons/steam-cracker.png",
    },
	{
    type = "recipe",
    name = "steam-cracker-3",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steam-cracker-2", 1},
	{"pipe", 10},
	{"titanium-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "steam-cracker-3",
    --icon = "__angelspetrochem__/graphics/icons/steam-cracker.png",
    },
	{
    type = "recipe",
    name = "steam-cracker-4",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steam-cracker-3", 1},
	{"pipe", 10},
	{"tungsten-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "steam-cracker-4",
    --icon = "__angelspetrochem__/graphics/icons/steam-cracker.png",
    },
 --ADVANCED CHEMICAL PLANT
	{
    type = "recipe",
    name = "advanced-chemical-plant",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"pipe", 10},
	{"stone-brick", 10},
	{"electronic-circuit", 5},
	},
    result= "advanced-chemical-plant",
    --icon = "__angelspetrochem__/graphics/icons/advanced-chemical-plant.png",
    },
	{
    type = "recipe",
    name = "advanced-chemical-plant-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"advanced-chemical-plant", 1},
	{"pipe", 10},
	{"titanium-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "advanced-chemical-plant-2",
    --icon = "__angelspetrochem__/graphics/icons/advanced-chemical-plant.png",
    },
--FLARE STACK
    {
    type = "recipe",
    name = "flare-stack",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"stone-brick", 20},
	{"electronic-circuit", 5},
	{"pipe", 5},
	},
    result= "angels-flare-stack",
    --icon = "__angelspetrochem__/graphics/icons/flare-stack.png",
    },
--VALVES
    {
    type = "recipe",
    name = "valve-check",
    energy_required = 2,
    enabled = false,
    ingredients =
    {
      {"steel-plate", 1},
      {"iron-gear-wheel", 1},
      {"pipe", 1}
    },
    result = "valve-check",
    --icon = "__angelspetrochem__/graphics/icons/valve-check.png",
    },
    {
    type = "recipe",
    name = "valve-overflow",
    energy_required = 2,
    enabled = false,
    ingredients =
    {
      {"electronic-circuit", 1},
      {"steel-plate", 1},
      {"iron-gear-wheel", 1},
      {"pipe", 1}
    },
    result = "valve-overflow",
    --icon = "__angelspetrochem__/graphics/icons/valve-overflow.png",
    },
    {
    type = "recipe",
    name = "valve-return",
    energy_required = 2,
    enabled = false,
    ingredients =
    {
      {"electronic-circuit", 1},
      {"steel-plate", 1},
      {"iron-gear-wheel", 1},
      {"pipe", 1}
    },
    result = "valve-return",
    },
    {
    type = "recipe",
    name = "valve-converter",
    energy_required = 2,
    enabled = false,
    ingredients =
    {
      {"electronic-circuit", 1},
      {"steel-plate", 1},
      {"iron-gear-wheel", 1},
      {"pipe", 1}
    },
    result = "valve-converter",
    },
--STORAGE TANKS
    {
    type = "recipe",
    name = "angels-storage-tank-1",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"iron-plate", 20},
	{"stone-brick", 10},
	{"pipe", 10},
	},
    result= "angels-storage-tank-1",
    },
    {
    type = "recipe",
    name = "angels-storage-tank-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"iron-plate", 20},
	{"stone-brick", 10},
	{"pipe", 10},
	},
    result= "angels-storage-tank-2",
    },
    {
    type = "recipe",
    name = "angels-storage-tank-3",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 5},
	{"iron-plate", 10},
	{"stone-brick", 5},
	{"pipe", 5},
	},
    result= "angels-storage-tank-3",
    },
--FLUID SPLITTER
    -- {
    -- type = "recipe",
    -- name = "fluid-splitter-2-way",
    -- energy_required = 2,
    -- enabled = false,
    -- ingredients =
    -- {
      -- {"electronic-circuit", 1},
      -- {"steel-plate", 1},
      -- {"iron-gear-wheel", 1},
      -- {"pipe", 1}
    -- },
    -- result = "angels-fluid-splitter-2-way",
    -- },
    -- {
    -- type = "recipe",
    -- name = "fluid-splitter-3-way",
    -- energy_required = 2,
    -- enabled = false,
    -- ingredients =
    -- {
      -- {"electronic-circuit", 1},
      -- {"steel-plate", 1},
      -- {"iron-gear-wheel", 1},
      -- {"pipe", 1}
    -- },
    -- result = "angels-fluid-splitter-3-way",
    -- },
--ELECTROLYSER
	{
    type = "recipe",
    name = "angels-electrolyser",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"iron-plate", 10},
	{"pipe", 10},
	{"stone-brick", 10},
	{"basic-circuit-board", 5},
	},
    result= "angels-electrolyser",
    --icon = "__angelspetrochem__/graphics/icons/electrolyser.png",
    },
	{
    type = "recipe",
    name = "angels-electrolyser-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"angels-electrolyser", 1},
	{"steel-plate", 10},
	{"pipe", 10},
	{"stone-brick", 10},
	{"electronic-circuit", 5},
	},
    result= "angels-electrolyser-2",
    --icon = "__angelspetrochem__/graphics/icons/electrolyser.png",
    },
	{
    type = "recipe",
    name = "angels-electrolyser-3",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"angels-electrolyser-2", 1},
	{"pipe", 10},
	{"aluminium-plate", 10},
	{"stone-brick", 10},
	{"advanced-circuit", 5},
	},
    result= "angels-electrolyser-3",
    --icon = "__angelspetrochem__/graphics/icons/electrolyser.png",
    },
	{
    type = "recipe",
    name = "angels-electrolyser-4",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"angels-electrolyser-3", 1},
	{"pipe", 10},
	{"titanium-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "angels-electrolyser-4",
    --icon = "__angelspetrochem__/graphics/icons/electrolyser.png",
    },
	-- {
    -- type = "recipe",
    -- name = "angels-electrolyser-4",
    -- energy_required = 10,
	-- enabled = false,
    -- ingredients ={
	-- {"angels-electrolyser-3", 1},
	-- {"pipe", 10},
	-- {"tungsten-plate", 10},
	-- {"stone-brick", 10},
	-- {"processing-unit", 5},
	-- },
    -- result= "angels-electrolyser-4",
    -- icon = "__angelspetrochem__/graphics/icons/electrolyser.png",
    -- },
--AIR FILTER
	{
    type = "recipe",
    name = "angels-air-filter",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"steel-plate", 10},
	{"pipe", 10},
	{"stone-brick", 10},
	{"electronic-circuit", 5},
	},
    result= "angels-air-filter",
    --icon = "__angelspetrochem__/graphics/icons/air-filter.png",
    },
	{
    type = "recipe",
    name = "angels-air-filter-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
	{"angels-air-filter", 1},
	{"pipe", 10},
	{"titanium-plate", 10},
	{"stone-brick", 10},
	{"processing-unit", 5},
	},
    result= "angels-air-filter-2",
    --icon = "__angelspetrochem__/graphics/icons/air-filter.png",
    },
--OIL REFINERY
	{
    type = "recipe",
    name = "oil-refinery-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
      {"oil-refinery", 1},
      {"brass-alloy", 15},
      {"brass-gear-wheel", 10},
      {"invar-alloy", 10},
      {"advanced-circuit", 10},
	  {"steel-bearing", 5},
      {"steel-pipe", 10}
	},
    result= "oil-refinery-2",
    --icon = "__base__/graphics/icons/oil-refinery.png",
    },
	{
    type = "recipe",
    name = "oil-refinery-3",
    energy_required = 5,
	enabled = false,
    ingredients ={
      {"oil-refinery-2", 1},
      {"titanium-plate", 15},
      {"titanium-gear-wheel", 10},
      {"silicon-nitride", 10},
      {"processing-unit", 10},
	  {"titanium-bearing", 5},
      {"titanium-pipe", 10}
	},
    result= "oil-refinery-3",
    --icon = "__base__/graphics/icons/oil-refinery.png",
    },
	{
    type = "recipe",
    name = "oil-refinery-4",
    energy_required = 5,
	enabled = false,
    ingredients ={
      {"oil-refinery-3", 1},
      {"nitinol-alloy", 15},
      {"nitinol-gear-wheel", 10},
      {"copper-tungsten-alloy", 10},
      {"advanced-processing-unit", 10},
	  {"nitinol-bearing", 5},
      {"tungsten-pipe", 10}
	},
    result= "oil-refinery-4",
    --icon = "__base__/graphics/icons/oil-refinery.png",
    },
--CHEMICAL PLANT
	{
    type = "recipe",
    name = "chemical-plant-2",
    energy_required = 5,
	enabled = false,
    ingredients ={
      {"chemical-plant", 1},
      {"glass", 10},
      {"steel-gear-wheel", 5},
      {"advanced-circuit", 5},
	  {"steel-bearing", 5},
      {"steel-pipe", 5},
	},
    result= "chemical-plant-2",
    --icon = "__base__/graphics/icons/chemical-plant.png",
    },
	{
    type = "recipe",
    name = "chemical-plant-3",
    energy_required = 5,
	enabled = false,
    ingredients ={
      {"chemical-plant-2", 1},
      {"titanium-plate", 10},
      {"titanium-gear-wheel", 5},
      {"processing-unit", 10},
	  {"titanium-bearing", 5},
      {"titanium-pipe", 5},
	},
    result= "chemical-plant-3",
    --icon = "__base__/graphics/icons/chemical-plant.png",
    },
	{
    type = "recipe",
    name = "chemical-plant-4",
    energy_required = 5,
	enabled = false,
    ingredients ={
      {"chemical-plant-3", 1},
      {"nitinol-alloy", 10},
      {"nitinol-gear-wheel", 5},
      {"advanced-processing-unit", 10},
	  {"nitinol-bearing", 5},
      {"tungsten-pipe", 5},
	},
    result= "chemical-plant-4",
    --icon = "__base__/graphics/icons/chemical-plant.png",
    },
  }
  )