local OV = angelsmods.functions.OV

--REFINING
if angelsmods.refining then
	OV.remove_science_pack("water-treatment-3", "angels-science-pack-green")
	OV.set_science_pack("water-treatment-3", "angels-science-pack-orange")	
	OV.remove_science_pack("water-treatment", "angels-science-pack-red")
	OV.set_science_pack("water-treatment", "angels-science-pack-grey")	
	OV.remove_science_pack("advanced-ore-refining-4", "angels-science-pack-blue")
	OV.set_science_pack("advanced-ore-refining-4", "angels-science-pack-yellow")	
	OV.remove_science_pack("ore-leaching", "angels-science-pack-blue")
	OV.set_science_pack("ore-leaching", "angels-science-pack-orange")	
	OV.remove_science_pack("geode-processing-2", "angels-science-pack-green")
	OV.set_science_pack("geode-processing-2", "angels-science-pack-orange")		
	OV.remove_science_pack("advanced-ore-refining-2", "angels-science-pack-green")
	OV.set_science_pack("advanced-ore-refining-2", "angels-science-pack-orange")	
	
	OV.set_science_pack("ore-crushing", "datacore-processing-1", 2)
	OV.set_science_pack("advanced-ore-refining-1", "datacore-processing-1", 2)
	OV.set_science_pack("geode-processing-1", "datacore-processing-1", 2)	
	OV.set_science_pack("slag-processing-1", "datacore-processing-1", 2)		
	OV.set_science_pack("ore-floatation", "datacore-processing-1", 2)		
	OV.set_science_pack("advanced-ore-refining-2", "datacore-processing-1", 2)
	OV.set_science_pack("geode-processing-2", "datacore-processing-1", 2)
	OV.set_science_pack("slag-processing-2", "datacore-processing-1", 2)		
	OV.set_science_pack("thermal-water-extraction", "datacore-processing-1", 2)		
	OV.set_science_pack("ore-leaching", "datacore-processing-1", 2)
	OV.set_science_pack("advanced-ore-refining-3", "datacore-processing-1", 2)		
	OV.set_science_pack("geode-crystallization", "datacore-processing-1", 2)		
	OV.set_science_pack("ore-refining", "datacore-processing-1", 2)		
	OV.set_science_pack("advanced-ore-refining-4", "datacore-processing-1", 2)
	OV.set_science_pack("angels-fluid-barreling", "datacore-logistic-1", 2)
	OV.set_science_pack("water-treatment", "datacore-basic", 2)	
	OV.set_science_pack("water-treatment-2", "datacore-processing-1", 2)		
	OV.set_science_pack("water-treatment-3", "datacore-processing-1", 2)
	OV.set_science_pack("water-treatment-4", "datacore-processing-1", 2)		
	OV.set_science_pack("water-washing", "datacore-processing-1", 2)		
	OV.set_science_pack("nodule-processing", "datacore-processing-1", 2)
end	
	
--PETROCHEM
if angelsmods.petrochem then
	OV.remove_science_pack("angels-advanced-chemistry-2", "angels-science-pack-green")
	OV.set_science_pack("angels-advanced-chemistry-2", "angels-science-pack-orange")	
	OV.remove_science_pack("plastic-1", "angels-science-pack-green")
	OV.set_science_pack("plastic-1", "angels-science-pack-orange")	
	OV.remove_science_pack("resin-2", "angels-science-pack-blue")
	OV.set_science_pack("resin-2", "angels-science-pack-orange")
	OV.remove_science_pack("rubber", "angels-science-pack-green")
	OV.set_science_pack("rubber", "angels-science-pack-orange")
	OV.remove_science_pack("rocket-booster-1", "angels-science-pack-green")
	OV.set_science_pack("rocket-booster-1", "angels-science-pack-orange")
	OV.remove_science_pack("rocket-explosives-1", "angels-science-pack-green")
	OV.set_science_pack("rocket-explosives-1", "angels-science-pack-orange")
	
	OV.set_science_pack("angels-fluid-control", "datacore-logistic-1", 2)
	OV.set_science_pack("basic-chemistry", "datacore-processing-1", 2)
	OV.set_science_pack("basic-chemistry-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-coal-processing", "datacore-processing-1", 2)
	OV.set_science_pack("angels-coal-processing-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-coal-cracking", "datacore-processing-1", 2)
	OV.set_science_pack("angels-sulfur-processing-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-sulfur-processing-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-nitrogen-processing-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-nitrogen-processing-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-nitrogen-processing-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-nitrogen-processing-4", "datacore-processing-1", 2)
	OV.set_science_pack("chlorine-processing-1", "datacore-processing-1", 2)
	OV.set_science_pack("chlorine-processing-2", "datacore-processing-1", 2)
	OV.set_science_pack("chlorine-processing-3", "datacore-processing-1", 2)
	OV.set_science_pack("sodium-processing", "datacore-processing-1", 2)
	OV.set_science_pack("oil-gas-extraction", "datacore-processing-1", 2)
	OV.set_science_pack("angels-oil-processing", "datacore-processing-1", 2)
	OV.set_science_pack("angels-advanced-oil-processing", "datacore-processing-1", 2)
	OV.set_science_pack("gas-processing", "datacore-processing-1", 2)
	OV.set_science_pack("angels-advanced-gas-processing", "datacore-processing-1", 2)
	OV.set_science_pack("angels-flare-stack", "datacore-processing-1", 2)
	OV.set_science_pack("angels-advanced-chemistry-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-advanced-chemistry-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-advanced-chemistry-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-advanced-chemistry-4", "datacore-processing-1", 2)
	OV.set_science_pack("gas-synthesis", "datacore-processing-1", 2)
	OV.set_science_pack("gas-steam-cracking-1", "datacore-processing-1", 2)
	OV.set_science_pack("gas-steam-cracking-2", "datacore-processing-1", 2)
	OV.set_science_pack("oil-steam-cracking-1", "datacore-processing-1", 2)
	OV.set_science_pack("oil-steam-cracking-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-electric-boiler", "datacore-energy-1", 2)
	OV.set_science_pack("plastic-1", "datacore-processing-1", 2)
	OV.set_science_pack("plastic-2", "datacore-processing-1", 2)
	OV.set_science_pack("plastic-3", "datacore-processing-1", 2)
	OV.set_science_pack("resin-1", "datacore-processing-1", 2)
	OV.set_science_pack("resin-2", "datacore-processing-1", 2)
	OV.set_science_pack("resin-3", "datacore-processing-1", 2)
	OV.set_science_pack("rubber", "datacore-processing-1", 2)
	OV.set_science_pack("angels-rocket-fuel", "datacore-processing-2", 2)
	OV.set_science_pack("rocket-booster-1", "datacore-processing-1", 2)
	OV.set_science_pack("rocket-booster-2", "datacore-processing-2", 2)
	OV.set_science_pack("rocket-explosives-1", "datacore-processing-1", 2)
	OV.set_science_pack("rocket-explosives-2", "datacore-processing-2", 2)
end

--SMELTING
if angelsmods.smelting then
	OV.remove_science_pack("angels-aluminium-smelting-2", "angels-science-pack-blue")
	OV.set_science_pack("angels-aluminium-smelting-2", "angels-science-pack-orange")
	OV.remove_science_pack("angels-copper-smelting-3", "angels-science-pack-green")
	OV.set_science_pack("angels-copper-smelting-3", "angels-science-pack-orange")
	OV.remove_science_pack("angels-iron-smelting-3", "angels-science-pack-green")
	OV.set_science_pack("angels-iron-smelting-3", "angels-science-pack-orange")
	OV.remove_science_pack("angels-silver-smelting-2", "angels-science-pack-blue")
	OV.set_science_pack("angels-silver-smelting-2", "angels-science-pack-orange")
	OV.remove_science_pack("angels-silicon-smelting-2", "angels-science-pack-blue")
	OV.set_science_pack("angels-silicon-smelting-2", "angels-science-pack-orange")
	OV.remove_science_pack("angels-zinc-smelting-2", "angels-science-pack-blue")
	OV.set_science_pack("angels-zinc-smelting-2", "angels-science-pack-orange")

	OV.set_science_pack("angels-aluminium-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-aluminium-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-aluminium-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-chrome-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-chrome-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-chrome-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-cobalt-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-cobalt-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-cobalt-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-copper-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-copper-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-copper-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-gold-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-gold-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-gold-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-iron-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-iron-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-iron-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-lead-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-lead-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-lead-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-manganese-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-manganese-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-manganese-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-nickel-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-nickel-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-nickel-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-platinum-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-platinum-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-platinum-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-silicon-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-silicon-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-silicon-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-silver-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-silver-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-silver-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-tin-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-tin-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-tin-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-titanium-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-titanium-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-titanium-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-tungsten-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-tungsten-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-tungsten-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-zinc-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-zinc-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-zinc-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-steel-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-steel-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-steel-smelting-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-solder-smelting-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-solder-smelting-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-solder-smelting-3", "datacore-processing-1", 2)

	OV.set_science_pack("angels-metallurgy-1", "datacore-processing-1", 2)
	OV.set_science_pack("angels-metallurgy-2", "datacore-processing-1", 2)
	OV.set_science_pack("angels-metallurgy-3", "datacore-processing-1", 2)
	OV.set_science_pack("angels-metallurgy-4", "datacore-processing-1", 2)
	OV.set_science_pack("advanced-angels-metallurgy-1", "datacore-processing-1", 2)
	OV.set_science_pack("advanced-angels-metallurgy-2", "datacore-processing-1", 2)
	OV.set_science_pack("advanced-angels-metallurgy-3", "datacore-processing-1", 2)
	OV.set_science_pack("advanced-angels-metallurgy-4", "datacore-processing-1", 2)
	OV.set_science_pack("ore-processing-1", "datacore-processing-1", 2)
	OV.set_science_pack("ore-processing-2", "datacore-processing-1", 2)
	OV.set_science_pack("ore-processing-3", "datacore-processing-1", 2)
	OV.set_science_pack("ore-processing-4", "datacore-processing-1", 2)
end

--BIO PROCESSING
if angelsmods.bioprocessing then
	OV.remove_science_pack("bio-processing-brown", "angels-science-pack-red")
	OV.set_science_pack("bio-processing-brown", "angels-science-pack-grey")
	OV.remove_science_pack("bio-wood-processing", "angels-science-pack-red")
	OV.set_science_pack("bio-wood-processing", "angels-science-pack-grey")
	OV.remove_science_pack("bio-paper-1", "angels-science-pack-red")
	OV.set_science_pack("bio-paper-1", "angels-science-pack-grey")
	OV.remove_science_pack("bio-temperate-farming", "angels-science-pack-red")
	OV.set_science_pack("bio-temperate-farming", "angels-science-pack-red", 4)
	
	OV.set_science_pack("bio-processing-green", "datacore-processing-1", 2)
	OV.set_science_pack("bio-processing-brown", "datacore-basic", 2)
	OV.set_science_pack("bio-processing-blue", "datacore-processing-1", 2)
	OV.set_science_pack("bio-processing-red", "datacore-processing-1", 2)
	OV.set_science_pack("bio-wood-processing", "datacore-basic", 2)
	OV.set_science_pack("bio-wood-processing-2", "datacore-processing-1", 2)
	OV.set_science_pack("bio-wood-processing-3", "datacore-processing-1", 2)
	OV.set_science_pack("bio-paper-1", "datacore-basic", 2)
	OV.set_science_pack("bio-paper-2", "datacore-processing-1", 2)
	OV.set_science_pack("bio-paper-3", "datacore-processing-1", 2)	
	OV.set_science_pack("gardens", "datacore-processing-1", 2)	
	OV.set_science_pack("bio-farm", "datacore-processing-1", 2)
	OV.set_science_pack("bio-temperate-farming", "datacore-processing-1", 8)
	OV.set_science_pack("bio-temperate-farm", "angels-science-pack-green", 4)
	OV.set_science_pack("bio-temperate-farm", "datacore-processing-1", 8)
	OV.set_science_pack("bio-desert-farming", "angels-science-pack-red", 4)
	OV.set_science_pack("bio-desert-farming", "datacore-processing-1", 8)	
	OV.set_science_pack("bio-desert-farm", "angels-science-pack-green", 4)
	OV.set_science_pack("bio-desert-farm", "datacore-processing-1", 8)	
	OV.set_science_pack("bio-swamp-farming", "angels-science-pack-red", 4)
	OV.set_science_pack("bio-swamp-farming", "datacore-processing-1", 8)
	OV.set_science_pack("bio-swamp-farm", "angels-science-pack-green", 4)
	OV.set_science_pack("bio-swamp-farm", "datacore-processing-1", 8)
	OV.set_science_pack("bio-nutrient-paste", "datacore-processing-1", 2)
	OV.set_science_pack("bio-pressing", "datacore-processing-1", 2)
	OV.set_science_pack("bio-fermentation", "datacore-processing-1", 2)
	OV.set_science_pack("bio-plastic-1", "datacore-processing-1", 2)
	OV.set_science_pack("bio-plastic-2", "datacore-processing-1", 2)
	OV.set_science_pack("bio-processing-paste", "datacore-processing-1", 2)
	OV.set_science_pack("bio-processing-alien", "datacore-processing-1", 2)
end

--COMPONENTS
if angelsmods.industries then
	OV.set_science_pack("angels-vequipment-1", "datacore-enhance-1", 2)
	OV.set_science_pack("angels-vequipment-2", "datacore-enhance-1", 2)

	OV.set_science_pack("cargo-robots", "datacore-logistic-1", 2)
	OV.set_science_pack("cargo-robots-2", "datacore-logistic-1", 2)
	OV.set_science_pack("cargo-robots-3", "datacore-logistic-1", 2)
	OV.set_science_pack("angels-crawler", "datacore-logistic-1", 2)
	OV.set_science_pack("angels-crawler-train", "datacore-logistic-1", 2)
	OV.set_science_pack("angels-yellow-loader", "datacore-logistic-1", 2)
	OV.set_science_pack("angels-red-loader", "datacore-logistic-1", 2)
	OV.set_science_pack("angels-blue-loader", "datacore-logistic-1", 2)
end

--EXPLORATION
if angelsmods.exploration then
	OV.set_science_pack("angels-heavy-tank", "datacore-war-1", 2)
end

--ADDONS
if angelsmods.addons then
	--PRESSURE TANKS
	if angelsmods.addons.pressuretanks then
		OV.set_science_pack("pressure-tanks", "datacore-logistic-1", 2)
	end
	--ORE SILORS
	if angelsmods.addons.oresilos then
		OV.set_science_pack("ore-silos", "datacore-logistic-1", 2)
	end
	--WAREHOUSES
	if angelsmods.addons.warehouses then
		OV.set_science_pack("angels-warehouses", "datacore-logistic-1", 2)
		OV.set_science_pack("angels-logistic-warehouses", "datacore-logistic-1", 2)
	end
	--PETROTRAIN
	if angelsmods.addons.petrotrain then
		OV.set_science_pack("angels-petro-train", "datacore-logistic-1", 2)
	end
end