local AF = angelsmods.functions

data:extend({
  --SOLIDS
  {
    type = "recipe",
    name = "angels-solid-plastic",
    localised_name = { "item-name.plastic-bar" },
    category = "crafting-with-fluid",
    subgroup = "angels-petrochem-solids",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "fluid", name = "angels-liquid-plastic", amount = 40 },
    },
    results = {
      { type = "item", name = "plastic-bar", amount = 4 },
    },
    icon_size = 32,
    crafting_machine_tint = AF.get_fluid_recipe_tint("angels-liquid-plastic"),
    order = "a[plastic]-b[solid]",
  },
  {
    type = "recipe",
    name = "angels-liquid-plastic",
    category = "angels-liquifying",
    subgroup = "angels-petrochem-solids",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-gas-propene", amount = 40 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-plastic", amount = 10 },
    },
    always_show_products = true,
    icons = AF.create_viscous_liquid_recipe_icon(nil, { { 255, 255, 255 }, { 255, 255, 255 } }, {
      AF.add_number_icon_layer({}, 1, angelsmods.petrochem.number_tint),
    }),
    crafting_machine_tint = AF.get_recipe_tints({ "angels-liquid-plastic", "angels-gas-propene" }),
    order = "a[plastic]-a[liquid]-a",
  },
  {
    type = "recipe",
    name = "angels-liquid-plastic-2",
    localised_name = { "fluid-name.angels-liquid-plastic" },
    category = "chemistry",
    subgroup = "angels-petrochem-solids",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-liquid-naphtha", amount = 20 },
      { type = "fluid", name = "angels-liquid-polyethylene", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-plastic", amount = 20 },
    },
    always_show_products = true,
    icons = AF.create_viscous_liquid_recipe_icon(nil, { { 255, 255, 255 }, { 255, 255, 255 } }, {
      AF.add_number_icon_layer({}, 2, angelsmods.petrochem.number_tint),
    }),
    crafting_machine_tint = AF.get_recipe_tints({ "angels-liquid-plastic", "angels-liquid-naphthta", "angels-liquid-polyethylene" }),
    order = "a[plastic]-a[liquid]-b",
  },
  {
    type = "recipe",
    name = "angels-liquid-plastic-3",
    localised_name = { "fluid-name.angels-liquid-plastic" },
    category = "chemistry",
    subgroup = "angels-petrochem-solids",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-gas-formaldehyde", amount = 20 },
      { type = "fluid", name = "angels-liquid-phenol", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-plastic", amount = 30 },
    },
    always_show_products = true,
    icons = AF.create_viscous_liquid_recipe_icon(nil, { { 255, 255, 255 }, { 255, 255, 255 } }, {
      AF.add_number_icon_layer({}, 3, angelsmods.petrochem.number_tint),
    }),
    crafting_machine_tint = AF.get_recipe_tints({ "angels-liquid-plastic", "angels-gas-formaldehyde", "angels-liquid-phenol" }),
    order = "a[plastic]-a[liquid]-c",
  },
  --RESIN
  {
    type = "recipe",
    name = "angels-solid-resin",
    localised_name = { "item-name.angels-solid-resin" },
    category = "crafting-with-fluid",
    subgroup = "angels-petrochem-solids",
    enabled = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "fluid", name = "angels-liquid-resin", amount = 40 },
    },
    results = {
      { type = "item", name = "angels-solid-resin", amount = 4 },
    },
    crafting_machine_tint = AF.get_fluid_recipe_tint("angels-liquid-resin"),
    order = "b[resin]-b[solid]",
  },
  {
    type = "recipe",
    name = "angels-liquid-resin",
    category = "chemistry",
    subgroup = "angels-petrochem-solids",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-gas-urea", amount = 20 },
      { type = "fluid", name = "angels-gas-formaldehyde", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-resin", amount = 10 },
    },
    always_show_products = true,
    icons = AF.create_viscous_liquid_recipe_icon(nil, { { 255, 225, 155 }, { 255, 225, 155 } }, {
      AF.add_number_icon_layer({}, 1, angelsmods.petrochem.number_tint),
    }),
    crafting_machine_tint = AF.get_recipe_tints({ "angels-liquid-resin", "angels-gas-urea", "angels-gas-formaldehyde" }),
    order = "b[resin]-a[liquid]-a",
  },
  {
    type = "recipe",
    name = "angels-liquid-resin-2",
    localised_name = { "fluid-name.angels-liquid-resin" },
    category = "chemistry",
    subgroup = "angels-petrochem-solids",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-gas-melamine", amount = 20 },
      { type = "fluid", name = "angels-gas-formaldehyde", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-resin", amount = 20 },
    },
    always_show_products = true,
    icons = AF.create_viscous_liquid_recipe_icon(nil, { { 255, 225, 155 }, { 255, 225, 155 } }, {
      AF.add_number_icon_layer({}, 2, angelsmods.petrochem.number_tint),
    }),
    crafting_machine_tint = AF.get_recipe_tints({ "angels-liquid-resin", "angels-gas-melamine", "angels-gas-formaldehyde" }),
    order = "b[resin]-a[liquid]-b",
  },
  {
    type = "recipe",
    name = "angels-liquid-resin-3",
    localised_name = { "fluid-name.angels-liquid-resin" },
    category = "chemistry",
    subgroup = "angels-petrochem-solids",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-liquid-bisphenol-a", amount = 20 },
      { type = "fluid", name = "angels-gas-epichlorhydrin", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-resin", amount = 30 },
    },
    always_show_products = true,
    icons = AF.create_viscous_liquid_recipe_icon(nil, { { 255, 225, 155 }, { 255, 225, 155 } }, {
      AF.add_number_icon_layer({}, 3, angelsmods.petrochem.number_tint),
    }),
    crafting_machine_tint = AF.get_recipe_tints({ "angels-liquid-resin", "angels-liquid-bisphenol-a", "angels-gas-epichlorhydrin" }),
    order = "b[resin]-a[liquid]-c",
  },
  --RUBBER
  {
    type = "recipe",
    name = "angels-solid-rubber",
    localised_name = { "item-name.angels-solid-rubber" },
    category = "crafting-with-fluid",
    subgroup = "angels-petrochem-solids-2",
    enabled = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "fluid", name = "angels-liquid-rubber", amount = 40 },
    },
    results = {
      { type = "item", name = "angels-solid-rubber", amount = 4 },
    },
    crafting_machine_tint = AF.get_fluid_recipe_tint("angels-liquid-rubber"),
    order = "b[rubber]-b[solid]",
  },
  {
    type = "recipe",
    name = "angels-liquid-rubber",
    category = "chemistry",
    subgroup = "angels-petrochem-solids-2",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-liquid-styrene", amount = 20 },
      { type = "fluid", name = "angels-gas-butadiene", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-rubber", amount = 10 },
    },
    always_show_products = true,
    icons = AF.create_viscous_liquid_recipe_icon(nil, { { 193, 197, 255 }, { 193, 197, 255 } }),
    crafting_machine_tint = AF.get_recipe_tints({ "angels-liquid-rubber", "angels-liquid-styrene", "angels-gas-butadiene" }),
    order = "b[rubber]-a[liquid]",
  },
  --FUEL
  {
    type = "recipe",
    name = "angels-solid-fuel-methane",
    localised_name = { "item-name.solid-fuel" },
    category = "chemistry",
    subgroup = "angels-petrochem-fuel",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-solid-coke", amount = 1 },
      { type = "fluid", name = "angels-gas-methane", amount = 100 },
    },
    results = {
      { type = "item", name = "solid-fuel", amount = 2 },
    },
    icons = AF.create_solid_recipe_icon({
      { "__angelspetrochemgraphics__/graphics/icons/molecules/methane.png", 72 },
    }, "solid-fuel"),
    crafting_machine_tint = AF.get_recipe_tints({ { r = 1, g = 1, b = 1 }, "angels-gas-methane" }),
    order = "a[solid-fuel-methane]",
  },
  {
    type = "recipe",
    name = "angels-solid-fuel-naphtha",
    localised_name = { "item-name.solid-fuel" },
    category = "chemistry",
    subgroup = "angels-petrochem-fuel",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-solid-coke", amount = 1 },
      { type = "fluid", name = "angels-liquid-naphtha", amount = 100 },
    },
    results = {
      { type = "item", name = "solid-fuel", amount = 2 },
    },
    icons = AF.create_solid_recipe_icon({
      "angels-liquid-naphtha",
    }, "solid-fuel"),
    crafting_machine_tint = AF.get_recipe_tints({
      { r = 105 / 255, g = 105 / 255, b = 105 / 255 },
      "angels-liquid-naphtha",
      AF.fluid_color("Cb"),
    }),
    order = "b[solid-fuel-naphtha]",
  },
  {
    type = "recipe",
    name = "angels-solid-fuel-fuel-oil",
    localised_name = { "item-name.solid-fuel" },
    category = "chemistry",
    subgroup = "angels-petrochem-fuel",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-solid-coke", amount = 1 },
      { type = "fluid", name = "angels-liquid-fuel-oil", amount = 50 },
    },
    results = {
      { type = "item", name = "solid-fuel", amount = 2 },
    },
    icons = AF.create_solid_recipe_icon({
      "angels-liquid-fuel-oil",
    }, "solid-fuel"),
    crafting_machine_tint = AF.get_recipe_tints({
      { r = 105 / 255, g = 105 / 255, b = 105 / 255 },
      "angels-liquid-fuel-oil",
      AF.fluid_color("Cb"),
    }),
    order = "c[solid-fuel-fuel-oil]",
  },
  {
    type = "recipe",
    name = "angels-solid-fuel-synthesis",
    localised_name = { "item-name.solid-fuel" },
    category = "chemistry",
    subgroup = "angels-petrochem-fuel",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-solid-coke", amount = 1 },
      { type = "fluid", name = "angels-gas-synthesis", amount = 100 },
    },
    results = {
      { type = "item", name = "solid-fuel", amount = 2 },
    },
    icons = AF.create_solid_recipe_icon({
      "angels-gas-synthesis",
    }, "solid-fuel"),
    crafting_machine_tint = AF.get_recipe_tints({
      { r = 105 / 255, g = 105 / 255, b = 105 / 255 },
      "angels-gas-synthesis",
      AF.fluid_color("Cb"),
    }),
    order = "d[solid-fuel-synthesis]",
  },
  {
    type = "recipe",
    name = "angels-solid-fuel-hydrazine",
    localised_name = { "item-name.solid-fuel" },
    category = "chemistry",
    subgroup = "angels-petrochem-fuel",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-gas-hydrazine", amount = 50 },
    },
    results = {
      { type = "item", name = "solid-fuel", amount = 2 },
    },
    icons = AF.create_solid_recipe_icon({
      { "__angelspetrochemgraphics__/graphics/icons/molecules/hydrazine.png", 72 },
    }, "solid-fuel"),
    crafting_machine_tint = AF.get_recipe_tints({ { r = 105 / 255, g = 105 / 255, b = 105 / 255 }, "angels-gas-hydrazine" }),
    order = "e[solid-fuel-hydrazine]",
  },
  --CATALYSTS
  {
    type = "recipe",
    name = "angels-catalyst-metal-carrier",
    localised_name = { "item-name.angels-catalyst-metal-carrier" },
    category = "crafting",
    subgroup = "angels-petrochem-catalysts",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "item", name = "iron-plate", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-catalyst-metal-carrier", amount = 10 },
    },
    icon = "__angelspetrochemgraphics__/graphics/icons/catalyst-metal-carrier.png",
    icon_size = 32,
    order = "c[catalyst-metal]-a[carrier]",
  },
  {
    type = "recipe",
    name = "angels-catalyst-metal-red",
    localised_name = { "item-name.angels-catalyst-metal-red" },
    category = "crafting",
    subgroup = "angels-petrochem-catalysts",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-catalyst-metal-carrier", amount = 10, ignored_by_stats = 10 },
      -- {type="item", name="iron-ore", amount=1},
      -- {type="item", name="copper-ore", amount=1},
    },
    results = {
      { type = "item", name = "angels-catalyst-metal-red", amount = 10 },
    },
    icon = "__angelspetrochemgraphics__/graphics/icons/catalyst-metal-red.png",
    icon_size = 32,
    order = "c[catalyst-metal]-b[red]",
  },
  {
    type = "recipe",
    name = "angels-catalyst-metal-green",
    localised_name = { "item-name.angels-catalyst-metal-green" },
    category = "crafting",
    subgroup = "angels-petrochem-catalysts",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-catalyst-metal-carrier", amount = 10, ignored_by_stats = 10 },
      -- {type="item", name="angels-bauxite-ore", amount=1},
      -- {type="item", name="angels-silver-ore", amount=1},
    },
    results = {
      { type = "item", name = "angels-catalyst-metal-green", amount = 10 },
    },
    icon = "__angelspetrochemgraphics__/graphics/icons/catalyst-metal-green.png",
    icon_size = 32,
    order = "c[catalyst-metal]-c[green]",
  },
  {
    type = "recipe",
    name = "angels-catalyst-metal-blue",
    localised_name = { "item-name.angels-catalyst-metal-blue" },
    category = "crafting",
    subgroup = "angels-petrochem-catalysts",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-catalyst-metal-carrier", amount = 10, ignored_by_stats = 10 },
      -- {type="item", name="angels-rutile-ore", amount=1},
      -- {type="item", name="angels-cobalt-ore", amount=1},
    },
    results = {
      { type = "item", name = "angels-catalyst-metal-blue", amount = 10 },
    },
    icon = "__angelspetrochemgraphics__/graphics/icons/catalyst-metal-blue.png",
    icon_size = 32,
    order = "c[catalyst-metal]-d[blue]",
  },
  {
    type = "recipe",
    name = "angels-catalyst-metal-yellow",
    localised_name = { "item-name.angels-catalyst-metal-yellow" },
    category = "crafting",
    subgroup = "angels-petrochem-catalysts",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-catalyst-metal-carrier", amount = 10, ignored_by_stats = 10 },
      -- {type="item", name="angels-tungsten-ore", amount=1},
      -- {type="item", name="angels-nickel-ore", amount=1},
    },
    results = {
      { type = "item", name = "angels-catalyst-metal-yellow", amount = 10 },
    },
    icon = "__angelspetrochemgraphics__/graphics/icons/catalyst-metal-yellow.png",
    icon_size = 32,
    order = "c[catalyst-metal]-e[yellow]",
  },
  --SPECIAL CATALYSTS
  {
    type = "recipe",
    name = "angels-electrode",
    localised_name = { "item-name.angels-electrode" },
    category = "crafting",
    subgroup = "angels-petrochem-catalysts",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "angels-solid-carbon", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-electrode", amount = 1 },
    },
    icon_size = 32,
    order = "a[electrode]-a[create]",
  },
  {
    type = "recipe",
    name = "angels-electrode-used",
    category = "chemistry",
    subgroup = "angels-petrochem-catalysts",
    energy_required = 1,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "angels-electrode-used", amount = 1 },
      { type = "fluid", name = "angels-water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-electrode", amount = 1 },
      { type = "fluid", name = "angels-water-mineralized", amount = 10 },
      { type = "fluid", name = "water", amount = 40 },
    },
    icon = "__angelspetrochemgraphics__/graphics/icons/solid-electrode-used.png",
    icon_size = 32,
    crafting_machine_tint = AF.get_recipe_tints({ "angels-water-mineralized", "angels-water-purified", "water" }),
    order = "a[electrode]-b[recycle]",
  },
  --EXPLOSIVES
  {
    type = "recipe",
    name = "angels-solid-nitroglycerin",
    localised_name = { "item-name.explosives" },
    category = "angels-advanced-chemistry",
    subgroup = "angels-petrochem-solids-2",
    energy_required = 2,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "fluid", name = "angels-liquid-glycerol", amount = 50 },
      { type = "fluid", name = "angels-liquid-sulfuric-acid", amount = 25 },
      { type = "fluid", name = "angels-liquid-nitric-acid", amount = 25 },
      { type = "item", name = "coal", amount = 1 },
    },
    results = {
      { type = "item", name = "explosives", amount = 2 },
    },
    icons = AF.add_number_icon_layer(AF.get_object_icons("explosives"), 2, angelsmods.petrochem.number_tint),
    main_product = "explosives",
    crafting_machine_tint = AF.get_recipe_tints({
      { r = 1, g = 0, b = 0 },
      "angels-liquid-glycerol",
      "angels-liquid-sulfuric-acid",
      "angels-liquid-nitric-acid",
    }),
    order = "a[explosives]-b",
  },
  {
    type = "recipe",
    name = "angels-solid-trinitrotoluene",
    localised_name = { "item-name.explosives" },
    category = "angels-advanced-chemistry",
    subgroup = "angels-petrochem-solids-2",
    energy_required = 2,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "fluid", name = "angels-liquid-toluene", amount = 50 },
      { type = "fluid", name = "angels-liquid-sulfuric-acid", amount = 25 },
      { type = "fluid", name = "angels-liquid-nitric-acid", amount = 25 },
    },
    results = {
      --{type="item", name="angels-solid-trinitrotoluene", amount=1},
      { type = "item", name = "explosives", amount = 3 },
      { type = "fluid", name = "angels-water-yellow-waste", amount = 25 },
    },
    icons = AF.add_number_icon_layer(AF.get_object_icons("explosives"), 3, angelsmods.petrochem.number_tint),
    main_product = "explosives",
    crafting_machine_tint = AF.get_recipe_tints({
      { r = 1, g = 0, b = 0 },
      "angels-liquid-toluene",
      "angels-liquid-sulfuric-acid",
      "angels-liquid-nitric-acid",
    }),
    order = "a[explosives]-c",
  },
})
