angelsmods.functions.RB.build({
  --SEPARATOR
  {
    type = "recipe",
    name = "angels-separator",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "ogseparat-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 2 },
      { type = "item", name = "t1-circuit", amount = 5 },
      { type = "item", name = "t1-brick", amount = 5 },
      { type = "item", name = "t1-pipe", amount = 10 },
    },
    results = { { type = "item", name = "angels-separator", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-separator-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "ogseparat-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-circuit", amount = 5 },
      { type = "item", name = "t3-brick", amount = 5 },
      { type = "item", name = "t3-pipe", amount = 10 },
    },
    results = { { type = "item", name = "angels-separator-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-separator-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "ogseparat-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-circuit", amount = 5 },
      { type = "item", name = "t4-brick", amount = 5 },
      { type = "item", name = "t4-pipe", amount = 10 },
    },
    results = { { type = "item", name = "angels-separator-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-separator-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "ogseparat-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 2 },
      { type = "item", name = "t5-circuit", amount = 5 },
      { type = "item", name = "t5-brick", amount = 5 },
      { type = "item", name = "t5-pipe", amount = 10 },
    },
    results = { { type = "item", name = "angels-separator-4", amount = 1 } },
  },
  --GAS REFINERY SMALL
  {
    type = "recipe",
    name = "angels-gas-refinery-small",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasrefsm-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 2 },
      { type = "item", name = "t1-circuit", amount = 4 },
      { type = "item", name = "t1-brick", amount = 4 },
      { type = "item", name = "t1-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-gas-refinery-small", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-gas-refinery-small-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasrefsm-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-circuit", amount = 4 },
      { type = "item", name = "t3-brick", amount = 4 },
      { type = "item", name = "t3-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-gas-refinery-small-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-gas-refinery-small-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasrefsm-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-circuit", amount = 4 },
      { type = "item", name = "t4-brick", amount = 4 },
      { type = "item", name = "t4-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-gas-refinery-small-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-gas-refinery-small-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasrefsm-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 2 },
      { type = "item", name = "t5-circuit", amount = 4 },
      { type = "item", name = "t5-brick", amount = 4 },
      { type = "item", name = "t5-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-gas-refinery-small-4", amount = 1 } },
  },
  --GAS REFINERY
  {
    type = "recipe",
    name = "angels-gas-refinery",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasref-1", amount = 1 },
      { type = "item", name = "t3-plate", amount = 5 },
      { type = "item", name = "t3-circuit", amount = 10 },
      { type = "item", name = "t3-brick", amount = 10 },
      { type = "item", name = "t3-pipe", amount = 19 },
    },
    results = { { type = "item", name = "angels-gas-refinery", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-gas-refinery-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasref-2", amount = 1 },
      { type = "item", name = "t4-plate", amount = 5 },
      { type = "item", name = "t4-circuit", amount = 10 },
      { type = "item", name = "t4-brick", amount = 10 },
      { type = "item", name = "t4-pipe", amount = 19 },
    },
    results = { { type = "item", name = "angels-gas-refinery-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-gas-refinery-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasref-3", amount = 1 },
      { type = "item", name = "t5-plate", amount = 5 },
      { type = "item", name = "t5-circuit", amount = 10 },
      { type = "item", name = "t5-brick", amount = 10 },
      { type = "item", name = "t5-pipe", amount = 19 },
    },
    results = { { type = "item", name = "angels-gas-refinery-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-gas-refinery-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "gasref-4", amount = 1 },
      { type = "item", name = "t6-plate", amount = 10 },
      { type = "item", name = "t6-circuit", amount = 5 },
      { type = "item", name = "t6-brick", amount = 10 },
      { type = "item", name = "t6-pipe", amount = 10 },
    },
    results = { { type = "item", name = "angels-gas-refinery-4", amount = 1 } },
  },
  --STEAM CRACKER
  {
    type = "recipe",
    name = "angels-steam-cracker",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cracker-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 2 },
      { type = "item", name = "t2-circuit", amount = 4 },
      { type = "item", name = "t2-brick", amount = 4 },
      { type = "item", name = "t2-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-steam-cracker", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-steam-cracker-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cracker-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-circuit", amount = 4 },
      { type = "item", name = "t3-brick", amount = 4 },
      { type = "item", name = "t3-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-steam-cracker-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-steam-cracker-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cracker-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-circuit", amount = 4 },
      { type = "item", name = "t4-brick", amount = 4 },
      { type = "item", name = "t4-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-steam-cracker-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-steam-cracker-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cracker-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 2 },
      { type = "item", name = "t5-circuit", amount = 4 },
      { type = "item", name = "t5-brick", amount = 4 },
      { type = "item", name = "t5-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-steam-cracker-4", amount = 1 } },
  },
  --ADVANCED CHEMICAL PLANT
  {
    type = "recipe",
    name = "angels-advanced-chemical-plant",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "advchem-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 2 },
      { type = "item", name = "t2-circuit", amount = 4 },
      { type = "item", name = "t2-brick", amount = 4 },
      { type = "item", name = "t2-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-advanced-chemical-plant", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-advanced-chemical-plant-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "advchem-2", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-circuit", amount = 4 },
      { type = "item", name = "t4-brick", amount = 4 },
      { type = "item", name = "t4-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-advanced-chemical-plant-2", amount = 1 } },
  },
  --FLARE STACK
  {
    type = "recipe",
    name = "angels-flare-stack",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "t0-plate", amount = 1 },
      { type = "item", name = "t0-circuit", amount = 1 },
      { type = "item", name = "t0-brick", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 1 },
    },
    results = { { type = "item", name = "angels-flare-stack", amount = 1 } },
  },
  --VALVES
  {
    type = "recipe",
    name = "angels-valve-inspector",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "t0-circuit", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 1 },
    },
    results = { { type = "item", name = "angels-valve-inspector", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-valve-one-way",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "t0-circuit", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 1 },
    },
    results = { { type = "item", name = "angels-valve-one-way", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-valve-overflow",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "t0-circuit", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 1 },
    },
    results = { { type = "item", name = "angels-valve-overflow", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-valve-top-up",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "t0-circuit", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 1 },
    },
    results = { { type = "item", name = "angels-valve-top-up", amount = 1 } },
  },
  --STORAGE TANKS
  {
    type = "recipe",
    name = "angels-storage-tank-1",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "t1-plate", amount = 2 },
      { type = "item", name = "t1-brick", amount = 4 },
      { type = "item", name = "t1-pipe", amount = 10 },
    },
    results = { { type = "item", name = "angels-storage-tank-1", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-storage-tank-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "t1-plate", amount = 4 },
      { type = "item", name = "t1-brick", amount = 8 },
      { type = "item", name = "t1-pipe", amount = 13 },
    },
    results = { { type = "item", name = "angels-storage-tank-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-storage-tank-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "t0-plate", amount = 1 },
      { type = "item", name = "t0-brick", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 2 },
    },
    results = { { type = "item", name = "angels-storage-tank-3", amount = 1 } },
  },
  --ELECTROLYSER
  {
    type = "recipe",
    name = "angels-electrolyser",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "electrol-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 3 },
      { type = "item", name = "t0-circuit", amount = 3 },
      { type = "item", name = "t0-brick", amount = 3 },
      { type = "item", name = "t0-pipe", amount = 13 },
    },
    results = { { type = "item", name = "angels-electrolyser", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-electrolyser-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "electrol-2", amount = 1 },
      { type = "item", name = "t2-plate", amount = 3 },
      { type = "item", name = "t2-circuit", amount = 3 },
      { type = "item", name = "t2-brick", amount = 3 },
      { type = "item", name = "t2-pipe", amount = 13 },
    },
    results = { { type = "item", name = "angels-electrolyser-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-electrolyser-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "electrol-3", amount = 1 },
      { type = "item", name = "t3-plate", amount = 3 },
      { type = "item", name = "t3-circuit", amount = 3 },
      { type = "item", name = "t3-brick", amount = 3 },
      { type = "item", name = "t3-pipe", amount = 13 },
    },
    results = { { type = "item", name = "angels-electrolyser-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-electrolyser-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "electrol-4", amount = 1 },
      { type = "item", name = "t4-plate", amount = 3 },
      { type = "item", name = "t4-circuit", amount = 3 },
      { type = "item", name = "t4-brick", amount = 3 },
      { type = "item", name = "t4-pipe", amount = 13 },
    },
    results = { { type = "item", name = "angels-electrolyser-4", amount = 1 } },
  },
  --AIR FILTER
  {
    type = "recipe",
    name = "angels-air-filter",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "airfilter-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 4 },
      { type = "item", name = "t0-circuit", amount = 5 },
      { type = "item", name = "t0-brick", amount = 5 },
      { type = "item", name = "t0-pipe", amount = 8 },
    },
    results = { { type = "item", name = "angels-air-filter", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-air-filter-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "airfilter-2", amount = 1 },
      { type = "item", name = "t2-plate", amount = 4 },
      { type = "item", name = "t2-circuit", amount = 5 },
      { type = "item", name = "t2-brick", amount = 5 },
      { type = "item", name = "t2-pipe", amount = 8 },
    },
    results = { { type = "item", name = "angels-air-filter-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-air-filter-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "airfilter-3", amount = 1 },
      { type = "item", name = "t3-plate", amount = 4 },
      { type = "item", name = "t3-circuit", amount = 5 },
      { type = "item", name = "t3-brick", amount = 5 },
      { type = "item", name = "t3-pipe", amount = 8 },
    },
    results = { { type = "item", name = "angels-air-filter-3", amount = 1 } },
  },
  --OIL REFINERY
  {
    type = "recipe",
    name = "oil-refinery",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "oilref-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 2 },
      { type = "item", name = "t1-gears", amount = 4 },
      { type = "item", name = "t1-circuit", amount = 4 },
      { type = "item", name = "t1-pipe", amount = 12 },
    },
    results = { { type = "item", name = "oil-refinery", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-oil-refinery-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "oilref-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-gears", amount = 4 },
      { type = "item", name = "t3-circuit", amount = 4 },
      { type = "item", name = "t3-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-oil-refinery-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-oil-refinery-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "oilref-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-gears", amount = 4 },
      { type = "item", name = "t4-circuit", amount = 4 },
      { type = "item", name = "t4-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-oil-refinery-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-oil-refinery-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "oilref-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 2 },
      { type = "item", name = "t5-gears", amount = 4 },
      { type = "item", name = "t5-circuit", amount = 4 },
      { type = "item", name = "t5-pipe", amount = 12 },
    },
    results = { { type = "item", name = "angels-oil-refinery-4", amount = 1 } },
  },
  --CHEMICAL PLANT
  {
    type = "recipe",
    name = "angels-chemical-plant",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chem-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 2 },
      { type = "item", name = "t0-gears", amount = 1 },
      { type = "item", name = "t0-circuit", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 4 },
    },
    results = { { type = "item", name = "angels-chemical-plant", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-chemical-plant-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chem-2", amount = 1 },
      { type = "item", name = "t2-plate", amount = 2 },
      { type = "item", name = "t2-gears", amount = 1 },
      { type = "item", name = "t2-circuit", amount = 1 },
      { type = "item", name = "t2-pipe", amount = 4 },
    },
    results = { { type = "item", name = "angels-chemical-plant-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-chemical-plant-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chem-3", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-gears", amount = 1 },
      { type = "item", name = "t3-circuit", amount = 1 },
      { type = "item", name = "t3-pipe", amount = 4 },
    },
    results = { { type = "item", name = "angels-chemical-plant-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-chemical-plant-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chem-4", amount = 1 },
      { type = "item", name = "t4-plate", amount = 1 },
      { type = "item", name = "t4-gears", amount = 1 },
      { type = "item", name = "t4-circuit", amount = 1 },
      { type = "item", name = "t4-pipe", amount = 4 },
    },
    results = { { type = "item", name = "angels-chemical-plant-4", amount = 1 } },
  },
  --ELECTRIC BOILER
  {
    type = "recipe",
    name = "angels-electric-boiler",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "t2-plate", amount = 1 },
      { type = "item", name = "t2-circuit", amount = 2 },
      { type = "item", name = "t2-brick", amount = 1 },
      { type = "item", name = "t2-pipe", amount = 5 },
    },
    results = { { type = "item", name = "angels-electric-boiler", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-electric-boiler-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "elec-boil-1", amount = 1 },
      { type = "item", name = "t3-plate", amount = 1 },
      { type = "item", name = "t3-circuit", amount = 2 },
      { type = "item", name = "t3-brick", amount = 1 },
      { type = "item", name = "t3-pipe", amount = 5 },
    },
    results = { { type = "item", name = "angels-electric-boiler-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-electric-boiler-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "elec-boil-2", amount = 1 },
      { type = "item", name = "t5-plate", amount = 1 },
      { type = "item", name = "t5-circuit", amount = 2 },
      { type = "item", name = "t5-brick", amount = 1 },
      { type = "item", name = "t5-pipe", amount = 5 },
    },
    results = { { type = "item", name = "angels-electric-boiler-3", amount = 1 } },
  },
})
