data:extend({
  -- ORE
  {
    type = "item",
    name = "angels-manganese-ore",
    icon = "__angelssmeltinggraphics__/graphics/icons/ore-manganese.png",
    icon_size = 32,
    subgroup = "angels-manganese",
    order = "a",
    stack_size = 200,
  },
  -- SMELTING INTERMEDIATE
  {
    type = "item",
    name = "angels-processed-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/processed-manganese.png",
    icon_size = 64,
    subgroup = "angels-manganese",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-pellet-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/pellet-manganese.png",
    icon_size = 64,
    subgroup = "angels-manganese",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-solid-manganese-oxide",
    icon = "__angelssmeltinggraphics__/graphics/icons/solid-manganese-oxide.png",
    icon_size = 32,
    subgroup = "angels-manganese",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-cathode-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/cathode-manganese.png",
    icon_size = 32,
    subgroup = "angels-manganese",
    order = "e",
    stack_size = 200,
  },
  -- SMELTING RESULTS
  {
    type = "item",
    name = "angels-ingot-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/ingot-manganese.png",
    icon_size = 64,
    subgroup = "angels-manganese",
    order = "f",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-powder-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/powder-manganese.png",
    icon_size = 64,
    subgroup = "angels-manganese",
    order = "g",
    stack_size = 200,
  },
  -- CASTING INTERMEDIATE
  {
    type = "fluid",
    name = "angels-liquid-molten-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/molten-manganese.png",
    icon_size = 64,
    subgroup = "angels-manganese-casting",
    order = "h",
    default_temperature = 1246,
    heat_capacity = "0kJ",
    base_color = { r = 242 / 255, g = 97 / 255, b = 97 / 255 },
    flow_color = { r = 242 / 255, g = 97 / 255, b = 97 / 255 },
    max_temperature = 1246,
    auto_barrel = false,
  },
  {
    type = "item",
    name = "angels-roll-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/roll-manganese.png",
    icon_size = 64,
    subgroup = "angels-manganese-casting",
    order = "i",
    stack_size = 200,
  },
  -- CASTING RESULT
  {
    type = "item",
    name = "angels-plate-manganese",
    icon = "__angelssmeltinggraphics__/graphics/icons/plate-manganese.png",
    icon_size = 32,
    subgroup = "angels-manganese-casting",
    order = "j",
    stack_size = 200,
  },
})
