data:extend({
  -- ORE
  -- order a reserved for ore
  -- SMELTING INTERMEDIATE
  {
    type = "item",
    name = "angels-processed-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/processed-copper.png",
    icon_size = 64,
    subgroup = "angels-copper",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-pellet-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/pellet-copper.png",
    icon_size = 64,
    subgroup = "angels-copper",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-anode-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/anode-copper.png",
    icon_size = 32,
    subgroup = "angels-copper",
    order = "d",
    stack_size = 200,
  },
  -- SMELTING RESULTS
  {
    type = "item",
    name = "angels-ingot-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/ingot-copper.png",
    icon_size = 64,
    subgroup = "angels-copper",
    order = "e",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-powder-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/powder-copper.png",
    icon_size = 64,
    subgroup = "angels-copper",
    order = "f",
    stack_size = 200,
  },
  -- CASTING INTERMEDIATE
  {
    type = "fluid",
    name = "angels-liquid-molten-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/molten-copper.png",
    icon_size = 64,
    subgroup = "angels-copper-casting",
    order = "g",
    default_temperature = 1085,
    heat_capacity = "0kJ",
    base_color = { r = 154 / 255, g = 101 / 255, b = 86 / 255 },
    flow_color = { r = 154 / 255, g = 101 / 255, b = 86 / 255 },
    max_temperature = 1085,
    auto_barrel = false,
  },
  {
    type = "item",
    name = "angels-roll-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/roll-copper.png",
    icon_size = 64,
    subgroup = "angels-copper-casting",
    order = "h",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-wire-coil-copper",
    icon = "__angelssmeltinggraphics__/graphics/icons/wire-coil-copper.png",
    icon_size = 64,
    subgroup = "angels-copper-casting",
    order = "i",
    stack_size = 200,
  },
})
