data:extend({
  --ORE
  {
    type = "item",
    name = "angels-chrome-ore",
    icon = "__angelssmeltinggraphics__/graphics/icons/ore-chrome.png",
    icon_size = 32,
    subgroup = "angels-chrome",
    order = "a",
    stack_size = 200,
  },
  -- SMELTING INTERMEDIATE
  {
    type = "item",
    name = "angels-processed-chrome",
    icon = "__angelssmeltinggraphics__/graphics/icons/processed-chrome.png",
    icon_size = 64,
    subgroup = "angels-chrome",
    order = "b",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-pellet-chrome",
    icon = "__angelssmeltinggraphics__/graphics/icons/pellet-chrome.png",
    icon_size = 64,
    subgroup = "angels-chrome",
    order = "c",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-solid-chromate",
    icon = "__angelssmeltinggraphics__/graphics/icons/solid-chromate.png",
    icon_size = 32,
    subgroup = "angels-chrome",
    order = "d",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-solid-dichromate",
    icon = "__angelssmeltinggraphics__/graphics/icons/solid-dichromate.png",
    icon_size = 32,
    subgroup = "angels-chrome",
    order = "e",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-solid-chrome-oxide",
    icon = "__angelssmeltinggraphics__/graphics/icons/solid-chrome-oxide.png",
    icon_size = 32,
    subgroup = "angels-chrome",
    order = "f",
    stack_size = 200,
  },
  -- SMELTING RESULTS
  {
    type = "item",
    name = "angels-ingot-chrome",
    icon = "__angelssmeltinggraphics__/graphics/icons/ingot-chrome.png",
    icon_size = 64,
    subgroup = "angels-chrome",
    order = "g",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-powder-chrome",
    icon = "__angelssmeltinggraphics__/graphics/icons/powder-chrome.png",
    icon_size = 64,
    subgroup = "angels-chrome",
    order = "h",
    stack_size = 200,
  },
  -- CASTING INTERMEDIATE
  {
    type = "fluid",
    name = "angels-liquid-molten-chrome",
    icon = "__angelssmeltinggraphics__/graphics/icons/molten-chrome.png",
    icon_size = 64,
    subgroup = "angels-chrome-casting",
    order = "i",
    default_temperature = 1907,
    heat_capacity = "0kJ",
    base_color = { r = 200 / 255, g = 186 / 255, b = 245 / 255 },
    flow_color = { r = 200 / 255, g = 186 / 255, b = 245 / 255 },
    max_temperature = 1907,
    auto_barrel = false,
  },
  {
    type = "item",
    name = "angels-roll-chrome",
    icon = "__angelssmeltinggraphics__/graphics/icons/roll-chrome.png",
    icon_size = 64,
    subgroup = "angels-chrome-casting",
    order = "j",
    stack_size = 200,
  },
  -- CASTING RESULT
  {
    type = "item",
    name = "angels-plate-chrome",
    icon = "__angelssmeltinggraphics__/graphics/icons/plate-chrome.png",
    icon_size = 32,
    subgroup = "angels-chrome-casting",
    order = "k",
    stack_size = 200,
  },
})
