data:extend(
{
--ORE PROCESSING MACHINE
	{
    type = "recipe",
    name = "ore-processing-machine",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "ore-processing-machine",
    },
	{
    type = "recipe",
    name = "ore-processing-machine-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"ore-processing-machine", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "ore-processing-machine-2",
    },
	{
    type = "recipe",
    name = "ore-processing-machine-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"ore-processing-machine-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "ore-processing-machine-3",
    },	
	{
    type = "recipe",
    name = "ore-processing-machine-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"ore-processing-machine-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "ore-processing-machine-4",
    },
--PELLET PRESS
	{
    type = "recipe",
    name = "pellet-press",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "pellet-press",
    },
	{
    type = "recipe",
    name = "pellet-press-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"pellet-press", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "pellet-press-2",
    },
	{
    type = "recipe",
    name = "pellet-press-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"pellet-press-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "pellet-press-3",
    },	
	{
    type = "recipe",
    name = "pellet-press-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"pellet-press-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "pellet-press-4",
    },
--POWDER MIXER
	{
    type = "recipe",
    name = "powder-mixer",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "powder-mixer",
    },
	{
    type = "recipe",
    name = "powder-mixer-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"powder-mixer", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "powder-mixer-2",
    },
	{
    type = "recipe",
    name = "powder-mixer-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"powder-mixer-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "powder-mixer-3",
    },	
	{
    type = "recipe",
    name = "powder-mixer-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"powder-mixer-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "powder-mixer-4",
    },
 --BLAST FURNACE
    {
    type = "recipe",
    name = "blast-furnace",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result="blast-furnace",
    },
	{
    type = "recipe",
    name = "blast-furnace-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"blast-furnace", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result="blast-furnace-2",
    },
	{
    type = "recipe",
    name = "blast-furnace-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"blast-furnace-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 20},
	{"pipe", 5},
	},
    result="blast-furnace-3",
    },
	{
    type = "recipe",
    name = "blast-furnace-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"blast-furnace-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 20},
	{"pipe", 5},
	},
    result="blast-furnace-4",
    },
--CHEMICAL FURNACE
	{
    type = "recipe",
    name = "angels-chemical-furnace",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "angels-chemical-furnace",
    },
	{
    type = "recipe",
    name = "angels-chemical-furnace-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"angels-chemical-furnace", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "angels-chemical-furnace-2",
    },
	{
    type = "recipe",
    name = "angels-chemical-furnace-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"angels-chemical-furnace-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "angels-chemical-furnace-3",
    },	
	{
    type = "recipe",
    name = "angels-chemical-furnace-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"angels-chemical-furnace-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "angels-chemical-furnace-4",
    },
--ARC FURNACE
	{
    type = "recipe",
    name = "induction-furnace",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "induction-furnace",
    },
	{
    type = "recipe",
    name = "induction-furnace-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"induction-furnace", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "induction-furnace-2",
    },
	{
    type = "recipe",
    name = "induction-furnace-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"induction-furnace-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "induction-furnace-3",
    },	
	{
    type = "recipe",
    name = "induction-furnace-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"induction-furnace-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "induction-furnace-4",
    },
--CASTING MACHINE
	{
    type = "recipe",
    name = "casting-machine",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "casting-machine",
    },
	{
    type = "recipe",
    name = "casting-machine-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"casting-machine", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "casting-machine-2",
    },
	{
    type = "recipe",
    name = "casting-machine-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"casting-machine-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "casting-machine-3",
    },	
	{
    type = "recipe",
    name = "casting-machine-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"casting-machine-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "casting-machine-4",
    },
--SINTERING OVEN
	{
    type = "recipe",
    name = "sintering-oven",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "sintering-oven",
    },
	{
    type = "recipe",
    name = "sintering-oven-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"sintering-oven", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "sintering-oven-2",
    },
	{
    type = "recipe",
    name = "sintering-oven-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"sintering-oven-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "sintering-oven-3",
    },	
	{
    type = "recipe",
    name = "sintering-oven-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"sintering-oven-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "sintering-oven-4",
    },
--STRAND CASTING MACHINE
	{
    type = "recipe",
    name = "strand-casting-machine",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"iron-plate", 10},
	{"stone-brick", 30},
	{"basic-circuit-board", 5},
	},
    result= "strand-casting-machine",
    },
	{
    type = "recipe",
    name = "strand-casting-machine-2",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"strand-casting-machine", 1},
	{"steel-plate", 10},
	{"stone-brick", 30},
	{"electronic-circuit", 5},
	},
    result= "strand-casting-machine-2",
    },
	{
    type = "recipe",
    name = "strand-casting-machine-3",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"strand-casting-machine-2", 1},
	{"aluminium-plate", 10},
	{"stone-brick", 30},
	{"advanced-circuit", 5},
	},
    result= "strand-casting-machine-3",
    },	
	{
    type = "recipe",
    name = "strand-casting-machine-4",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"strand-casting-machine-3", 1},
	{"titanium-plate", 10},
	{"stone-brick", 30},
	{"processing-unit", 5},
	},
    result= "strand-casting-machine-4",
    },
--COOLING TOWER
	{
    type = "recipe",
    name = "cooling-tower",
    energy_required = 5,
	enabled = "false",
    ingredients ={
	{"steel-plate", 10},
	{"stone-brick", 10},
	{"electronic-circuit", 5},
	},
    result= "cooling-tower",
    },
  }
  )