angelsmods.functions.OV.remove_science_pack("automation", "angels-science-pack-red")
angelsmods.functions.OV.set_science_pack("automation", "angels-science-pack-grey")

angelsmods.functions.OV.remove_science_pack("logistics", "angels-science-pack-red")
angelsmods.functions.OV.set_science_pack("logistics", "angels-science-pack-grey")

angelsmods.functions.OV.remove_science_pack("advanced-material-processing", "angels-science-pack-red")
angelsmods.functions.OV.set_science_pack("advanced-material-processing", "angels-science-pack-green")

angelsmods.functions.OV.remove_science_pack("armor-making-2", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("armor-making-2", "angels-science-pack-red")

angelsmods.functions.OV.remove_science_pack("battery", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("battery", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("oil-processing", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("oil-processing", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("circuit-network", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("circuit-network", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("armor-making-3", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("armor-making-3", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("solar-energy", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("solar-energy", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("electric-engine", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("electric-engine", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("electric-energy-accumulators-1", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("electric-energy-accumulators-1", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("energy-shield-equipment", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("energy-shield-equipment", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("night-vision-equipment", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("night-vision-equipment", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("battery-equipment", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("battery-equipment", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("solar-panel-equipment", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("solar-panel-equipment", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("sulfur-processing", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("sulfur-processing", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("plastics", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("plastics", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("modules", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("modules", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("speed-module", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("speed-module", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("productivity-module", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("productivity-module", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("effectivity-module", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("effectivity-module", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("combat-robotics", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("combat-robotics", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("flamethrower-damage-1", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("flamethrower-damage-1", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("bullet-damage-3", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("bullet-damage-3", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("flying", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("flying", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("robotics", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("robotics", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("automated-construction", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("automated-construction", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("construction-robotics", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("construction-robotics", "angels-science-pack-orange")

angelsmods.functions.OV.remove_science_pack("electric-energy-distribution-2", "angels-science-pack-blue")
angelsmods.functions.OV.set_science_pack("electric-energy-distribution-2", "angels-science-pack-orange")
angelsmods.functions.OV.remove_science_pack("logistic-robotics", "angels-science-pack-green")
angelsmods.functions.OV.set_science_pack("logistic-robotics", "angels-science-pack-blue")

--BASIC
angelsmods.functions.OV.set_science_pack("logistics", "datacore-basic", 2)
angelsmods.functions.OV.set_science_pack("automation", "datacore-basic", 2)

--ENERGY
angelsmods.functions.OV.set_science_pack("solar-energy", "datacore-energy-1", 2)
angelsmods.functions.OV.set_science_pack("optics", "datacore-energy-1", 2)
angelsmods.functions.OV.set_science_pack("electric-energy-distribution-1", "datacore-energy-1", 2)
angelsmods.functions.OV.set_science_pack("electric-energy-distribution-2", "datacore-energy-1", 2)
angelsmods.functions.OV.set_science_pack("electric-energy-accumulators-1", "datacore-energy-1", 2)

--ENHANCEMENT
angelsmods.functions.OV.set_science_pack("effect-transmission", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("toolbelt", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("energy-shield-equipment", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("night-vision-equipment","datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("battery-equipment", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("solar-panel-equipment", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("energy-shield-mk2-equipment", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("battery-mk2-equipment", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("personal-laser-defense-equipment", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("discharge-defense-equipment", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("fusion-reactor-equipment", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("exoskeleton-equipment", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("personal-roboport-equipment", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("module", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("speed-module", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("speed-module-2", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("speed-module-3", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("productivity-module", "datacore-enhance-1", 2)
angelsmods.functions.OV.set_science_pack("productivity-module-2", "datacore-enhance-2", 2)
angelsmods.functions.OV.set_science_pack("productivity-module-3", "datacore-enhance-2", 2)

--LOGISTIC
angelsmods.functions.OV.set_science_pack("logistics-2", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("railway", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("flying", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("robotics", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("automated-rail-transportation", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("rail-signals", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("construction-robotics", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("automated-construction", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("logistics-3", "datacore-logistic-2", 2)
angelsmods.functions.OV.set_science_pack("logistic-robotics", "datacore-logistic-2", 2)
angelsmods.functions.OV.set_science_pack("logistic-system", "datacore-logistic-2", 2)
angelsmods.functions.OV.set_science_pack("fluid-handling", "datacore-logistic-1", 2)

angelsmods.functions.OV.set_science_pack("worker-robots-speed-1", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("worker-robots-speed-2", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("worker-robots-speed-3", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("worker-robots-speed-4", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("worker-robots-speed-5", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("worker-robots-storage-1", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("worker-robots-storage-2", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("worker-robots-storage-3", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-slots-1", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-slots-2", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-slots-3", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-slots-4", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-slots-5", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-slots-6", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-trash-slots-1", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("character-logistic-trash-slots-2", "datacore-logistic-1", 2)
angelsmods.functions.OV.set_science_pack("auto-character-logistic-trash-slots", "datacore-logistic-1", 2)

--PROCESSING
angelsmods.functions.OV.set_science_pack("steel-processing", "datacore-processing-1", 2)
--angelsmods.functions.OV.add_prereq("steel-processing", "tech-red-labs")
angelsmods.functions.OV.set_science_pack("electronics", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("automation-2", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("advanced-material-processing", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("advanced-material-processing-2", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("concrete", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("circuit-network", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("advanced-electronics", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("advanced-electronics-2", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("oil-processing", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("engine", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("landfill", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("electric-engine", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("sulfur-processing", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("battery", "datacore-processing-1", 2)
angelsmods.functions.OV.set_science_pack("automation-3", "datacore-processing-2", 2)
angelsmods.functions.OV.set_science_pack("advanced-oil-processing", "datacore-processing-2", 2)

--WAR
angelsmods.functions.OV.set_science_pack("turrets", "datacore-war-1", 2)
angelsmods.functions.OV.add_prereq("turrets", "tech-red-labs")
angelsmods.functions.OV.set_science_pack("military", "datacore-war-1", 2)
--angelsmods.functions.OV.add_prereq("military", "tech-red-labs")
angelsmods.functions.OV.set_science_pack("armor-making", "datacore-war-1", 2)
--angelsmods.functions.OV.add_prereq("armor-making", "tech-red-labs")
angelsmods.functions.OV.set_science_pack("armor-making-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("armor-making-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("stone-walls", "datacore-war-1", 2)
--angelsmods.functions.OV.add_prereq("stone-walls", "tech-red-labs")
angelsmods.functions.OV.set_science_pack("gates", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("explosives", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flammables", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("land-mine", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flame-thrower", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("automobilism", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("tanks", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turrets", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocketry", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("military-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("military-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("military-4", "datacore-war-2", 2)
angelsmods.functions.OV.set_science_pack("power-armor", "datacore-war-2", 2)
angelsmods.functions.OV.set_science_pack("power-armor-2", "datacore-war-2", 2)
angelsmods.functions.OV.set_science_pack("explosive-rocketry", "datacore-war-2", 2)
angelsmods.functions.OV.set_science_pack("cluster-grenade", "datacore-war-2", 2)
angelsmods.functions.OV.set_science_pack("combat-robotics", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("combat-robotics-2", "datacore-war-2", 2)
angelsmods.functions.OV.set_science_pack("combat-robotics-3", "datacore-war-2", 2)

angelsmods.functions.OV.set_science_pack("shotgun-shell-damage-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-damage-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-damage-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-damage-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-damage-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-damage-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-speed-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-speed-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-speed-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-speed-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-speed-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("shotgun-shell-speed-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-damage-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-damage-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-damage-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-damage-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-damage-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-damage-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-speed-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-speed-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-speed-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-speed-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-speed-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("laser-turret-speed-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("gun-turret-damage-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("gun-turret-damage-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("gun-turret-damage-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("gun-turret-damage-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("gun-turret-damage-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("gun-turret-damage-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flamethrower-damage-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flamethrower-damage-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flamethrower-damage-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flamethrower-damage-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flamethrower-damage-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("flamethrower-damage-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-damage-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-damage-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-damage-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-damage-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-damage-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-damage-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-speed-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-speed-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-speed-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-speed-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-speed-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("bullet-speed-6", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("combat-robot-damage-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("combat-robot-damage-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("combat-robot-damage-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("combat-robot-damage-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("combat-robot-damage-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-damage-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-damage-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-damage-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-damage-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-damage-5", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-speed-1", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-speed-2", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-speed-3", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-speed-4", "datacore-war-1", 2)
angelsmods.functions.OV.set_science_pack("rocket-speed-5", "datacore-war-1", 2)
