circuit_connector_definitions["angels-clarifier"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  6, main_offset = util.by_pixel( 67,  63), shadow_offset = util.by_pixel( 67,  63), show_shadow = true },
  { variation =  6, main_offset = util.by_pixel( 67,  63), shadow_offset = util.by_pixel( 67,  63), show_shadow = true },
  { variation =  6, main_offset = util.by_pixel( 67,  63), shadow_offset = util.by_pixel( 67,  63), show_shadow = true },
  { variation =  6, main_offset = util.by_pixel( 67,  63), shadow_offset = util.by_pixel( 67,  63), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-clarifier",
    icons = {
      {
        icon = "__angelsrefininggraphics__/graphics/icons/clarifier.png",
        icon_size = 64,
        scale = 0.5,
      },
    },
    subgroup = "angels-water-treatment-building",
    order = "c[clarifier]",
    place_result = "angels-clarifier",
    stack_size = 10,
  },
  {
    type = "furnace",
    name = "angels-clarifier",
    icons = {
      {
        icon = "__angelsrefininggraphics__/graphics/icons/clarifier.png",
        icon_size = 64,
        scale = 0.5,
      },
    },
    flags = { "placeable-neutral", "placeable-player", "player-creation" },
    minable = { mining_time = 1, result = "angels-clarifier" },
    max_health = 100,
    fast_replaceable_group = "angels-clarifier",
    corpse = "small-remnants",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    crafting_categories = { "angels-water-void" },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "pollution" },
    result_inventory_size = 0,
    crafting_speed = 2,
    source_inventory_size = 0,
    show_recipe_icon = false,
    resistances = {
      {
        type = "fire",
        percent = 80,
      },
      {
        type = "explosion",
        percent = 30,
      },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 2 }, direction = defines.direction.south } },
      },
    },
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 0.6 },
    },
    energy_usage = "30kW",
    circuit_connector = circuit_connector_definitions["angels-clarifier"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-base.png",
        priority = "extra-high",
        frame_count = 64,
        line_length = 8,
        animation_speed = 0.5,
        width = 374,
        height = 365,
        shift = util.by_pixel(10, 0),
        scale = 0.5,
      },
      working_visualisations = {
        {
          always_draw = true,
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-shadow.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            x = 0,
            y = 0,
            frame_count = 1,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
            draw_as_shadow = true,
          },
          east_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-shadow.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            x = 374,
            y = 0,
            frame_count = 1,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
            draw_as_shadow = true,
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-shadow.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            x = 748,
            y = 0,
            frame_count = 1,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
            draw_as_shadow = true,
          },
          west_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-shadow.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            x = 1122,
            y = 0,
            frame_count = 1,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
            draw_as_shadow = true,
          },
        },
        {
          always_draw = true,
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-pipe-connections.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            x = 0,
            y = 0,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-pipe-connections.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            x = 748,
            y = 0,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
          },
        },
        {
          always_draw = true,
          render_layer = "higher-object-under",
          east_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-pipe-connections.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            frame_count = 18,
            frame_sequence = {
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
              2,
            },
            animation_speed = 0.5,
            line_length = 6,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
          },
          west_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-pipe-connections.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            frame_count = 18,
            frame_sequence = {
              5,
              6,
              7,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              4,
              8,
              9.5,
              10,
              11,
            },
            line_length = 6,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
            animation_speed = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "primary",
          animation = {
            animation_speed = 0.5,
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/clarifier-recipe-mask.png",
            priority = "extra-high",
            width = 374,
            height = 365,
            frame_count = 64,
            line_length = 8,
            scale = 0.5,
            shift = util.by_pixel(10, 0),
          },
        },
        {
          always_draw = true,
          south_animation = {
            draw_as_shadow = true,
            filename = "__angelsrefininggraphics__/graphics/entity/clarifier/vertical-pipe-shadow-patch.png",
            priority = "high",
            width = 128,
            height = 128,
            repeat_count = 36,
            scale = 0.5,
            shift = { 0, -2 },
          },
        },
      },
    },
    impact_category = "metal",
    repair_sound = { filename = "__base__/sound/manual-repair-simple.ogg" },
    open_sound = { filename = "__base__/sound/machine-open.ogg", volume = 0.85 },
    close_sound = { filename = "__base__/sound/machine-close.ogg", volume = 0.75 },
  },
})
