data:extend({
  {
    type = "item",
    name = "angels-electro-whinning-cell",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/electro-whinning-cell-ico.png",
        icon_size = 32,
      },
    }, 1, angelsmods.refining.number_tint),
    subgroup = "angels-ore-whinning",
    order = "d",
    place_result = "angels-electro-whinning-cell",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-electro-whinning-cell",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/electro-whinning-cell-ico.png",
        icon_size = 32,
      },
    }, 1, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-electro-whinning-cell" },
    fast_replaceable_group = "angels-electro-whinning-cell",
    next_upgrade = "angels-electro-whinning-cell-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-refining-t3-5" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.2 },
    },
    energy_usage = "200kW",
    graphics_set = {
      animation = {
        filename = "__angelsrefininggraphics__/graphics/entity/electro-whinning-cell/electro-whinning-cell.png",
        priority = "extra-high",
        width = 224,
        height = 224,
        frame_count = 36,
        line_length = 6,
        shift = { 0, 0 },
        animation_speed = 0.5,
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-leaching-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 1, 2 }, direction = defines.direction.south } },
      },
      {
        production_type = "input",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { -1, 2 }, direction = defines.direction.south } },
      },
      {
        production_type = "output",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { 1, -2 }, direction = defines.direction.north },
        },
      },
      {
        production_type = "output",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { -1, -2 }, direction = defines.direction.north },
        },
      },
    },
  },
  {
    type = "item",
    name = "angels-electro-whinning-cell-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/electro-whinning-cell-ico.png",
        icon_size = 32,
      },
    }, 2, angelsmods.refining.number_tint),
    subgroup = "angels-ore-whinning",
    order = "e",
    place_result = "angels-electro-whinning-cell-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-electro-whinning-cell-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/electro-whinning-cell-ico.png",
        icon_size = 32,
      },
    }, 2, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-electro-whinning-cell-2" },
    fast_replaceable_group = "angels-electro-whinning-cell",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-refining-t3-5" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "250kW",
    graphics_set = {
      animation = {
        filename = "__angelsrefininggraphics__/graphics/entity/electro-whinning-cell/electro-whinning-cell.png",
        priority = "extra-high",
        width = 224,
        height = 224,
        frame_count = 36,
        line_length = 6,
        shift = { 0, 0 },
        animation_speed = 0.5,
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-leaching-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 1, 2 }, direction = defines.direction.south } },
      },
      {
        production_type = "input",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { -1, 2 }, direction = defines.direction.south } },
      },
      {
        production_type = "output",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { 1, -2 }, direction = defines.direction.north },
        },
      },
      {
        production_type = "output",
        pipe_picture = angelsmods.refining.floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { -1, -2 }, direction = defines.direction.north },
        },
      },
    },
  },
})
