local function floatationpipepictures()
  return {
    north = {
      filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/pipe-north.png",
      priority = "extra-high",
      width = 48,
      height = 48,
      shift = { 0.01, 0.95 },
    },
    east = {
      filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/pipe-east.png",
      priority = "extra-high",
      width = 40,
      height = 45,
      shift = { -0.71875, 0.1 },
    },
    south = {
      filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/pipe-south.png",
      priority = "extra-high",
      width = 34,
      height = 39,
      shift = { 0, -0.75 },
    },
    west = {
      filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/pipe-west.png",
      priority = "extra-high",
      width = 40,
      height = 45,
      shift = { 0.78125, 0.01 },
    },
  }
end

circuit_connector_definitions["angels-ore-floatation-cell"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation = 27, main_offset = util.by_pixel(-25.375,  10.875), shadow_offset = util.by_pixel(-25.375,  10.875), show_shadow = true },
  { variation = 27, main_offset = util.by_pixel(-25.375,  10.875), shadow_offset = util.by_pixel(-25.375,  10.875), show_shadow = true },
  { variation = 27, main_offset = util.by_pixel(-25.375,  10.875), shadow_offset = util.by_pixel(-25.375,  10.875), show_shadow = true },
  { variation = 27, main_offset = util.by_pixel(-25.375,  10.875), shadow_offset = util.by_pixel(-25.375,  10.875), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-ore-floatation-cell",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-floatation-cell.png",
        icon_size = 64,
      },
    }, 1, angelsmods.refining.number_tint),
    subgroup = "angels-ore-floatation",
    order = "a[ore-floatation-cell]",
    place_result = "angels-ore-floatation-cell",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-floatation-cell",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-floatation-cell.png",
        icon_size = 64,
      },
    }, 1, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-ore-floatation-cell" },
    fast_replaceable_group = "angels-ore-floatation-cell",
    next_upgrade = "angels-ore-floatation-cell-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-refining-t2" },
    crafting_speed = 0.75,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.2 },
    },
    energy_usage = "200kW",
    circuit_connector = circuit_connector_definitions["angels-ore-floatation-cell"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 3,
    graphics_set = {
      animation = {
        north = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        east = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              x = 333,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              x = 390,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        south = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        west = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              x = 333,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              x = 390,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
      },
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-idle.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 32,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-base.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-water-tintable.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "secondary",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-froth-tintable.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          render_layer = "higher-object-under",
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          east_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            x = 333,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          west_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            x = 333,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/vertical-pipe-shadow-patch.png",
            priority = "high",
            width = 128,
            height = 128,
            repeat_count = 36,
            draw_as_shadow = true,
            shift = { 0, -2 },
            scale = 0.5,
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/vertical-pipe-shadow-patch.png",
            priority = "high",
            width = 128,
            height = 128,
            repeat_count = 36,
            draw_as_shadow = true,
            shift = { 0, -2 },
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-floatation-cell.ogg", volume = 1 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_picture = floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 2 }, direction = defines.direction.south } },
      },
      {
        production_type = "output",
        pipe_picture = floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { 0, -2 }, direction = defines.direction.north },
        },
      },
    },
  },
  {
    type = "item",
    name = "angels-ore-floatation-cell-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-floatation-cell.png",
        icon_size = 64,
      },
    }, 2, angelsmods.refining.number_tint),
    subgroup = "angels-ore-floatation",
    order = "b[ore-floatation-cell-2]",
    place_result = "angels-ore-floatation-cell-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-floatation-cell-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-floatation-cell.png",
        icon_size = 64,
      },
    }, 2, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-ore-floatation-cell-2" },
    fast_replaceable_group = "angels-ore-floatation-cell",
    next_upgrade = "angels-ore-floatation-cell-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-refining-t2" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "250kW",
    circuit_connector = circuit_connector_definitions["angels-ore-floatation-cell"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 3,
    graphics_set = {
      animation = {
        north = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        east = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              x = 333,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              x = 390,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        south = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        west = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              x = 333,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              x = 390,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
      },
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-idle.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 32,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-base.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-water-tintable.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "secondary",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-froth-tintable.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          render_layer = "higher-object-under",
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          east_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            x = 333,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          west_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            x = 333,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/vertical-pipe-shadow-patch.png",
            priority = "high",
            width = 128,
            height = 128,
            repeat_count = 36,
            draw_as_shadow = true,
            shift = { 0, -2 },
            scale = 0.5,
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/vertical-pipe-shadow-patch.png",
            priority = "high",
            width = 128,
            height = 128,
            repeat_count = 36,
            draw_as_shadow = true,
            shift = { 0, -2 },
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-floatation-cell.ogg", volume = 1 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_picture = floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 2 }, direction = defines.direction.south } },
      },
      {
        production_type = "output",
        pipe_picture = floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { 0, -2 }, direction = defines.direction.north },
        },
      },
    },
  },
  {
    type = "item",
    name = "angels-ore-floatation-cell-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-floatation-cell.png",
        icon_size = 64,
      },
    }, 3, angelsmods.refining.number_tint),
    subgroup = "angels-ore-floatation",
    order = "c[ore-floatation-cell-3]",
    place_result = "angels-ore-floatation-cell-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-floatation-cell-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-floatation-cell.png",
        icon_size = 64,
      },
    }, 3, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-ore-floatation-cell-3" },
    fast_replaceable_group = "angels-ore-floatation-cell",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-refining-t2" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "300kW",
    circuit_connector = circuit_connector_definitions["angels-ore-floatation-cell"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 3,
    graphics_set = {
      animation = {
        north = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        east = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              x = 333,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              x = 390,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        south = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
        west = {
          layers = {
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-base.png",
              priority = "extra-high",
              width = 333,
              height = 363,
              x = 333,
              shift = util.by_pixel_hr(-1, -1),
              scale = 0.5,
            },
            {
              filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-shadow.png",
              priority = "extra-high",
              width = 390,
              height = 326,
              x = 390,
              shift = util.by_pixel_hr(29, 18),
              draw_as_shadow = true,
              scale = 0.5,
            },
          },
        },
      },
      working_visualisations = {
        {
          always_draw = true,
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-idle.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 32,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-base.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-water-tintable.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "secondary",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-animation-froth-tintable.png",
            priority = "extra-high",
            width = 166,
            height = 117,
            frame_count = 64,
            line_length = 8,
            shift = util.by_pixel_hr(62, 5),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          render_layer = "higher-object-under",
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          east_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            x = 333,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
          west_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/ore-flotation-cell-pipe-cover-overlays.png",
            priority = "extra-high",
            width = 333,
            height = 363,
            x = 333,
            shift = util.by_pixel_hr(-1, -1),
            scale = 0.5,
          },
        },
        {
          always_draw = true,
          north_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/vertical-pipe-shadow-patch.png",
            priority = "high",
            width = 128,
            height = 128,
            repeat_count = 36,
            draw_as_shadow = true,
            shift = { 0, -2 },
            scale = 0.5,
          },
          south_animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-floatation-cell/vertical-pipe-shadow-patch.png",
            priority = "high",
            width = 128,
            height = 128,
            repeat_count = 36,
            draw_as_shadow = true,
            shift = { 0, -2 },
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-floatation-cell.ogg", volume = 1 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_picture = floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 2 }, direction = defines.direction.south } },
      },
      {
        production_type = "output",
        pipe_picture = floatationpipepictures(),
        pipe_covers = pipecoverspictures(),
        volume = 100,
        pipe_connections = {
          { flow_direction = "output", position = { 0, -2 }, direction = defines.direction.north },
        },
      },
    },
  },
})
