circuit_connector_definitions["angels-ore-refinery"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  5, main_offset = util.by_pixel( 31.25,  49.875), shadow_offset = util.by_pixel( 31.25,  49.875), show_shadow = true },
  { variation =  5, main_offset = util.by_pixel( 31.25,  49.875), shadow_offset = util.by_pixel( 31.25,  49.875), show_shadow = true },
  { variation =  5, main_offset = util.by_pixel( 31.25,  49.875), shadow_offset = util.by_pixel( 31.25,  49.875), show_shadow = true },
  { variation =  5, main_offset = util.by_pixel( 31.25,  49.875), shadow_offset = util.by_pixel( 31.25,  49.875), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-ore-refinery",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-refinery.png",
        icon_size = 64,
      },
    }, 1, angelsmods.refining.number_tint),
    subgroup = "angels-ore-refining",
    order = "a[ore-refinery]",
    place_result = "angels-ore-refinery",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-refinery",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-refinery.png",
        icon_size = 64,
      },
    }, 1, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-ore-refinery" },
    fast_replaceable_group = "angels-ore-refinery",
    next_upgrade = "angels-ore-refinery-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_slots = 1,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-refining-t4" },
    crafting_speed = 0.75,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.2 },
    },
    energy_usage = "300kW",
    circuit_connector = circuit_connector_definitions["angels-ore-refinery"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/ore-refinery-base.png",
            priority = "extra-high",
            width = 440,
            height = 509,
            shift = util.by_pixel(0.5, -16),
            scale = 0.5,
          },
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/ore-refinery-shadow.png",
            priority = "extra-high",
            width = 522,
            height = 340,
            shift = util.by_pixel(21.5, 29),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/ore-refinery-lights.png",
            priority = "extra-high",
            width = 440,
            height = 509,
            shift = util.by_pixel(0.5, -16),
            draw_as_glow = true,
            blend_mode = "additive-soft",
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          constant_speed = true,
          apply_recipe_tint = "primary",
          north_position = util.by_pixel_hr(-63, -255),
          east_position = util.by_pixel_hr(-63, -255),
          south_position = util.by_pixel_hr(-63, -255),
          west_position = util.by_pixel_hr(-63, -255),
          render_layer = "wires",
          animation = {
            filename = "__base__/graphics/entity/chemical-plant/chemical-plant-smoke-outer.png",
            frame_count = 47,
            line_length = 16,
            width = 90,
            height = 188,
            animation_speed = 0.5,
            shift = util.by_pixel(-2, -40),
            tint = util.color("808080"),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          constant_speed = true,
          --apply_recipe_tint = "primary",
          north_position = util.by_pixel_hr(-63, -255),
          east_position = util.by_pixel_hr(-63, -255),
          south_position = util.by_pixel_hr(-63, -255),
          west_position = util.by_pixel_hr(-63, -255),
          render_layer = "wires",
          animation = {
            filename = "__base__/graphics/entity/chemical-plant/chemical-plant-smoke-inner.png",
            frame_count = 47,
            line_length = 16,
            width = 40,
            height = 84,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -14),
            tint = util.color("b3b3b3"),
            scale = 0.5 * 1.2,
          },
        },
        {
          always_draw = true,
          apply_recipe_tint = "primary",
          render_layer = "wires",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/stack-patch-overlay.png",
            priority = "extra-high",
            width = 46,
            height = 25,
            shift = util.by_pixel_hr(-61, -246),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-refinery.ogg", volume = 0.7 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-refinery-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-refinery.png",
        icon_size = 64,
      },
    }, 2, angelsmods.refining.number_tint),
    subgroup = "angels-ore-refining",
    order = "b[ore-refinery-2]",
    place_result = "angels-ore-refinery-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-refinery-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-refinery.png",
        icon_size = 64,
      },
    }, 2, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    collision_mask = angelsmods.functions.set_building_collision_mask("asm", { "elevated_rail" }),
    minable = { mining_time = 1, result = "angels-ore-refinery-2" },
    fast_replaceable_group = "angels-ore-refinery",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-refining-t4" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "350kW",
    circuit_connector = circuit_connector_definitions["angels-ore-refinery"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/ore-refinery-base.png",
            priority = "extra-high",
            width = 440,
            height = 509,
            shift = util.by_pixel(0.5, -16),
            scale = 0.5,
          },
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/ore-refinery-shadow.png",
            priority = "extra-high",
            width = 522,
            height = 340,
            shift = util.by_pixel(21.5, 29),
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
      working_visualisations = {
        {
          fadeout = true,
          effect = "uranium-glow",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/ore-refinery-lights.png",
            priority = "extra-high",
            width = 440,
            height = 509,
            shift = util.by_pixel(0.5, -16),
            draw_as_glow = true,
            blend_mode = "additive-soft",
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          constant_speed = true,
          apply_recipe_tint = "primary",
          north_position = util.by_pixel_hr(-63, -255),
          east_position = util.by_pixel_hr(-63, -255),
          south_position = util.by_pixel_hr(-63, -255),
          west_position = util.by_pixel_hr(-63, -255),
          render_layer = "wires",
          animation = {
            filename = "__base__/graphics/entity/chemical-plant/chemical-plant-smoke-outer.png",
            frame_count = 47,
            line_length = 16,
            width = 90,
            height = 188,
            animation_speed = 0.5,
            shift = util.by_pixel(-2, -40),
            tint = util.color("808080"),
            scale = 0.5,
          },
        },
        {
          fadeout = true,
          constant_speed = true,
          --apply_recipe_tint = "primary",
          north_position = util.by_pixel_hr(-63, -255),
          east_position = util.by_pixel_hr(-63, -255),
          south_position = util.by_pixel_hr(-63, -255),
          west_position = util.by_pixel_hr(-63, -255),
          render_layer = "wires",
          animation = {
            filename = "__base__/graphics/entity/chemical-plant/chemical-plant-smoke-inner.png",
            frame_count = 47,
            line_length = 16,
            width = 40,
            height = 84,
            animation_speed = 0.5,
            shift = util.by_pixel(0, -14),
            tint = util.color("b3b3b3"),
            scale = 0.5 * 1.2,
          },
        },
        {
          always_draw = true,
          render_layer = "wires",
          animation = {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-refinery/stack-patch-overlay.png",
            priority = "extra-high",
            width = 46,
            height = 25,
            shift = util.by_pixel_hr(-61, -246),
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-refinery.ogg", volume = 0.7 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
