circuit_connector_definitions["angels-ore-sorting-facility"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  4, main_offset = util.by_pixel( 41.375, -13.125), shadow_offset = util.by_pixel( 41.375, -13.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 41.375, -13.125), shadow_offset = util.by_pixel( 41.375, -13.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 41.375, -13.125), shadow_offset = util.by_pixel( 41.375, -13.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 41.375, -13.125), shadow_offset = util.by_pixel( 41.375, -13.125), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-ore-sorting-facility",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 1, angelsmods.refining.number_tint),
    subgroup = "angels-ore-sorter",
    order = "a[ore-sorting-facility]",
    place_result = "angels-ore-sorting-facility",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-sorting-facility",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 1, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-sorting-facility" },
    fast_replaceable_group = "angels-ore-sorting-facility",
    next_upgrade = "angels-ore-sorting-facility-2",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-sorting" },
    crafting_speed = 0.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 1.8 },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-ore-sorting-facility"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 2,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-base.png",
            priority = "extra-high",
            width = 449,
            height = 458,
            frame_count = 40,
            line_length = 10,
            shift = util.by_pixel(0, -2.5),
            animation_speed = 0.5,
            scale = 0.5,
          },
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-shadow.png",
            priority = "extra-high",
            width = 528,
            height = 356,
            repeat_count = 40,
            shift = util.by_pixel(21.5, 24.5),
            animation_speed = 0.5,
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-sorting-facility.ogg", volume = 0.5 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-sorting-facility-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 2, angelsmods.refining.number_tint),
    subgroup = "angels-ore-sorter",
    order = "b[ore-sorting-facility-2]",
    place_result = "angels-ore-sorting-facility-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-sorting-facility-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 2, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-sorting-facility-2" },
    fast_replaceable_group = "angels-ore-sorting-facility",
    next_upgrade = "angels-ore-sorting-facility-3",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-sorting", "angels-ore-sorting-2" },
    crafting_speed = 0.75,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 2.4 },
    },
    energy_usage = "200kW",
    circuit_connector = circuit_connector_definitions["angels-ore-sorting-facility"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-base.png",
            priority = "extra-high",
            width = 449,
            height = 458,
            frame_count = 40,
            line_length = 10,
            shift = util.by_pixel(0, -2.5),
            animation_speed = 0.5,
            scale = 0.5,
          },
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-shadow.png",
            priority = "extra-high",
            width = 528,
            height = 356,
            repeat_count = 40,
            shift = util.by_pixel(21.5, 24.5),
            animation_speed = 0.5,
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-sorting-facility.ogg", volume = 0.5 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-sorting-facility-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 3, angelsmods.refining.number_tint),
    subgroup = "angels-ore-sorter",
    order = "c[ore-sorting-facility-3]",
    place_result = "angels-ore-sorting-facility-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-sorting-facility-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 3, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-sorting-facility-3" },
    fast_replaceable_group = "angels-ore-sorting-facility",
    next_upgrade = "angels-ore-sorting-facility-4",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-sorting", "angels-ore-sorting-2", "angels-ore-sorting-3" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3 },
    },
    energy_usage = "250kW",
    circuit_connector = circuit_connector_definitions["angels-ore-sorting-facility"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-base.png",
            priority = "extra-high",
            width = 449,
            height = 458,
            frame_count = 40,
            line_length = 10,
            shift = util.by_pixel(0, -2.5),
            animation_speed = 0.5,
            scale = 0.5,
          },
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-shadow.png",
            priority = "extra-high",
            width = 528,
            height = 356,
            repeat_count = 40,
            shift = util.by_pixel(21.5, 24.5),
            animation_speed = 0.5,
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-sorting-facility.ogg", volume = 0.5 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-sorting-facility-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 4, angelsmods.refining.number_tint),
    subgroup = "angels-ore-sorter",
    order = "d[ore-sorting-facility-4]",
    place_result = "angels-ore-sorting-facility-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-sorting-facility-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 4, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-sorting-facility-4" },
    fast_replaceable_group = "angels-ore-sorting-facility",
    next_upgrade = "angels-ore-sorting-facility-5",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-sorting", "angels-ore-sorting-2", "angels-ore-sorting-3", "angels-ore-sorting-4" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 3.6 },
    },
    energy_usage = "300kW",
    circuit_connector = circuit_connector_definitions["angels-ore-sorting-facility"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 6,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-base.png",
            priority = "extra-high",
            width = 449,
            height = 458,
            frame_count = 40,
            line_length = 10,
            shift = util.by_pixel(0, -2.5),
            animation_speed = 0.5,
            scale = 0.5,
          },
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-shadow.png",
            priority = "extra-high",
            width = 528,
            height = 356,
            repeat_count = 40,
            shift = util.by_pixel(21.5, 24.5),
            animation_speed = 0.5,
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-sorting-facility.ogg", volume = 0.5 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
  {
    type = "item",
    name = "angels-ore-sorting-facility-5",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 5, angelsmods.refining.number_tint),
    subgroup = "angels-ore-sorter",
    order = "e[ore-sorting-facility-5]",
    place_result = "angels-ore-sorting-facility-5",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-ore-sorting-facility-5",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsrefininggraphics__/graphics/icons/ore-sorting-facility.png",
        icon_size = 64,
      },
    }, 5, angelsmods.refining.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-ore-sorting-facility-5" },
    fast_replaceable_group = "angels-ore-sorting-facility",
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    module_slots = 3,
    allowed_effects = { "consumption", "speed", "pollution", "productivity" },
    crafting_categories = { "angels-ore-sorting", "angels-ore-sorting-2", "angels-ore-sorting-3", "angels-ore-sorting-4", "angels-ore-sorting-5" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 4.2 },
    },
    energy_usage = "350kW",
    circuit_connector = circuit_connector_definitions["angels-ore-sorting-facility"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-base.png",
            priority = "extra-high",
            width = 449,
            height = 458,
            frame_count = 40,
            line_length = 10,
            shift = util.by_pixel(0, -2.5),
            animation_speed = 0.5,
            scale = 0.5,
          },
          {
            filename = "__angelsrefininggraphics__/graphics/entity/ore-sorting-facility/ore-sorting-facility-shadow.png",
            priority = "extra-high",
            width = 528,
            height = 356,
            repeat_count = 40,
            shift = util.by_pixel(21.5, 24.5),
            animation_speed = 0.5,
            draw_as_shadow = true,
            scale = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__angelsrefininggraphics__/sound/ore-sorting-facility.ogg", volume = 0.5 },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
