local sounds = require("__base__.prototypes.entity.sounds")
local hit_effects = require("__base__.prototypes.entity.hit-effects")

data:extend({
  {
    type = "item",
    name = "angels-sea-pump",
    icon = "__angelsrefininggraphics__/graphics/icons/sea-pump-ico.png",
    icon_size = 32,
    subgroup = "angels-washing-building",
    order = "f",
    place_result = "angels-sea-pump-placeable",
    stack_size = 10,
  },
  {
    type = "offshore-pump",
    name = "angels-sea-pump-placeable",
    localised_name = { "entity-name.angels-sea-pump" },
    localised_description = { "entity-description.angels-sea-pump" },
    icon = "__angelsrefininggraphics__/graphics/icons/sea-pump-ico.png",
    icon_size = 32,
    flags = { "placeable-neutral", "player-creation", "filter-directions" },
    hidden_in_factoriopedia = true,
    collision_mask = { layers = { object = true, train = true, is_object = true, is_lower_object = true } },
    tile_buildability_rules = {
      {
        area = { { -1.4, -1.4 }, { 1.4, 0.4 } },
        required_tiles = { layers = { ground_tile = true } },
        colliding_tiles = { layers = { water_tile = true } },
        remove_on_collision = true,
      },
      {
        area = { { -2, -3 }, { 2, -2 } },
        required_tiles = { layers = { water_tile = true } },
        colliding_tiles = { layers = {} },
      },
    },
    minable = { mining_time = 0.1, result = "angels-sea-pump" },
    max_health = 200,
    corpse = "small-remnants",
    fluid_source_offset = { 0, -1 },
    resistances = {
      {
        type = "fire",
        percent = 70,
      },
      {
        type = "impact",
        percent = 30,
      },
    },
    collision_box = { { -1.6, -2.05 }, { 1.6, 0.3 } },
    selection_box = { { -1.6, -2.49 }, { 1.6, 0.49 } },
    damaged_trigger_effect = hit_effects.entity(),
    fluid_box = {
      volume = 100000,
      pipe_covers = pipecoverspictures(),
      production_type = "output",
      filter = "water",
      pipe_connections = {
        {
          position = { 0, 0 },
          direction = defines.direction.south,
          flow_direction = "output",
        },
      },
    },
    energy_source = {
      type = "void",
    },
    energy_usage = "250kW",
    pumping_speed = 1500 / 60,
    tile_width = 3,
    tile_height = 3,
    impact_category = "metal",
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    working_sound = {
      sound = {
        filename = "__base__/sound/offshore-pump.ogg",
        volume = 0.5,
        modifiers = volume_multiplier("tips-and-tricks", 1.1),
        audible_distance_modifier = 0.7,
      },
      match_volume_to_activity = true,
      max_sounds_per_prototype = 3,
      fade_in_ticks = 4,
      fade_out_ticks = 20,
    },
    perceived_performance = { minimum = 0.5 },
    always_draw_fluid = true,
    graphics_set = {
      base_pictures = {
        north = {
          filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
          priority = "high",
          shift = { 0, -1 },
          width = 160,
          height = 160,
        },
        east = {
          filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
          priority = "high",
          shift = { 1, 0 },
          x = 160,
          width = 160,
          height = 160,
        },
        south = {
          filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
          priority = "high",
          shift = { 0, 1 },
          x = 320,
          width = 160,
          height = 160,
        },
        west = {
          filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
          priority = "high",
          shift = { -1, 0 },
          x = 480,
          width = 160,
          height = 160,
        },
      },
    },
    placeable_position_visualization = {
      filename = "__core__/graphics/cursor-boxes-32x32.png",
      priority = "extra-high-no-scale",
      width = 64,
      height = 64,
      scale = 0.5,
      x = 3 * 64,
    },
    circuit_connector = circuit_connector_definitions["offshore-pump"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
  },
  {
    type = "resource-category",
    name = "angels-sea-pump",
  },
  {
    type = "resource",
    name = "angels-sea-pump-resource",
    localised_name = { "fluid-name.water" },
    icon = "__base__/graphics/icons/fluid/water.png",
    icon_size = 64,
    flags = { "placeable-neutral", "not-on-map" },
    hidden = true,
    hidden_in_factoriopedia = true,
    selectable_in_game = false,
    category = "angels-sea-pump",
    subgroup = "raw-resource",
    order = "a-b-a",
    infinite = true,
    highlight = false,
    minimum = 100000,
    normal = 100000,
    infinite_depletion_amount = 1,
    resource_patch_search_radius = 1,
    minable = {
      mining_time = 1, -- how long it takes to 'tick'
      results = {
        {
          type = "fluid",
          name = "water",
          amount_min = 1500, -- amount of water it produces each 'tick'
          amount_max = 1500,
          probability = 1,
        },
      },
    },
    walking_sound = sounds.oil,
    collision_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    selection_box = { { -0.5, -0.5 }, { 0.5, 0.5 } },
    stage_counts = { 0 },
    stages = {
      sheet = {
        filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/empty.png",
        priority = "extra-high",
        width = 1,
        height = 1,
        frame_count = 1,
        variation_count = 1,
        shift = util.by_pixel(0, 0),
        scale = 1,
      },
    },
    map_color = { 0, 0, 0, 0 },
  },
  {
    type = "mining-drill",
    name = "angels-sea-pump",
    localised_name = { "entity-name.angels-sea-pump" },
    localised_description = { "entity-description.angels-sea-pump" },
    icon = "__angelsrefininggraphics__/graphics/icons/sea-pump-ico.png",
    icon_size = 32,
    flags = { "placeable-neutral", "player-creation", "filter-directions" },
    collision_mask = { layers = { object = true, train = true, is_object = true, is_lower_object = true } },
    tile_buildability_rules = {
      {
        area = { { -1.4, -1.4 }, { 1.4, 0.4 } },
        required_tiles = { layers = { ground_tile = true } },
        colliding_tiles = { layers = { water_tile = true } },
        remove_on_collision = true,
      },
      {
        area = { { -2, -3 }, { 2, -2 } },
        required_tiles = { layers = { water_tile = true } },
        colliding_tiles = { layers = {} },
      },
    },
    minable = { mining_time = 0.1, result = "angels-sea-pump" },
    placeable_by = { item = "angels-sea-pump", count = 1 },
    resource_categories = { "angels-sea-pump" },
    max_health = 200,
    corpse = "small-remnants",
    dying_explosion = "pumpjack-explosion",
    resistances = {
      {
        type = "fire",
        percent = 70,
      },
      {
        type = "impact",
        percent = 30,
      },
    },
    collision_box = { { -1.6, -2.05 }, { 1.6, 0.3 } },
    selection_box = { { -1.6, -2.49 }, { 1.6, 0.49 } },
    damaged_trigger_effect = hit_effects.entity(),
    output_fluid_box = {
      volume = 100000,
      pipe_covers = pipecoverspictures(),
      production_type = "output",
      filter = "water",
      pipe_connections = {
        {
          position = { 0, 0 },
          direction = defines.direction.south,
          flow_direction = "output",
        },
      },
    },
    energy_source = {
      type = "electric",
      emissions_per_minute = { pollution = 10 },
      usage_priority = "secondary-input",
    },
    energy_usage = "250kW",
    tile_width = 3,
    tile_height = 3,
    impact_category = "metal",
    open_sound = sounds.machine_open,
    close_sound = sounds.machine_close,
    working_sound = {
      sound = {
        filename = "__base__/sound/offshore-pump.ogg",
        volume = 0.5,
        modifiers = volume_multiplier("tips-and-tricks", 1.1),
        audible_distance_modifier = 0.7,
      },
      match_volume_to_activity = true,
      max_sounds_per_prototype = 3,
      fade_in_ticks = 4,
      fade_out_ticks = 20,
    },
    mining_speed = 1, -- how fast it 'ticks'
    uses_force_mining_productivity_bonus = false,
    resource_searching_radius = 0.49,
    vector_to_place_result = { 0, 0 },
    module_slots = 2,
    allowed_effects = { "speed", "consumption", "pollution" }, -- disallow productivity modules
    radius_visualisation_picture = {
      filename = "__base__/graphics/entity/pumpjack/pumpjack-radius-visualization.png",
      width = 12,
      height = 12,
    },
    base_picture = {
      north = {
        filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
        priority = "high",
        shift = { 0, -1 },
        width = 160,
        height = 160,
      },
      east = {
        filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
        priority = "high",
        shift = { 1, 0 },
        x = 160,
        width = 160,
        height = 160,
      },
      south = {
        filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
        priority = "high",
        shift = { 0, 1 },
        x = 320,
        width = 160,
        height = 160,
      },
      west = {
        filename = "__angelsrefininggraphics__/graphics/entity/sea-pump/sea-pump.png",
        priority = "high",
        shift = { -1, 0 },
        x = 480,
        width = 160,
        height = 160,
      },
    },
    circuit_connector = circuit_connector_definitions["angels-seafloor-pump"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
  },
})
