local ore_tints = angelsmods.refining.ore_tints

data:extend({
  ---------------------------------------------------------------------------
  -- TIER 1 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angelsore1-crushed",
    localised_name = { "recipe-name.angelsore1-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = true,
    ingredients = { { type = "item", name = "angels-ore1", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore1-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore1-crushed",
    order = "a[angelsore1-crushed]",
  },
  {
    type = "recipe",
    name = "angelsore1-crushed-hand",
    localised_name = { "recipe-name.angelsore1-crushed-hand" },
    category = "angels-manual-crafting",
    subgroup = "processing-crafting",
    energy_required = 4,
    enabled = true,
    ingredients = { { type = "item", name = "angels-ore1", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore1-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore1-crushed",
    allow_decomposition = false,
    always_show_made_in = true,
    order = "a[angelsore1-crushed-hand]",
  },
  {
    type = "recipe",
    name = "angelsore2-crushed",
    localised_name = { "recipe-name.angelsore2-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = false,
    ingredients = { { type = "item", name = "angels-ore2", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore2-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore2-crushed",
    order = "b[angelsore2-crushed]",
  },
  {
    type = "recipe",
    name = "angelsore3-crushed",
    localised_name = { "recipe-name.angelsore3-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = true,
    ingredients = { { type = "item", name = "angels-ore3", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore3-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore3-crushed",
    order = "c[angelsore3-crushed]",
  },
  {
    type = "recipe",
    name = "angelsore3-crushed-hand",
    localised_name = { "recipe-name.angelsore3-crushed-hand" },
    category = "angels-manual-crafting",
    subgroup = "processing-crafting",
    energy_required = 4,
    enabled = true,
    ingredients = { { type = "item", name = "angels-ore3", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore3-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore3-crushed",
    allow_decomposition = false,
    always_show_made_in = true,
    order = "b[angelsore3-crushed-hand]",
  },
  {
    type = "recipe",
    name = "angelsore4-crushed",
    localised_name = { "recipe-name.angelsore4-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = false,
    ingredients = { { type = "item", name = "angels-ore4", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore4-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore4-crushed",
    order = "d[angelsore4-crushed]",
  },
  {
    type = "recipe",
    name = "angelsore5-crushed",
    localised_name = { "recipe-name.angelsore5-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = true,
    ingredients = { { type = "item", name = "angels-ore5", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore5-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore5-crushed",
    order = "e[angelsore5-crushed]",
  },
  {
    type = "recipe",
    name = "angelsore6-crushed",
    localised_name = { "recipe-name.angelsore6-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = true,
    ingredients = { { type = "item", name = "angels-ore6", amount = 2 } },
    results = {
      { type = "item", name = "angels-ore6-crushed", amount = 2 },
      { type = "item", name = "stone-crushed", amount = 1 },
    },
    main_product = "angels-ore6-crushed",
    order = "f[angelsore6-crushed]",
  },
  ---------------------------------------------------------------------------
  -- TIER 1.5 ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angelsore8-crushed",
    localised_name = { "recipe-name.angelsore8-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore1-crushed", amount = 2 },
      { type = "item", name = "angels-ore2-crushed", amount = 2 },
      { type = "item", name = "angels-ore5-crushed", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-ore8-crushed", amount = 6 },
    },
    always_show_products = true,
    show_amount_in_title = false,
    order = "g",
  },
  {
    type = "recipe",
    name = "angelsore8-powder",
    localised_name = { "recipe-name.angelsore8-powder" },
    category = "ore-refining-t1-5",
    subgroup = "ore-processing-a",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore8-crushed", amount = 3 },
      { type = "item", name = "milling-drum", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "item", name = "angels-ore8-powder", amount = 3 },
      { type = "item", name = "milling-drum-used", amount = 1, ignored_by_productivity = 1 },
    },
    main_product = "angels-ore8-powder",
    order = "h",
  },
  {
    type = "recipe",
    name = "angelsore9-crushed",
    localised_name = { "recipe-name.angelsore9-crushed" },
    category = "ore-refining-t1",
    subgroup = "ore-processing-a",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore3-crushed", amount = 2 },
      { type = "item", name = "angels-ore4-crushed", amount = 2 },
      { type = "item", name = "angels-ore6-crushed", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-ore9-crushed", amount = 6 },
    },
    always_show_products = true,
    show_amount_in_title = false,
    order = "i",
  },
  {
    type = "recipe",
    name = "angelsore9-powder",
    localised_name = { "recipe-name.angelsore9-powder" },
    category = "ore-refining-t1-5",
    subgroup = "ore-processing-a",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore9-crushed", amount = 3 },
      { type = "item", name = "milling-drum", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "item", name = "angels-ore9-powder", amount = 3 },
      { type = "item", name = "milling-drum-used", amount = 1, ignored_by_productivity = 1 },
    },
    main_product = "angels-ore9-powder",
    order = "j",
  },
  ---------------------------------------------------------------------------
  -- TIER 2 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angelsore1-chunk",
    localised_name = { "recipe-name.angelsore1-chunk" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore1-crushed", amount = 2 },
      { type = "fluid", name = "water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-ore1-chunk", amount = 2 },
      { type = "fluid", name = "water-yellow-waste", amount = 50 },
      { type = "item", name = "geode-blue", amount = 1, probability = 0.5 },
    },
    main_product = "angels-ore1-chunk",
    order = "a[angelsore1-chunk]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "water-yellow-waste", ore_tints["ore1"] }),
  },
  {
    type = "recipe",
    name = "angelsore2-chunk",
    localised_name = { "recipe-name.angelsore2-chunk" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore2-crushed", amount = 2 },
      { type = "fluid", name = "water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-ore2-chunk", amount = 2 },
      { type = "fluid", name = "water-yellow-waste", amount = 50 },
      { type = "item", name = "geode-purple", amount = 1, probability = 0.5 },
    },
    main_product = "angels-ore2-chunk",
    order = "b[angelsore2-chunk]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "water-yellow-waste", ore_tints["ore2"] }),
  },
  {
    type = "recipe",
    name = "angelsore3-chunk",
    localised_name = { "recipe-name.angelsore3-chunk" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore3-crushed", amount = 2 },
      { type = "fluid", name = "water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-ore3-chunk", amount = 2 },
      { type = "fluid", name = "water-yellow-waste", amount = 50 },
      { type = "item", name = "geode-yellow", amount = 1, probability = 0.5 },
    },
    main_product = "angels-ore3-chunk",
    order = "c[angelsore3-chunk]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "water-yellow-waste", ore_tints["ore3"] }),
  },
  {
    type = "recipe",
    name = "angelsore4-chunk",
    localised_name = { "recipe-name.angelsore4-chunk" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore4-crushed", amount = 2 },
      { type = "fluid", name = "water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-ore4-chunk", amount = 2 },
      { type = "fluid", name = "water-yellow-waste", amount = 50 },
      { type = "item", name = "geode-lightgreen", amount = 1, probability = 0.5 },
    },
    main_product = "angels-ore4-chunk",
    order = "d[angelsore4-chunk]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "water-yellow-waste", ore_tints["ore4"] }),
  },
  {
    type = "recipe",
    name = "angelsore5-chunk",
    localised_name = { "recipe-name.angelsore5-chunk" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore5-crushed", amount = 2 },
      { type = "fluid", name = "water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-ore5-chunk", amount = 2 },
      { type = "fluid", name = "water-yellow-waste", amount = 50 },
      { type = "item", name = "geode-cyan", amount = 1, probability = 0.5 },
    },
    main_product = "angels-ore5-chunk",
    order = "e[angelsore5-chunk]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "water-yellow-waste", ore_tints["ore5"] }),
  },
  {
    type = "recipe",
    name = "angelsore6-chunk",
    localised_name = { "recipe-name.angelsore6-chunk" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore6-crushed", amount = 2 },
      { type = "fluid", name = "water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-ore6-chunk", amount = 2 },
      { type = "fluid", name = "water-yellow-waste", amount = 50 },
      { type = "item", name = "geode-red", amount = 1, probability = 0.5 },
    },
    main_product = "angels-ore6-chunk",
    order = "f[angelsore6-chunk]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "water-yellow-waste", ore_tints["ore6"] }),
  },
  ---------------------------------------------------------------------------
  -- TIER 2.5 ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angelsore8-sludge",
    localised_name = { "recipe-name.angelsore8-sludge" },
    category = "chemistry",
    subgroup = "ore-processing-b",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore8-powder", amount = 3 },
      { type = "item", name = "angels-ore1-chunk", amount = 1 },
      { type = "item", name = "angels-ore2-chunk", amount = 1 },
      { type = "item", name = "angels-ore5-chunk", amount = 1 },
      { type = "fluid", name = "thermal-water", amount = 20 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-ore8-sludge", amount = 6 },
    },
    main_product = "angels-ore8-sludge",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-ore8-sludge",
      "thermal-water",
      "sulfuric-acid",
    }),
    order = "g",
  },
  {
    type = "recipe",
    name = "angelsore8-dust",
    localised_name = { "recipe-name.angelsore8-dust" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore8-sludge", amount = 4 },
      --{type="item", name="solid-sodium-hydroxide", amount=2},
    },
    results = {
      { type = "item", name = "angels-ore8-dust", amount = 4 },
      { type = "fluid", name = "water-yellow-waste", amount = 20 },
    },
    main_product = "angels-ore8-dust",
    order = "h",
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-ore8-sludge"),
  },
  {
    type = "recipe",
    name = "angelsore9-sludge",
    localised_name = { "recipe-name.angelsore9-sludge" },
    category = "chemistry",
    subgroup = "ore-processing-b",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore9-powder", amount = 3 },
      { type = "item", name = "angels-ore3-chunk", amount = 1 },
      { type = "item", name = "angels-ore4-chunk", amount = 1 },
      { type = "item", name = "angels-ore6-chunk", amount = 1 },
      { type = "fluid", name = "thermal-water", amount = 20 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-ore9-sludge", amount = 6 },
    },
    main_product = "angels-ore9-sludge",
    always_show_products = true,
    show_amount_in_title = false,
    order = "i",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "thermal-water",
      "sulfuric-acid",
      "angels-ore9-sludge",
    }),
  },
  {
    type = "recipe",
    name = "angelsore9-dust",
    localised_name = { "recipe-name.angelsore9-dust" },
    category = "ore-refining-t2",
    subgroup = "ore-processing-b",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore9-sludge", amount = 4 },
      --{type="item", name="solid-sodium-hydroxide", amount=2},
    },
    results = {
      { type = "item", name = "angels-ore9-dust", amount = 4 },
      { type = "fluid", name = "water-yellow-waste", amount = 20 },
    },
    main_product = "angels-ore9-dust",
    order = "j",
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-ore9-sludge"),
  },
  ---------------------------------------------------------------------------
  -- TIER 3 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angelsore1-crystal",
    localised_name = { "recipe-name.angelsore1-crystal" },
    category = "ore-refining-t3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore1-chunk", amount = 2 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-ore1-crystal", amount = 2 },
    },
    main_product = "angels-ore1-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    order = "a[angelsore1-crystal]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "sulfuric-acid", ore_tints["ore1"] }),
  },
  {
    type = "recipe",
    name = "angelsore2-crystal",
    localised_name = { "recipe-name.angelsore2-crystal" },
    category = "ore-refining-t3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore2-chunk", amount = 2 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-ore2-crystal", amount = 2 },
    },
    main_product = "angels-ore2-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    order = "b[angelsore2-crystal]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "sulfuric-acid", ore_tints["ore2"] }),
  },
  {
    type = "recipe",
    name = "angelsore3-crystal",
    localised_name = { "recipe-name.angelsore3-crystal" },
    category = "ore-refining-t3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore3-chunk", amount = 2 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-ore3-crystal", amount = 2 },
    },
    main_product = "angels-ore3-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    order = "c[angelsore3-crystal]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "sulfuric-acid", ore_tints["ore3"] }),
  },
  {
    type = "recipe",
    name = "angelsore4-crystal",
    localised_name = { "recipe-name.angelsore4-crystal" },
    category = "ore-refining-t3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore4-chunk", amount = 2 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-ore4-crystal", amount = 2 },
    },
    main_product = "angels-ore4-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    order = "d[angelsore4-crystal]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "sulfuric-acid", ore_tints["ore4"] }),
  },
  {
    type = "recipe",
    name = "angelsore5-crystal",
    localised_name = { "recipe-name.angelsore5-crystal" },
    category = "ore-refining-t3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore5-chunk", amount = 2 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-ore5-crystal", amount = 2 },
    },
    main_product = "angels-ore5-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    order = "e[angelsore5-crystal]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "sulfuric-acid", ore_tints["ore5"] }),
  },
  {
    type = "recipe",
    name = "angelsore6-crystal",
    localised_name = { "recipe-name.angelsore6-crystal" },
    category = "ore-refining-t3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore6-chunk", amount = 2 },
      { type = "fluid", name = "sulfuric-acid", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-ore6-crystal", amount = 2 },
    },
    main_product = "angels-ore6-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    order = "f[angelsore6-crystal]",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "sulfuric-acid", ore_tints["ore6"] }),
  },
  ---------------------------------------------------------------------------
  -- TIER 3.5 ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angelsore8-solution",
    localised_name = { "recipe-name.angelsore8-solution" },
    category = "ore-refining-t3b",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore8-dust", amount = 3 },
      { type = "item", name = "angels-ore1-crystal", amount = 1 },
      { type = "item", name = "angels-ore2-crystal", amount = 1 },
      { type = "item", name = "angels-ore5-crystal", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-ore8-solution", amount = 60 },
    },
    main_product = "angels-ore8-solution",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-ore8-solution", "sulfuric-acid" }),
    order = "g",
  },
  {
    type = "recipe",
    name = "angelsore8-anode-sludge-filtering",
    localised_name = { "recipe-name.angelsore8-solution-filtering" },
    category = "filtering-3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore8-solution", amount = 60 },
      { type = "fluid", name = "water-purified", amount = 50 },
      { type = "item", name = "filter-ceramic", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "fluid", name = "angels-ore8-slime", amount = 60 },
      { type = "fluid", name = "water-yellow-waste", amount = 10 },
      { type = "item", name = "filter-ceramic-used", amount = 1 },
    },
    main_product = "angels-ore8-slime",
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "ceramic",
      { { 104, 112, 113 }, { 133, 196, 060 }, { 133, 196, 060 }, { 113, 224, 028, 0.9 } }
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-ore8-slime",
      "water-purified",
      "water-yellow-waste",
    }),
    order = "h",
  },
  {
    type = "recipe",
    name = "angelsore8-anode-sludge",
    localised_name = { "recipe-name.angelsore8-anode-sludge" },
    category = "ore-refining-t3-5",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore8-slime", amount = 60 },
      --{type="fluid", name="liquid-ferric-chloride-solution", amount=2},
    },
    results = {
      { type = "fluid", name = "angels-ore8-anode-sludge", amount = 60 },
      { type = "fluid", name = "water-yellow-waste", amount = 20 },
      { type = "item", name = "slag", amount = 1 },
    },
    main_product = "angels-ore8-anode-sludge",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-ore8-anode-sludge",
      "angels-ore8-slime",
      "water-yellow-waste",
    }),
    order = "g",
  },
  {
    type = "recipe",
    name = "angelsore8-crystal",
    localised_name = { "recipe-name.angelsore8-crystal" },
    category = "crystallizing-3",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore8-anode-sludge", amount = 60 },
    },
    results = {
      { type = "item", name = "angels-ore8-crystal", amount = 6 },
    },
    main_product = "angels-ore8-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-ore8-anode-sludge"),
    order = "h",
  },
  {
    type = "recipe",
    name = "angelsore9-solution",
    localised_name = { "recipe-name.angelsore9-solution" },
    category = "ore-refining-t3b",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore9-dust", amount = 3 },
      { type = "item", name = "angels-ore3-crystal", amount = 1 },
      { type = "item", name = "angels-ore4-crystal", amount = 1 },
      { type = "item", name = "angels-ore6-crystal", amount = 1 },
      { type = "fluid", name = "sulfuric-acid", amount = 20 },
    },
    results = {
      { type = "fluid", name = "angels-ore9-solution", amount = 60 },
    },
    main_product = "angels-ore9-solution",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-ore9-solution", "sulfuric-acid" }),
    order = "i",
  },
  {
    type = "recipe",
    name = "angelsore9-anode-sludge-filtering",
    localised_name = { "recipe-name.angelsore9-solution-filtering" },
    category = "filtering-3",
    subgroup = "ore-processing-c",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore9-solution", amount = 60 },
      { type = "fluid", name = "water-purified", amount = 50 },
      { type = "item", name = "filter-ceramic", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "fluid", name = "angels-ore9-slime", amount = 60 },
      { type = "fluid", name = "water-yellow-waste", amount = 10 },
      { type = "item", name = "filter-ceramic-used", amount = 1 },
    },
    main_product = "angels-ore9-slime",
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "ceramic",
      { { 095, 106, 090 }, { 254, 110, 022 }, { 254, 110, 022, 0.8 }, { 252, 103, 005, 0.9 } }
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-ore9-slime",
      "water-purified",
      "water-yellow-waste",
    }),
    order = "j",
  },
  {
    type = "recipe",
    name = "angelsore9-anode-sludge",
    localised_name = { "recipe-name.angelsore9-anode-sludge" },
    category = "ore-refining-t3-5",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore9-slime", amount = 60 },
      --{type="fluid", name="liquid-cupric-chloride-solution", amount=2},
    },
    results = {
      { type = "fluid", name = "angels-ore9-anode-sludge", amount = 60 },
      { type = "fluid", name = "water-yellow-waste", amount = 20 },
      { type = "item", name = "slag", amount = 1 },
    },
    main_product = "angels-ore9-anode-sludge",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-ore9-anode-sludge",
      "angels-ore9-slime",
      "water-yellow-waste",
    }),
    order = "i",
  },
  {
    type = "recipe",
    name = "angelsore9-crystal",
    localised_name = { "recipe-name.angelsore9-crystal" },
    category = "crystallizing-3",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-ore9-anode-sludge", amount = 60 },
    },
    results = {
      { type = "item", name = "angels-ore9-crystal", amount = 6 },
    },
    main_product = "angels-ore9-crystal",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-ore9-anode-sludge"),
    order = "j",
  },
  ---------------------------------------------------------------------------
  -- TIER 4 -----------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angelsore1-pure",
    localised_name = { "recipe-name.angelsore1-pure" },
    category = "ore-refining-t4",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore1-crystal", amount = 4 },
    },
    results = {
      { type = "item", name = "angels-ore1-pure", amount = 4 },
    },
    main_product = "angels-ore1-pure",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ angelsmods.refining.ore_tints["ore1"] }, 0.6),
    order = "a[angelsore1-pure]",
  },
  {
    type = "recipe",
    name = "angelsore2-pure",
    localised_name = { "recipe-name.angelsore2-pure" },
    category = "ore-refining-t4",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore2-crystal", amount = 4 },
    },
    results = {
      { type = "item", name = "angels-ore2-pure", amount = 4 },
    },
    main_product = "angels-ore2-pure",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ angelsmods.refining.ore_tints["ore2"] }, 0.6),
    order = "b[angelsore2-pure]",
  },
  {
    type = "recipe",
    name = "angelsore3-pure",
    localised_name = { "recipe-name.angelsore3-pure" },
    category = "ore-refining-t4",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore3-crystal", amount = 4 },
    },
    results = {
      { type = "item", name = "angels-ore3-pure", amount = 4 },
    },
    main_product = "angels-ore3-pure",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ angelsmods.refining.ore_tints["ore3"] }, 0.6),
    order = "c[angelsore3-pure]",
  },
  {
    type = "recipe",
    name = "angelsore4-pure",
    localised_name = { "recipe-name.angelsore4-pure" },
    category = "ore-refining-t4",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore4-crystal", amount = 4 },
    },
    results = {
      { type = "item", name = "angels-ore4-pure", amount = 4 },
    },
    main_product = "angels-ore4-pure",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ angelsmods.refining.ore_tints["ore4"] }, 0.6),
    order = "d[angelsore4-pure]",
  },
  {
    type = "recipe",
    name = "angelsore5-pure",
    localised_name = { "recipe-name.angelsore5-pure" },
    category = "ore-refining-t4",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore5-crystal", amount = 4 },
    },
    results = {
      { type = "item", name = "angels-ore5-pure", amount = 4 },
    },
    main_product = "angels-ore5-pure",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ angelsmods.refining.ore_tints["ore5"] }, 0.6),
    order = "e[angelsore5-pure]",
  },
  {
    type = "recipe",
    name = "angelsore6-pure",
    localised_name = { "recipe-name.angelsore6-pure" },
    category = "ore-refining-t4",
    subgroup = "ore-processing-d",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-ore6-crystal", amount = 4 },
    },
    results = {
      { type = "item", name = "angels-ore6-pure", amount = 4 },
    },
    main_product = "angels-ore6-pure",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ angelsmods.refining.ore_tints["ore6"] }, 0.6),
    order = "f[angelsore6-pure]",
  },
  --SLAG PROCESSING
  {
    type = "recipe",
    name = "filter-frame",
    localised_name = { "item-name.filter-frame" },
    category = "crafting",
    subgroup = "geode-crystallization",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "item", name = "iron-plate", amount = 1 },
    },
    results = {
      { type = "item", name = "filter-frame", amount = 1 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/filter-frame.png",
    icon_size = 32,
    order = "x[filter-frame]",
  },
  {
    type = "recipe",
    name = "filter-coal",
    localised_name = { "item-name.filter-coal" },
    category = "crafting",
    subgroup = "geode-crystallization",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "coal", amount = 1 },
      { type = "item", name = "filter-frame", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      { type = "item", name = "filter-coal", amount = 5 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/filter-coal.png",
    icon_size = 32,
    order = "y[filter-coal]",
  },
  {
    type = "recipe",
    name = "filter-ceramic",
    localised_name = { "item-name.filter-ceramic" },
    category = "crafting",
    subgroup = "geode-crystallization",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "filter-frame", amount = 1 },
      { type = "item", name = "plastic-bar", amount = 2 },
    },
    results = {
      { type = "item", name = "filter-ceramic", amount = 1 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/filter-ceramic.png",
    icon_size = 32,
    order = "z[filter-ceramic]-a[new]",
  },
  {
    type = "recipe",
    name = "filter-ceramic-refurbish",
    localised_name = { "item-name.filter-ceramic" },
    category = "crafting-with-fluid",
    subgroup = "geode-crystallization",
    energy_required = 0.5,
    enabled = false,
    ingredients = {
      { type = "item", name = "filter-ceramic-used", amount = 1 },
      { type = "fluid", name = "water-purified", amount = 50 },
    },
    results = {
      { type = "item", name = "filter-ceramic", amount = 1, ignored_by_stats = 1 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/filter-ceramic.png",
    icon_size = 32,
    order = "z[filter-ceramic]-b[refurbish]",
  },
  {
    type = "recipe",
    name = "milling-drum",
    localised_name = { "item-name.milling-drum" },
    category = "crafting-with-fluid",
    subgroup = "ore-powderizer",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "steel-plate", amount = 1 },
      { type = "fluid", name = "lubricant", amount = 10 },
    },
    results = {
      { type = "item", name = "milling-drum", amount = 1 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/milling-drum.png",
    icon_size = 32,
    order = "z[milling-drum]-a[new]",
  },
  {
    type = "recipe",
    name = "milling-drum-used",
    localised_name = { "item-name.milling-drum" },
    category = "crafting-with-fluid",
    subgroup = "ore-powderizer",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "item", name = "milling-drum-used", amount = 1 },
      { type = "fluid", name = "lubricant", amount = 10 },
    },
    results = {
      { type = "item", name = "milling-drum", amount = 1, ignored_by_stats = 1 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/milling-drum-used.png",
    icon_size = 32,
    order = "z[milling-drum]-b[recycle]",
  },
  {
    type = "recipe",
    name = "slag-processing-dissolution",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "slag", amount = 5 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "slag-slurry", amount = 50 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 142, 079, 028 }, { 107, 062, 021 }, { 075, 040, 015 } },
      { "slag" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("slag-slurry"),
    order = "i [slag-processing-dissolution]",
  },
  {
    type = "recipe",
    name = "stone-crushed-dissolution",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "stone-crushed", amount = 25 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "slag-slurry", amount = 50 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 142, 079, 028 }, { 107, 062, 021 }, { 075, 040, 015 } },
      { "stone-crushed" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("slag-slurry"),
    order = "j [stone-crushed-dissolution]",
  },
  --FILTERING
  {
    type = "recipe",
    name = "slag-processing-filtering-1",
    category = "filtering",
    subgroup = "filtering",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "slag-slurry", amount = 50 },
      { type = "fluid", name = "water-purified", amount = 50 },
      { type = "item", name = "filter-coal", amount = 1 },
    },
    results = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
      { type = "fluid", name = "water-yellow-waste", amount = 40 },
      { type = "item", name = "filter-frame", amount = 1, ignored_by_stats = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "coal",
      { { 140, 073, 029 }, { 230, 116, 017 } }
    ),
    order = "a[filtering-mineral]-a[slag-processing]-a[coal]",
  },
  {
    type = "recipe",
    name = "slag-processing-filtering-2",
    category = "filtering-2",
    subgroup = "filtering",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "slag-slurry", amount = 35 },
      { type = "fluid", name = "water-purified", amount = 50 },
      { type = "item", name = "filter-ceramic", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "fluid", name = "mineral-sludge", amount = 35 },
      { type = "fluid", name = "water-yellow-waste", amount = 20 },
      { type = "item", name = "filter-ceramic-used", amount = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "ceramic",
      { { 140, 073, 029 }, { 230, 116, 017 } }
    ),
    order = "a[filtering-mineral]-a[slag-processing]-b[ceramic]",
  },
  {
    type = "recipe",
    name = "thermal-water-filtering-1",
    category = "filtering",
    subgroup = "filtering",
    energy_required = 4,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "thermal-water", amount = 50 },
      { type = "item", name = "filter-coal", amount = 1 },
    },
    results = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
      { type = "item", name = "filter-frame", amount = 1, ignored_by_stats = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "coal",
      { { 243, 135, 000 }, { 230, 116, 017 }, { 247, 140, 003 } }
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "mineral-sludge", "thermal-water" }),
    order = "a[filtering-mineral]-a[thermal-processing]-a[coal]",
  },
  {
    type = "recipe",
    name = "thermal-water-filtering-2",
    category = "filtering-2",
    subgroup = "filtering",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "thermal-water", amount = 35 },
      { type = "item", name = "filter-ceramic", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "fluid", name = "mineral-sludge", amount = 35 },
      { type = "item", name = "filter-ceramic-used", amount = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "ceramic",
      { { 243, 135, 000 }, { 230, 116, 017 }, { 247, 140, 003 } }
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "mineral-sludge", "thermal-water" }),
    order = "a[filtering-mineral]-a[thermal-processing]-b[ceramic]",
  },
  --CRYSTAL SLURRY
  --GEODES LIQUIFY
  {
    type = "recipe",
    name = "geode-blue-liquify",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "geode-blue", amount = 5 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "crystal-slurry", amount = 20 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 184, 231, 043 }, { 080, 172, 033 }, { 055, 126, 017 } },
      { "geode-blue" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("crystal-slurry"),
    order = "a[geode-blue-liquify]",
  },
  {
    type = "recipe",
    name = "geode-red-liquify",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "geode-red", amount = 5 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "crystal-slurry", amount = 20 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 184, 231, 043 }, { 080, 172, 033 }, { 055, 126, 017 } },
      { "geode-red" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("crystal-slurry"),
    order = "f[geode-red-liquify]",
  },
  {
    type = "recipe",
    name = "geode-yellow-liquify",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "geode-yellow", amount = 5 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "crystal-slurry", amount = 30 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 184, 231, 043 }, { 080, 172, 033 }, { 055, 126, 017 } },
      { "geode-yellow" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("crystal-slurry"),
    order = "c[geode-yellow-liquify]",
  },
  {
    type = "recipe",
    name = "geode-purple-liquify",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "geode-purple", amount = 5 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "crystal-slurry", amount = 40 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 184, 231, 043 }, { 080, 172, 033 }, { 055, 126, 017 } },
      { "geode-purple" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("crystal-slurry"),
    order = "b[geode-purple-liquify]",
  },
  {
    type = "recipe",
    name = "geode-cyan-liquify",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "geode-cyan", amount = 5 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "crystal-slurry", amount = 50 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 184, 231, 043 }, { 080, 172, 033 }, { 055, 126, 017 } },
      { "geode-cyan" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("crystal-slurry"),
    order = "e[geode-cyan-liquify]",
  },
  {
    type = "recipe",
    name = "geode-lightgreen-liquify",
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "geode-lightgreen", amount = 5 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "crystal-slurry", amount = 50 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 184, 231, 043 }, { 080, 172, 033 }, { 055, 126, 017 } },
      { "geode-lightgreen" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("crystal-slurry"),
    order = "d[geode-lightgreen-liquify]",
  },
  {
    type = "recipe",
    name = "crystal-dust-liquify",
    localised_name = { "fluid-name.crystal-slurry" },
    category = "liquifying",
    subgroup = "liquifying",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "item", name = "crystal-dust", amount = 10 },
      { type = "fluid", name = "sulfuric-acid", amount = 15 },
    },
    results = {
      { type = "fluid", name = "crystal-slurry", amount = 50 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon(
      nil,
      { { 184, 231, 043 }, { 080, 172, 033 }, { 055, 126, 017 } },
      { "crystal-dust" }
    ),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("crystal-slurry"),
    order = "g",
  },
  --FILTERING
  {
    type = "recipe",
    name = "crystal-slurry-filtering-1",
    category = "filtering",
    subgroup = "filtering",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "crystal-slurry", amount = 50 },
      { type = "fluid", name = "water-purified", amount = 50 },
      { type = "item", name = "filter-coal", amount = 1 },
    },
    results = {
      { type = "fluid", name = "crystal-seedling", amount = 50 },
      { type = "fluid", name = "water-yellow-waste", amount = 40 },
      { type = "item", name = "filter-frame", amount = 1, ignored_by_stats = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "coal",
      { { 105, 237, 038 }, { 211, 255, 052 }, { 100, 255, 000 }, { 147, 207, 47 } }
    ),
    order = "b[filtering-crystal]-c[crystal-processing]-a[coal]",
  },
  {
    type = "recipe",
    name = "crystal-slurry-filtering-2",
    category = "filtering-2",
    subgroup = "filtering",
    energy_required = 1.5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "crystal-slurry", amount = 35 },
      { type = "fluid", name = "water-purified", amount = 50 },
      { type = "item", name = "filter-ceramic", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "fluid", name = "crystal-seedling", amount = 35 },
      { type = "fluid", name = "water-yellow-waste", amount = 20 },
      { type = "item", name = "filter-ceramic-used", amount = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "ceramic",
      { { 105, 237, 038 }, { 211, 255, 052 }, { 100, 255, 000 }, { 147, 207, 47 } }
    ),
    order = "b[filtering-crystal]-c[crystal-processing]-b[ceramic]",
  },
  {
    type = "recipe",
    name = "crystal-slurry-filtering-conversion-1",
    category = "filtering",
    subgroup = "filtering",
    energy_required = 3,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "crystal-slurry", amount = 50 },
      { type = "fluid", name = "water-mineralized", amount = 100 },
      { type = "item", name = "filter-coal", amount = 1 },
    },
    results = {
      { type = "fluid", name = "mineral-sludge", amount = 50 },
      { type = "fluid", name = "water-yellow-waste", amount = 40 },
      { type = "item", name = "filter-frame", amount = 1, ignored_by_stats = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "coal",
      { { 105, 237, 038 }, { 230, 116, 017 }, { 100, 255, 000 } }
    ),
    order = "a[filtering-mineral]-c[crystal-processing]-a[coal]",
  },
  {
    type = "recipe",
    name = "crystal-slurry-filtering-conversion-2",
    category = "filtering-2",
    subgroup = "filtering",
    energy_required = 1.5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "crystal-slurry", amount = 35 },
      { type = "fluid", name = "water-mineralized", amount = 100 },
      { type = "item", name = "filter-ceramic", amount = 1, ignored_by_stats = 1 },
    },
    results = {
      { type = "fluid", name = "mineral-sludge", amount = 35 },
      { type = "fluid", name = "water-yellow-waste", amount = 20 },
      { type = "item", name = "filter-ceramic-used", amount = 1 },
    },
    icons = angelsmods.functions.create_viscous_liquid_filtering_recipe_icon(
      "ceramic",
      { { 105, 237, 038 }, { 230, 116, 017 }, { 100, 255, 000 } }
    ),
    order = "a[filtering-mineral]-c[crystal-processing]-b[ceramic]",
  },
  --CATALYSTS
  {
    type = "recipe",
    name = "catalysator-brown",
    localised_name = { "item-name.catalysator-brown" },
    category = "crystallizing",
    subgroup = "geode-crystallization",
    --subgroup = "slag-processing-1",
    energy_required = 0.5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "mineral-sludge", amount = 25 },
    },
    results = {
      { type = "item", name = "catalysator-brown", amount = 2 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/catalysator-brown.png",
    icon_size = 32,
    order = "i[catalysator-brown]",
  },
  {
    type = "recipe",
    name = "catalysator-green",
    localised_name = { "item-name.catalysator-green" },
    category = "crystallizing-2",
    subgroup = "geode-crystallization",
    energy_required = 0.5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "crystal-seedling", amount = 25 },
    },
    results = {
      { type = "item", name = "catalysator-green", amount = 2 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/catalysator-green.png",
    icon_size = 32,
    order = "j[catalysator-green]",
  },
  {
    type = "recipe",
    name = "catalysator-orange",
    localised_name = { "item-name.catalysator-orange" },
    category = "crystallizing-3",
    subgroup = "geode-crystallization",
    energy_required = 0.5,
    enabled = false,
    ingredients = {
      { type = "item", name = "catalysator-brown", amount = 2 },
      { type = "item", name = "catalysator-green", amount = 2 },
    },
    results = {
      { type = "item", name = "catalysator-orange", amount = 2 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/catalysator-orange.png",
    icon_size = 32,
    order = "k[catalysator-orange]",
  },
  --VANILLA
  --IRON
  {
    type = "recipe",
    name = "angels-iron-pebbles-smelting",
    localised_name = { "item-name.iron-plate" },
    category = "smelting",
    subgroup = "raw-material",
    energy_required = 7,
    enabled = false,
    ingredients = { { type = "item", name = "angels-iron-pebbles", amount = 4 } },
    results = {
      { type = "item", name = "iron-plate", amount = 2 },
    },
    icons = {
      mods["angelssmelting"] and {
        icon = "__angelssmeltinggraphics__/graphics/icons/plate-iron.png",
        icon_size = 32,
      } or {
        icon = "__base__/graphics/icons/iron-plate.png",
        icon_size = 64,
        scale = 32 / 64,
      },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/iron-pebbles.png",
        icon_size = 32,
        scale = 0.4,
        shift = { -10, -10 },
      },
    },
    order = "b[iron-ore]-c[pebbles]",
  },
  {
    type = "recipe",
    name = "angels-iron-nugget-smelting",
    localised_name = { "item-name.iron-plate" },
    category = "smelting",
    subgroup = "raw-material",
    energy_required = 7,
    enabled = false,
    ingredients = { { type = "item", name = "angels-iron-nugget", amount = 2 } },
    results = {
      { type = "item", name = "iron-plate", amount = 3 },
    },
    icons = {
      mods["angelssmelting"] and {
        icon = "__angelssmeltinggraphics__/graphics/icons/plate-iron.png",
        icon_size = 32,
      } or {
        icon = "__base__/graphics/icons/iron-plate.png",
        icon_size = 64,
        scale = 32 / 64,
      },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/iron-nugget.png",
        icon_size = 32,
        scale = 0.4,
        shift = { -10, -10 },
      },
    },
    order = "b[iron-ore]-d[nugget]",
  },
  {
    type = "recipe",
    name = "angels-iron-pebbles",
    localised_name = { "item-name.angels-iron-pebbles" },
    category = "ore-refining-t1",
    subgroup = "ore-sorting-advanced",
    energy_required = 1,
    enabled = false,
    ingredients = { { type = "item", name = "iron-ore", amount = 2 } },
    results = {
      { type = "item", name = "angels-iron-pebbles", amount = 4 },
    },
    order = "a[iron]-c[pebbles]",
  },
  --COPPER
  {
    type = "recipe",
    name = "angels-copper-pebbles-smelting",
    localised_name = { "item-name.copper-plate" },
    category = "smelting",
    subgroup = "raw-material",
    energy_required = 7,
    enabled = false,
    ingredients = { { type = "item", name = "angels-copper-pebbles", amount = 4 } },
    results = {
      { type = "item", name = "copper-plate", amount = 2 },
    },
    icons = {
      mods["angelssmelting"] and {
        icon = "__angelssmeltinggraphics__/graphics/icons/plate-copper.png",
        icon_size = 32,
      } or {
        icon = "__base__/graphics/icons/copper-plate.png",
        icon_size = 64,
        scale = 32 / 64,
      },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/copper-pebbles.png",
        icon_size = 32,
        scale = 0.4,
        shift = { -10, -10 },
      },
    },
    order = "c[copper-ore]-c[pebbles]",
  },
  {
    type = "recipe",
    name = "angels-copper-nugget-smelting",
    localised_name = { "item-name.copper-plate" },
    category = "smelting",
    subgroup = "raw-material",
    energy_required = 7,
    enabled = false,
    ingredients = { { type = "item", name = "angels-copper-nugget", amount = 2 } },
    results = {
      { type = "item", name = "copper-plate", amount = 3 },
    },
    icons = {
      mods["angelssmelting"] and {
        icon = "__angelssmeltinggraphics__/graphics/icons/plate-copper.png",
        icon_size = 32,
      } or {
        icon = "__base__/graphics/icons/copper-plate.png",
        icon_size = 64,
        scale = 32 / 64,
      },
      {
        icon = "__angelsrefininggraphics__/graphics/icons/copper-nugget.png",
        icon_size = 32,
        scale = 0.4,
        shift = { -10, -10 },
      },
    },
    order = "c[copper-ore]-d[nugget]",
  },
  {
    type = "recipe",
    name = "angels-copper-pebbles",
    localised_name = { "item-name.angels-copper-pebbles" },
    category = "ore-refining-t1",
    subgroup = "ore-sorting-advanced",
    energy_required = 1,
    enabled = false,
    ingredients = { { type = "item", name = "copper-ore", amount = 2 } },
    results = {
      { type = "item", name = "angels-copper-pebbles", amount = 4 },
    },
    order = "b[copper]-c[pebbles]",
  },
})
