data:extend({
  {
    type = "recipe",
    name = "angels-water-mineralized",
    localised_name = { "fluid-name.angels-water-mineralized" },
    category = "angels-liquifying",
    subgroup = "angels-water-treatment",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "water", amount = 100 },
      { type = "item", name = "angels-stone-crushed", amount = 10 },
    },
    results = {
      { type = "fluid", name = "angels-water-mineralized", amount = 100 },
    },
    main_product = "angels-water-mineralized",
    always_show_products = true,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "water",--[[,"angels-stone-crushed"]]
      "angels-water-mineralized",
    }), --get_fluid_recipe_tint("angels-water-mineralized"),
    order = "a[water-water-mineralized]",
  },
  {
    type = "recipe",
    name = "angels-water-purified",
    category = "angels-water-treatment",
    subgroup = "angels-water-treatment",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "water", amount = 150 },
    },
    results = {
      { type = "fluid", name = "angels-water-saline", amount = 20 },
      { type = "fluid", name = "angels-water-purified", amount = 100 },
    },
    main_product = "angels-water-purified",
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon({
      "angels-water-saline",
      "angels-water-purified",
    }, "WsWsWs"),
    order = "b[water-purification]",
  },
  {
    type = "recipe",
    name = "angels-thermal-water-purification",
    category = "angels-water-treatment",
    subgroup = "angels-water-treatment",
    energy_required = 1,
    enabled = false,
    hidden = true,
    ingredients = {
      { type = "fluid", name = "angels-thermal-water", amount = 50 },
    },
    results = {
      { type = "fluid", name = "angels-mineral-sludge", amount = 20 },
      { type = "fluid", name = "angels-water-purified", amount = 30 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon({
      "angels-water-purified",
      "angels-mineral-sludge",
    }, { { 238, 113, 022 }, { 203, 099, 015 }, { 167, 078, 013 } }),
    order = "c[thermal-water-purification]",
  },
  --WASTE WATER TREATMENT
  {
    type = "recipe",
    name = "angels-yellow-waste-water-purification",
    category = "angels-water-treatment",
    subgroup = "angels-water-cleaning",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-yellow-waste", amount = 100 },
    },
    results = {
      { type = "fluid", name = "angels-water-mineralized", amount = 20 },
      { type = "fluid", name = "angels-water-purified", amount = 70 },
      { type = "item", name = "sulfur", amount = 1 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon({
      "angels-water-mineralized",
      "angels-water-purified",
      mods["angelspetrochem"] and { "__angelspetrochemgraphics__/graphics/icons/solid-sulfur.png", 32 } or "sulfur",
    }, "WsSS"),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-water-mineralized",
      "angels-water-yellow-waste",
      "angels-water-purified",
    }),
    order = "d[yellow-waste-water-purification]",
  },
  {
    type = "recipe",
    name = "angels-red-waste-water-purification",
    category = "angels-water-treatment",
    subgroup = "angels-water-cleaning",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-red-waste", amount = 100 },
    },
    results = {
      { type = "fluid", name = "angels-water-mineralized", amount = 20 },
      { type = "fluid", name = "angels-water-purified", amount = 70 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon({
      "angels-water-mineralized",
      "angels-water-purified",
      mods["angelspetrochem"] and { "__angelspetrochemgraphics__/graphics/icons/solid-sodium-nitrate.png", 32 } or nil,
    }, "WsOO"),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-water-mineralized",
      "angels-water-red-waste",
      "angels-water-purified",
    }),
    order = "g[red-waste-water-purification]",
  },
  {
    type = "recipe",
    name = "angels-green-waste-water-purification",
    category = "angels-water-treatment",
    subgroup = "angels-water-cleaning",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-green-waste", amount = 100 },
    },
    results = {
      { type = "fluid", name = "angels-water-saline", amount = 20 },
      { type = "fluid", name = "angels-water-purified", amount = 70 },
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon({
      "angels-water-saline",
      "angels-water-purified",
      mods["angelspetrochem"] and "angels-solid-salt" or nil,
    }, "WsClCl"),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-water-saline",
      "angels-water-green-waste",
      "angels-water-purified",
    }),
    order = "f[green-waste-water-purification]",
  },
  {
    type = "recipe",
    name = "angels-greenyellow-waste-water-purification",
    category = "angels-water-treatment",
    subgroup = "angels-water-cleaning",
    energy_required = 1,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-greenyellow-waste", amount = 100 },
    },
    results = {
      { type = "fluid", name = "angels-water-mineralized", amount = 20 },
      { type = "fluid", name = "angels-water-purified", amount = 70 },
      --{type="item", name="angels-fluorite-ore", amount=1},
    },
    always_show_products = true,
    icons = angelsmods.functions.create_liquid_recipe_icon({
      "angels-water-mineralized",
      "angels-water-purified",
      mods["angelspetrochem"] and { "__angelspetrochemgraphics__/graphics/icons/ore-fluorite.png", 32 } or nil,
    }, "WsFF"),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-water-mineralized",
      "angels-water-greenyellow-waste",
      "angels-water-purified",
    }),
    order = "e[greenyellow-waste-water-purification]",
  },
  --SALINATION
  {
    type = "recipe",
    name = "angels-water-saline-from-water",
    localised_name = { "fluid-name.angels-water-saline" },
    category = "angels-salination-plant",
    subgroup = "angels-water-salination",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "water", amount = 1000 },
    },
    results = {
      { type = "fluid", name = "angels-water-saline", amount = 400 },
    },
    main_product = "angels-water-saline",
    always_show_products = true,
    icons = angelsmods.functions.create_viscous_liquid_recipe_icon(
      nil,
      { { 039, 112, 194 }, { 168, 173, 173 }, { 070, 133, 232 }, { 185, 185, 185, 0.8 } },
      {
        "water",
      }
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-water-saline", "water" }),
    order = "a[water-saline]-a[water]",
  },
  {
    type = "recipe",
    name = "angels-solid-salt-dissolving",
    localised_name = { "fluid-name.angels-water-saline" },
    category = "angels-salination-plant",
    subgroup = "angels-water-salination",
    energy_required = 2,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-solid-salt", amount = 10 },
      { type = "fluid", name = "angels-water-purified", amount = 1000 },
    },
    results = {
      { type = "fluid", name = "angels-water-saline", amount = 400 },
    },
    main_product = "angels-water-saline",
    always_show_products = true,
    icons = angelsmods.functions.create_viscous_liquid_recipe_icon(
      nil,
      { { 039, 112, 194 }, { 168, 173, 173 }, { 070, 133, 232 }, { 185, 185, 185, 0.8 } },
      {
        "angels-solid-salt",
      }
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-water-saline", "angels-water-purified" }),
    order = "a[water-saline]-b[salt]",
  },
  {
    type = "recipe",
    name = "angels-solid-salt-from-saline",
    localised_name = { "item-name.angels-solid-salt" },
    category = "angels-salination-plant",
    subgroup = "angels-water-salination",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-saline", amount = 1000 },
    },
    results = {
      { type = "item", name = "angels-solid-salt", amount = 25 },
    },
    main_product = "angels-solid-salt",
    icons = angelsmods.functions.create_solid_recipe_icon(nil, "angels-solid-salt", { "angels-water-saline" }),
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-water-saline"),
    order = "b[solid-salt-from-saline]",
  },
  {
    type = "recipe",
    name = "angels-solid-salt",
    localised_name = { "item-name.angels-solid-salt" },
    category = "angels-salination-plant",
    subgroup = "angels-water-salination",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "water", amount = 1000 },
    },
    results = {
      { type = "item", name = "angels-solid-salt", amount = 10 },
    },
    main_product = "angels-solid-salt",
    icons = angelsmods.functions.create_solid_recipe_icon(nil, "angels-solid-salt", { "water" }),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-water-saline", "water" }),
    order = "c[solid-salt]",
  },
  {
    type = "recipe",
    name = "angels-solid-lithium",
    localised_name = { "item-name.angels-solid-lithium" },
    category = "angels-salination-plant",
    subgroup = "angels-water-salination",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-thermal-water", amount = 1000 },
    },
    results = {
      { type = "item", name = "angels-solid-lithium", amount = 20 },
    },
    crafting_machine_tint = angelsmods.functions.get_fluid_recipe_tint("angels-thermal-water"),
    order = "d[solid-lithium]",
  },
  --WASHING
  {
    type = "recipe",
    name = "angels-water-heavy-mud",
    category = "angels-washing-plant",
    subgroup = "angels-water-washing",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-viscous-mud", amount = 200 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "fluid", name = "angels-water-heavy-mud", amount = 200 },
      { type = "item", name = "angels-solid-mud", amount_min = 0, amount_max = 3, probability = 0.5 },
    },
    main_product = "angels-water-heavy-mud",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-water-heavy-mud", "angels-water-viscous-mud", "water" }),
    order = "b",
  },
  {
    type = "recipe",
    name = "angels-water-concentrated-mud",
    category = "angels-washing-plant",
    subgroup = "angels-water-washing",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-heavy-mud", amount = 200 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "fluid", name = "angels-water-concentrated-mud", amount = 200 },
      { type = "item", name = "angels-solid-mud", amount_min = 0, amount_max = 3, probability = 0.5 },
    },
    main_product = "angels-water-concentrated-mud",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-water-concentrated-mud",
      "angels-water-heavy-mud",
      "water",
    }),
    order = "c",
  },
  {
    type = "recipe",
    name = "angels-water-light-mud",
    category = "angels-washing-plant",
    subgroup = "angels-water-washing",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-concentrated-mud", amount = 200 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "fluid", name = "angels-water-light-mud", amount = 200 },
      { type = "item", name = "angels-solid-mud", amount_min = 0, amount_max = 3, probability = 0.5 },
    },
    main_product = "angels-water-light-mud",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-water-light-mud",
      "angels-water-concentrated-mud",
      "water",
    }),
    order = "d",
  },
  {
    type = "recipe",
    name = "angels-water-thin-mud",
    category = "angels-washing-plant",
    subgroup = "angels-water-washing",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-light-mud", amount = 200 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "fluid", name = "angels-water-thin-mud", amount = 200 },
      { type = "item", name = "angels-solid-mud", amount_min = 0, amount_max = 3, probability = 0.5 },
    },
    main_product = "angels-water-thin-mud",
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-water-thin-mud", "angels-water-light-mud", "water" }),
    order = "e",
  },
  {
    type = "recipe",
    name = "angels-water-saline",
    category = "angels-washing-plant",
    subgroup = "angels-water-washing",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-thin-mud", amount = 200 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "fluid", name = "angels-water-saline", amount = 200 },
      { type = "item", name = "angels-solid-mud", amount_min = 0, amount_max = 3, probability = 0.5 },
    },
    main_product = "angels-water-saline",
    icons = angelsmods.functions.add_number_icon_layer(
      angelsmods.functions.create_viscous_liquid_fluid_icon(
        nil,
        { { 039, 112, 194 }, { 168, 173, 173 }, { 070, 133, 232 }, { 185, 185, 185, 0.8 } }
      ),    
      5, angelsmods.refining.number_tint
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-water-saline", "angels-water-thin-mud", "water" }),
    order = "f",
  },
  {
    type = "recipe",
    name = "angels-water-viscous-mud",
    category = "angels-liquifying",
    subgroup = "angels-water-washing",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-solid-mud", amount = 10 },
      { type = "fluid", name = "water", amount = 150 },
    },
    results = {
      { type = "fluid", name = "angels-water-viscous-mud", amount = 150 },
    },
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({ "angels-water-viscous-mud", "water" }),
    order = "a",
  },
  {
    type = "recipe",
    name = "angels-solid-mud-landfill",
    localised_name = { "item-name.landfill" },
    category = "crafting",
    subgroup = "angels-water-washing-filtering",
    energy_required = 5,
    enabled = false,
    auto_recycle = false,
    ingredients = {
      { type = "item", name = "angels-solid-mud", amount = 25 },
    },
    results = {
      { type = "item", name = "landfill", amount = 1 },
    },
    order = "a",
  },
  --WASHING FILTERING
  {
    type = "recipe",
    name = "angels-solid-geodes",
    category = "angels-washing-plant",
    subgroup = "angels-water-washing-filtering",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-heavy-mud", amount = 40 },
      { type = "fluid", name = "water", amount = 25 },
    },
    results = {
      { type = "item", name = "angels-geode-blue", amount = 2, probability = 0.75 },
      { type = "item", name = "angels-geode-cyan", amount = 1, probability = 0.6 },
      { type = "item", name = "angels-geode-lightgreen", amount = 1, probability = 0.6 },
      { type = "item", name = "angels-geode-purple", amount = 1, probability = 0.75 },
      { type = "item", name = "angels-geode-red", amount = 2, probability = 0.75 },
      { type = "item", name = "angels-geode-yellow", amount = 1, probability = 1 },
    },
    icon = "__angelsrefininggraphics__/graphics/icons/geode-blue.png",
    icon_size = 32,
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-water-heavy-mud",
      { r = 1, g = 0, b = 0 },
      "water",
      { r = 0, g = 0, b = 1 },
      { r = 0, g = 1, b = 0 },
      { r = 0, g = 0.5, b = 0.5 },
      { r = 0.5, g = 0, b = 0.5 },
    }), --may need a better custom tint for "rainbow"
    order = "b",
  },
  {
    type = "recipe",
    name = "angels-solid-clay",
    localised_name = { "item-name.angels-solid-clay" },
    category = "angels-washing-plant",
    subgroup = "angels-water-washing-filtering",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-concentrated-mud", amount = 30 },
      { type = "fluid", name = "water", amount = 25 },
    },
    results = {
      { type = "item", name = "angels-solid-clay", amount = 3 },
    },
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      { r = 100 / 255, g = 065 / 255, b = 042 / 255 },
      "angels-water-concentrated-mud",
      "water",
    }),
    order = "c",
  },
  {
    type = "recipe",
    name = "angels-solid-limestone",
    localised_name = { "item-name.angels-solid-limestone" },
    category = "angels-washing-plant",
    subgroup = "angels-water-washing-filtering",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-light-mud", amount = 20 },
      { type = "fluid", name = "water", amount = 25 },
    },
    results = {
      { type = "item", name = "angels-solid-limestone", amount = 3 },
    },
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      { r = 185 / 255, g = 152 / 255, b = 126 / 255 },
      "angels-water-light-mud",
      "water",
    }),
    order = "d",
  },
  {
    type = "recipe",
    name = "angels-solid-sand",
    localised_name = { "item-name.angels-solid-sand" },
    category = "angels-washing-plant",
    subgroup = "angels-water-washing-filtering",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "fluid", name = "angels-water-thin-mud", amount = 10 },
      { type = "fluid", name = "water", amount = 25 },
    },
    results = {
      { type = "item", name = "angels-solid-sand", amount = 5 },
    },
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      { r = 199 / 255, g = 192 / 255, b = 181 / 255 },
      "angels-water-thin-mud",
      "water",
    }),
    order = "e",
  },
})
