if angelsmods.refining then
  --ADD UNLOCK TO BARRELS
  angelsmods.functions.OV.add_prereq("bob-fluid-barreling", "angels-fluid-control")

  --CREATE CONVERTER
  angelsmods.functions.make_converter("sulfuric-acid", "angels-liquid-sulfuric-acid")
  angelsmods.functions.disable_barreling_recipes("sulfuric-acid")
  angelsmods.functions.make_converter("heavy-oil", "angels-liquid-naphtha")
  angelsmods.functions.disable_barreling_recipes("heavy-oil")
  angelsmods.functions.make_converter("light-oil", "angels-liquid-fuel-oil")
  angelsmods.functions.disable_barreling_recipes("light-oil")
  angelsmods.functions.make_converter("petroleum-gas", "angels-gas-methane")
  angelsmods.functions.disable_barreling_recipes("petroleum-gas")
  if bobmods then
    if bobmods.plates then
      angelsmods.functions.make_converter("bob-chlorine", "angels-gas-chlorine")
      angelsmods.functions.disable_barreling_recipes("bob-chlorine")
      angelsmods.functions.make_converter("bob-oxygen", "angels-gas-oxygen")
      angelsmods.functions.disable_barreling_recipes("bob-oxygen")
      angelsmods.functions.make_converter("bob-hydrogen", "angels-gas-hydrogen")
      angelsmods.functions.disable_barreling_recipes("bob-hydrogen")
      angelsmods.functions.make_converter("bob-hydrogen-chloride", "angels-gas-hydrogen-chloride")
      angelsmods.functions.disable_barreling_recipes("bob-hydrogen-chloride")
      angelsmods.functions.make_converter("bob-nitrogen", "angels-gas-nitrogen")
      angelsmods.functions.disable_barreling_recipes("bob-nitrogen")
      angelsmods.functions.make_converter("bob-sulfur-dioxide", "angels-gas-sulfur-dioxide")
      angelsmods.functions.disable_barreling_recipes("bob-sulfur-dioxide")
      angelsmods.functions.make_converter("bob-nitric-acid", "angels-liquid-nitric-acid")
      angelsmods.functions.disable_barreling_recipes("bob-nitric-acid")
      angelsmods.functions.make_converter("bob-nitrogen-dioxide", "angels-gas-nitrogen-dioxide")
      angelsmods.functions.disable_barreling_recipes("bob-nitrogen-dioxide")
      angelsmods.functions.make_converter("bob-liquid-air", "angels-gas-compressed-air")
      angelsmods.functions.disable_barreling_recipes("bob-liquid-air")
      angelsmods.functions.make_converter("bob-ferric-chloride-solution", "angels-liquid-ferric-chloride-solution")
      angelsmods.functions.disable_barreling_recipes("bob-ferric-chloride-solution")
      angelsmods.functions.make_converter("bob-hydrogen-sulfide", "angels-gas-hydrogen-sulfide")
      angelsmods.functions.disable_barreling_recipes("bob-hydrogen-sulfide")
    end
    if data.raw["fluid"]["dinitrogen-tetroxide"] then
      angelsmods.functions.make_converter("bob-ammonia", "angels-gas-ammonia")
      angelsmods.functions.disable_barreling_recipes("bob-ammonia")
      angelsmods.functions.make_converter("bob-nitric-oxide", "angels-gas-nitrogen-monoxide")
      angelsmods.functions.disable_barreling_recipes("bob-nitric-oxide")
      angelsmods.functions.make_converter("bob-dinitrogen-tetroxide", "angels-gas-dinitrogen-tetroxide")
      angelsmods.functions.disable_barreling_recipes("bob-dinitrogen-tetroxide")
      angelsmods.functions.make_converter("bob-hydrazine", "angels-gas-hydrazine")
      angelsmods.functions.disable_barreling_recipes("bob-hydrazine")
    end
  end

  --CREATE BARRELS
  angelsmods.functions.make_void("angels-gas-compressed-air", "chemical")
  angelsmods.functions.make_void("angels-gas-hydrogen", "chemical")
  --angelsmods.functions.make_void("angels-gas-deuterium", "chemical")
  angelsmods.functions.make_void("angels-gas-oxygen", "chemical")
  angelsmods.functions.make_void("angels-gas-carbon-monoxide", "chemical")
  angelsmods.functions.make_void("angels-gas-carbon-dioxide", "chemical")
  angelsmods.functions.make_void("angels-gas-hydrogen-fluoride", "chemical")
  angelsmods.functions.make_void("angels-liquid-hydrofluoric-acid", "chemical")

  angelsmods.functions.make_void("angels-liquid-aqueous-sodium-hydroxide", "water")

  angelsmods.functions.make_void("angels-gas-chlorine", "chemical")
  angelsmods.functions.make_void("angels-gas-hydrogen-chloride", "chemical")
  angelsmods.functions.make_void("angels-liquid-hydrochloric-acid", "chemical")
  angelsmods.functions.make_void("angels-gas-allylchlorid", "chemical")
  angelsmods.functions.make_void("angels-gas-epichlorhydrin", "chemical")
  angelsmods.functions.make_void("angels-gas-chlor-methane", "chemical")
  angelsmods.functions.make_void("angels-liquid-perchloric-acid", "chemical")
  if data.raw.fluid["ferric-chloride-solution"] then
    angelsmods.functions.make_void("ferric-chloride-solution", "chemical")
  end
  angelsmods.functions.make_void("angels-liquid-ferric-chloride-solution", "chemical")
  angelsmods.functions.make_void("angels-liquid-cupric-chloride-solution", "chemical")

  angelsmods.functions.make_void("angels-gas-nitrogen", "chemical")
  angelsmods.functions.make_void("angels-gas-ammonia", "chemical")
  angelsmods.functions.make_void("angels-gas-nitrogen-dioxide", "chemical")
  angelsmods.functions.make_void("angels-gas-dinitrogen-tetroxide", "chemical")
  angelsmods.functions.make_void("angels-gas-nitrogen-monoxide", "chemical")
  angelsmods.functions.make_void("angels-gas-ammonium-chloride", "chemical")
  angelsmods.functions.make_void("angels-gas-urea", "chemical")
  angelsmods.functions.make_void("angels-gas-melamine", "chemical")
  angelsmods.functions.make_void("angels-liquid-nitric-acid", "chemical")
  angelsmods.functions.make_void("angels-gas-monochloramine", "chemical")
  angelsmods.functions.make_void("angels-gas-hydrazine", "chemical")

  angelsmods.functions.make_void("angels-gas-methylamine", "chemical")
  angelsmods.functions.make_void("angels-gas-dimethylamine", "chemical")
  angelsmods.functions.make_void("angels-gas-dimethylhydrazine", "chemical")

  angelsmods.functions.make_void("angels-gas-natural-1", "chemical")
  angelsmods.functions.make_void("angels-liquid-multi-phase-oil", "chemical")
  angelsmods.functions.make_void("crude-oil", "chemical")
  angelsmods.functions.make_void("angels-gas-raw-1", "chemical")
  angelsmods.functions.make_void("angels-liquid-condensates", "chemical")
  angelsmods.functions.make_void("angels-liquid-ngl", "chemical")
  angelsmods.functions.make_void("angels-gas-residual", "chemical")

  angelsmods.functions.make_void("angels-gas-methane", "chemical")
  angelsmods.functions.make_void("angels-gas-ethane", "chemical")
  angelsmods.functions.make_void("angels-gas-butane", "chemical")
  angelsmods.functions.make_void("angels-gas-propene", "chemical")
  angelsmods.functions.make_void("angels-liquid-naphtha", "chemical")
  angelsmods.functions.make_void("angels-liquid-mineral-oil", "chemical")
  angelsmods.functions.make_void("angels-liquid-fuel-oil", "chemical")
  angelsmods.functions.make_void("angels-gas-methanol", "chemical")
  angelsmods.functions.make_void("angels-gas-ethylene", "chemical")
  angelsmods.functions.make_void("angels-gas-benzene", "chemical")

  angelsmods.functions.make_void("angels-gas-synthesis", "chemical")
  angelsmods.functions.make_void("angels-gas-butadiene", "chemical")
  angelsmods.functions.make_void("angels-liquid-phenol", "chemical")
  angelsmods.functions.make_void("angels-liquid-ethylbenzene", "chemical")
  angelsmods.functions.make_void("angels-liquid-styrene", "chemical")
  angelsmods.functions.make_void("angels-gas-formaldehyde", "chemical")
  angelsmods.functions.make_void("angels-liquid-polyethylene", "chemical")
  angelsmods.functions.make_void("angels-liquid-glycerol", "chemical")
  angelsmods.functions.make_void("lubricant", "chemical")
  angelsmods.functions.make_void("angels-gas-acetone", "chemical")
  angelsmods.functions.make_void("angels-liquid-toluene", "chemical")
  angelsmods.functions.make_void("angels-liquid-bisphenol-a", "chemical")

  angelsmods.functions.make_void("angels-gas-acid", "chemical")
  angelsmods.functions.make_void("angels-gas-hydrogen-sulfide", "chemical")
  angelsmods.functions.make_void("angels-gas-sulfur-dioxide", "chemical")
  angelsmods.functions.make_void("angels-liquid-sulfuric-acid", "chemical")
end
