angelsmods.functions.RB.build({
  --ORE PROCESSING MACHINE
  {
    type = "recipe",
    name = "ore-processing-machine",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "orepro-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 2 },
      { type = "item", name = "t2-gears", amount = 2 },
      { type = "item", name = "t2-brick", amount = 4 },
    },
    results = {{ type = "item", name = "ore-processing-machine", amount = 1 }},
  },
  {
    type = "recipe",
    name = "ore-processing-machine-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "orepro-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-gears", amount = 2 },
      { type = "item", name = "t3-brick", amount = 4 },
    },
    results = {{ type = "item", name = "ore-processing-machine-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "ore-processing-machine-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "orepro-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-gears", amount = 2 },
      { type = "item", name = "t4-brick", amount = 4 },
    },
    results = {{ type = "item", name = "ore-processing-machine-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "ore-processing-machine-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "orepro-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 2 },
      { type = "item", name = "t5-gears", amount = 2 },
      { type = "item", name = "t5-brick", amount = 4 },
    },
    results = {{ type = "item", name = "ore-processing-machine-4", amount = 1 }},
  },
  --PELLET PRESS
  {
    type = "recipe",
    name = "pellet-press",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "pelletpre-1", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-gears", amount = 4 },
      { type = "item", name = "t3-brick", amount = 2 },
    },
    results = {{ type = "item", name = "pellet-press", amount = 1 }},
  },
  {
    type = "recipe",
    name = "pellet-press-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "pelletpre-2", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-gears", amount = 4 },
      { type = "item", name = "t4-brick", amount = 2 },
    },
    results = {{ type = "item", name = "pellet-press-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "pellet-press-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "pelletpre-3", amount = 1 },
      { type = "item", name = "t5-plate", amount = 2 },
      { type = "item", name = "t5-gears", amount = 4 },
      { type = "item", name = "t5-brick", amount = 2 },
    },
    results = {{ type = "item", name = "pellet-press-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "pellet-press-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "pelletpre-4", amount = 1 },
      { type = "item", name = "t6-plate", amount = 2 },
      { type = "item", name = "t6-gears", amount = 4 },
      { type = "item", name = "t6-brick", amount = 2 },
    },
    results = {{ type = "item", name = "pellet-press-4", amount = 1 }},
  },
  --POWDER MIXER
  {
    type = "recipe",
    name = "powder-mixer",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "powdermix-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 1 },
      { type = "item", name = "t2-gears", amount = 1 },
      { type = "item", name = "t2-brick", amount = 1 },
    },
    results = {{ type = "item", name = "powder-mixer", amount = 1 }},
  },
  {
    type = "recipe",
    name = "powder-mixer-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "powdermix-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 1 },
      { type = "item", name = "t3-gears", amount = 1 },
      { type = "item", name = "t3-brick", amount = 1 },
    },
    results = {{ type = "item", name = "powder-mixer-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "powder-mixer-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "powdermix-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 1 },
      { type = "item", name = "t4-gears", amount = 1 },
      { type = "item", name = "t4-brick", amount = 1 },
    },
    results = {{ type = "item", name = "powder-mixer-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "powder-mixer-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "powdermix-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 1 },
      { type = "item", name = "t5-gears", amount = 1 },
      { type = "item", name = "t5-brick", amount = 1 },
    },
    results = {{ type = "item", name = "powder-mixer-4", amount = 1 }},
  },
  --BLAST FURNACE
  {
    type = "recipe",
    name = "blast-furnace",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "blastfur-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 4 },
      { type = "item", name = "t0-circuit", amount = 3 },
      { type = "item", name = "t0-brick", amount = 10 },
      { type = "item", name = "t0-pipe", amount = 5 },
    },
    results = {{ type = "item", name = "blast-furnace", amount = 1 }},
  },
  {
    type = "recipe",
    name = "blast-furnace-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "blastfur-2", amount = 1 },
      { type = "item", name = "t1-plate", amount = 4 },
      { type = "item", name = "t1-circuit", amount = 3 },
      { type = "item", name = "t1-brick", amount = 10 },
      { type = "item", name = "t1-pipe", amount = 5 },
    },
    results = {{ type = "item", name = "blast-furnace-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "blast-furnace-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "blastfur-3", amount = 1 },
      { type = "item", name = "t3-plate", amount = 4 },
      { type = "item", name = "t3-circuit", amount = 3 },
      { type = "item", name = "t3-brick", amount = 10 },
      { type = "item", name = "t3-pipe", amount = 5 },
    },
    results = {{ type = "item", name = "blast-furnace-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "blast-furnace-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "blastfur-4", amount = 1 },
      { type = "item", name = "t4-plate", amount = 4 },
      { type = "item", name = "t4-circuit", amount = 3 },
      { type = "item", name = "t4-brick", amount = 10 },
      { type = "item", name = "t4-pipe", amount = 5 },
    },
    results = {{ type = "item", name = "blast-furnace-4", amount = 1 }},
  },
  --CHEMICAL FURNACE
  {
    type = "recipe",
    name = "angels-chemical-furnace",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chemfur-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 2 },
      { type = "item", name = "t1-circuit", amount = 5 },
      { type = "item", name = "t1-brick", amount = 5 },
      { type = "item", name = "t1-pipe", amount = 10 },
    },
    results = {{ type = "item", name = "angels-chemical-furnace", amount = 1 }},
  },
  {
    type = "recipe",
    name = "angels-chemical-furnace-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chemfur-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-circuit", amount = 5 },
      { type = "item", name = "t3-brick", amount = 5 },
      { type = "item", name = "t3-pipe", amount = 10 },
    },
    results = {{ type = "item", name = "angels-chemical-furnace-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "angels-chemical-furnace-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chemfur-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 2 },
      { type = "item", name = "t4-circuit", amount = 5 },
      { type = "item", name = "t4-brick", amount = 5 },
      { type = "item", name = "t4-pipe", amount = 10 },
    },
    results = {{ type = "item", name = "angels-chemical-furnace-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "angels-chemical-furnace-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "chemfur-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 2 },
      { type = "item", name = "t5-circuit", amount = 5 },
      { type = "item", name = "t5-brick", amount = 5 },
      { type = "item", name = "t5-pipe", amount = 10 },
    },
    results = {{ type = "item", name = "angels-chemical-furnace-4", amount = 1 }},
  },
  --INDUCTION FURNACE
  {
    type = "recipe",
    name = "induction-furnace",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "indufur-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 5 },
      { type = "item", name = "t0-circuit", amount = 5 },
      { type = "item", name = "t0-brick", amount = 5 },
      { type = "item", name = "t0-gears", amount = 3 },
      { type = "item", name = "t0-pipe", amount = 4 },
    },
    results = {{ type = "item", name = "induction-furnace", amount = 1 }},
  },
  {
    type = "recipe",
    name = "induction-furnace-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "indufur-2", amount = 1 },
      { type = "item", name = "t1-plate", amount = 5 },
      { type = "item", name = "t1-circuit", amount = 5 },
      { type = "item", name = "t1-brick", amount = 5 },
      { type = "item", name = "t1-gears", amount = 3 },
      { type = "item", name = "t1-pipe", amount = 4 },
    },
    results = {{ type = "item", name = "induction-furnace-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "induction-furnace-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "indufur-3", amount = 1 },
      { type = "item", name = "t3-plate", amount = 5 },
      { type = "item", name = "t3-circuit", amount = 5 },
      { type = "item", name = "t3-brick", amount = 5 },
      { type = "item", name = "t3-gears", amount = 3 },
      { type = "item", name = "t3-pipe", amount = 4 },
    },
    results = {{ type = "item", name = "induction-furnace-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "induction-furnace-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "indufur-4", amount = 1 },
      { type = "item", name = "t4-plate", amount = 5 },
      { type = "item", name = "t4-circuit", amount = 5 },
      { type = "item", name = "t4-brick", amount = 5 },
      { type = "item", name = "t4-gears", amount = 3 },
      { type = "item", name = "t4-pipe", amount = 4 },
    },
    results = {{ type = "item", name = "induction-furnace-4", amount = 1 }},
  },
  --CASTING MACHINE
  {
    type = "recipe",
    name = "casting-machine",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "castingm-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 3 },
      { type = "item", name = "t0-circuit", amount = 1 },
      { type = "item", name = "t0-gears", amount = 1 },
      { type = "item", name = "t0-brick", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 2 },
    },
    results = {{ type = "item", name = "casting-machine", amount = 1 }},
  },
  {
    type = "recipe",
    name = "casting-machine-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "castingm-2", amount = 1 },
      { type = "item", name = "t1-plate", amount = 3 },
      { type = "item", name = "t1-circuit", amount = 1 },
      { type = "item", name = "t1-gears", amount = 1 },
      { type = "item", name = "t1-brick", amount = 1 },
      { type = "item", name = "t1-pipe", amount = 2 },
    },
    results = {{ type = "item", name = "casting-machine-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "casting-machine-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "castingm-3", amount = 1 },
      { type = "item", name = "t3-plate", amount = 3 },
      { type = "item", name = "t3-circuit", amount = 1 },
      { type = "item", name = "t3-gears", amount = 1 },
      { type = "item", name = "t3-brick", amount = 1 },
      { type = "item", name = "t3-pipe", amount = 2 },
    },
    results = {{ type = "item", name = "casting-machine-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "casting-machine-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "castingm-4", amount = 1 },
      { type = "item", name = "t4-plate", amount = 3 },
      { type = "item", name = "t4-circuit", amount = 1 },
      { type = "item", name = "t4-gears", amount = 1 },
      { type = "item", name = "t4-brick", amount = 1 },
      { type = "item", name = "t4-pipe", amount = 2 },
    },
    results = {{ type = "item", name = "casting-machine-4", amount = 1 }},
  },
  --SINTERING OVEN
  {
    type = "recipe",
    name = "sintering-oven",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "sinteringo-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 8 },
      { type = "item", name = "t1-circuit", amount = 5 },
      { type = "item", name = "t1-brick", amount = 9 },
    },
    results = {{ type = "item", name = "sintering-oven", amount = 1 }},
  },
  {
    type = "recipe",
    name = "sintering-oven-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "sinteringo-2", amount = 1 },
      { type = "item", name = "t2-plate", amount = 8 },
      { type = "item", name = "t2-circuit", amount = 5 },
      { type = "item", name = "t2-brick", amount = 9 },
    },
    results = {{ type = "item", name = "sintering-oven-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "sintering-oven-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "sinteringo-3", amount = 1 },
      { type = "item", name = "t3-plate", amount = 8 },
      { type = "item", name = "t3-circuit", amount = 5 },
      { type = "item", name = "t3-brick", amount = 9 },
    },
    results = {{ type = "item", name = "sintering-oven-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "sintering-oven-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "sinteringo-4", amount = 1 },
      { type = "item", name = "t4-plate", amount = 8 },
      { type = "item", name = "t4-circuit", amount = 5 },
      { type = "item", name = "t4-brick", amount = 9 },
    },
    results = {{ type = "item", name = "sintering-oven-4", amount = 1 }},
  },
  {
    type = "recipe",
    name = "sintering-oven-5",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "sinteringo-5", amount = 1 },
      { type = "item", name = "t5-plate", amount = 8 },
      { type = "item", name = "t5-circuit", amount = 5 },
      { type = "item", name = "t5-brick", amount = 9 },
    },
    results = {{ type = "item", name = "sintering-oven-5", amount = 1 }},
  },
  --STRAND CASTING MACHINE
  {
    type = "recipe",
    name = "strand-casting-machine",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "strandcast-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 6 },
      { type = "item", name = "t2-circuit", amount = 3 },
      { type = "item", name = "t2-brick", amount = 3 },
      { type = "item", name = "t2-pipe", amount = 6 },
      { type = "item", name = "t2-gears", amount = 4 },
    },
    results = {{ type = "item", name = "strand-casting-machine", amount = 1 }},
  },
  {
    type = "recipe",
    name = "strand-casting-machine-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "strandcast-2", amount = 1 },
      { type = "item", name = "t3-plate", amount = 6 },
      { type = "item", name = "t3-circuit", amount = 3 },
      { type = "item", name = "t3-brick", amount = 3 },
      { type = "item", name = "t3-pipe", amount = 6 },
      { type = "item", name = "t3-gears", amount = 4 },
    },
    results = {{ type = "item", name = "strand-casting-machine-2", amount = 1 }},
  },
  {
    type = "recipe",
    name = "strand-casting-machine-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "strandcast-3", amount = 1 },
      { type = "item", name = "t4-plate", amount = 6 },
      { type = "item", name = "t4-circuit", amount = 3 },
      { type = "item", name = "t4-brick", amount = 3 },
      { type = "item", name = "t4-pipe", amount = 6 },
      { type = "item", name = "t4-gears", amount = 4 },
    },
    results = {{ type = "item", name = "strand-casting-machine-3", amount = 1 }},
  },
  {
    type = "recipe",
    name = "strand-casting-machine-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "strandcast-4", amount = 1 },
      { type = "item", name = "t5-plate", amount = 6 },
      { type = "item", name = "t5-circuit", amount = 3 },
      { type = "item", name = "t5-brick", amount = 3 },
      { type = "item", name = "t5-pipe", amount = 6 },
      { type = "item", name = "t5-gears", amount = 4 },
    },
    results = {{ type = "item", name = "strand-casting-machine-4", amount = 1 }},
  },
  --COOLING TOWER
  {
    type = "recipe",
    name = "cooling-tower",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "coolingt-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 10 },
      { type = "item", name = "t2-circuit", amount = 5 },
      { type = "item", name = "t2-pipe", amount = 5 },
      { type = "item", name = "t2-brick", amount = 10 },
    },
    results = {{ type = "item", name = "cooling-tower", amount = 1 }},
  },
})
