data:extend({
  -- SPLINTER
  {
    type = "recipe",
    name = "angels-crystal-splinter-cutting",
    category = "crafting",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-raw", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-splinter-blue-cut", amount = 1 },
      { type = "item", name = "angels-crystal-splinter-red-cut", amount = 1 },
      { type = "item", name = "angels-crystal-splinter-green-cut", amount = 1 },
      { type = "item", name = "angels-crystal-powder", amount = 1 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-raw.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-blue.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -12, 12 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-red.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -0, 12 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-green.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 12, 12 },
      },
    },
    order = "b[splitting]",
  },
  {
    type = "recipe",
    name = "angels-crystal-splinter-blue",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-blue-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-splinter-blue", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-splinter-blue",
    order = "c[polishing]-a[blue]",
  },
  {
    type = "recipe",
    name = "angels-crystal-splinter-red",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-red-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-splinter-red", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-splinter-red",
    order = "c[polishing]-b[red]",
  },
  {
    type = "recipe",
    name = "angels-crystal-splinter-green",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-green-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-splinter-green", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-splinter-green",
    order = "c[polishing]-c[green]",
  },
  {
    type = "recipe",
    name = "angels-crystal-splinter-harmonic",
    category = "crafting",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-blue", amount = 1 },
      { type = "item", name = "angels-crystal-splinter-red", amount = 1 },
      { type = "item", name = "angels-crystal-splinter-green", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-splinter-harmonic", amount = 1 },
    },
    always_show_products = true,
    main_product = "angels-crystal-splinter-harmonic",
    order = "d[harmonizing]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-splinter-blue",
    localised_name = { "recipe-name.angels-crystal-powder-from-splinter" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-blue-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 5 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-blue.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-a[blue]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-splinter-red",
    localised_name = { "recipe-name.angels-crystal-powder-from-splinter" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-red-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 5 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-red.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-b[red]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-splinter-green",
    localised_name = { "recipe-name.angels-crystal-powder-from-splinter" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-splinter-green-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 5 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-green.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-c[green]",
  },
  -- SHARD
  {
    type = "recipe",
    name = "angels-crystal-shard-cutting",
    category = "crafting",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-raw", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-shard-blue-cut", amount = 1 },
      { type = "item", name = "angels-crystal-shard-red-cut", amount = 1 },
      { type = "item", name = "angels-crystal-shard-green-cut", amount = 1 },
      { type = "item", name = "angels-crystal-powder", amount = 1 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-raw.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-blue.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -12, 12 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-red.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -0, 12 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-green.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 12, 12 },
      },
    },
    order = "b[splitting]",
  },
  {
    type = "recipe",
    name = "angels-crystal-shard-blue",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-blue-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-shard-blue", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-shard-blue",
    order = "c[polishing]-a[blue]",
  },
  {
    type = "recipe",
    name = "angels-crystal-shard-red",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-red-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-shard-red", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-shard-red",
    order = "c[polishing]-b[red]",
  },
  {
    type = "recipe",
    name = "angels-crystal-shard-green",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-green-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-shard-green", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-shard-green",
    order = "c[polishing]-c[green]",
  },
  {
    type = "recipe",
    name = "angels-crystal-shard-harmonic",
    category = "crafting",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-blue", amount = 1 },
      { type = "item", name = "angels-crystal-shard-red", amount = 1 },
      { type = "item", name = "angels-crystal-shard-green", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-shard-harmonic", amount = 1 },
    },
    always_show_products = true,
    main_product = "angels-crystal-shard-harmonic",
    order = "d[harmonizing]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-shard-blue",
    localised_name = { "recipe-name.angels-crystal-powder-from-shard" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-blue-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 10 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-blue.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-a[blue]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-shard-red",
    localised_name = { "recipe-name.angels-crystal-powder-from-shard" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-red-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 10 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-red.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-b[red]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-shard-green",
    localised_name = { "recipe-name.angels-crystal-powder-from-shard" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-shard-green-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 10 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-green.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-c[green]",
  },
  -- FULL
  {
    type = "recipe",
    name = "angels-crystal-full-cutting",
    category = "crafting",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-raw", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-full-blue-cut", amount = 1 },
      { type = "item", name = "angels-crystal-full-red-cut", amount = 1 },
      { type = "item", name = "angels-crystal-full-green-cut", amount = 1 },
      { type = "item", name = "angels-crystal-powder", amount = 1 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-raw.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-blue.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -12, 12 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-red.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -0, 12 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-green.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 12, 12 },
      },
    },
    order = "b[splitting]",
  },
  {
    type = "recipe",
    name = "angels-crystal-full-blue",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-blue-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-full-blue", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-full-blue",
    order = "c[polishing]-a[blue]",
  },
  {
    type = "recipe",
    name = "angels-crystal-full-red",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-red-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-full-red", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-full-red",
    order = "c[polishing]-b[red]",
  },
  {
    type = "recipe",
    name = "angels-crystal-full-green",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-green-cut", amount = 1 },
      { type = "item", name = "angels-crystal-grindstone", amount = 1, ignored_by_stats = 1 },
      { type = "fluid", name = "angels-crystal-slurry", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-crystal-full-green", amount = 1 },
      {
        type = "item",
        name = "angels-crystal-grindstone",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 2 / 3,
      },
    },
    main_product = "angels-crystal-full-green",
    order = "c[polishing]-c[green]",
  },
  {
    type = "recipe",
    name = "angels-crystal-full-harmonic",
    category = "crafting",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-blue", amount = 1 },
      { type = "item", name = "angels-crystal-full-red", amount = 1 },
      { type = "item", name = "angels-crystal-full-green", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-full-harmonic", amount = 1 },
    },
    always_show_products = true,
    main_product = "angels-crystal-full-harmonic",
    order = "d[harmonizing]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-full-blue",
    localised_name = { "recipe-name.angels-crystal-powder-from-full" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-blue-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 15 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-blue.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-a[blue]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-full-red",
    localised_name = { "recipe-name.angels-crystal-powder-from-full" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-red-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 15 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-red.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-b[red]",
  },
  {
    type = "recipe",
    name = "angels-crystal-powder-full-green",
    localised_name = { "recipe-name.angels-crystal-powder-from-full" },
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-biter-processing-crystal-full",
    enabled = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-crystal-full-green-cut", amount = 5 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-powder", amount = 15 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    allow_decomposition = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-green.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    order = "e[powderizing]-c[green]",
  },
})
