data:extend({
  {
    type = "recipe",
    name = "angels-bio-alien-processed-meat",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-biter-butchery",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "fluid", name = "angels-alien-goo", amount = 2 },
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 1 },
    },
    always_show_products = true,
    main_product = "angels-bio-alien-processed-meat",
    order = "d[meat]",
  },
  ---------------------------------------------------------------------------
  -- EGGSPERIMINTS ----------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-biter-small-egg",
    localised_name = { "recipe-name.angels-biter-small-egg" },
    category = "advanced-crafting",
    subgroup = "angels-bio-biter-egg",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-crystal-seed", amount = 1 },
      { type = "item", name = "angels-crystal-dust", amount = 1 },
      { type = "item", name = "angels-bio-puffer-egg-3", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-biter-small-egg", amount = 1 },
    },
    always_show_products = true,
    main_product = "angels-biter-small-egg",
    order = "a[small]-a[experiment]",
  },
  {
    type = "recipe",
    name = "angels-biter-medium-egg",
    localised_name = { "recipe-name.angels-biter-medium-egg" },
    category = "advanced-crafting",
    subgroup = "angels-bio-biter-egg",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-crystal-seed", amount = 1 },
      { type = "item", name = "angels-crystal-enhancer", amount = 1 },
      { type = "item", name = "angels-crystal-splinter-raw", amount = 1 },
      { type = "item", name = "angels-bio-puffer-egg-4", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-biter-medium-egg", amount = 1 },
    },
    always_show_products = true,
    main_product = "angels-biter-medium-egg",
    order = "b[medium]-a[experiment]",
  },
  {
    type = "recipe",
    name = "angels-biter-big-egg",
    localised_name = { "recipe-name.angels-biter-big-egg" },
    category = "advanced-crafting",
    subgroup = "angels-bio-biter-egg",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-crystal-seed", amount = 1 },
      { type = "item", name = "angels-crystal-enhancer", amount = 1 },
      { type = "item", name = "angels-crystal-shard-raw", amount = 1 },
      { type = "item", name = "angels-bio-puffer-egg-5", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-biter-big-egg", amount = 1 },
    },
    always_show_products = true,
    main_product = "angels-biter-big-egg",
    order = "c[big]-a[experiment]",
  },
  ---------------------------------------------------------------------------
  -- BREEDING ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-biter-small-breeding",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-biter-queen-small", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-biter-queen-small", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-biter-queen-small",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 0.99,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-biter-small-egg", amount = 1 },
      {
        type = "item",
        name = "angels-biter-small-egg",
        amount = 1,
        probability = 0.5,
        show_details_in_recipe_tooltip = false,
      },
    },
    allow_productivity = true,
    always_show_products = true,
    main_product = "angels-biter-small-egg",
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
        tint = { r = 0.75, g = 0.75, b = 0.75 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-small.png",
        icon_size = 32,
        tint = { r = 1, g = 1, b = 1, a = 0.75 },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-crown.png",
        icon_size = 15,
        scale = 0.4,
        shift = { 7.3, -9.5 },
      },
    },
    order = "a[small]-b[breeding]",
  },
  {
    type = "recipe",
    name = "angels-biter-medium-breeding",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-biter-queen-medium", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 40 },
    },
    results = {
      { type = "item", name = "angels-biter-queen-medium", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-biter-queen-medium",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 0.99,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-biter-medium-egg", amount = 1 },
      {
        type = "item",
        name = "angels-biter-medium-egg",
        amount = 1,
        probability = 0.5,
        show_details_in_recipe_tooltip = false,
      },
    },
    allow_productivity = true,
    always_show_products = true,
    main_product = "angels-biter-medium-egg",
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-medium.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-crown.png",
        icon_size = 15,
        scale = 0.45,
        shift = { 8, -11 },
      },
    },
    order = "b[medium]-b[breeding]",
  },
  {
    type = "recipe",
    name = "angels-biter-big-breeding",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-biter-queen-big", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 60 },
    },
    results = {
      { type = "item", name = "angels-biter-queen-big", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-biter-queen-big",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 0.99,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-biter-big-egg", amount = 1 },
      { type = "item", name = "angels-biter-big-egg", amount = 1, probability = 0.5, show_details_in_recipe_tooltip = false },
    },
    allow_productivity = true,
    always_show_products = true,
    main_product = "angels-biter-big-egg",
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-big.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-crown.png",
        icon_size = 15,
        scale = 0.5,
        shift = { 9, -12 },
      },
    },
    order = "c[big]-b[breeding]",
  },
  ---------------------------------------------------------------------------
  -- HATCHERY ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-biter-small",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter-egg",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-biter-small-egg", amount = 1 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 1 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-biter-small", amount = 1, probability = 0.95 },
      { type = "item", name = "angels-biter-queen-small", amount = 1, probability = 0.05 },
    },
    main_product = "angels-biter-small",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/egg-small.png",
    icon_size = 32,
    order = "a[small]-b[hatching]",
  },
  {
    type = "recipe",
    name = "angels-biter-medium",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter-egg",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-biter-medium-egg", amount = 1 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 1 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-biter-medium", amount = 1, probability = 0.975 },
      { type = "item", name = "angels-biter-queen-medium", amount = 1, probability = 0.025 },
    },
    main_product = "angels-biter-medium",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/egg-medium.png",
    icon_size = 32,
    order = "b[medium]-b[hatching]",
  },
  {
    type = "recipe",
    name = "angels-biter-big",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter-egg",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-biter-big-egg", amount = 1 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 1 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 30 },
    },
    results = {
      { type = "item", name = "angels-biter-big", amount = 1, probability = 0.99 },
      { type = "item", name = "angels-biter-queen-big", amount = 1, probability = 0.01 },
    },
    main_product = "angels-biter-big",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/egg-large.png",
    icon_size = 32,
    order = "c[big]-b[hatching]",
  },
  ---------------------------------------------------------------------------
  -- ZOO KEEPING ------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-biter-small-keeping",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-biter-small", amount = 4, ignored_by_stats = 4 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-biter-small", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-biter-small",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 0.9,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-crystal-splinter-raw", amount = 4 },
    },
    main_product = "angels-crystal-splinter-raw",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-small.png",
    icon_size = 32,
    order = "a[small]-a[keeping]",
  },
  {
    type = "recipe",
    name = "angels-biter-medium-keeping",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-biter-medium", amount = 4, ignored_by_stats = 4 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 3 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 40 },
    },
    results = {
      { type = "item", name = "angels-biter-medium", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-biter-medium",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 0.85,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-crystal-shard-raw", amount = 4 },
    },
    main_product = "angels-crystal-shard-raw",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-medium.png",
    icon_size = 32,
    order = "b[medium]-a[keeping]",
  },
  {
    type = "recipe",
    name = "angels-biter-big-keeping",
    category = "angels-bio-refugium-biter",
    subgroup = "angels-bio-biter",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-biter-big", amount = 4, ignored_by_stats = 4 },
      { type = "item", name = "angels-bio-alien-processed-meat", amount = 4 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 60 },
    },
    results = {
      { type = "item", name = "angels-biter-big", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-biter-big",
        amount = 1,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        probability = 0.75,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-crystal-full-raw", amount = 4 },
    },
    main_product = "angels-crystal-full-raw",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/biter-big.png",
    icon_size = 32,
    order = "c[big]-a[keeping]",
  },
  ---------------------------------------------------------------------------
  -- BUTCHERY ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-biter-queen-small-butchering",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-biter-queen-small" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-biter-butchery",
    enabled = false,
    energy_required = 45,
    ingredients = {
      { type = "item", name = "angels-biter-queen-small", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount_min = 1, amount_max = 2 },
      { type = "item", name = "angels-crystal-splinter-raw", amount = 1, probability = 0.9 },
      {
        type = "item",
        name = "angels-crystal-splinter-raw",
        amount = 1,
        probability = 0.45,
        show_details_in_recipe_tooltip = false,
      },
    },
    main_product = "angels-bio-raw-meat",
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-biter-queen-small" },
      "angels-bio-raw-meat"
    ),
    order = "a[small]-b[queen]",
  },
  {
    type = "recipe",
    name = "angels-biter-small-butchering",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-biter-small" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-biter-butchery",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-biter-small", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
      { type = "item", name = "angels-crystal-splinter-raw", amount = 1, probability = 0.9 },
    },
    main_product = "angels-bio-raw-meat",
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-biter-small" },
      "angels-bio-raw-meat"
    ),
    order = "a[small]-a[normal]",
  },
  {
    type = "recipe",
    name = "angels-biter-queen-medium-butchering",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-biter-queen-medium" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-biter-butchery",
    enabled = false,
    energy_required = 45,
    ingredients = {
      { type = "item", name = "angels-biter-queen-medium", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount_min = 1, amount_max = 2 },
      { type = "item", name = "angels-crystal-shard-raw", amount = 1, probability = 0.7 },
      {
        type = "item",
        name = "angels-crystal-shard-raw",
        amount = 1,
        probability = 0.35,
        show_details_in_recipe_tooltip = false,
      },
    },
    main_product = "angels-bio-raw-meat",
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-biter-queen-medium" },
      "angels-bio-raw-meat"
    ),
    order = "b[medium]-b[queen]",
  },
  {
    type = "recipe",
    name = "angels-biter-medium-butchering",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-biter-medium" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-biter-butchery",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-biter-medium", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
      { type = "item", name = "angels-crystal-shard-raw", amount = 1, probability = 0.7 },
    },
    main_product = "angels-bio-raw-meat",
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-biter-medium" },
      "angels-bio-raw-meat"
    ),
    order = "b[medium]-a[normal]",
  },
  {
    type = "recipe",
    name = "angels-biter-queen-big-butchering",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-biter-queen-big" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-biter-butchery",
    enabled = false,
    energy_required = 45,
    ingredients = {
      { type = "item", name = "angels-biter-queen-big", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount_min = 1, amount_max = 2 },
      { type = "item", name = "angels-crystal-full-raw", amount = 1, probability = 0.5 },
      {
        type = "item",
        name = "angels-crystal-full-raw",
        amount = 1,
        probability = 0.25,
        show_details_in_recipe_tooltip = false,
      },
    },
    main_product = "angels-bio-raw-meat",
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-biter-queen-big" },
      "angels-bio-raw-meat"
    ),
    order = "c[big]-b[queen]",
  },
  {
    type = "recipe",
    name = "angels-biter-big-butchering",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-biter-big" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-biter-butchery",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-biter-big", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
      { type = "item", name = "angels-crystal-full-raw", amount = 1, probability = 0.5 },
    },
    main_product = "angels-bio-raw-meat",
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-biter-big" },
      "angels-bio-raw-meat"
    ),
    order = "c[big]-a[normal]",
  },
})
