angelsmods.functions.RB.build({
  {
    type = "recipe",
    name = "angels-temperate-upgrade",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-token-bio", amount = 5 },
      { type = "item", name = "t2-circuit", amount = 1 },
      { type = "item", name = "t2-brick", amount = 1 },
      { type = "item", name = "t2-pipe", amount = 1 },
    },
    results = { { type = "item", name = "angels-temperate-upgrade", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-desert-upgrade",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-token-bio", amount = 5 },
      { type = "item", name = "t2-circuit", amount = 1 },
      { type = "item", name = "t2-brick", amount = 2 },
    },
    results = { { type = "item", name = "angels-desert-upgrade", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-swamp-upgrade",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-token-bio", amount = 5 },
      { type = "item", name = "t2-circuit", amount = 1 },
      { type = "item", name = "t2-pipe", amount = 2 },
    },
    results = { { type = "item", name = "angels-swamp-upgrade", amount = 1 } },
  },
  --ALGAE FARM
  {
    type = "recipe",
    name = "angels-algae-farm",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "algaefarm-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 6 },
      { type = "item", name = "t0-circuit", amount = 2 },
      { type = "item", name = "t0-brick", amount = 6 },
      { type = "item", name = "t0-pipe", amount = 9 },
    },
    results = { { type = "item", name = "angels-algae-farm", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-algae-farm-2",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "algaefarm-2", amount = 1 },
      { type = "item", name = "t0-plate", amount = 11 },
      { type = "item", name = "t0-circuit", amount = 4 },
      { type = "item", name = "t0-brick", amount = 11 },
      { type = "item", name = "t0-pipe", amount = 18 },
    },
    results = { { type = "item", name = "angels-algae-farm-2", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-algae-farm-3",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "algaefarm-3", amount = 1 },
      { type = "item", name = "t2-plate", amount = 11 },
      { type = "item", name = "t2-circuit", amount = 4 },
      { type = "item", name = "t2-brick", amount = 11 },
      { type = "item", name = "t2-pipe", amount = 18 },
    },
    results = { { type = "item", name = "angels-algae-farm-3", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-algae-farm-4",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "algaefarm-4", amount = 1 },
      { type = "item", name = "t3-plate", amount = 11 },
      { type = "item", name = "t3-circuit", amount = 4 },
      { type = "item", name = "t3-brick", amount = 11 },
      { type = "item", name = "t3-pipe", amount = 18 },
    },
    results = { { type = "item", name = "angels-algae-farm-4", amount = 1 } },
  },
  --CROP FARM
  {
    type = "recipe",
    name = "angels-crop-farm",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cropfarm-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 8 },
      { type = "item", name = "t1-circuit", amount = 2 },
      { type = "item", name = "t1-brick", amount = 9 },
      { type = "item", name = "t1-pipe", amount = 3 },
    },
    results = { { type = "item", name = "angels-crop-farm", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-temperate-farm",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cropfarm-2", amount = 1 },
      { type = "item", name = "angels-temperate-upgrade", amount = 1 },
      { type = "item", name = "t3-plate", amount = 8 },
      { type = "item", name = "t3-circuit", amount = 2 },
      { type = "item", name = "t3-brick", amount = 9 },
      { type = "item", name = "t3-pipe", amount = 3 },
    },
    results = { { type = "item", name = "angels-temperate-farm", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-desert-farm",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cropfarm-2", amount = 1 },
      { type = "item", name = "angels-desert-upgrade", amount = 1 },
      { type = "item", name = "t3-plate", amount = 8 },
      { type = "item", name = "t3-circuit", amount = 2 },
      { type = "item", name = "t3-brick", amount = 9 },
      { type = "item", name = "t3-pipe", amount = 3 },
    },
    results = { { type = "item", name = "angels-desert-farm", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-swamp-farm",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "cropfarm-2", amount = 1 },
      { type = "item", name = "angels-swamp-upgrade", amount = 1 },
      { type = "item", name = "t3-plate", amount = 8 },
      { type = "item", name = "t3-circuit", amount = 2 },
      { type = "item", name = "t3-brick", amount = 9 },
      { type = "item", name = "t3-pipe", amount = 3 },
    },
    results = { { type = "item", name = "angels-swamp-farm", amount = 1 } },
  },
  --COMPOSTER
  {
    type = "recipe",
    name = "angels-composter",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "compo-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 2 },
      { type = "item", name = "t0-circuit", amount = 2 },
      { type = "item", name = "t0-brick", amount = 2 },
      { type = "item", name = "t0-gears", amount = 2 },
    },
    results = { { type = "item", name = "angels-composter", amount = 1 } },
  },
  --SEED EXTRACTOR
  {
    type = "recipe",
    name = "angels-seed-extractor",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "seedex-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 1 },
      { type = "item", name = "t1-circuit", amount = 4 },
      { type = "item", name = "t1-brick", amount = 1 },
      { type = "item", name = "t1-gears", amount = 2 },
    },
    results = { { type = "item", name = "angels-seed-extractor", amount = 1 } },
  },
  --PRESS
  {
    type = "recipe",
    name = "angels-bio-press",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "biopress-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 2 },
      { type = "item", name = "t2-circuit", amount = 2 },
      { type = "item", name = "t2-brick", amount = 1 },
      { type = "item", name = "t2-pipe", amount = 1 },
      { type = "item", name = "t2-gears", amount = 2 },
    },
    results = { { type = "item", name = "angels-bio-press", amount = 1 } },
  },
  --PROCESSOR
  {
    type = "recipe",
    name = "angels-bio-processor",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "biopro-1", amount = 1 },
      { type = "item", name = "t1-plate", amount = 5 },
      { type = "item", name = "t1-circuit", amount = 8 },
      { type = "item", name = "t1-brick", amount = 5 },
      { type = "item", name = "t1-gears", amount = 4 },
    },
    results = { { type = "item", name = "angels-bio-processor", amount = 1 } },
  },
  --NUTRIENT EXTRACTOR
  {
    type = "recipe",
    name = "angels-nutrient-extractor",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "nutrientex-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 1 },
      { type = "item", name = "t2-circuit", amount = 2 },
      { type = "item", name = "t2-brick", amount = 1 },
      { type = "item", name = "t2-pipe", amount = 2 },
      { type = "item", name = "t2-gears", amount = 2 },
    },
    results = { { type = "item", name = "angels-nutrient-extractor", amount = 1 } },
  },
  --ABORETUM
  {
    type = "recipe",
    name = "angels-bio-generator-temperate-1",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-temperate-tree", amount = 1 },
      { type = "item", name = "t0-plate", amount = 2 },
      { type = "item", name = "t0-circuit", amount = 2 },
      { type = "item", name = "t0-brick", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 3 },
    },
    results = { { type = "item", name = "angels-bio-generator-temperate-1", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-bio-generator-swamp-1",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-swamp-tree", amount = 1 },
      { type = "item", name = "t0-plate", amount = 2 },
      { type = "item", name = "t0-circuit", amount = 2 },
      { type = "item", name = "t0-brick", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 3 },
    },
    results = { { type = "item", name = "angels-bio-generator-swamp-1", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-bio-generator-desert-1",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "angels-desert-tree", amount = 1 },
      { type = "item", name = "t0-plate", amount = 2 },
      { type = "item", name = "t0-circuit", amount = 2 },
      { type = "item", name = "t0-brick", amount = 1 },
      { type = "item", name = "t0-pipe", amount = 3 },
    },
    results = { { type = "item", name = "angels-bio-generator-desert-1", amount = 1 } },
  },
  --ARBORETUM
  {
    type = "recipe",
    name = "angels-bio-arboretum-1",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "arboretum-1", amount = 1 },
      { type = "item", name = "t0-plate", amount = 6 },
      { type = "item", name = "t0-circuit", amount = 2 },
      { type = "item", name = "t0-brick", amount = 6 },
      { type = "item", name = "t0-pipe", amount = 8 },
    },
    results = { { type = "item", name = "angels-bio-arboretum-1", amount = 1 } },
  },
  --REFUGIUM
  {
    type = "recipe",
    name = "angels-bio-refugium-puffer",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "puffer-1", amount = 1 },
      { type = "item", name = "t3-plate", amount = 4 },
      { type = "item", name = "t3-circuit", amount = 4 },
      { type = "item", name = "t3-brick", amount = 3 },
      { type = "item", name = "t3-pipe", amount = 11 },
    },
    results = { { type = "item", name = "angels-bio-refugium-puffer", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-bio-refugium-fish",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "fish-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 2 },
      { type = "item", name = "t2-circuit", amount = 5 },
      { type = "item", name = "t2-brick", amount = 4 },
      { type = "item", name = "t2-pipe", amount = 25 },
    },
    results = { { type = "item", name = "angels-bio-refugium-fish", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-bio-refugium-biter",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "biter-1", amount = 1 },
      { type = "item", name = "t4-plate", amount = 10 },
      { type = "item", name = "t4-circuit", amount = 4 },
      { type = "item", name = "t4-brick", amount = 19 },
      { type = "item", name = "t4-pipe", amount = 11 },
    },
    results = { { type = "item", name = "angels-bio-refugium-biter", amount = 1 } },
  },
  --PROCESSING
  {
    type = "recipe",
    name = "angels-bio-hatchery",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "hatch-1", amount = 1 },
      { type = "item", name = "t3-plate", amount = 2 },
      { type = "item", name = "t3-circuit", amount = 4 },
      { type = "item", name = "t3-brick", amount = 2 },
    },
    results = { { type = "item", name = "angels-bio-hatchery", amount = 1 } },
  },
  {
    type = "recipe",
    name = "angels-bio-butchery",
    energy_required = 5,
    enabled = false,
    ingredients = {
      { type = "item", name = "butch-1", amount = 1 },
      { type = "item", name = "t2-plate", amount = 3 },
      { type = "item", name = "t2-circuit", amount = 1 },
      { type = "item", name = "t2-brick", amount = 2 },
      { type = "item", name = "t2-gears", amount = 2 },
    },
    results = { { type = "item", name = "angels-bio-butchery", amount = 1 } },
  },
})
