local AF = angelsmods.functions
data:extend({
  {
    type = "recipe",
    name = "angels-cellulose-fiber-raw-wood",
    category = "crafting",
    subgroup = "angels-bio-processing-wood",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "wood", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-cellulose-fiber", amount = 4 },
    },
    always_show_products = true,
    show_amount_in_title = false,
    icon = "__angelsbioprocessinggraphics__/graphics/icons/cellulose-fiber-raw-wood.png",
    icon_size = 32,
    order = "b",
  },
  {
    type = "recipe",
    name = "angels-wood-pellets",
    category = "crafting",
    subgroup = "angels-bio-processing-wood",
    enabled = false,
    hide_from_signal_gui = true,
    energy_required = 4,
    ingredients = {
      { type = "item", name = "angels-cellulose-fiber", amount = 12 },
    },
    results = {
      { type = "item", name = "angels-wood-pellets", amount = 2 },
    },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/wood-pellets.png",
    icon_size = 32,
    order = "c",
  },
  {
    type = "recipe",
    name = "angels-wood-bricks",
    category = "crafting",
    subgroup = "angels-bio-processing-wood",
    enabled = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-wood-pellets", amount = 8 },
    },
    results = {
      { type = "item", name = "angels-wood-bricks", amount = 4 },
    },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/wood-bricks.png",
    icon_size = 32,
    order = "d",
  },
  {
    type = "recipe",
    name = "angels-gas-carbon-dioxide-from-wood",
    category = "angels-liquifying",
    subgroup = "angels-bio-processing-wood",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-wood-pellets", amount = 1 },
    },
    results = {
      { type = "fluid", name = "angels-gas-carbon-dioxide", amount = 70 },
    },
    always_show_products = true,
    show_amount_in_title = false,
    icons = AF.create_gas_recipe_icon({
      { "__angelspetrochemgraphics__/graphics/icons/molecules/carbon-dioxide.png", 72 },
    }, "COcOc"),
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-gas-carbon-dioxide",
      { r = 225 / 255, g = 160 / 255, b = 106 / 255 },
      "angels-gas-carbon-dioxide",
      { r = 225 / 255, g = 160 / 255, b = 106 / 255 },
    }),
    order = "e",
  },
  {
    type = "recipe",
    name = "angels-wood-charcoal",
    category = "smelting",
    subgroup = "angels-bio-processing-wood",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-wood-pellets", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-wood-charcoal", amount = 3 },
    },
    icon_size = 32,
    order = "f",
  },
  {
    type = "recipe",
    name = "angels-carbon-from-charcoal",
    localised_name = { "item-name.angels-solid-carbon" },
    category = "angels-liquifying",
    subgroup = "angels-bio-processing-wood",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-wood-charcoal", amount = 1 },
      { type = "fluid", name = "angels-gas-oxygen", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-solid-carbon", amount = 2 },
    },
    icon_size = 32,
    crafting_machine_tint = AF.get_recipe_tints({
      AF.fluid_color("Cb"),
      "angels-gas-oxygen",
      AF.fluid_color("C"),
      "angels-gas-oxygen",
    }),
    order = "g",
  },
  --PULP
  --T1
  {
    type = "recipe",
    name = "angels-solid-wood-pulp",
    category = "angels-liquifying",
    subgroup = "angels-bio-paper",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 20,
    ingredients = {
      { type = "item", name = "angels-cellulose-fiber", amount = 20 },
      { type = "item", name = "angels-solid-alginic-acid", amount = 5 },
      { type = "fluid", name = "water", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-solid-wood-pulp", amount = 20 },
    },
    icons = AF.add_number_icon_layer(
      AF.get_object_icons("angels-solid-wood-pulp"),
      1,
      angelsmods.bioprocessing.number_tint
    ),
    crafting_machine_tint = AF.get_recipe_tints({
      "water",
    }),
    order = "aa",
  },
  --T2 SULFITE PROCESS
  {
    type = "recipe",
    name = "angels-liquid-pulping-liquor",
    category = "angels-advanced-chemistry",
    subgroup = "angels-bio-liquor",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "fluid", name = "angels-gas-sulfur-dioxide", amount = 100 },
      { type = "fluid", name = "angels-gas-oxygen", amount = 40 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-pulping-liquor", amount = 100 },
    },
    main_product = "angels-liquid-pulping-liquor",
    always_show_products = true,
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-liquid-pulping-liquor",
      "angels-gas-sulfur-dioxide",
      "water",
      "angels-gas-oxygen",
    }),
    order = "ba",
  },
  {
    type = "recipe",
    name = "angels-brown-liquor-recovery",
    category = "angels-liquifying",
    subgroup = "angels-bio-liquor",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 4,
    ingredients = {
      { type = "fluid", name = "angels-liquid-brown-liquor", amount = 50 },
      { type = "item", name = "angels-solid-sodium-hydroxide", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-solid-sodium-sulfate", amount = 1 },
      { type = "fluid", name = "angels-water-red-waste", amount = 50 },
    },
    icons = {
      {
        icon = "__angelspetrochemgraphics__/graphics/icons/solid-sodium-sulfate.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/liquid-brown-liquor.png",
        icon_size = 32,
        scale = 0.4375,
        shift = { -10, -10 },
      },
    },
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-water-red-waste",
      "angels-liquid-brown-liquor",
      AF.fluid_color("NaSO3"),
      AF.fluid_color("NaOH"),
    }),
    order = "bb",
  },
  {
    type = "recipe",
    name = "angels-sulfite-pulping",
    category = "angels-advanced-chemistry",
    subgroup = "angels-bio-paper",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 6,
    ingredients = {
      { type = "item", name = "angels-cellulose-fiber", amount = 20 },
      { type = "fluid", name = "angels-liquid-pulping-liquor", amount = 75 },
      { type = "fluid", name = "angels-gas-ammonia", amount = 25 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-solid-wood-pulp", amount = 25 },
      { type = "fluid", name = "angels-liquid-brown-liquor", amount = 75 },
    },
    icons = AF.add_number_icon_layer(
      AF.get_object_icons("angels-solid-wood-pulp"),
      2,
      angelsmods.bioprocessing.number_tint
    ),
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-liquid-brown-liquor",
      "angels-liquid-pulping-liquor",
      "angels-gas-ammonia",
      "water",
    }),
    order = "ab",
  },
  --T3 KRAFT PROCESS (SULFATE PROCESS)
  {
    type = "recipe",
    name = "angels-liquid-white-liquor",
    category = "angels-liquifying",
    subgroup = "angels-bio-liquor",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-solid-sodium-hydroxide", amount = 2 },
      { type = "item", name = "angels-solid-sodium-sulfate", amount = 2 },
      { type = "fluid", name = "water", amount = 40 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-white-liquor", amount = 40 },
    },
    main_product = "angels-liquid-white-liquor",
    always_show_products = true,
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-liquid-white-liquor",
      "water",
      AF.fluid_color("Na2SO3"),
      AF.fluid_color("NaOH"),
    }),
    order = "caa",
  },
  {
    type = "recipe",
    name = "angels-liquid-green-liquor",
    localised_name = { "recipe-name.angels-kraft-recovery" },
    category = "angels-liquifying",
    subgroup = "angels-bio-liquor",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 4,
    ingredients = {
      { type = "fluid", name = "angels-liquid-black-liquor", amount = 40 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-green-liquor", amount = 40 }, --+energy gain
    },
    main_product = "angels-liquid-green-liquor",
    always_show_products = true,
    show_amount_in_title = false,
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-liquid-green-liquor",
      "angels-liquid-black-liquor",
      "angels-liquid-green-liquor",
      "angels-liquid-black-liquor",
    }),
    order = "cb",
  },
  {
    type = "recipe",
    name = "angels-kraft-causting",
    category = "chemistry",
    subgroup = "angels-bio-liquor",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 6,
    ingredients = {
      { type = "fluid", name = "angels-liquid-green-liquor", amount = 60 },
      { type = "fluid", name = "water", amount = 60 },
      { type = "item", name = "angels-solid-lime", amount = 4 },
    },
    results = {
      { type = "fluid", name = "angels-liquid-white-liquor", amount = 55 },
      { type = "item", name = "angels-solid-limestone", amount = 4 },
    },
    main_product = "angels-liquid-white-liquor",
    always_show_products = true,
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-liquid-white-liquor",
      "water",
      AF.fluid_color("Na2SO3"),
      AF.fluid_color("NaOH"),
    }),
    order = "cab",
  },
  {
    type = "recipe",
    name = "angels-kraft-cooking-washing",
    category = "angels-liquifying",
    subgroup = "angels-bio-paper",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 6,
    ingredients = {
      { type = "item", name = "angels-cellulose-fiber", amount = 20 },
      { type = "fluid", name = "angels-liquid-white-liquor", amount = 40 },
    },
    results = {
      { type = "item", name = "angels-solid-wood-pulp", amount = 40 },
      { type = "fluid", name = "angels-liquid-black-liquor", amount_min = 35, amount_max = 40 },
    },
    always_show_products = true,
    icons = AF.add_number_icon_layer(
      AF.get_object_icons("angels-solid-wood-pulp"),
      3,
      angelsmods.bioprocessing.number_tint
    ),
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-liquid-black-liquor",
      "angels-liquid-white-liquor",
      "angels-liquid-black-liquor",
      "angels-liquid-white-liquor",
    }),
    order = "ac",
  },
  --PAPER BLEACHING
  {
    type = "recipe",
    name = "angels-solid-paper",
    localised_name = { "recipe-name.angels-solid-paper" },
    category = "crafting",
    subgroup = "angels-bio-paper",
    enabled = false,
    hide_from_signal_gui = true,
    energy_required = 8,
    ingredients = {
      { type = "item", name = "angels-solid-wood-pulp", amount = 4 },
    },
    results = {
      { type = "item", name = "angels-solid-paper", amount = 3 },
    },
    always_show_products = true,
    show_amount_in_title = false,
    allow_decomposition = false,
    icons = AF.add_number_icon_layer(
      AF.get_object_icons("angels-solid-paper"),
      1,
      angelsmods.bioprocessing.number_tint
    ),
    order = "ba",
  },
  {
    type = "recipe",
    name = "angels-solid-paper-2",
    category = "angels-liquifying",
    subgroup = "angels-bio-paper",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-solid-wood-pulp", amount = 2 },
      { type = "item", name = "angels-solid-sodium-hydroxide", amount = 2 },
      { type = "fluid", name = "angels-gas-chlorine", amount = 80 },
    },
    results = {
      { type = "item", name = "angels-solid-paper", amount = 2 },
      { type = "item", name = "angels-solid-sodium-hypochlorite", amount = 2 },
    },
    allow_decomposition = false,
    icons = AF.add_number_icon_layer(
      AF.get_object_icons("angels-solid-paper"),
      2,
      angelsmods.bioprocessing.number_tint
    ),
    crafting_machine_tint = AF.get_recipe_tints({
      AF.fluid_color("NaOCl"),
      "angels-gas-chlorine",
      AF.fluid_color("NaOH"),
      { r = 1, g = 1, b = 1, a = 1 },--[[paper]]
    }),
    order = "bb",
  },
  -- SOLID SOIDUM HYPOCHLORITE DECOMPOSITION
  {
    type = "recipe",
    name = "angels-solid-sodium-hypochlorite-decomposition",
    category = "angels-chemical-smelting",
    subgroup = "angels-petrochem-sodium",
    energy_required = 2,
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    ingredients = {
      { type = "item", name = "angels-solid-sodium-hypochlorite", amount = 10 },
    },
    results = {
      { type = "item", name = "angels-solid-salt", amount = 20 },
      { type = "fluid", name = "angels-gas-oxygen", amount = 100 },
    },
    main_product = "angels-solid-salt",
    icons = angelsmods.functions.create_solid_recipe_icon({ "angels-solid-sodium-hypochlorite" }, "angels-solid-salt"),
    icon_size = 32,
    crafting_machine_tint = AF.get_recipe_tints({ "angels-gas-oxygen", AF.fluid_color("NaOCl") }),
    order = "g[solid-sodium-hypochlorite-decomposition]",
  },
  {
    type = "recipe",
    name = "angels-solid-paper-3",
    category = "chemistry",
    subgroup = "angels-bio-paper",
    enabled = false,
    auto_recycle = false,
    hide_from_signal_gui = true,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-solid-wood-pulp", amount = 2 },
      { type = "item", name = "angels-solid-sodium-hydroxide", amount = 2 },
      { type = "fluid", name = "angels-gas-sulfur-dioxide", amount = 40 },
      { type = "fluid", name = "water", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-solid-paper", amount = 5 },
      { type = "item", name = "angels-solid-sodium-carbonate", amount = 2 },
      { type = "fluid", name = "angels-gas-oxygen", amount = 40 },
      { type = "fluid", name = "angels-water-yellow-waste", amount = 100 },
    },
    allow_decomposition = false,
    icons = AF.add_number_icon_layer(
      AF.get_object_icons("angels-solid-paper"),
      3,
      angelsmods.bioprocessing.number_tint
    ),
    crafting_machine_tint = AF.get_recipe_tints({
      "angels-water-yellow-waste",
      "water",
      "angels-gas-oxygen",
      "angels-gas-sulfur-dioxide",
    }),
    order = "bc",
  },
})
