data:extend({
  {
    type = "recipe",
    name = "angels-gas-puffer-atmosphere",
    category = "angels-advanced-chemistry",
    subgroup = "angels-bio-puffer-1",
    enabled = false,
    energy_required = 30,
    ingredients = {
      { type = "fluid", name = "angels-gas-sulfur-dioxide", amount = 20 },
      { type = "fluid", name = "angels-gas-hydrogen-fluoride", amount = 10 },
      { type = "fluid", name = "angels-gas-oxygen", amount = 10 },
    },
    results = {
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 60 },
    },
    main_product = "angels-gas-puffer-atmosphere",
    always_show_products = true,
    icons = angelsmods.functions.create_gas_recipe_icon(
      nil,
      { { 194, 227, 091 }, { 184, 239, 000 }, { 156, 207, 000 } }
    ),
    crafting_machine_tint = angelsmods.functions.get_recipe_tints({
      "angels-gas-puffer-atmosphere",
      "angels-gas-sulfur-dioxide",
      "angels-gas-oxygen",
      "angels-gas-hydrogen-fluoride",
    }),
    order = "b",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-egg-shell-powder",
    category = "angels-ore-refining-t1-5",
    subgroup = "angels-bio-puffer-egg",
    enabled = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-egg-shell", amount = 2 },
      { type = "item", name = "angels-milling-drum-lubricated", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-egg-shell-powder", amount = 2 },
      { type = "item", name = "angels-milling-drum", amount = 1, ignored_by_stats = 1, ignored_by_productivity = 1 },
    },
    main_product = "angels-bio-puffer-egg-shell-powder",
    icon_size = 32,
    order = "f",
  },
  ---------------------------------------------------------------------------
  -- PUFFING MK1 ------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-puffer-puffing-1",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-1",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 4, ignored_by_stats = 4 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-gas-compressed-air", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-1", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.95,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 220, ignored_by_productivity = 20 },
    },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
    icon_size = 32,
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-2",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-1",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-2", amount = 4, ignored_by_stats = 4 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-gas-ammonia", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-2", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-bio-puffer-2",
        amount = 1,
        probability = 0.95,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-raw-1", amount = 200 },
    },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-2-icon.png",
    icon_size = 32,
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-3",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-1",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-3", amount = 4, ignored_by_stats = 4 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-gas-carbon-monoxide", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-3", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-bio-puffer-3",
        amount = 1,
        probability = 0.95,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-urea", amount = 200 },
    },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-3-icon.png",
    icon_size = 32,
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-4",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-1",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-4", amount = 4, ignored_by_stats = 4 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-gas-sulfur-dioxide", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-4", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-bio-puffer-4",
        amount = 1,
        probability = 0.95,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-synthesis", amount = 200 },
    },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-4-icon.png",
    icon_size = 32,
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-5",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-1",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-5", amount = 4, ignored_by_stats = 4 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-gas-hydrogen-chloride", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-5", amount = 3, ignored_by_productivity = 3, ignored_by_stats = 3 },
      {
        type = "item",
        name = "angels-bio-puffer-5",
        amount = 1,
        probability = 0.95,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-hydrazine", amount = 200 },
    },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-5-icon.png",
    icon_size = 32,
    order = "ae",
  },
  ---------------------------------------------------------------------------
  -- PUFFING MK2 ------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-puffer-puffing-23",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-2",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-2", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-puffer-3", amount = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-gas-acid", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-2", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-2",
        amount = 1,
        probability = 0.98,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-3", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-3",
        amount = 1,
        probability = 0.99,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "fluid",
        name = "angels-gas-acid",
        amount = 20,
        ignored_by_productivity = 20,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 100 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/empty_icon.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-2-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-3-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-12",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-2",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-puffer-2", amount = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-water-yellow-waste", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.98,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-2", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-2",
        amount = 1,
        probability = 0.99,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-hydrogen-sulfide", amount = 100 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/empty_icon.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-2-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-13",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-2",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-puffer-3", amount = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-water-red-waste", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.98,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-3", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-3",
        amount = 1,
        probability = 0.99,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-ammonia", amount = 100 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/empty_icon.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-3-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-14",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-2",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-puffer-4", amount = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-water-greenyellow-waste", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.98,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-4", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-4",
        amount = 1,
        probability = 0.99,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-hydrogen-fluoride", amount = 100 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/empty_icon.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-4-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-puffer-puffing-15",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-2",
    enabled = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-bio-puffer-5", amount = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
      { type = "fluid", name = "angels-water-green-waste", amount = 100 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.98,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-5", amount = 1, ignored_by_productivity = 1, ignored_by_stats = 1 },
      {
        type = "item",
        name = "angels-bio-puffer-5",
        amount = 1,
        probability = 0.99,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "fluid", name = "angels-gas-hydrogen-chloride", amount = 100 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/empty_icon.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-5-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ae",
  },
  ---------------------------------------------------------------------------
  -- BREEDING MK1 -----------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-bio-puffer-egg-1",
    localised_name = { "recipe-name.angels-bio-puffer-egg-1" },
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-1",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-solid-beans", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-1", amount = 2, ignored_by_productivity = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "item", name = "angels-bio-puffer-egg-1", amount = 1, probability = 0.75 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-2",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-3",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-4",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-5",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
    },
    main_product = "angels-bio-puffer-egg-1",
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
      },
    },
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-egg-2",
    localised_name = { "recipe-name.angels-bio-puffer-egg-2" },
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-1",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-2", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-solid-leafs", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-2", amount = 2, ignored_by_productivity = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-1",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-egg-2", amount = 1, probability = 0.75 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-3",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-4",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-5",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
    },
    main_product = "angels-bio-puffer-egg-2",
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-2-icon.png",
        icon_size = 32,
      },
    },
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-egg-3",
    localised_name = { "recipe-name.angels-bio-puffer-egg-3" },
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-1",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-3", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-solid-nuts", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-3", amount = 2, ignored_by_productivity = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-1",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-2",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-egg-3", amount = 1, probability = 0.7 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-4",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-5",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
    },
    main_product = "angels-bio-puffer-egg-3",
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-3-icon.png",
        icon_size = 32,
      },
    },
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-egg-4",
    localised_name = { "recipe-name.angels-bio-puffer-egg-4" },
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-1",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-4", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-solid-pips", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-4", amount = 2, ignored_by_productivity = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-1",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-2",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-3",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-egg-4", amount = 1, probability = 0.7 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-5",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
    },
    main_product =  "angels-bio-puffer-egg-4",
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-4-icon.png",
        icon_size = 32,
      },
    },
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-egg-5",
    localised_name = { "recipe-name.angels-bio-puffer-egg-5" },
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-1",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-5", amount = 2, ignored_by_stats = 2 },
      { type = "item", name = "angels-solid-fruit", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-5", amount = 2, ignored_by_productivity = 2, ignored_by_stats = 2 },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      {
        type = "item",
        name = "angels-bio-puffer-egg-1",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-2",
        amount = 1,
        probability = 0.1,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-3",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      {
        type = "item",
        name = "angels-bio-puffer-egg-4",
        amount = 1,
        probability = 0.05,
        show_details_in_recipe_tooltip = false,
      },
      { type = "item", name = "angels-bio-puffer-egg-5", amount = 1, probability = 0.7 },
    },
    main_product = "angels-bio-puffer-egg-5",
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-5-icon.png",
        icon_size = 32,
      },
    },
    order = "ae",
  },
  ---------------------------------------------------------------------------
  -- BREEDING MK2 -----------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-puffer-breeding-23",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-2",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-2", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-bio-puffer-3", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-fruit", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      {
        type = "item",
        name = "angels-bio-puffer-2",
        amount = 1,
        probability = 0.95,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      {
        type = "item",
        name = "angels-bio-puffer-3",
        amount = 1,
        probability = 0.90,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "item", name = "angels-bio-puffer-egg-1", amount = 1 },
    },
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-2-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-3-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-puffer-breeding-12",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-2",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-bio-puffer-2", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-pips", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.90,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      {
        type = "item",
        name = "angels-bio-puffer-2",
        amount = 1,
        probability = 0.85,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "item", name = "angels-bio-puffer-egg-2", amount = 1 },
    },
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-2-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-puffer-breeding-13",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-2",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-bio-puffer-3", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-beans", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.85,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      {
        type = "item",
        name = "angels-bio-puffer-3",
        amount = 1,
        probability = 0.80,
        ignored_by_productivity = 1,
        ignored_by_stats = 11,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "item", name = "angels-bio-puffer-egg-3", amount = 1 },
    },
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-3-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-puffer-breeding-14",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-2",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-bio-puffer-4", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-corn", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.80,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      {
        type = "item",
        name = "angels-bio-puffer-4",
        amount = 1,
        probability = 0.75,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "item", name = "angels-bio-puffer-egg-4", amount = 1 },
    },
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-4-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-puffer-breeding-15",
    category = "angels-bio-refugium-puffer",
    subgroup = "angels-bio-puffer-breeding-2",
    enabled = false,
    energy_required = 60,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-bio-puffer-5", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-leafs", amount = 5 },
      { type = "fluid", name = "angels-liquid-nutrient-pulp", amount = 20 },
      { type = "fluid", name = "angels-gas-puffer-atmosphere", amount = 20 },
    },
    results = {
      {
        type = "item",
        name = "angels-bio-puffer-1",
        amount = 1,
        probability = 0.75,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      {
        type = "item",
        name = "angels-bio-puffer-5",
        amount = 1,
        probability = 0.70,
        ignored_by_productivity = 1,
        ignored_by_stats = 1,
      },
      { type = "fluid", name = "angels-gas-acid", amount = 20, ignored_by_productivity = 20 },
      { type = "item", name = "angels-bio-puffer-egg-5", amount = 1 },
    },
    allow_productivity = true,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/breeding.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-icon.png",
        icon_size = 32,
        shift = { -5, 5 },
        scale = 0.75,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-5-icon.png",
        icon_size = 32,
        shift = { 5, -5 },
        scale = 0.75,
      },
    },
    order = "ae",
  },
  ---------------------------------------------------------------------------
  -- HATCHERY ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-bio-puffer-1",
    localised_name = { "recipe-name.angels-bio-puffer-1" },
    category = "angels-bio-hatchery",
    subgroup = "angels-bio-puffer-egg",
    enabled = false,
    hidden = false,
    energy_required = 10,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-egg-1", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-egg-shell", amount = 1 },
      { type = "item", name = "angels-bio-puffer-1", amount = 1, probability = 0.95 },
      { type = "item", name = "angels-bio-puffer-2", amount = 1, probability = 0.05, show_details_in_recipe_tooltip = false },
    },
    main_product = "angels-bio-puffer-1",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-1-egg.png",
    icon_size = 32,
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-2",
    localised_name = { "recipe-name.angels-bio-puffer-2" },
    category = "angels-bio-hatchery",
    subgroup = "angels-bio-puffer-egg",
    enabled = false,
    hidden = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-egg-2", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-egg-shell", amount = 1 },
      { type = "item", name = "angels-bio-puffer-2", amount = 1, probability = 0.8 },
      { type = "item", name = "angels-bio-puffer-1", amount = 1, probability = 0.2, show_details_in_recipe_tooltip = false },
    },
    main_product = "angels-bio-puffer-2",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-2-egg.png",
    icon_size = 32,
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-3",
    localised_name = { "recipe-name.angels-bio-puffer-3" },
    category = "angels-bio-hatchery",
    subgroup = "angels-bio-puffer-egg",
    enabled = false,
    hidden = false,
    energy_required = 20,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-egg-3", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-egg-shell", amount = 1 },
      { type = "item", name = "angels-bio-puffer-3", amount = 1, probability = 0.7 },
      { type = "item", name = "angels-bio-puffer-1", amount = 1, probability = 0.3, show_details_in_recipe_tooltip = false },
    },
    main_product = "angels-bio-puffer-3",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-3-egg.png",
    icon_size = 32,
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-4",
    localised_name = { "recipe-name.angels-bio-puffer-4" },
    category = "angels-bio-hatchery",
    subgroup = "angels-bio-puffer-egg",
    enabled = false,
    hidden = false,
    energy_required = 25,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-egg-4", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-egg-shell", amount = 1 },
      { type = "item", name = "angels-bio-puffer-4", amount = 1, probability = 0.6 },
      { type = "item", name = "angels-bio-puffer-1", amount = 1, probability = 0.4, show_details_in_recipe_tooltip = false },
    },
    main_product = "angels-bio-puffer-4",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-4-egg.png",
    icon_size = 32,
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-bio-puffer-5",
    localised_name = { "recipe-name.angels-bio-puffer-5" },
    category = "angels-bio-hatchery",
    subgroup = "angels-bio-puffer-egg",
    enabled = false,
    hidden = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-egg-5", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-puffer-egg-shell", amount = 1 },
      { type = "item", name = "angels-bio-puffer-5", amount = 1, probability = 0.5 },
      { type = "item", name = "angels-bio-puffer-1", amount = 1, probability = 0.5, show_details_in_recipe_tooltip = false },
    },
    main_product = "angels-bio-puffer-5",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/puffer-5-egg.png",
    icon_size = 32,
    order = "ae",
  },
  ---------------------------------------------------------------------------
  -- BUTCHERY ---------------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-puffer-butchery-1",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-bio-puffer-1" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-puffer-butchery",
    enabled = false,
    hidden = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-1", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
    },
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-bio-puffer-1" },
      "angels-bio-raw-meat"
    ),
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-puffer-butchery-2",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-bio-puffer-2" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-puffer-butchery",
    enabled = false,
    hidden = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-2", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
    },
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-bio-puffer-2" },
      "angels-bio-raw-meat"
    ),
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-puffer-butchery-3",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-bio-puffer-3" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-puffer-butchery",
    enabled = false,
    hidden = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-3", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
    },
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-bio-puffer-3" },
      "angels-bio-raw-meat"
    ),
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-puffer-butchery-4",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-bio-puffer-4" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-puffer-butchery",
    enabled = false,
    hidden = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-4", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
    },
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-bio-puffer-4" },
      "angels-bio-raw-meat"
    ),
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-puffer-butchery-5",
    localised_name = { "recipe-name.angels-butchering", { "item-name.angels-bio-puffer-5" }  },
    category = "angels-bio-butchery",
    subgroup = "angels-bio-puffer-butchery",
    enabled = false,
    hidden = false,
    energy_required = 15,
    ingredients = {
      { type = "item", name = "angels-bio-puffer-5", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-bio-raw-meat", amount = 1 },
    },
    icons = angelsmods.functions.create_solid_recipe_icon(
      { "angels-bio-puffer-5" },
      "angels-bio-raw-meat"
    ),
    order = "ae",
  },
  ---------------------------------------------------------------------------
  -- CRYSTALIZATION ---------------------------------------------------------
  ---------------------------------------------------------------------------
  {
    type = "recipe",
    name = "angels-crystal-shard-crystalization-1",
    localised_name = { "item-name.angels-crystal-shard-raw" },
    category = "angels-crystallizing-2",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    hidden = false,
    energy_required = 8,
    ingredients = {
      { type = "fluid", name = "angels-liquid-polluted-fish-atmosphere", amount = 50 },
      { type = "item", name = "angels-egg-shell-seed", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-shard-raw", amount = 1, probability = 0.4 },
    },
    always_show_products = true,
    icons = angelsmods.functions.add_number_icon_layer(
      angelsmods.functions.get_object_icons("angels-crystal-shard-raw"),
      1,
      angelsmods.bioprocessing.number_tint
    ),
    order = "a[crystalization]-a",
  },
  {
    type = "recipe",
    name = "angels-crystal-shard-crystalization-2",
    localised_name = { "item-name.angels-crystal-shard-raw" },
    category = "angels-crystallizing-2",
    subgroup = "angels-bio-biter-processing-crystal-shard",
    enabled = false,
    hidden = false,
    energy_required = 8,
    ingredients = {
      { type = "fluid", name = "angels-liquid-polluted-fish-atmosphere", amount = 50 },
      { type = "item", name = "angels-egg-shell-seed", amount = 1 },
      { type = "item", name = "angels-crystal-enhancer", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-crystal-shard-raw", amount = 1 },
    },
    always_show_products = true,
    icons = angelsmods.functions.add_number_icon_layer(
      angelsmods.functions.get_object_icons("angels-crystal-shard-raw"),
      2,
      angelsmods.bioprocessing.number_tint
    ),
    order = "a[crystalization]-b",
  },
})
