data:extend({
  -- TEMPERATE VEGETABLES
  {
    type = "recipe",
    name = "angels-temperate-1",
    category = "angels-temperate-farming",
    subgroup = "angels-farming-temperate",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-temperate-1-seed", amount = 5 },
      { type = "item", name = "angels-solid-soil", amount = 5 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-temperate-1", amount_min = 40, amount_max = 60 },
    },
    always_show_products = true,
    allow_productivity = true,
    main_product = "angels-temperate-1",
    icon_size = 32,
    order = "aa",
    crafting_machine_tint = {
      primary = { r = 222 / 255, g = 209 / 255, b = 95 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-temperate-2",
    category = "angels-temperate-farming",
    subgroup = "angels-farming-temperate",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-temperate-2-seed", amount = 5 },
      { type = "item", name = "angels-solid-soil", amount = 5 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-temperate-2", amount_min = 40, amount_max = 60 },
    },
    always_show_products = true,
    main_product = "angels-temperate-2",
    allow_productivity = true,
    icon_size = 32,
    order = "ab",
    crafting_machine_tint = {
      primary = { r = 190 / 255, g = 190 / 255, b = 190 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-temperate-3",
    category = "angels-temperate-farming",
    subgroup = "angels-farming-temperate",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-temperate-3-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-soil", amount = 5 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-temperate-3", amount_min = 40, amount_max = 60 },
      { type = "item", name = "angels-temperate-3-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-temperate-3",
    allow_productivity = true,
    icon_size = 32,
    order = "ac",
    crafting_machine_tint = {
      primary = { r = 65 / 255, g = 83 / 255, b = 39 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-temperate-4",
    category = "angels-advanced-temperate-farming",
    subgroup = "angels-farming-temperate",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-temperate-4-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-soil", amount = 5 },
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-temperate-4", amount_min = 40, amount_max = 60 },
      { type = "item", name = "angels-temperate-4-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-temperate-4",
    allow_productivity = true,
    icon_size = 32,
    order = "ad",
    crafting_machine_tint = {
      primary = { r = 63 / 255, g = 101 / 255, b = 4 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-temperate-5",
    category = "angels-advanced-temperate-farming",
    subgroup = "angels-farming-temperate",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-temperate-5-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-soil", amount = 5 },
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
      { type = "fluid", name = "water", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-temperate-5", amount_min = 40, amount_max = 60 },
      { type = "item", name = "angels-temperate-5-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-temperate-5",
    allow_productivity = true,
    icon_size = 32,
    order = "ae",
    crafting_machine_tint = {
      primary = { r = 109 / 255, g = 173 / 255, b = 74 / 255, a = 1 },
    },
  },
  -- TEMPERATE SEEDS
  {
    type = "recipe",
    name = "angels-temperate-1-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-temperate-1", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-temperate-1-seed", amount_min = 5, amount_max = 6 },
    },
    icon_size = 32,
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-temperate-2-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-temperate-2", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-temperate-2-seed", amount_min = 5, amount_max = 6 },
    },
    icon_size = 32,
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-temperate-3-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-temperate-3-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      {
        type = "item",
        name = "angels-temperate-3-seed",
        amount = 5,
        ignored_by_productivity = 5,
        ignored_by_stats = 5,
      },
      { type = "item", name = "angels-temperate-3-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-temperate-3-seed",
    icon_size = 32,
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-temperate-4-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-temperate-4-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      {
        type = "item",
        name = "angels-temperate-4-seed",
        amount = 5,
        ignored_by_productivity = 5,
        ignored_by_stats = 5,
      },
      { type = "item", name = "angels-temperate-4-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-temperate-4-seed",
    icon_size = 32,
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-temperate-5-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-temperate-5-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      {
        type = "item",
        name = "angels-temperate-5-seed",
        amount = 5,
        ignored_by_productivity = 5,
        ignored_by_stats = 5,
      },
      { type = "item", name = "angels-temperate-5-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-temperate-5-seed",
    icon_size = 32,
    order = "ae",
  },
  -- DESERT VEGETABLES
  {
    type = "recipe",
    name = "angels-desert-1",
    category = "angels-desert-farming",
    subgroup = "angels-farming-desert",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-desert-1-seed", amount = 5 },
      { type = "item", name = "angels-solid-sand", amount = 10 },
      { type = "fluid", name = "angels-water-saline", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-desert-1", amount_min = 30, amount_max = 40 },
    },
    always_show_products = true,
    main_product = "angels-desert-1",
    allow_productivity = true,
    icon_size = 32,
    order = "aa",
    crafting_machine_tint = {
      primary = { r = 240 / 255, g = 157 / 255, b = 14 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-desert-2",
    category = "angels-desert-farming",
    subgroup = "angels-farming-desert",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-desert-2-seed", amount = 5 },
      { type = "item", name = "angels-solid-sand", amount = 10 },
      { type = "fluid", name = "angels-water-saline", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-desert-2", amount_min = 30, amount_max = 40 },
    },
    always_show_products = true,
    main_product = "angels-desert-2",
    allow_productivity = true,
    icon_size = 32,
    order = "ab",
    crafting_machine_tint = {
      primary = { r = 79 / 255, g = 39 / 255, b = 34 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-desert-3",
    category = "angels-desert-farming",
    subgroup = "angels-farming-desert",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-desert-3-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-sand", amount = 10 },
      { type = "fluid", name = "angels-water-saline", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-desert-3", amount_min = 30, amount_max = 40 },
      { type = "item", name = "angels-desert-3-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-desert-3",
    allow_productivity = true,
    icon_size = 32,
    order = "ac",
    crafting_machine_tint = {
      primary = { r = 130 / 255, g = 106 / 255, b = 49 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-desert-4",
    category = "angels-advanced-desert-farming",
    subgroup = "angels-farming-desert",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-desert-4-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-sand", amount = 10 },
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
      { type = "fluid", name = "angels-water-saline", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-desert-4", amount_min = 30, amount_max = 40 },
      { type = "item", name = "angels-desert-4-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-desert-4",
    allow_productivity = true,
    icon_size = 32,
    order = "ad",
    crafting_machine_tint = {
      primary = { r = 212 / 255, g = 95 / 255, b = 0 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-desert-5",
    category = "angels-advanced-desert-farming",
    subgroup = "angels-farming-desert",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-desert-5-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-sand", amount = 10 },
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
      { type = "fluid", name = "angels-water-saline", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-desert-5", amount_min = 30, amount_max = 40 },
      { type = "item", name = "angels-desert-5-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-desert-5",
    allow_productivity = true,
    icon_size = 32,
    order = "ae",
    crafting_machine_tint = {
      primary = { r = 194 / 255, g = 135 / 255, b = 0 / 255, a = 1 },
    },
  },
  -- DESERT SEEDS
  {
    type = "recipe",
    name = "angels-desert-1-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-desert-1", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-desert-1-seed", amount_min = 5, amount_max = 6 },
    },
    icon_size = 32,
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-desert-2-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-desert-2", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-desert-2-seed", amount_min = 5, amount_max = 6 },
    },
    icon_size = 32,
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-desert-3-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-desert-3-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      { type = "item", name = "angels-desert-3-seed", amount = 5, ignored_by_productivity = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-desert-3-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-desert-3-seed",
    icon_size = 32,
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-desert-4-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-desert-4-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      { type = "item", name = "angels-desert-4-seed", amount = 5, ignored_by_productivity = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-desert-4-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-desert-4-seed",
    icon_size = 32,
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-desert-5-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-desert-5-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      { type = "item", name = "angels-desert-5-seed", amount = 5, ignored_by_productivity = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-desert-5-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-desert-5-seed",
    icon_size = 32,
    order = "ae",
  },
  --SWAMP VEGETABLES
  {
    type = "recipe",
    name = "angels-swamp-1",
    category = "angels-swamp-farming",
    subgroup = "angels-farming-swamp",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-swamp-1-seed", amount = 5 },
      { type = "item", name = "angels-solid-mud", amount = 10 },
      { type = "fluid", name = "angels-water-viscous-mud", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-swamp-1", amount_min = 40, amount_max = 50 },
    },
    always_show_products = true,
    main_product = "angels-swamp-1",
    allow_productivity = true,
    icon_size = 32,
    order = "aa",
    crafting_machine_tint = {
      primary = { r = 106 / 255, g = 45 / 255, b = 36 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-swamp-2",
    category = "angels-swamp-farming",
    subgroup = "angels-farming-swamp",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-swamp-2-seed", amount = 5 },
      { type = "item", name = "angels-solid-mud", amount = 10 },
      { type = "fluid", name = "angels-water-heavy-mud", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-swamp-2", amount_min = 40, amount_max = 50 },
    },
    always_show_products = true,
    main_product = "angels-swamp-2",
    allow_productivity = true,
    icon_size = 32,
    order = "ab",
    crafting_machine_tint = {
      primary = { r = 53 / 255, g = 71 / 255, b = 19 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-swamp-3",
    category = "angels-swamp-farming",
    subgroup = "angels-farming-swamp",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-swamp-3-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-mud", amount = 10 },
      { type = "fluid", name = "angels-water-concentrated-mud", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-swamp-3", amount_min = 40, amount_max = 50 },
      { type = "item", name = "angels-swamp-3-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-swamp-3",
    allow_productivity = true,
    icon_size = 32,
    order = "ac",
    crafting_machine_tint = {
      primary = { r = 80 / 255, g = 98 / 255, b = 47 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-swamp-4",
    category = "angels-advanced-swamp-farming",
    subgroup = "angels-farming-swamp",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-swamp-4-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-mud", amount = 10 },
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
      { type = "fluid", name = "angels-water-light-mud", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-swamp-4", amount_min = 40, amount_max = 50 },
      { type = "item", name = "angels-swamp-4-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-swamp-4",
    allow_productivity = true,
    icon_size = 32,
    order = "ad",
    crafting_machine_tint = {
      primary = { r = 119 / 255, g = 79 / 255, b = 63 / 255, a = 1 },
    },
  },
  {
    type = "recipe",
    name = "angels-swamp-5",
    category = "angels-advanced-swamp-farming",
    subgroup = "angels-farming-swamp",
    enabled = false,
    auto_recycle = false,
    energy_required = 30,
    ingredients = {
      { type = "item", name = "angels-swamp-5-seed", amount = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-solid-mud", amount = 10 },
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
      { type = "fluid", name = "angels-water-thin-mud", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-swamp-5", amount_min = 40, amount_max = 50 },
      { type = "item", name = "angels-swamp-5-seed-dormant", amount = 5, ignored_by_productivity = 5 },
    },
    main_product = "angels-swamp-5",
    allow_productivity = true,
    icon_size = 32,
    order = "ae",
    crafting_machine_tint = {
      primary = { r = 104 / 255, g = 85 / 255, b = 146 / 255, a = 1 },
    },
  },
  --SWAMP SEEDS
  {
    type = "recipe",
    name = "angels-swamp-1-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-swamp-1", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-swamp-1-seed", amount_min = 5, amount_max = 6 },
    },
    icon_size = 32,
    order = "aa",
  },
  {
    type = "recipe",
    name = "angels-swamp-2-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-swamp-2", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-swamp-2-seed", amount_min = 5, amount_max = 6 },
    },
    icon_size = 32,
    order = "ab",
  },
  {
    type = "recipe",
    name = "angels-swamp-3-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-swamp-3-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      { type = "item", name = "angels-swamp-3-seed", amount = 5, ignored_by_productivity = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-swamp-3-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-swamp-3-seed",
    icon_size = 32,
    order = "ac",
  },
  {
    type = "recipe",
    name = "angels-swamp-4-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-swamp-4-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      { type = "item", name = "angels-swamp-4-seed", amount = 5, ignored_by_productivity = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-swamp-4-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-swamp-4-seed",
    icon_size = 32,
    order = "ad",
  },
  {
    type = "recipe",
    name = "angels-swamp-5-seed",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 0.5,
    ingredients = {
      { type = "item", name = "angels-swamp-5-seed-dormant", amount = 5, ignored_by_stats = 5 },
    },
    results = {
      { type = "item", name = "angels-swamp-5-seed", amount = 5, ignored_by_productivity = 5, ignored_by_stats = 5 },
      { type = "item", name = "angels-swamp-5-seed", amount = 1, probability = 0.05 },
    },
    main_product = "angels-swamp-5-seed",
    icon_size = 32,
    order = "ae",
  },
})
