local seed_icon_shift = 12

data:extend({
  --TEMPERATE
  {
    type = "recipe",
    name = "angels-temperate-garden-cultivating-a",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-gardens",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-temperate-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-token-bio", amount = 32 },
    },
    main_product = "angels-token-bio",
    always_show_products = true,
    show_amount_in_title = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bb",
  },
  {
    type = "recipe",
    name = "angels-temperate-garden",
    category = "angels-temperate-farming",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 60,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-temperate-garden", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-alienated-fertilizer", amount = 2 },
      { type = "item", name = "angels-token-bio", amount = 30 },
      { type = "fluid", name = "angels-water-mineralized", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-temperate-garden", amount = 2, ignored_by_productivity = 1, ignored_by_stats = 1 },
    },
    main_product = "angels-temperate-garden",
    allow_productivity = true,
    always_show_products = true,
    show_amount_in_title = false,
    order = "ba",
  },
  {
    type = "recipe",
    name = "angels-temperate-garden-a",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-temperate-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-token-bio", amount = 16 },
      { type = "item", name = "angels-temperate-1-seed", amount = 5, probability = 0.4 },
      { type = "item", name = "angels-temperate-2-seed", amount = 5, probability = 0.3 },
      { type = "item", name = "angels-temperate-3-seed", amount = 5, probability = 0.2 },
      { type = "item", name = "angels-temperate-4-seed", amount = 5, probability = 0.1 },
      { type = "item", name = "angels-temperate-5-seed", amount = 5, probability = 0.05 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-1-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-2-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-3-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-4-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-5-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bc",
  },
  {
    type = "recipe",
    name = "angels-temperate-garden-b",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-temperate-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-temperate-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-temperate-1-seed", amount = 5, probability = 0.8 },
      { type = "item", name = "angels-temperate-2-seed", amount = 5, probability = 0.6 },
      { type = "item", name = "angels-temperate-3-seed", amount = 5, probability = 0.4 },
      { type = "item", name = "angels-temperate-4-seed", amount = 5, probability = 0.2 },
      { type = "item", name = "angels-temperate-5-seed", amount = 5, probability = 0.1 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-1-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-2-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-3-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-4-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-5-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bd",
  },
  --DESERT
  {
    type = "recipe",
    name = "angels-desert-garden-cultivating-a",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-gardens",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-desert-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-token-bio", amount = 32 },
    },
    main_product = "angels-token-bio",
    always_show_products = true,
    show_amount_in_title = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bb",
  },
  {
    type = "recipe",
    name = "angels-desert-garden",
    category = "angels-desert-farming",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 60,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-desert-garden", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-alienated-fertilizer", amount = 2 },
      { type = "item", name = "angels-token-bio", amount = 30 },
      { type = "fluid", name = "angels-water-mineralized", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-desert-garden", amount = 2, ignored_by_productivity = 1, ignored_by_stats = 1 },
    },
    main_product = "angels-desert-garden",
    allow_productivity = true,
    always_show_products = true,
    show_amount_in_title = false,
    order = "ba",
  },
  {
    type = "recipe",
    name = "angels-desert-garden-a",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-desert-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-token-bio", amount = 16 },
      { type = "item", name = "angels-desert-1-seed", amount = 5, probability = 0.4 },
      { type = "item", name = "angels-desert-2-seed", amount = 5, probability = 0.3 },
      { type = "item", name = "angels-desert-3-seed", amount = 5, probability = 0.2 },
      { type = "item", name = "angels-desert-4-seed", amount = 5, probability = 0.1 },
      { type = "item", name = "angels-desert-5-seed", amount = 5, probability = 0.05 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-1-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-2-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-3-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-4-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-5-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bc",
  },
  {
    type = "recipe",
    name = "angels-desert-garden-b",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-desert-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-desert-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-desert-1-seed", amount = 5, probability = 0.8 },
      { type = "item", name = "angels-desert-2-seed", amount = 5, probability = 0.6 },
      { type = "item", name = "angels-desert-3-seed", amount = 5, probability = 0.4 },
      { type = "item", name = "angels-desert-4-seed", amount = 5, probability = 0.2 },
      { type = "item", name = "angels-desert-5-seed", amount = 5, probability = 0.1 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-1-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-2-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-3-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-4-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-5-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bd",
  },
  --SWAMP
  {
    type = "recipe",
    name = "angels-swamp-garden-cultivating-a",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-gardens",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-swamp-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-token-bio", amount = 32 },
    },
    main_product = "angels-token-bio",
    always_show_products = true,
    show_amount_in_title = false,
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bb",
  },
  {
    type = "recipe",
    name = "angels-swamp-garden",
    category = "angels-swamp-farming",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 60,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-swamp-garden", amount = 1, ignored_by_stats = 1 },
      { type = "item", name = "angels-solid-alienated-fertilizer", amount = 2 },
      { type = "item", name = "angels-token-bio", amount = 30 },
      { type = "fluid", name = "angels-water-mineralized", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-swamp-garden", amount = 2, ignored_by_productivity = 1, ignored_by_stats = 1 },
    },
    main_product = "angels-swamp-garden",
    allow_productivity = true,
    always_show_products = true,
    show_amount_in_title = false,
    order = "ba",
  },
  {
    type = "recipe",
    name = "angels-swamp-garden-a",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-swamp-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-token-bio", amount = 16 },
      { type = "item", name = "angels-swamp-1-seed", amount = 5, probability = 0.4 },
      { type = "item", name = "angels-swamp-2-seed", amount = 5, probability = 0.3 },
      { type = "item", name = "angels-swamp-3-seed", amount = 5, probability = 0.2 },
      { type = "item", name = "angels-swamp-4-seed", amount = 5, probability = 0.1 },
      { type = "item", name = "angels-swamp-5-seed", amount = 5, probability = 0.05 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-1-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-2-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-3-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-4-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-5-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bc",
  },
  {
    type = "recipe",
    name = "angels-swamp-garden-b",
    category = "angels-seed-extractor",
    subgroup = "angels-farming-swamp-seed",
    enabled = false,
    auto_recycle = false,
    energy_required = 300,
    overload_multiplier = 1,
    ingredients = {
      { type = "item", name = "angels-swamp-garden", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-swamp-1-seed", amount = 5, probability = 0.8 },
      { type = "item", name = "angels-swamp-2-seed", amount = 5, probability = 0.6 },
      { type = "item", name = "angels-swamp-3-seed", amount = 5, probability = 0.4 },
      { type = "item", name = "angels-swamp-4-seed", amount = 5, probability = 0.2 },
      { type = "item", name = "angels-swamp-5-seed", amount = 5, probability = 0.1 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-garden.png",
        icon_size = 32,
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-1-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-2-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, -seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-3-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-4-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-5-seed.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, seed_icon_shift },
      },
    },
    order = "bd",
  },
  --COMPOST
  {
    type = "recipe",
    name = "angels-solid-soil",
    localised_name = { "item-name.angels-solid-soil" },
    category = "crafting",
    subgroup = "angels-bio-wood",
    enabled = false,
    auto_recycle = false,
    energy_required = 4,
    ingredients = {
      { type = "item", name = "angels-solid-mud", amount = 1 },
      { type = "item", name = "angels-solid-compost", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-solid-soil", amount = 1 },
    },
    icons = angelsmods.functions.create_solid_recipe_icon(nil, "angels-solid-soil", { "angels-solid-mud" }),
    icon_size = 32,
    order = "a[support]-aa",
  },
  {
    type = "recipe",
    name = "angels-solid-soil-alternative",
    localised_name = { "item-name.angels-solid-soil" },
    category = "crafting",
    subgroup = "angels-bio-wood",
    enabled = false,
    auto_recycle = false,
    energy_required = 4,
    ingredients = {
      { type = "item", name = "angels-solid-sand", amount = 1 },
      { type = "item", name = "angels-solid-compost", amount = 2 },
    },
    results = {
      { type = "item", name = "angels-solid-soil", amount = 1 },
    },
    icons = angelsmods.functions.create_solid_recipe_icon(nil, "angels-solid-soil", { "angels-solid-sand" }),
    icon_size = 32,
    order = "a[support]-ab",
  },
  {
    type = "recipe",
    name = "angels-solid-fertilizer",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-wood",
    enabled = false,
    auto_recycle = false,
    energy_required = 1,
    ingredients = {
      { type = "item", name = "angels-solid-compost", amount = 2 },
      { type = "fluid", name = "angels-gas-urea", amount = 20 },
    },
    results = {
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
    },
    icon_size = 32,
    order = "a[support]-ca", -- order a[support]-cb reserved for bob fertilizer
  },
  {
    type = "recipe",
    name = "angels-solid-alienated-fertilizer",
    category = "crafting-with-fluid",
    subgroup = "angels-bio-wood",
    enabled = false,
    auto_recycle = false,
    energy_required = 2,
    ingredients = {
      { type = "item", name = "angels-solid-fertilizer", amount = 1 },
      { type = "fluid", name = "angels-alien-goo", amount = 5 },
    },
    results = {
      { type = "item", name = "angels-solid-alienated-fertilizer", amount = 1 },
    },
    icon_size = 32,
    order = "a[support]-d",
  },

  --UPGRADES
  {
    type = "recipe",
    name = "angels-temperate-upgrade",
    category = "crafting",
    subgroup = "angels-bio-processing-blocks",
    enabled = false,
    energy_required = 4,
    ingredients = {
      { type = "item", name = "angels-token-bio", amount = 5 },
      { type = "item", name = "angels-void", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-temperate-upgrade", amount = 1 },
    },
    icon_size = 32,
    order = "d",
  },
  {
    type = "recipe",
    name = "angels-desert-upgrade",
    category = "crafting",
    subgroup = "angels-bio-processing-blocks",
    enabled = false,
    energy_required = 4,
    ingredients = {
      { type = "item", name = "angels-token-bio", amount = 5 },
      { type = "item", name = "angels-void", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-desert-upgrade", amount = 1 },
    },
    icon_size = 32,
    order = "d",
  },
  {
    type = "recipe",
    name = "angels-swamp-upgrade",
    category = "crafting",
    subgroup = "angels-bio-processing-blocks",
    enabled = false,
    energy_required = 4,
    ingredients = {
      { type = "item", name = "angels-token-bio", amount = 5 },
      { type = "item", name = "angels-void", amount = 1 },
    },
    results = {
      { type = "item", name = "angels-swamp-upgrade", amount = 1 },
    },
    icon_size = 32,
    order = "d",
  },

  --GENERATION
  {
    type = "recipe",
    name = "angels-garden-cultivating",
    category = "angels-basic-farming",
    subgroup = "angels-farming-gardens",
    enabled = false,
    auto_recycle = false,
    energy_required = 100,
    ingredients = {
      { type = "item", name = "angels-token-bio", amount = 1 },
      { type = "item", name = "angels-solid-wood-pulp", amount = 5 },
      { type = "fluid", name = "angels-water-mineralized", amount = 50 },
    },
    results = {
      { type = "item", name = "angels-temperate-garden", amount = 1, probability = 0.01 },
      { type = "item", name = "angels-desert-garden", amount = 1, probability = 0.01 },
      { type = "item", name = "angels-swamp-garden", amount = 1, probability = 0.01 },
    },
    icons = {
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
        icon_size = 32,
        --scale = 0.5,
        --shift = {0,-5}
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-garden.png",
        icon_size = 32,
        scale = 0.35,
        shift = { -seed_icon_shift, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-garden.png",
        icon_size = 32,
        scale = 0.35,
        shift = { 0, seed_icon_shift },
      },
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-garden.png",
        icon_size = 32,
        scale = 0.35,
        shift = { seed_icon_shift, seed_icon_shift },
      },
    },
    order = "be",
  },
})
