data:extend(
{
--CIRCUIT COMPONENTS
	{
    type = "recipe",
    name = "circuit-resistor",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "solid-paper", amount = 1},
		{type = "item", name = "copper-cable", amount = 1},
	},
    result = "circuit-resistor",
	icon_size = 32,
    },
	-- {
    -- type = "recipe",
    -- name = "circuit-resistor",
    -- energy_required = 3,
	-- category = "advanced-crafting",
	-- enabled = "true",
    -- ingredients ={
		-- {type = "item", name = "plastic", amount = 1},
		-- {type = "item", name = "paste-cellulose", amount = 1},
		-- {type = "item", name = "solid-carbon", amount = 1},
		-- {type = "item", name = "copper-cable", amount = 1},
	-- },
    -- result = "circuit-resistor",
	-- icon_size = 32,
	-- order = "b",
    -- },
	{
    type = "recipe",
    name = "circuit-transistor",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "iron-plate", amount = 1},
		{type = "item", name = "angels-wire-tin", amount = 1},
	},
    result = "circuit-transistor",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-microchip",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "iron-plate", amount = 1},
		{type = "item", name = "angels-wire-silver", amount = 1},
		{type = "fluid", name = "liquid-plastic", amount = 1},
		{type = "fluid", name = "liquid-sulfuric-acid", amount = 1},
	},
    result = "circuit-microchip",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-transformer",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "iron-plate", amount = 1},
		{type = "item", name = "angels-wire-gold", amount = 1},
	},
    result = "circuit-transformer",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-cpu",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "iron-plate", amount = 1},
		{type = "item", name = "angels-wire-platinum", amount = 1},
	},
    result = "circuit-cpu",
	icon_size = 32,
    },
--BOARDS
	{
    type = "recipe",
    name = "circuit-grey-board",
    energy_required = 1,
	category = "crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "wood", amount = 1},
	},
    result = "circuit-grey-board",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-red-board",
    energy_required = 3,
	category = "crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "solid-paper", amount = 1},
	},
    result = "circuit-red-board",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-green-board",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "solid-paper", amount = 1},
		{type = "fluid", name = "liquid-resin", amount = 2},
	},
    result = "circuit-green-board",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-orange-board",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "cellulose-fiber", amount = 1},
		{type = "fluid", name = "liquid-plastic", amount = 2},
	},
    result = "circuit-orange-board",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-blue-board",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "angels-coil-glass-fiber", amount = 2},
		{type = "fluid", name = "liquid-resin", amount = 2},
	},
    result = "circuit-blue-board",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-yellow-board",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "angels-coil-glass-fiber", amount = 2},
		{type = "fluid", name = "liquid-resin", amount = 2},
		{type = "fluid", name = "liquid-plastic", amount = 2},
	},
    result = "circuit-yellow-board",
	icon_size = 32,
    },
--CIRCUIT BOARDS
	{
    type = "recipe",
    name = "circuit-grey",
    energy_required = 3,
	category = "crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-grey-board", amount = 2},
		{type = "item", name = "angels-wire-copper", amount = 2},
	},
    result = "circuit-grey",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-red",
    energy_required = 3,
	category = "crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-red-board", amount = 1},
		{type = "item", name = "angels-wire-copper", amount = 2},
	},
    result = "circuit-red",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-green",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-green-board", amount = 1},
		{type = "item", name = "angels-wire-tin", amount = 2},
	},
    result = "circuit-green",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-orange",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-orange-board", amount = 1},
		{type = "item", name = "angels-wire-silver", amount = 2},
		{type = "fluid", name = "liquid-ferric-chloride-solution", amount = 2},
	},
    result = "circuit-orange",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-blue",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-blue-board", amount = 1},
		{type = "item", name = "angels-wire-gold", amount = 2},
		{type = "fluid", name = "liquid-ferric-chloride-solution", amount = 2},
	},
    result = "circuit-blue",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-yellow",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-yellow-board", amount = 1},
		{type = "item", name = "angels-wire-platinum", amount = 2},
		{type = "fluid", name = "liquid-ferric-chloride-solution", amount = 2},
	},
    result = "circuit-yellow",
	icon_size = 32,
    },
--CIRCUIT LOADED
	{
    type = "recipe",
    name = "circuit-red-loaded",
    energy_required = 3,
	category = "crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-red", amount = 1},
		{type = "item", name = "circuit-resistor", amount = 1},
		{type = "item", name = "angels-solder", amount = 1},
	},
    result = "circuit-red-loaded",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-green-loaded",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-green", amount = 1},
		{type = "item", name = "circuit-resistor", amount = 1},
		{type = "item", name = "circuit-transistor", amount = 1},
		{type = "item", name = "angels-solder", amount = 1},
	},
    result = "circuit-green-loaded",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-orange-loaded",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-orange", amount = 1},
		{type = "item", name = "circuit-resistor", amount = 1},
		{type = "item", name = "circuit-transistor", amount = 1},
		{type = "item", name = "circuit-microchip", amount = 1},
		{type = "item", name = "angels-solder", amount = 1},
	},
    result = "circuit-orange-loaded",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-blue-loaded",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-blue", amount = 1},
		{type = "item", name = "circuit-resistor", amount = 1},
		{type = "item", name = "circuit-transistor", amount = 1},
		{type = "item", name = "circuit-microchip", amount = 1},
		{type = "item", name = "circuit-transformer", amount = 1},
		{type = "item", name = "angels-solder", amount = 1},
	},
    result = "circuit-blue-loaded",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "circuit-yellow-loaded",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "circuit-yellow", amount = 1},
		{type = "item", name = "circuit-resistor", amount = 1},
		{type = "item", name = "circuit-transistor", amount = 1},
		{type = "item", name = "circuit-microchip", amount = 1},
		{type = "item", name = "circuit-transformer", amount = 1},
		{type = "item", name = "circuit-cpu", amount = 1},
		{type = "item", name = "angels-solder", amount = 1},
	},
    result = "circuit-yellow-loaded",
	icon_size = 32,
    },
--CABLE HARNESS
	{
    type = "recipe",
    name = "cable-harness-1",
    energy_required = 3,
	category = "crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "copper-cable", amount = 2},
		{type = "item", name = "cellulose-fiber", amount = 1},
	},
    result = "cable-harness-1",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "cable-harness-2",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "angels-wire-tin", amount = 2},
		{type = "item", name = "cellulose-fiber", amount = 1},
	},
    result = "cable-harness-2",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "cable-harness-3",
    energy_required = 3,
	category = "advanced-crafting",
	enabled = "true",
    ingredients ={
		{type = "item", name = "angels-wire-silver", amount = 2},
		{type = "item", name = "solid-rubber", amount = 1},
	},
    result = "cable-harness-3",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "cable-harness-4",
    energy_required = 3,
	category = "crafting-with-fluid",
	enabled = "true",
    ingredients ={
		{type = "item", name = "angels-wire-gold", amount = 2},
		{type = "fluid", name = "liquid-plastic", amount = 1},
	},
    result = "cable-harness-4",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "cable-harness-5",
    energy_required = 3,
	category = "crafting-with-fluid",
	enabled = "true",
    ingredients ={
		{type = "item", name = "angels-wire-platinum", amount = 2},
		{type = "fluid", name = "liquid-plastic", amount = 1},
	},
    result = "cable-harness-5",
	icon_size = 32,
    },
}
)