data:extend(
{
--DATACORES
	{
    type = "recipe",
    name = "datacore-basic",
    energy_required = 3,
	enabled = "true",
    ingredients ={
		{"iron-plate", 2},
		{"circuit-grey", 1},
	},
    result = "datacore-basic",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-exploration-1",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-basic", 1},
		{"circuit-red-loaded", 1},
	},
    result = "datacore-exploration-1",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-exploration-2",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-exploration-1", 1},
		{"circuit-orange-loaded", 1},
	},
    result = "datacore-exploration-2",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-enhance-1",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-basic", 1},
		{"circuit-red-loaded", 1},
		{"repair-pack", 1},
		{"iron-axe", 1},
	},
    result = "datacore-enhance-1",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-enhance-2",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-enhance-1", 1},
		{"circuit-orange-loaded", 1},
		{"modular-armor", 1},
		{"speed-module", 1},
	},
    result = "datacore-enhance-2",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-energy-1",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-basic", 1},
		{"circuit-red-loaded", 1},
		{"steam-engine", 1},
		{"small-electric-pole", 1},
	},
    result = "datacore-energy-1",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-energy-2",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-energy-1", 1},
		{"circuit-orange-loaded", 1},
		{"substation", 1},
		{"solar-panel", 1},
	},
    result = "datacore-energy-2",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-logistic-1",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-basic", 1},
		{"circuit-red-loaded", 1},
		{"inserter", 1},
		{"transport-belt", 1},
	},
    result = "datacore-logistic-1",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-logistic-2",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-logistic-1", 1},
		{"circuit-orange-loaded", 1},
		{"construction-robot", 1},
		{"filter-inserter", 1},
	},
    result = "datacore-logistic-2",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-processing-1",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-basic", 1},
		{"circuit-red-loaded", 1},
		{"assembling-machine-1", 1},
		{"electric-mining-drill", 1},
	},
    result = "datacore-processing-1",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-processing-2",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-processing-1", 1},
		{"circuit-orange-loaded", 1},
		{"ore-crusher-2", 1},
		{"angels-chemical-plant-2", 1},
	},
    result = "datacore-processing-2",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-war-1",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-basic", 1},
		{"circuit-red-loaded", 1},
		{"gun-turret", 1},
		{"firearm-magazine", 1},
	},
    result = "datacore-war-1",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "datacore-war-2",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"datacore-war-1", 1},
		{"circuit-orange-loaded", 1},
		{"flamethrower-turret", 1},
		{"piercing-rounds-magazine", 1},
	},
    result = "datacore-war-2",
	icon_size = 32,
    },
--SCIENCE PACKS
	{
    type = "recipe",
    name = "angels-science-pack-grey",
    energy_required = 3,
	enabled = "true",
    ingredients ={
		{"iron-plate", 2},
		{"science-data-analyzer", 1},
		{"circuit-grey", 1},
	},
    result = "angels-science-pack-grey",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "angels-science-pack-red",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"angels-science-pack-grey", 1},
		{"science-force-analyzer", 1},
		{"circuit-red-loaded", 1},
	},
    result = "angels-science-pack-red",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "angels-science-pack-green",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"angels-science-pack-red", 1},
		{"science-harmonics-analyzer", 1},
		{"circuit-green-loaded", 1},
	},
    result = "angels-science-pack-green",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "angels-science-pack-orange",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"angels-science-pack-green", 1},
		{"circuit-orange-loaded", 1},
	},
    result = "angels-science-pack-orange",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "angels-science-pack-blue",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"angels-science-pack-orange", 1},
		{"circuit-blue-loaded", 1},
	},
    result = "angels-science-pack-blue",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "angels-science-pack-yellow",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"angels-science-pack-blue", 1},
		{"circuit-yellow-loaded", 1},
	},
    result = "angels-science-pack-yellow",
	icon_size = 32,
    },
--SCIENCE PACKS COMPONENTS
	{
    type = "recipe",
    name = "science-data-analyzer",
    energy_required = 3,
	enabled = "true",
    ingredients ={
		{"iron-plate", 1},
		{"copper-plate", 2},
	},
    result = "science-data-analyzer",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "science-force-analyzer",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"angels-plate-tin", 1},
		{"steel-plate", 1},
	},
    result = "science-force-analyzer",
	icon_size = 32,
    },
	{
    type = "recipe",
    name = "science-harmonics-analyzer",
    energy_required = 10,
	enabled = "true",
    ingredients ={
		{"angels-plate-silver", 1},
		{"angels-plate-aluminium", 1},
	},
    result = "science-harmonics-analyzer",
	icon_size = 32,
    },
	-- {
    -- type = "recipe",
    -- name = "angels-science-pack-orange",
    -- energy_required = 10,
	-- enabled = "true",
    -- ingredients ={
		-- {"angels-science-pack-green", 1},
		-- {"circuit-orange-loaded", 1},
	-- },
    -- result = "angels-science-pack-orange",
	-- icon_size = 32,
    -- },
	-- {
    -- type = "recipe",
    -- name = "angels-science-pack-blue",
    -- energy_required = 10,
	-- enabled = "true",
    -- ingredients ={
		-- {"angels-science-pack-orange", 1},
		-- {"circuit-blue-loaded", 1},
	-- },
    -- result = "angels-science-pack-blue",
	-- icon_size = 32,
    -- },
	-- {
    -- type = "recipe",
    -- name = "angels-science-pack-yellow",
    -- energy_required = 10,
	-- enabled = "true",
    -- ingredients ={
		-- {"angels-science-pack-blue", 1},
		-- {"circuit-yellow-loaded", 1},
	-- },
    -- result = "angels-science-pack-yellow",
	-- icon_size = 32,
    -- },
  }
  )