circuit_connector_definitions["angels-algae-farm"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  6, main_offset = util.by_pixel( 97, -51.375), shadow_offset = util.by_pixel( 97, -51.375), show_shadow = true },
  { variation =  6, main_offset = util.by_pixel( 97, -51.375), shadow_offset = util.by_pixel( 97, -51.375), show_shadow = true },
  { variation =  6, main_offset = util.by_pixel( 97, -51.375), shadow_offset = util.by_pixel( 97, -51.375), show_shadow = true },
  { variation =  6, main_offset = util.by_pixel( 97, -51.375), shadow_offset = util.by_pixel( 97, -51.375), show_shadow = true }
})

data:extend({
  {
    type = "item",
    name = "angels-algae-farm",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 1, angelsmods.bioprocessing.number_tint),
    subgroup = "angels-bio-processing-buildings-nauvis-a",
    order = "a[algae]-a",
    place_result = "angels-algae-farm",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-algae-farm",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 1, angelsmods.bioprocessing.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-algae-farm" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    fast_replaceable_group = "angels-algae-farm",
    next_upgrade = "angels-algae-farm-2",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-bio-processing" },
    crafting_speed = 0.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -100 / 3 * 0.5 },
    },
    energy_usage = "100kW",
    circuit_connector = circuit_connector_definitions["angels-algae-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 4,
    graphics_set = {
      animation = {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/algae-farm.png",
        width = 288,
        height = 288,
        line_length = 6,
        frame_count = 36,
        shift = { 0, 0 },
        animation_speed = 0.4,
      },
      working_visualisations = {
        {
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/water-splash.png",
            line_length = 5,
            frame_count = 10,
            width = 92,
            height = 99,
            scale = 0.4,
            shift = { -1.4, 0 },
            animation_speed = 0.2,
            run_mode = "forward",
          },
          light = { intensity = 0.4, size = 6 },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -3 }, direction = defines.direction.north } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 3 }, direction = defines.direction.south } },
      },
    },
  },
  {
    type = "item",
    name = "angels-algae-farm-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 2, angelsmods.bioprocessing.number_tint),
    subgroup = "angels-bio-processing-buildings-nauvis-a",
    order = "a[algae]-b",
    place_result = "angels-algae-farm-2",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-algae-farm-2",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 2, angelsmods.bioprocessing.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-algae-farm-2" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    fast_replaceable_group = "angels-algae-farm",
    next_upgrade = "angels-algae-farm-3",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-bio-processing", "angels-bio-processing-2" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -100 / 3 * 1 },
    },
    energy_usage = "125kW",
    circuit_connector = circuit_connector_definitions["angels-algae-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 4,
    graphics_set = {
      animation = {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/algae-farm.png",
        width = 288,
        height = 288,
        line_length = 6,
        frame_count = 36,
        shift = { 0, 0 },
        animation_speed = 0.4,
      },
      working_visualisations = {
        {
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/water-splash.png",
            line_length = 5,
            frame_count = 10,
            width = 92,
            height = 99,
            scale = 0.4,
            shift = { -1.4, 0 },
            animation_speed = 0.2,
            run_mode = "forward",
          },
          light = { intensity = 0.4, size = 6 },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -3 }, direction = defines.direction.north } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 3 }, direction = defines.direction.south } },
      },
    },
  },
  {
    type = "item",
    name = "angels-algae-farm-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 3, angelsmods.bioprocessing.number_tint),
    subgroup = "angels-bio-processing-buildings-nauvis-a",
    order = "a[algae]-c",
    place_result = "angels-algae-farm-3",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-algae-farm-3",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 3, angelsmods.bioprocessing.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-algae-farm-3" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    fast_replaceable_group = "angels-algae-farm",
    next_upgrade = "angels-algae-farm-4",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-bio-processing", "angels-bio-processing-2", "angels-bio-processing-3" },
    crafting_speed = 1.5,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -100 / 3 * 1.5 },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-algae-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 4,
    graphics_set = {
      animation = {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/algae-farm.png",
        width = 288,
        height = 288,
        line_length = 6,
        frame_count = 36,
        shift = { 0, 0 },
        animation_speed = 0.4,
      },
      working_visualisations = {
        {
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/water-splash.png",
            line_length = 5,
            frame_count = 10,
            width = 92,
            height = 99,
            scale = 0.4,
            shift = { -1.4, 0 },
            animation_speed = 0.2,
            run_mode = "forward",
          },
          light = { intensity = 0.4, size = 6 },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -3 }, direction = defines.direction.north } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 3 }, direction = defines.direction.south } },
      },
    },
  },
  {
    type = "item",
    name = "angels-algae-farm-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 4, angelsmods.bioprocessing.number_tint),
    subgroup = "angels-bio-processing-buildings-nauvis-a",
    order = "a[algae]-d",
    place_result = "angels-algae-farm-4",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-algae-farm-4",
    icons = angelsmods.functions.add_number_icon_layer({
      {
        icon = "__angelsbioprocessinggraphics__/graphics/icons/algae-farm.png",
        icon_size = 32,
      },
    }, 4, angelsmods.bioprocessing.number_tint),
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-algae-farm-4" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    fast_replaceable_group = "angels-algae-farm",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-bio-processing", "angels-bio-processing-2", "angels-bio-processing-3", "angels-bio-processing-4" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -100 / 3 * 2 },
    },
    energy_usage = "175kW",
    circuit_connector = circuit_connector_definitions["angels-algae-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    ingredient_count = 4,
    graphics_set = {
      animation = {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/algae-farm.png",
        width = 288,
        height = 288,
        line_length = 6,
        frame_count = 36,
        shift = { 0, 0 },
        animation_speed = 0.4,
      },
      working_visualisations = {
        {
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/algae-farm/water-splash.png",
            line_length = 5,
            frame_count = 10,
            width = 92,
            height = 99,
            scale = 0.4,
            shift = { -1.4, 0 },
            animation_speed = 0.2,
            run_mode = "forward",
          },
          light = { intensity = 0.4, size = 6 },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -3 }, direction = defines.direction.north } },
      },
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, 3 }, direction = defines.direction.south } },
      },
    },
  },
})

angelsmods.functions.allow_bio_productivity("angels-algae-farm")
angelsmods.functions.allow_bio_productivity("angels-algae-farm-2")
angelsmods.functions.allow_bio_productivity("angels-algae-farm-3")
angelsmods.functions.allow_bio_productivity("angels-algae-farm-4")
