circuit_connector_definitions["angels-bio-processor"] = circuit_connector_definitions.create_vector(universal_connector_template, {
  { variation =  3, main_offset = util.by_pixel(-11.5, -30.875), shadow_offset = util.by_pixel(-11.5, -30.875), show_shadow = true },
  { variation =  3, main_offset = util.by_pixel(-11.5, -30.875), shadow_offset = util.by_pixel(-11.5, -30.875), show_shadow = true },
  { variation =  3, main_offset = util.by_pixel(-11.5, -30.875), shadow_offset = util.by_pixel(-11.5, -30.875), show_shadow = true },
  { variation =  3, main_offset = util.by_pixel(-11.5, -30.875), shadow_offset = util.by_pixel(-11.5, -30.875), show_shadow = true },
})

data:extend({
  {
    type = "item",
    name = "angels-bio-processor",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/bio-processor.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-buildings-vegetabilis-b",
    order = "c",
    place_result = "angels-bio-processor",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-bio-processor",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/bio-processor.png",
    icon_size = 32,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-bio-processor" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    drawing_box_vertical_extension = 1,
    fast_replaceable_group = "angels-bio-processor",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-bio-processor" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = 0.03 * 60 },
    },
    energy_usage = "150kW",
    circuit_connector = circuit_connector_definitions["angels-bio-processor"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    --ingredient_count = 4,
    graphics_set = {
      animation = {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/bio-processor/bio-processor.png",
        width = 224,
        height = 224,
        line_length = 5,
        frame_count = 25,
        shift = { 0, 0 },
        animation_speed = 0.5,
      },
      working_visualisations = {
        {
          fadeout = true,
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/bio-processor/bio-processor-bg.png",
            line_length = 5,
            frame_count = 25,
            width = 224,
            height = 224,
            shift = { 0, 0 },
            animation_speed = 0.5,
          },
        },
        {
          always_draw = true,
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/bio-processor/bio-processor-trans.png",
            line_length = 5,
            frame_count = 25,
            width = 224,
            height = 224,
            shift = { 0, 0 },
            animation_speed = 0.5,
          },
        },
        {
          fadeout = true,
          apply_recipe_tint = "secondary",
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/bio-processor/bio-processor-ani.png",
            line_length = 5,
            frame_count = 25,
            width = 224,
            height = 224,
            shift = { 0, 0 },
            animation_speed = 0.5,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
  },
})
