circuit_connector_definitions["angels-crop-farm"] = circuit_connector_definitions.create_vector(universal_connector_template,
{
  { variation =  4, main_offset = util.by_pixel( 38.5,  55.125), shadow_offset = util.by_pixel( 38.5,  55.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 38.5,  55.125), shadow_offset = util.by_pixel( 38.5,  55.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 38.5,  55.125), shadow_offset = util.by_pixel( 38.5,  55.125), show_shadow = true },
  { variation =  4, main_offset = util.by_pixel( 38.5,  55.125), shadow_offset = util.by_pixel( 38.5,  55.125), show_shadow = true }
})

data:extend({
  {
    type = "item",
    name = "angels-crop-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/basic-farm.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-buildings-vegetabilis-a",
    order = "a",
    place_result = "angels-crop-farm",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-crop-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/basic-farm.png",
    icon_size = 32,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-crop-farm" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    fast_replaceable_group = "angels-crop-farm",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-temperate-farming", "angels-desert-farming", "angels-swamp-farming", "angels-basic-farming" },
    crafting_speed = 1,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -40 },
    },
    energy_usage = "100kW",
    circuit_connector = circuit_connector_definitions["angels-crop-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/farm-base.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-basic.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
        },
      },
      working_visualisations = {
        {
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-animation-1.png",
            line_length = 6,
            frame_count = 36,
            width = 224,
            height = 224,
            shift = { 0, 0 },
            animation_speed = 0.005,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -2 }, direction = defines.direction.north } },
      },
    },
  },
  {
    type = "item",
    name = "angels-temperate-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-farm.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-buildings-vegetabilis-a",
    order = "ba",
    place_result = "angels-temperate-farm",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-temperate-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-farm.png",
    icon_size = 32,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-temperate-farm" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    fast_replaceable_group = "angels-crop-farm",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-temperate-farming", "angels-advanced-temperate-farming" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -80 },
    },
    energy_usage = "125kW",
    circuit_connector = circuit_connector_definitions["angels-crop-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/farm-base.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-temperate.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
        },
      },
      working_visualisations = {
        {
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-animation-2.png",
            line_length = 6,
            frame_count = 36,
            width = 224,
            height = 224,
            shift = { 0, 0 },
            animation_speed = 0.01,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -2 }, direction = defines.direction.north } },
      },
    },
  },
  {
    type = "item",
    name = "angels-desert-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-farm.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-buildings-vegetabilis-a",
    order = "bc",
    place_result = "angels-desert-farm",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-desert-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-farm.png",
    icon_size = 32,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-desert-farm" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    fast_replaceable_group = "angels-crop-farm",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-desert-farming", "angels-advanced-desert-farming" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -80 },
    },
    energy_usage = "125kW",
    circuit_connector = circuit_connector_definitions["angels-crop-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/farm-base.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-desert.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
        },
      },
      working_visualisations = {
        {
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-animation-3.png",
            line_length = 6,
            frame_count = 36,
            width = 224,
            height = 224,
            shift = { 0, 0 },
            animation_speed = 0.01,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -2 }, direction = defines.direction.north } },
      },
    },
  },
  {
    type = "item",
    name = "angels-swamp-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-farm.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-buildings-vegetabilis-a",
    order = "bb",
    place_result = "angels-swamp-farm",
    stack_size = 10,
  },
  {
    type = "assembling-machine",
    name = "angels-swamp-farm",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-farm.png",
    icon_size = 32,
    flags = { "placeable-neutral", "player-creation" },
    minable = { mining_time = 1, result = "angels-swamp-farm" },
    max_health = 300,
    corpse = "big-remnants",
    dying_explosion = "medium-explosion",
    collision_box = { { -2.4, -2.4 }, { 2.4, 2.4 } },
    selection_box = { { -2.5, -2.5 }, { 2.5, 2.5 } },
    fast_replaceable_group = "angels-crop-farm",
    module_slots = 2,
    allowed_effects = { "consumption", "speed", "productivity", "pollution" },
    crafting_categories = { "angels-swamp-farming", "angels-advanced-swamp-farming" },
    crafting_speed = 2,
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      emissions_per_minute = { pollution = -80 },
    },
    energy_usage = "125kW",
    circuit_connector = circuit_connector_definitions["angels-crop-farm"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    graphics_set = {
      animation = {
        layers = {
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/farm-base.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
          {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-water.png",
            width = 224,
            height = 224,
            line_length = 1,
            frame_count = 1,
            shift = { 0, 0 },
          },
        },
      },
      working_visualisations = {
        {
          apply_recipe_tint = "primary",
          animation = {
            filename = "__angelsbioprocessinggraphics__/graphics/entity/crop-farm/field-animation-4.png",
            line_length = 6,
            frame_count = 36,
            width = 224,
            height = 224,
            shift = { 0, 0 },
            animation_speed = 0.01,
          },
        },
      },
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/chemical-plant.ogg" },
      idle_sound = { filename = "__base__/sound/idle1.ogg", volume = 0.6 },
    },
    fluid_boxes = {
      {
        production_type = "input",
        pipe_covers = pipecoverspictures(),
        volume = 1000,
        pipe_connections = { { flow_direction = "input", position = { 0, -2 }, direction = defines.direction.north } },
      },
    },
  },
})

angelsmods.functions.allow_bio_productivity("angels-crop-farm")
angelsmods.functions.allow_bio_productivity("angels-temperate-farm")
angelsmods.functions.allow_bio_productivity("angels-desert-farm")
angelsmods.functions.allow_bio_productivity("angels-swamp-farm")
