local simulations = require("prototypes.factoriopedia-simulations")

data.raw.planet.nauvis.map_gen_settings.autoplace_settings.entity.settings["angels-temperate-garden"] = {}
data.raw.planet.nauvis.map_gen_settings.autoplace_settings.entity.settings["angels-desert-garden"] = {}
data.raw.planet.nauvis.map_gen_settings.autoplace_settings.entity.settings["angels-swamp-garden"] = {}

data:extend({
  {
    type = "item",
    name = "angels-temperate-garden",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-garden.png",
    icon_size = 32,
    subgroup = "angels-farming-gardens",
    order = "b[garden]-a",
    stack_size = 200,
  },
  {
    type = "tree",
    name = "angels-temperate-garden",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-garden.png",
    icon_size = 32,
    flags = { "placeable-neutral", "placeable-off-grid", "breaths-air" },
    minable = {
      mining_particle = "wooden-particle",
      mining_time = 1,
      results = {
        { type = 'item', name = "angels-temperate-garden", amount = 1 },
        { type = 'item', name = "angels-temperate-1",      amount = 5, probability = 0.4 },
        { type = 'item', name = "angels-temperate-2",      amount = 5, probability = 0.3 },
        { type = 'item', name = "angels-temperate-3",      amount = 5, probability = 0.2 },
        { type = 'item', name = "angels-temperate-4",      amount = 5, probability = 0.1 },
        { type = 'item', name = "angels-temperate-5",      amount = 5, probability = 0.05 },
      },
    },
    emissions_per_second = { pollution = -0.006 }, --emissions_per_tick = -0.0001,
    factoriopedia_simulation = simulations.factoriopedia_angels_temperate_garden,
    max_health = 20,
    collision_box = { { -1.1, -1.1 }, { 1.1, 1.1 } },
    selection_box = { { -1.3, -1.3 }, { 1.3, 1.3 } },
    map_color = { r = 0.2, g = 0.8, b = 0.2 },
    subgroup = "trees",
    order = "a[tree]-b[dead-tree]",
    impact_category = "wood",
    autoplace = {
      order = "xab",
      probability_expression = 0.000025,
      tile_restriction = { "grass-1", "grass-2", "grass-3", "grass-4", "dry-dirt" },
    },
    pictures = {
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/temperate-garden-1.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/temperate-garden-2.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/temperate-garden-3.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/temperate-garden-4.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/temperate-garden-5.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
    },
  },
  {
    type = "item",
    name = "angels-desert-garden",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-garden.png",
    icon_size = 32,
    subgroup = "angels-farming-gardens",
    order = "b[garden]-c",
    stack_size = 200,
  },
  {
    type = "tree",
    name = "angels-desert-garden",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-garden.png",
    icon_size = 32,
    flags = { "placeable-neutral", "placeable-off-grid", "breaths-air" },
    minable = {
      mining_particle = "wooden-particle",
      mining_time = 1,
      results = {
        { type = 'item', name = "angels-desert-garden", amount = 1 },
        { type = 'item', name = "angels-desert-1",      amount = 5, probability = 0.4 },
        { type = 'item', name = "angels-desert-2",      amount = 5, probability = 0.3 },
        { type = 'item', name = "angels-desert-3",      amount = 5, probability = 0.2 },
        { type = 'item', name = "angels-desert-4",      amount = 5, probability = 0.1 },
        { type = 'item', name = "angels-desert-5",      amount = 5, probability = 0.05 },
      },
    },
    emissions_per_second = { pollution = -0.006 }, --emissions_per_tick = -0.0001,
    factoriopedia_simulation = simulations.factoriopedia_angels_desert_garden,
    max_health = 20,
    collision_box = { { -1.1, -1.1 }, { 1.1, 1.1 } },
    selection_box = { { -1.3, -1.3 }, { 1.3, 1.3 } },
    map_color = { r = 0.2, g = 0.8, b = 0.2 },
    subgroup = "trees",
    order = "a[tree]-b[dead-tree]",
    impact_category = "wood",
    autoplace = {
      order = "yab",
      probability_expression = 0.000025,
      tile_restriction = { "red-desert-0", "red-desert-1", "red-desert-2", "red-desert-3", "sand-1", "sand-2", "sand-3" },
    },
    pictures = {
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/desert-garden-1.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/desert-garden-2.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/desert-garden-3.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/desert-garden-4.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
    },
  },
  {
    type = "item",
    name = "angels-swamp-garden",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-garden.png",
    icon_size = 32,
    subgroup = "angels-farming-gardens",
    order = "b[garden]-b",
    stack_size = 200,
  },
  {
    type = "tree",
    name = "angels-swamp-garden",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-garden.png",
    icon_size = 32,
    flags = { "placeable-neutral", "placeable-off-grid", "breaths-air" },
    minable = {
      mining_particle = "wooden-particle",
      mining_time = 1,
      results = {
        { type = 'item', name = "angels-swamp-garden", amount = 1 },
        { type = 'item', name = "angels-swamp-1",      amount = 5, probability = 0.4 },
        { type = 'item', name = "angels-swamp-2",      amount = 5, probability = 0.3 },
        { type = 'item', name = "angels-swamp-3",      amount = 5, probability = 0.2 },
        { type = 'item', name = "angels-swamp-4",      amount = 5, probability = 0.1 },
        { type = 'item', name = "angels-swamp-5",      amount = 5, probability = 0.05 },
      },
    },
    emissions_per_second = { pollution = -0.006 }, --emissions_per_tick = -0.0001,
    factoriopedia_simulation = simulations.factoriopedia_angels_swamp_garden,
    max_health = 20,
    collision_box = { { -1.1, -1.1 }, { 1.1, 1.1 } },
    selection_box = { { -1.3, -1.3 }, { 1.3, 1.3 } },
    map_color = { r = 0.2, g = 0.8, b = 0.2 },
    subgroup = "trees",
    order = "a[tree]-b[dead-tree]",
    impact_category = "wood",
    autoplace = {
      order = "yab",
      probability_expression = 0.000025,
      tile_restriction = { "dirt-1", "dirt-2", "dirt-3", "dirt-4", "dirt-5", "dirt-6", "dirt-7" },
    },
    pictures = {
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/swamp-garden-1.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/swamp-garden-2.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/gardens/swamp-garden-3.png",
        width = 128,
        height = 128,
        scale = 0.75,
        shift = { 0, 0 },
      },
    },
  },
})
