local simulations = require("prototypes.factoriopedia-simulations")

data.raw.planet.nauvis.map_gen_settings.autoplace_settings.entity.settings["angels-temperate-tree"] = {}
data.raw.planet.nauvis.map_gen_settings.autoplace_settings.entity.settings["angels-swamp-tree"] = {}
data.raw.planet.nauvis.map_gen_settings.autoplace_settings.entity.settings["angels-desert-tree"] = {}

data:extend({
  {
    type = "item",
    name = "angels-temperate-tree",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/tree-temperate.png",
    icon_size = 64,
    subgroup = "angels-bio-arboretum-temperate",
    order = "b",
    stack_size = 10,
  },
  {
    type = "tree",
    name = "angels-temperate-tree",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/tree-temperate.png",
    icon_size = 64,
    flags = { "placeable-neutral", "placeable-off-grid", "breaths-air" },
    minable = {
      mining_particle = "wooden-particle",
      mining_time = 1,
      results = {
        { type = "item", name = "wood", amount = 100 },
        { type = "item", name = "angels-temperate-tree", amount = 1 },
      },
    },
    emissions_per_second = {pollution = -0.006}, --emissions_per_tick = -0.0001,
    factoriopedia_simulation = simulations.factoriopedia_angels_temperate_tree,
    max_health = 20,
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -2, -5 }, { 2, 1 } },
    map_color = { r = 0.2, g = 0.7, b = 0.8 }, -- {r = 0.2, g = 0.2, b = 0.8},
    subgroup = "trees",
    order = "z-a",
    impact_category = "wood",
    autoplace = {
      order = "xaa",
      probability_expression = 0.000025,
      tile_restriction = {"grass-1", "grass-2", "grass-3", "grass-4", "dry-dirt"},
    },
    pictures = {
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-1-a.png",
        width = 256,
        height = 256,
        shift = { 0.5, -1.5 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-1-b.png",
        width = 256,
        height = 256,
        shift = { 0.5, -1.5 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-1-c.png",
        width = 256,
        height = 256,
        shift = { 0.5, -1.5 },
      },
    },
  },
  {
    type = "item",
    name = "angels-swamp-tree",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/tree-swamp.png",
    icon_size = 64,
    subgroup = "angels-bio-arboretum-temperate",
    order = "c",
    stack_size = 10,
  },
  {
    type = "tree",
    name = "angels-swamp-tree",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/tree-swamp.png",
    icon_size = 64,
    flags = { "placeable-neutral", "placeable-off-grid", "breaths-air" },
    minable = {
      mining_particle = "wooden-particle",
      mining_time = 1,
      results = {
        { type = "item", name = "wood", amount = 100 },
        { type = "item", name = "angels-swamp-tree", amount = 1 },
      },
    },
    emissions_per_second = {pollution = -0.006}, --emissions_per_tick = -0.0001,
    factoriopedia_simulation = simulations.factoriopedia_angels_swamp_tree,
    max_health = 20,
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -1.5, -5 }, { 1.5, 1 } },
    map_color = { r = 0.2, g = 0.7, b = 0.8 }, -- {r = 0.2, g = 0.2, b = 0.8},
    subgroup = "trees",
    order = "z-b",
    impact_category = "wood",
    autoplace = {
      order = "yaa",
      probability_expression = 0.000025,
      tile_restriction = {"dirt-1", "dirt-2", "dirt-3", "dirt-4", "dirt-5", "dirt-6", "dirt-7"},
    },
    pictures = {
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-2-a.png",
        width = 256,
        height = 256,
        shift = { 1, -2 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-2-b.png",
        width = 256,
        height = 256,
        shift = { 1, -2 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-2-c.png",
        width = 256,
        height = 256,
        shift = { 1, -2 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-2-d.png",
        width = 256,
        height = 256,
        shift = { 1, -2 },
      },
    },
  },
  {
    type = "item",
    name = "angels-desert-tree",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/tree-desert.png",
    icon_size = 64,
    subgroup = "angels-bio-arboretum-temperate",
    order = "d",
    stack_size = 10,
  },
  {
    type = "tree",
    name = "angels-desert-tree",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/tree-desert.png",
    icon_size = 64,
    flags = { "placeable-neutral", "placeable-off-grid", "breaths-air" },
    minable = {
      mining_particle = "wooden-particle",
      mining_time = 1,
      results = {
        { type = "item", name = "wood", amount = 100 },
        { type = "item", name = "angels-desert-tree", amount = 1 },
      },
    },
    emissions_per_second = {pollution = -0.006}, --emissions_per_tick = -0.0001,
    factoriopedia_simulation = simulations.factoriopedia_angels_desert_tree,
    max_health = 20,
    collision_box = { { -0.9, -0.9 }, { 0.9, 0.9 } },
    selection_box = { { -2.5, -5 }, { 2.5, 1 } },
    map_color = { r = 0.2, g = 0.7, b = 0.8 }, -- {r = 0.2, g = 0.2, b = 0.8},
    subgroup = "trees",
    order = "z-b",
    impact_category = "wood",
    autoplace = {
      order = "yaa",
      probability_expression = 0.000025,
      tile_restriction = {"dirt-1", "dirt-2", "dirt-3", "dirt-4", "dirt-5", "dirt-6", "dirt-7"},
    },
    pictures = {
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-3-a.png",
        width = 256,
        height = 256,
        shift = { 0.5, -2 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-3-b.png",
        width = 256,
        height = 256,
        shift = { 1.5, -2 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-3-c.png",
        width = 256,
        height = 256,
        shift = { 0.25, -2 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-3-d.png",
        width = 256,
        height = 256,
        shift = { 0.5, -2 },
      },
      {
        filename = "__angelsbioprocessinggraphics__/graphics/entity/trees/tree-3-e.png",
        width = 256,
        height = 256,
        shift = { 0.5, -2 },
      },
    },
  },
})
