angelsmods.functions.make_void("wood", "bio")
angelsmods.functions.make_void("angels-cellulose-fiber", "bio", 2)

angelsmods.functions.make_void("angels-algae-green", "bio", 4)
angelsmods.functions.make_void("angels-algae-brown", "bio", 3)
angelsmods.functions.make_void("angels-algae-red", "bio", 2)
angelsmods.functions.make_void("angels-algae-blue", "bio")

angelsmods.functions.make_void("angels-temperate-garden", "bio", 2)
angelsmods.functions.make_void("angels-desert-garden", "bio", 2)
angelsmods.functions.make_void("angels-swamp-garden", "bio", 2)

angelsmods.functions.make_void("angels-temperate-1", "bio", 2)
angelsmods.functions.make_void("angels-temperate-1-seed", "bio", 20)
angelsmods.functions.make_void("angels-temperate-2", "bio", 2)
angelsmods.functions.make_void("angels-temperate-2-seed", "bio", 20)
angelsmods.functions.make_void("angels-temperate-3", "bio", 2)
angelsmods.functions.make_void("angels-temperate-3-seed", "bio", 20)
angelsmods.functions.make_void("angels-temperate-3-seed-dormant", "bio", 20)
angelsmods.functions.make_void("angels-temperate-4", "bio", 2)
angelsmods.functions.make_void("angels-temperate-4-seed", "bio", 20)
angelsmods.functions.make_void("angels-temperate-4-seed-dormant", "bio", 20)
angelsmods.functions.make_void("angels-temperate-5", "bio", 2)
angelsmods.functions.make_void("angels-temperate-5-seed", "bio", 20)
angelsmods.functions.make_void("angels-temperate-5-seed-dormant", "bio", 20)

angelsmods.functions.make_void("angels-desert-1", "bio", 2)
angelsmods.functions.make_void("angels-desert-1-seed", "bio", 20)
angelsmods.functions.make_void("angels-desert-2", "bio", 2)
angelsmods.functions.make_void("angels-desert-2-seed", "bio", 20)
angelsmods.functions.make_void("angels-desert-3", "bio", 2)
angelsmods.functions.make_void("angels-desert-3-seed", "bio", 20)
angelsmods.functions.make_void("angels-desert-3-seed-dormant", "bio", 20)
angelsmods.functions.make_void("angels-desert-4", "bio", 2)
angelsmods.functions.make_void("angels-desert-4-seed", "bio", 20)
angelsmods.functions.make_void("angels-desert-4-seed-dormant", "bio", 20)
angelsmods.functions.make_void("angels-desert-5", "bio", 2)
angelsmods.functions.make_void("angels-desert-5-seed", "bio", 20)
angelsmods.functions.make_void("angels-desert-5-seed-dormant", "bio", 20)

angelsmods.functions.make_void("angels-swamp-1", "bio", 2)
angelsmods.functions.make_void("angels-swamp-1-seed", "bio", 20)
angelsmods.functions.make_void("angels-swamp-2", "bio", 2)
angelsmods.functions.make_void("angels-swamp-2-seed", "bio", 20)
angelsmods.functions.make_void("angels-swamp-3", "bio", 2)
angelsmods.functions.make_void("angels-swamp-3-seed", "bio", 20)
angelsmods.functions.make_void("angels-swamp-3-seed-dormant", "bio", 20)
angelsmods.functions.make_void("angels-swamp-4", "bio", 2)
angelsmods.functions.make_void("angels-swamp-4-seed", "bio", 20)
angelsmods.functions.make_void("angels-swamp-4-seed-dormant", "bio", 20)
angelsmods.functions.make_void("angels-swamp-5", "bio", 2)
angelsmods.functions.make_void("angels-swamp-5-seed", "bio", 20)
angelsmods.functions.make_void("angels-swamp-5-seed-dormant", "bio", 20)

angelsmods.functions.make_void("angels-gas-ethanol", "chemical")

angelsmods.functions.make_void("angels-alien-spores", "chemical")
angelsmods.functions.make_void("angels-alien-bacteria", "bio")
angelsmods.functions.make_void("angels-bio-puffer-egg-shell", "bio", 10)
