angelsmods.functions.make_void("wood", "bio")
angelsmods.functions.make_void("cellulose-fiber", "bio", 2)

angelsmods.functions.make_void("algae-green", "bio", 4)
angelsmods.functions.make_void("algae-brown", "bio", 3)
angelsmods.functions.make_void("algae-red", "bio", 2)
angelsmods.functions.make_void("algae-blue", "bio")

angelsmods.functions.make_void("temperate-garden", "bio", 2)
angelsmods.functions.make_void("desert-garden", "bio", 2)
angelsmods.functions.make_void("swamp-garden", "bio", 2)

angelsmods.functions.make_void("temperate-1", "bio", 2)
angelsmods.functions.make_void("temperate-1-seed", "bio", 20)
angelsmods.functions.make_void("temperate-2", "bio", 2)
angelsmods.functions.make_void("temperate-2-seed", "bio", 20)
angelsmods.functions.make_void("temperate-3", "bio", 2)
angelsmods.functions.make_void("temperate-3-seed", "bio", 20)
angelsmods.functions.make_void("temperate-3-seed-dormant", "bio", 20)
angelsmods.functions.make_void("temperate-4", "bio", 2)
angelsmods.functions.make_void("temperate-4-seed", "bio", 20)
angelsmods.functions.make_void("temperate-4-seed-dormant", "bio", 20)
angelsmods.functions.make_void("temperate-5", "bio", 2)
angelsmods.functions.make_void("temperate-5-seed", "bio", 20)
angelsmods.functions.make_void("temperate-5-seed-dormant", "bio", 20)

angelsmods.functions.make_void("desert-1", "bio", 2)
angelsmods.functions.make_void("desert-1-seed", "bio", 20)
angelsmods.functions.make_void("desert-2", "bio", 2)
angelsmods.functions.make_void("desert-2-seed", "bio", 20)
angelsmods.functions.make_void("desert-3", "bio", 2)
angelsmods.functions.make_void("desert-3-seed", "bio", 20)
angelsmods.functions.make_void("desert-3-seed-dormant", "bio", 20)
angelsmods.functions.make_void("desert-4", "bio", 2)
angelsmods.functions.make_void("desert-4-seed", "bio", 20)
angelsmods.functions.make_void("desert-4-seed-dormant", "bio", 20)
angelsmods.functions.make_void("desert-5", "bio", 2)
angelsmods.functions.make_void("desert-5-seed", "bio", 20)
angelsmods.functions.make_void("desert-5-seed-dormant", "bio", 20)

angelsmods.functions.make_void("swamp-1", "bio", 2)
angelsmods.functions.make_void("swamp-1-seed", "bio", 20)
angelsmods.functions.make_void("swamp-2", "bio", 2)
angelsmods.functions.make_void("swamp-2-seed", "bio", 20)
angelsmods.functions.make_void("swamp-3", "bio", 2)
angelsmods.functions.make_void("swamp-3-seed", "bio", 20)
angelsmods.functions.make_void("swamp-3-seed-dormant", "bio", 20)
angelsmods.functions.make_void("swamp-4", "bio", 2)
angelsmods.functions.make_void("swamp-4-seed", "bio", 20)
angelsmods.functions.make_void("swamp-4-seed-dormant", "bio", 20)
angelsmods.functions.make_void("swamp-5", "bio", 2)
angelsmods.functions.make_void("swamp-5-seed", "bio", 20)
angelsmods.functions.make_void("swamp-5-seed-dormant", "bio", 20)

angelsmods.functions.make_void("gas-ethanol", "chemical")

angelsmods.functions.make_void("alien-spores", "chemical")
angelsmods.functions.make_void("alien-bacteria", "bio")
angelsmods.functions.make_void("bio-puffer-egg-shell", "bio", 10)
