circuit_connector_definitions["angels-cargo-hub"] = circuit_connector_definitions.create_single(universal_connector_template,
  { variation =  4, main_offset = util.by_pixel(-4.375,  94.25), shadow_offset = util.by_pixel(-4.375,  94.25), show_shadow = true }
)

circuit_connector_definitions["angels-cargo-box"] = circuit_connector_definitions.create_single(universal_connector_template,
  { variation =  4, main_offset = util.by_pixel(-4.75,  55.125), shadow_offset = util.by_pixel(-4.75,  55.125), show_shadow = true }
)

circuit_connector_definitions["angels-cargo-roboport"] = circuit_connector_definitions.create_single(universal_connector_template,
  { variation =  2, main_offset = util.by_pixel(-59.25, -31.375), shadow_offset = util.by_pixel(-59.25, -31.375), show_shadow = true }
)

data:extend({
  {
    type = "item",
    name = "angels-cargo-roboport",
    icon = "__angelsaddons-bots__/graphics/icons/cargo-roboport.png",
    icon_size = 32,
    subgroup = "angels-cargo-ports",
    order = "a[roboport]-b",
    place_result = "angels-cargo-roboport",
    stack_size = 50,
  },
  {
    type = "roboport",
    name = "angels-cargo-roboport",
    icon = "__angelsaddons-bots__/graphics/icons/cargo-roboport.png",
    icon_size = 32,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-cargo-roboport" },
    max_health = 1000,
    corpse = "big-remnants",
    collision_box = { { -2.9, -2.9 }, { 2.9, 2.9 } },
    selection_box = { { -3, -3 }, { 3, 3 } },
    drawing_box_vertical_extension = 2,
    dying_explosion = "medium-explosion",
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      input_flow_limit = "1MW",
      buffer_capacity = "24MJ",
    },
    recharge_minimum = "20MJ",
    energy_usage = "200kW",
    -- per one charge slot
    charging_energy = "200kW",
    logistics_radius = 7,
    construction_radius = 0,
    charge_approach_distance = 10,
    robot_slots_count = 4,
    material_slots_count = 4,
    stationing_offset = { 1.5, -0.25 },
    charging_offsets = {
      { -1, -1 },
      { -1, -3 },
      { 1.5, -4 },
    },
    base = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport.png",
      width = 320,
      height = 320,
      shift = { 1, -1 },
    },
    base_patch = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport-patch.png",
      priority = "medium",
      width = 96,
      height = 96,
      shift = { 46 / 32, -13 / 32 },
    },
    base_animation = {
      filename = "__angelsaddons-bots__/graphics/entity/empty.png",
      priority = "medium",
      width = 1,
      height = 1,
      frame_count = 1,
      shift = { 0, 0 },
    },
    door_animation_up = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport-door-up.png",
      priority = "medium",
      width = 64,
      height = 32,
      frame_count = 16,
      shift = { 1.5, -1 },
    },
    door_animation_down = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport-door-down.png",
      priority = "medium",
      width = 64,
      height = 32,
      frame_count = 16,
      shift = { 1.5, 0 },
    },
    recharging_animation = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargoroboport-recharging.png",
      priority = "high",
      width = 74,
      height = 70,
      frame_count = 16,
      scale = 1.5,
      animation_speed = 0.5,
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/roboport-working.ogg", volume = 0.6 },
      max_sounds_per_prototype = 3,
      probability = 1 / (5 * 60), -- average pause between the sound is 5 seconds
    },
    recharging_light = { intensity = 0.4, size = 10 },
    request_to_open_door_timeout = 15,
    spawn_and_station_height = 0,
    draw_logistic_radius_visualization = true,
    draw_construction_radius_visualization = true,
    open_door_trigger_effect = {
      {
        type = "play-sound",
        sound = { filename = "__base__/sound/roboport-door.ogg", volume = 1.2 },
      },
    },
    close_door_trigger_effect = {
      {
        type = "play-sound",
        sound = { filename = "__base__/sound/roboport-door.ogg", volume = 0.75 },
      },
    },
    circuit_connector = circuit_connector_definitions["angels-cargo-roboport"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    default_available_logistic_output_signal = { type = "virtual", name = "signal-X" },
    default_total_logistic_output_signal = { type = "virtual", name = "signal-Y" },
    default_available_construction_output_signal = { type = "virtual", name = "signal-Z" },
    default_total_construction_output_signal = { type = "virtual", name = "signal-T" },
  },
  {
    type = "item",
    name = "angels-cargo-hub",
    icon = "__angelsaddons-bots__/graphics/icons/cargo-hub.png",
    icon_size = 32,
    subgroup = "angels-cargo-ports",
    order = "a[roboport]-c",
    place_result = "angels-cargo-hub",
    stack_size = 50,
  },
  {
    type = "roboport",
    name = "angels-cargo-hub",
    icon = "__angelsaddons-bots__/graphics/icons/cargo-hub.png",
    icon_size = 32,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-cargo-hub" },
    max_health = 1000,
    corpse = "big-remnants",
    collision_box = { { -3.4, -3.4 }, { 3.4, 3.4 } },
    selection_box = { { -3.5, -3.5 }, { 3.5, 3.5 } },
    dying_explosion = "medium-explosion",
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      input_flow_limit = "2MW",
      buffer_capacity = "48MJ",
    },
    recharge_minimum = "20MJ",
    energy_usage = "200kW",
    -- per one charge slot
    charging_energy = "200kW",
    logistics_radius = 7.5,
    construction_radius = 0,
    charge_approach_distance = 6,
    robot_slots_count = 7,
    material_slots_count = 7,
    stationing_offset = { -0, -1 },
    charging_offsets = {
      { -3, -1 },
      { 3, -1 },
      { 1.5, 1 },
      { -1.5, 1 },
      { 1.5, -3 },
      { -1.5, -3 },
    },
    base = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-hub.png",
      width = 320,
      height = 320,
      shift = { 0.5, -0.25 },
    },
    base_patch = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-hub-patch.png",
      priority = "medium",
      width = 96,
      height = 96,
      shift = { 0, -0.25 },
    },
    base_animation = {
      filename = "__angelsaddons-bots__/graphics/entity/empty.png",
      priority = "medium",
      width = 1,
      height = 1,
      frame_count = 1,
      shift = { 0, 0 },
    },
    door_animation_up = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport-door-up.png",
      priority = "medium",
      width = 64,
      height = 32,
      frame_count = 16,
      shift = { 0, -1 },
    },
    door_animation_down = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport-door-down.png",
      priority = "medium",
      width = 64,
      height = 32,
      frame_count = 16,
      shift = { 0, 0 },
    },
    recharging_animation = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargoroboport-recharging.png",
      priority = "high",
      width = 74,
      height = 70,
      frame_count = 16,
      scale = 1.5,
      animation_speed = 0.5,
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/roboport-working.ogg", volume = 0.6 },
      max_sounds_per_prototype = 3,
      probability = 1 / (5 * 60), -- average pause between the sound is 5 seconds
    },
    recharging_light = { intensity = 0.4, size = 10 },
    request_to_open_door_timeout = 15,
    spawn_and_station_height = -0.1,
    draw_logistic_radius_visualization = true,
    draw_construction_radius_visualization = true,
    open_door_trigger_effect = {
      {
        type = "play-sound",
        sound = { filename = "__base__/sound/roboport-door.ogg", volume = 1.2 },
      },
    },
    close_door_trigger_effect = {
      {
        type = "play-sound",
        sound = { filename = "__base__/sound/roboport-door.ogg", volume = 0.75 },
      },
    },
    circuit_connector = circuit_connector_definitions["angels-cargo-hub"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    default_available_logistic_output_signal = { type = "virtual", name = "signal-X" },
    default_total_logistic_output_signal = { type = "virtual", name = "signal-Y" },
    default_available_construction_output_signal = { type = "virtual", name = "signal-Z" },
    default_total_construction_output_signal = { type = "virtual", name = "signal-T" },
  },
  {
    type = "item",
    name = "angels-cargo-box",
    icon = "__angelsaddons-bots__/graphics/icons/cargo-box-icon.png",
    icon_size = 32,
    subgroup = "angels-cargo-ports",
    order = "a[roboport]-a",
    place_result = "angels-cargo-box",
    stack_size = 50,
  },
  {
    type = "roboport",
    name = "angels-cargo-box",
    icon = "__angelsaddons-bots__/graphics/icons/cargo-box-icon.png",
    icon_size = 32,
    flags = { "placeable-player", "player-creation" },
    minable = { mining_time = 0.5, result = "angels-cargo-box" },
    max_health = 1000,
    corpse = "big-remnants",
    collision_box = { { -1.9, -1.9 }, { 1.9, 1.9 } },
    selection_box = { { -2, -2 }, { 2, 2 } },
    drawing_box_vertical_extension = 1.33,
    dying_explosion = "medium-explosion",
    energy_source = {
      type = "electric",
      usage_priority = "secondary-input",
      input_flow_limit = "2MW",
      buffer_capacity = "10MJ",
    },
    recharge_minimum = "5MJ",
    energy_usage = "200kW",
    -- per one charge slot
    charging_energy = "200kW",
    logistics_radius = 7,
    construction_radius = 0,
    charge_approach_distance = 4,
    robot_slots_count = 12,
    material_slots_count = 2,
    stationing_offset = { -0, -0.5 },
    charging_offsets = {
      { 1.5, -2.25 },
    },
    base = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-box.png",
      width = 192,
      height = 192,
      shift = { 0, -0.75 },
    },
    base_patch = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-box-patch.png",
      priority = "medium",
      width = 96,
      height = 96,
      shift = { 0, -0.75 },
    },
    base_animation = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-box-animation.png",
      priority = "medium",
      width = 32,
      height = 32,
      frame_count = 16,
      line_length = 4,
      shift = { -1.5, -3.25 },
      animation_speed = 0.5,
    },
    door_animation_up = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport-door-up.png",
      priority = "medium",
      width = 64,
      height = 32,
      frame_count = 16,
      shift = { 0, -40 / 32 },
    },
    door_animation_down = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargo-roboport-door-down.png",
      priority = "medium",
      width = 64,
      height = 32,
      frame_count = 16,
      shift = { 0, -8 / 32 },
    },
    recharging_animation = {
      filename = "__angelsaddons-bots__/graphics/entity/cargo-roboport/cargoroboport-recharging.png",
      priority = "high",
      width = 74,
      height = 70,
      frame_count = 16,
      scale = 1.5,
      animation_speed = 0.5,
    },
    impact_category = "metal",
    working_sound = {
      sound = { filename = "__base__/sound/roboport-working.ogg", volume = 0.6 },
      max_sounds_per_prototype = 3,
      probability = 1 / (5 * 60), -- average pause between the sound is 5 seconds
    },
    recharging_light = { intensity = 0.4, size = 10 },
    request_to_open_door_timeout = 15,
    spawn_and_station_height = -1,
    draw_logistic_radius_visualization = true,
    draw_construction_radius_visualization = true,
    open_door_trigger_effect = {
      {
        type = "play-sound",
        sound = { filename = "__base__/sound/roboport-door.ogg", volume = 1.2 },
      },
    },
    close_door_trigger_effect = {
      {
        type = "play-sound",
        sound = { filename = "__base__/sound/roboport-door.ogg", volume = 0.75 },
      },
    },
    circuit_connector = circuit_connector_definitions["angels-cargo-box"],
    circuit_wire_max_distance = default_circuit_wire_max_distance,
    default_available_logistic_output_signal = { type = "virtual", name = "signal-X" },
    default_total_logistic_output_signal = { type = "virtual", name = "signal-Y" },
    default_available_construction_output_signal = { type = "virtual", name = "signal-Z" },
    default_total_construction_output_signal = { type = "virtual", name = "signal-T" },
  },
})
