data:extend({
  --BROWN
  {
    type = "item",
    name = "algae-brown",
    icon = "__angelsbioprocessing__/graphics/icons/algae-brown.png",
    icon_size = 32,
    subgroup = "bio-processing-brown",
    order = "a[algae-brown]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "solid-alginic-acid",
    icon = "__angelsbioprocessing__/graphics/icons/solid-alginic-acid.png",
    icon_size = 32,
    subgroup = "bio-processing-brown",
    order = "b[solid-alginic-acid]",
    stack_size = 200,
  },
  --GREEN
  {
    type = "item",
    name = "algae-green",
    icon = "__angelsbioprocessing__/graphics/icons/algae-green.png",
    icon_size = 32,
    subgroup = "bio-processing-green",
    order = "a[algae-green]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-cellulose",
    icon = "__angelsbioprocessing__/graphics/icons/paste-cellulose.png",
    icon_size = 32,
    subgroup = "bio-processing-green",
    order = "c[paste-cellulose]",
    stack_size = 200,
  },
  --BLUE
  {
    type = "item",
    name = "algae-blue",
    icon = "__angelsbioprocessing__/graphics/icons/algae-blue.png",
    icon_size = 32,
    subgroup = "bio-processing-blue",
    order = "a[algae-blue]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "blue-cellulose-fiber",
    icon = "__angelsbioprocessing__/graphics/icons/blue-cellulose-fiber.png",
    icon_size = 32,
    subgroup = "bio-processing-blue",
    order = "b[blue-cellulose-fiber]",
    stack_size = 200,
  },
  --RED
  {
    type = "item",
    name = "algae-red",
    icon = "__angelsbioprocessing__/graphics/icons/algae-red.png",
    icon_size = 32,
    subgroup = "bio-processing-red",
    order = "a[algae-red]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "red-cellulose-fiber",
    icon = "__angelsbioprocessing__/graphics/icons/red-cellulose-fiber.png",
    icon_size = 32,
    subgroup = "bio-processing-red",
    order = "b[red-cellulose-fiber]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "solid-calcium-carbonate",
    icon = "__angelsbioprocessing__/graphics/icons/solid-calcium-carbonate.png",
    icon_size = 32,
    subgroup = "bio-processing-red",
    order = "c[solid-calcium-carbonate]",
    stack_size = 200,
  },
})
