data:extend({
  --PASTE
  {
    type = "item",
    name = "paste-cobalt",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-cobalt.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-cobalt]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-copper",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-copper.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-copper]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-gold",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-gold.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-gold]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-iron",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-iron.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-iron]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-silver",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-silver.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-silver]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-titanium",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-titanium.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-titanium]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-tungsten",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-tungsten.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-tungsten]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "paste-zinc",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/paste-zinc.png",
    icon_size = 32,
    subgroup = "bio-processing-paste",
    order = "a[paste-zinc]",
    stack_size = 200,
  },
})
