data:extend({
  {
    type = "item",
    name = "angels-crystal-powder",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-powder.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "d[powder]",
    stack_size = 200,
  },

  -- RAW
  {
    type = "item",
    name = "angels-crystal-splinter-raw",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-raw.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "a[raw]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-raw",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-raw.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "a[raw]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-raw",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-raw.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "a[raw]",
    stack_size = 200,
  },

  -- CUT
  {
    type = "item",
    name = "angels-crystal-splinter-blue-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-blue.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "b[split]-a[blue]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-splinter-red-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-red.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "b[split]-b[red]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-splinter-green-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-green.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "b[split]-c[green]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-blue-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-blue.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "b[split]-a[blue]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-red-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-red.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "b[split]-b[red]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-green-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-green.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "b[split]-c[green]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-blue-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-blue.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "b[split]-a[blue]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-red-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-red.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "b[split]-b[red]-a[cut]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-green-cut",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-green.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "b[split]-c[green]-a[cut]",
    stack_size = 200,
  },

  -- CRYSTAL
  {
    type = "item",
    name = "angels-crystal-splinter-blue",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-blue.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "b[split]-a[blue]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-splinter-red",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-red.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "b[split]-b[red]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-splinter-green",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-green.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "b[split]-c[green]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-splinter-harmonic",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-splinter-harmonic.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-splinter",
    order = "c[harmonic]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-blue",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-blue.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "b[split]-a[blue]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-red",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-red.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "b[split]-b[red]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-green",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-green.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "b[split]-c[green]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-shard-harmonic",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-shard-harmonic.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-shard",
    order = "c[harmonic]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-blue",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-blue.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "b[split]-a[blue]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-red",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-red.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "b[split]-b[red]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-green",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-green.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "b[split]-c[green]-b[polished]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-full-harmonic",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-full-harmonic.png",
    icon_size = 32,
    subgroup = "angels-bio-biter-processing-crystal-full",
    order = "c[harmonic]",
    stack_size = 200,
  },
})
