data:extend({
  -- ALIEN
  {
    type = "fluid",
    name = "angels-alien-spores",
    default_temperature = 0,
    max_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 0.572, g = 0.392, b = 0.894 },
    flow_color = { r = 0.572, g = 0.392, b = 0.894 },
    icon = "__angelsbioprocessinggraphics__/graphics/icons/alien-spores.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "a[alien]-a[spores]",
  },
  {
    type = "item",
    name = "angels-alien-bacteria",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/alien-bacteria.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "a[alien]-b[bacteria]",
    stack_size = 200,
  },
  {
    type = "fluid",
    name = "angels-alien-goo",
    icons = angelsmods.functions.create_viscous_liquid_fluid_icon(
      nil,
      { { 168, 035, 194 }, { 168, 035, 194 }, { 241, 050, 238, 0.9 }, { 241, 050, 238, 0.9 } }
    ),
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "a[alien]-c[goo]",
    default_temperature = 0,
    max_temperature = 0,
    heat_capacity = "1kJ",
    base_color = { r = 0.572, g = 0.392, b = 0.894 },
    flow_color = { r = 0.572, g = 0.392, b = 0.894 },
  },

  -- DISH
  {
    type = "item",
    name = "angels-petri-dish",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/petri-dish.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "b[dish]-a[petri]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-substrate-dish",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/substrate-dish.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "b[dish]-b[substrate]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-seeded-dish",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/alien-pre-artifact.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "b[dish]-c[seeded]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-seed.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "b[dish]-d[seed]-a[crystal]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-egg-shell-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/egg-shell-seed.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "b[dish]-d[seed]-b[egg-shell]",
    stack_size = 200,
  },

  -- DISH USAGE
  {
    type = "item",
    name = "angels-crystal-enhancer",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-enhancer.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "c[crystal]-a[enhancer]",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-crystal-grindstone",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/crystal-grindstone.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-alien-intermediate",
    order = "c[crystal]-b[grindstone]",
    stack_size = 200,
  },
})
