data:extend({
  -----------------------------------------------------------------------------
  -- SUPPORT ------------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-solid-compost",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/solid-compost.png",
    icon_size = 32,
    subgroup = "angels-bio-wood",
    order = "a[support]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-solid-soil",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/solid-soil.png",
    icon_size = 32,
    subgroup = "angels-bio-wood",
    order = "a[support]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-solid-fertilizer",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/solid-fertilizer.png",
    icon_size = 32,
    subgroup = "angels-bio-wood",
    order = "a[support]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-solid-alienated-fertilizer",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/solid-alienated-fertilizer.png",
    icon_size = 32,
    subgroup = "angels-bio-wood",
    order = "a[support]-d",
    stack_size = 500,
  },
  {
    type = "tool",
    name = "angels-token-bio",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/token-bio.png",
    icon_size = 32,
    subgroup = "science-pack",
    order = "c[token-bio]",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value",
  },
  -----------------------------------------------------------------------------
  -- UPGRADES -----------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-temperate-upgrade",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-upgrade.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-blocks",
    order = "aa",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-desert-upgrade",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-upgrade.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-blocks",
    order = "ab",
    stack_size = 200,
  },
  {
    type = "item",
    name = "angels-swamp-upgrade",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-upgrade.png",
    icon_size = 32,
    subgroup = "angels-bio-processing-blocks",
    order = "ac",
    stack_size = 200,
  },
  -----------------------------------------------------------------------------
  -- TEMPERATE SEEDS ----------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-temperate-1-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-1-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "a[seed]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-2-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-2-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "a[seed]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-3-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-3-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "a[seed]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-3-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-3-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "b[seed-dormant]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-4-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-4-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "a[seed]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-4-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-4-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "b[seed-dormant]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-5-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-5-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "a[seed]-e",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-5-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-5-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate-seed",
    order = "b[seed-dormant]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- TEMPERATE VEGETABLES -----------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-temperate-1",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-1.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate",
    order = "a[vegetable]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-2",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-2.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate",
    order = "a[vegetable]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-3",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-3.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate",
    order = "a[vegetable]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-4",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-4.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate",
    order = "a[vegetable]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-temperate-5",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/temperate-5.png",
    icon_size = 32,
    subgroup = "angels-farming-temperate",
    order = "a[vegetable]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- DESERT SEEDS -------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-desert-1-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-1-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "a[seed]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-2-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-2-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "a[seed]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-3-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-3-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "a[seed]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-3-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-3-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "b[seed-dormant]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-4-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-4-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "a[seed]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-4-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-4-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "b[seed-dormant]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-5-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-5-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "a[seed]-e",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-5-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-5-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-desert-seed",
    order = "b[seed-dormant]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- DESERT VEGETABLES --------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-desert-1",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-1.png",
    icon_size = 32,
    subgroup = "angels-farming-desert",
    order = "a[vegetable]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-2",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-2.png",
    icon_size = 32,
    subgroup = "angels-farming-desert",
    order = "a[vegetable]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-3",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-3.png",
    icon_size = 32,
    subgroup = "angels-farming-desert",
    order = "a[vegetable]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-4",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-4.png",
    icon_size = 32,
    subgroup = "angels-farming-desert",
    order = "a[vegetable]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-desert-5",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/desert-5.png",
    icon_size = 32,
    subgroup = "angels-farming-desert",
    order = "a[vegetable]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- SWAMP SEEDS --------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-swamp-1-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-1-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "a[seed]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-2-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-2-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "a[seed]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-3-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-3-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "a[seed]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-3-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-3-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "b[seed-dormant]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-4-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-4-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "a[seed]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-4-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-4-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "b[seed-dormant]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-5-seed",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-5-seed.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "a[seed]-e",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-5-seed-dormant",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-5-seed-dormant.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp-seed",
    order = "b[seed-dormant]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- SWAMP VEGETABLES ---------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "angels-swamp-1",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-1.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp",
    order = "a[vegetable]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-2",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-2.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp",
    order = "a[vegetable]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-3",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-3.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp",
    order = "a[vegetable]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-4",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-4.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp",
    order = "a[vegetable]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "angels-swamp-5",
    icon = "__angelsbioprocessinggraphics__/graphics/icons/swamp-5.png",
    icon_size = 32,
    subgroup = "angels-farming-swamp",
    order = "a[vegetable]-e",
    stack_size = 500,
  },
})
