data:extend({
  -----------------------------------------------------------------------------
  -- SUPPORT ------------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "solid-compost",
    icon = "__angelsbioprocessing__/graphics/icons/solid-compost.png",
    icon_size = 32,
    subgroup = "bio-wood",
    order = "a[support]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "solid-soil",
    icon = "__angelsbioprocessing__/graphics/icons/solid-soil.png",
    icon_size = 32,
    subgroup = "bio-wood",
    order = "a[support]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "solid-fertilizer",
    icon = "__angelsbioprocessing__/graphics/icons/solid-fertilizer.png",
    icon_size = 32,
    subgroup = "bio-wood",
    order = "a[support]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "solid-alienated-fertilizer",
    icon = "__angelsbioprocessing__/graphics/icons/solid-alienated-fertilizer.png",
    icon_size = 32,
    subgroup = "bio-wood",
    order = "a[support]-d",
    stack_size = 500,
  },
  --{
  --  type = "item",
  --  name = "solid-nuclear-fertilizer",
  --  icon = "__angelsbioprocessing__/graphics/icons/solid-nuclear-fertilizer.png",
  --  icon_size = 32,
  --  subgroup = "bio-wood",
  --  order = "a[support]-e",
  --  stack_size = 500
  --},
  {
    type = "tool",
    name = "token-bio",
    icon = "__angelsbioprocessing__/graphics/icons/token-bio.png",
    icon_size = 32,
    subgroup = "farming-gardens",
    order = "g",
    stack_size = 200,
    durability = 1,
    durability_description_key = "description.science-pack-remaining-amount-key",
    durability_description_value = "description.science-pack-remaining-amount-value",
  },
  -----------------------------------------------------------------------------
  -- UPGRADES -----------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "temperate-upgrade",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-upgrade.png",
    icon_size = 32,
    subgroup = "bio-processing-blocks",
    order = "aa",
    stack_size = 200,
  },
  {
    type = "item",
    name = "desert-upgrade",
    icon = "__angelsbioprocessing__/graphics/icons/desert-upgrade.png",
    icon_size = 32,
    subgroup = "bio-processing-blocks",
    order = "ab",
    stack_size = 200,
  },
  {
    type = "item",
    name = "swamp-upgrade",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-upgrade.png",
    icon_size = 32,
    subgroup = "bio-processing-blocks",
    order = "ac",
    stack_size = 200,
  },
  -----------------------------------------------------------------------------
  -- TEMPERATE SEEDS ----------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "temperate-1-seed",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-1-seed.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "a[seed]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-2-seed",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-2-seed.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "a[seed]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-3-seed",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-3-seed.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "a[seed]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-3-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-3-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "b[seed-dormant]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-4-seed",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-4-seed.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "a[seed]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-4-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-4-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "b[seed-dormant]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-5-seed",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-5-seed.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "a[seed]-e",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-5-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-5-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-temperate-seed",
    order = "b[seed-dormant]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- TEMPERATE VEGETABLES -----------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "temperate-1",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-1.png",
    icon_size = 32,
    subgroup = "farming-temperate",
    order = "a[vegetable]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-2",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-2.png",
    icon_size = 32,
    subgroup = "farming-temperate",
    order = "a[vegetable]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-3",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-3.png",
    icon_size = 32,
    subgroup = "farming-temperate",
    order = "a[vegetable]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-4",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-4.png",
    icon_size = 32,
    subgroup = "farming-temperate",
    order = "a[vegetable]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "temperate-5",
    icon = "__angelsbioprocessing__/graphics/icons/temperate-5.png",
    icon_size = 32,
    subgroup = "farming-temperate",
    order = "a[vegetable]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- DESERT SEEDS -------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "desert-1-seed",
    icon = "__angelsbioprocessing__/graphics/icons/desert-1-seed.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "a[seed]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-2-seed",
    icon = "__angelsbioprocessing__/graphics/icons/desert-2-seed.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "a[seed]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-3-seed",
    icon = "__angelsbioprocessing__/graphics/icons/desert-3-seed.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "a[seed]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-3-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/desert-3-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "b[seed-dormant]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-4-seed",
    icon = "__angelsbioprocessing__/graphics/icons/desert-4-seed.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "a[seed]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-4-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/desert-4-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "b[seed-dormant]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-5-seed",
    icon = "__angelsbioprocessing__/graphics/icons/desert-5-seed.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "a[seed]-e",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-5-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/desert-5-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-desert-seed",
    order = "b[seed-dormant]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- DESERT VEGETABLES --------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "desert-1",
    icon = "__angelsbioprocessing__/graphics/icons/desert-1.png",
    icon_size = 32,
    subgroup = "farming-desert",
    order = "a[vegetable]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-2",
    icon = "__angelsbioprocessing__/graphics/icons/desert-2.png",
    icon_size = 32,
    subgroup = "farming-desert",
    order = "a[vegetable]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-3",
    icon = "__angelsbioprocessing__/graphics/icons/desert-3.png",
    icon_size = 32,
    subgroup = "farming-desert",
    order = "a[vegetable]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-4",
    icon = "__angelsbioprocessing__/graphics/icons/desert-4.png",
    icon_size = 32,
    subgroup = "farming-desert",
    order = "a[vegetable]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "desert-5",
    icon = "__angelsbioprocessing__/graphics/icons/desert-5.png",
    icon_size = 32,
    subgroup = "farming-desert",
    order = "a[vegetable]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- SWAMP SEEDS --------------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "swamp-1-seed",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-1-seed.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "a[seed]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-2-seed",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-2-seed.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "a[seed]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-3-seed",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-3-seed.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "a[seed]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-3-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-3-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "b[seed-dormant]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-4-seed",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-4-seed.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "a[seed]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-4-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-4-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "b[seed-dormant]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-5-seed",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-5-seed.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "a[seed]-e",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-5-seed-dormant",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-5-seed-dormant.png",
    icon_size = 32,
    subgroup = "farming-swamp-seed",
    order = "b[seed-dormant]-e",
    stack_size = 500,
  },
  -----------------------------------------------------------------------------
  -- SWAMP VEGETABLES ---------------------------------------------------------
  -----------------------------------------------------------------------------
  {
    type = "item",
    name = "swamp-1",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-1.png",
    icon_size = 32,
    subgroup = "farming-swamp",
    order = "a[vegetable]-a",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-2",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-2.png",
    icon_size = 32,
    subgroup = "farming-swamp",
    order = "a[vegetable]-b",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-3",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-3.png",
    icon_size = 32,
    subgroup = "farming-swamp",
    order = "a[vegetable]-c",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-4",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-4.png",
    icon_size = 32,
    subgroup = "farming-swamp",
    order = "a[vegetable]-d",
    stack_size = 500,
  },
  {
    type = "item",
    name = "swamp-5",
    icon = "__angelsbioprocessing__/graphics/icons/swamp-5.png",
    icon_size = 32,
    subgroup = "farming-swamp",
    order = "a[vegetable]-e",
    stack_size = 500,
  },
})
